### ISSUE TITLE
Whitelist players from country protection

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1020]
Originally from https://www.spigotmc.org/threads/authme-reloaded.62079/page-28#post-2049649, via @Platinteufel:

> Is there a way to whitelist existing players or a few players when blacklisting countries?

-> There isn't currently, could be implemented by adding a new setting.

**Comment by Twonox** [comment]
There is way to whitelist.
A registered player with blacklisted contry can join the server. So, if `enableProtectionRegistered: false` we can register to whitelist

**Comment by ljacqu** [comment]
Then anyone that has registered can join from the banned country, not only the specified players.

**Comment by Twonox** [comment]
Yeah, a whitelist is better if we want blacklist country for registered player.
How you want integrate it? With a whitelist or with a permission?

**Comment by ljacqu** [comment]
What's your preference @Twonox? Permission has the advantage that you can easily mass apply it, a whitelist setting has the advantage that you can easily change the list. I didn't even think of a permission but now I would lean towards that. Thoughts? :)

**Comment by sgdc3** [comment]
+1 for permission ;)

**Comment by sgdc3** [comment]
+1 for permission ;)

**Comment by Twonox** [comment]
If you add commands to edit and see the whitelist,  it will be better, otherwise the permission is fine.

**Comment by sgdc3** [comment]
I added a new permission, please check #1321 for more infos
