### ISSUE TITLE
Conversion of LoginSecurity to AuthMe Reloaded

### ISSUE THREAD

**Issue by PinoyLifeCraft** [AuthMe/AuthMeReloaded#1023]
Hello Everyone 👋🏻 Can I Convert my old 🔗Login Security Plugin to ➡ Authme Reloaded ⁉️

**Comment by ljacqu** [comment]
We'd have to implement a converter for that.

**Comment by PinoyLifeCraft** [comment]
So it means that I can't use Authme? Can you make Converter for it?

**Comment by Thorney15** [comment]
I would also love to see this happen!

**Comment by ljacqu** [comment]
This got asked for again. Shall be implemented in the month to come.

**Comment by ljacqu** [comment]
@PinoyLifeCraft @Thorney15 As I started working on this I noticed some data to test with would be very helpful. Could one of you kindly email me your LoginSecurity database please?
My email is my username @ hotmail.com

**Comment by ljacqu** [comment]
I would have had time to do this but no one supplied a few rows to test on -> delayed to next milestone.

**Comment by KsenMih** [comment]
Hi @ljacqu , if this can be useful : 

LoginSecurity v2.1.6 "ls_players" table :
https://hastebin.com/ivofibubat.sql

LoginSecurity v2.1.6 folder (.DB included) :
[LoginSecurity.zip](https://github.com/AuthMe/AuthMeReloaded/files/983269/LoginSecurity.zip)

**Comment by ljacqu** [comment]
@KsenMih You're the best, thank you! I will have a look at this on Wednesday

**Comment by PinoyLifeCraft** [comment]
@ljacqu Haha sorry, I already reborn my server and change my plugin to AuthMe .... I'm out of this Issue if you have any question just mention me 🙂

**Comment by KsenMih** [comment]
@ljacqu Thanks YOU for making a way to switch from LoginSecurity to AuthMe <3 !

**Comment by ljacqu** [comment]
Managed to do some good progress on this, thanks again :) This will be available in, let's say, two days.

@PinoyLifeCraft Thanks for the feedback, glad you got it to work :)

**Comment by ljacqu** [comment]
hi @KsenMih @Thorney15, the latest build now has `/authme converter loginsecurity`. The next time you start your server the necessary configurations will be added to config.yml (just do a search for "loginsecurity" then).
I've only tested with SQLite and will verify with MySQL in the days to come. So if your interest is MySQL, feel free to wait until I write another comment.

**Comment by KsenMih** [comment]
I will try it ASAP ! Thanks !

**Comment by ljacqu** [comment]
Tested with MySQL and fixed an issue in the process, I think we're good to go now!

**Comment by KsenMih** [comment]
Sorry for the long delay, everything works perfectly. Thanks 👍
