### ISSUE TITLE
Sessions with Multiple Lobbies

### ISSUE THREAD

**Issue by voodootje0** [AuthMe/AuthMeReloaded#1031]
How this is currently handled? 

Since now it's kinda buggy, when you're using mysql, sessions and multiple lobbies.

**Comment by sgdc3** [comment]
AuthMeBungee should be ready, it only needs testing.
https://github.com/AuthMe/AuthMeBungee
http://ci.xephi.fr/job/AuthMeBungee/

**Comment by Eufranio** [comment]
So, it is an alternative for AuthMeBridge? Should we use both or only one? Can we just drop AuthMeBridge?

**Comment by sgdc3** [comment]
You need to replace authmebridge with authmebungee on both spigot and bungee. Please start testing it on a test environment, DON'T USE IT ON A PUBLIC SERVER.

**Comment by Eufranio** [comment]
RIP, don't have a testing environment for this kinda of thing (multiple servers, networking...), need just wait then

**Comment by jordanwilliams1** [comment]
@voodootje0 What do you mean by "buggy" Dose it some times cause lag and kick users?

**Comment by sgdc3** [comment]
We need to provide an official proper way

**Comment by ljacqu** [comment]
Can you please create a new issue and describe the problem and some thoughts? This issue is going nowhere and no one can pick it up because it's unclear what there is to do.

**Comment by sgdc3** [comment]
- (Re)create the bungee integration code
- Handle sessions correctly

**Comment by sgdc3** [comment]
@voodootje0 If you are still interested could you check the latest dev builds please? :)

**Comment by voodootje0** [comment]
@sgdc3 Can you explain what is changed since my current version? This is really necessary since nothing may break, there are total 1653018 users in the database.
Now I'm using AuthMeReloaded v5.2 build 1530.

Database structure now.
![image](https://user-images.githubusercontent.com/6852308/31671912-5ee29fc2-b35b-11e7-81a1-2f5ba459a823.png)

Also, do I need to use AuthMeBridge when updating?

**Comment by voodootje0** [comment]
@sgdc3 @ljacqu ^

**Comment by sgdc3** [comment]
Sorry xD

We didn't break any expected behaviour atm, we added an hasSession column to the db schema and changed how session internally works, in order to make it working on bungee networks, you can use AuthMeBridge with the latest builds. ;)

**Comment by sgdc3** [comment]
If you have any issue you can revert to the previous version without having to rollback anything ;)

**Comment by sgdc3** [comment]
Ah, we recently deprecated some unsalted password hash types, but if you are using SHA256 you are already ok :)

**Comment by sgdc3** [comment]
I'm currently using this feature in my server, it is working perfectly ;)
