### ISSUE TITLE
Disable VIP-kick

### ISSUE THREAD

**Issue by AkitakiLab** [AuthMe/AuthMeReloaded#1040]
On my server with Authme, when an OP joins (with authme.vip permission), a random person get kicked with the message "A VIP player has joined the server when it was full!".
Is there a way to keep this function while not kicking people?
I'd like the OPs to join even if it's full.

Thanks in advance

**Comment by ljacqu** [comment]
Good input; I think this should be easy to do. Note that if you're using Essentials I'm fairly sure they have exactly this feature. In that case I would suggest to use Essentials' and not to assign the AuthMe VIP perm to anyone.

**Comment by AkiraTaki** [comment]
Thanks for the quick reply :D
I had once thought of using the one in Essentials before but with no luck, after that I never tried it. Maybe I can test it again to see if it work (with Authme installed at the same time)

**Comment by YellowZaki** [comment]
This is the same issue I posted https://github.com/Xephi/AuthMeReloaded/issues/1001
@ljacq said it was not an authme fault, but I think yes it is. Because the kick message comes from Authme.

**Comment by Pluginsel** [comment]
Add option in config.yml 
VIP-kick: true

**Comment by Pluginsel** [comment]
Please add option in config.yml
VIP-kick: true
@ljacqu

**Comment by sgdc3** [comment]
@Pluginsel if you don't give the vip permission it is already "disabled"

**Comment by ljacqu** [comment]
Just so it's documented in this issue: the solution is to not assign the authme.vip node by default to OP players, cf. #1512:

> I think this is the best solution, better than implementing a case to not kick anyone when an OP player joins.
There's Essentials and other plugins for allowing more people than maximum slots.
