### ISSUE TITLE
New command event to Commands.yml: first login

### ISSUE THREAD

**Issue by belfedia** [AuthMe/AuthMeReloaded#1046]
I keep an eye on commands.yml

# Supported command events: onLogin, onJoin, onRegister
# onFirstLogin :
#  welcome:
#  command: 'give %p Cobblestone '
#  executor: 'PLAYER'**

Could you add a firstlogin event ? :)
I register only on my forum, and i search a clue to give some objects, make a global welcome to new player :)

**Comment by ljacqu** [comment]
I'm guessing you want commands to always fire if a user is not registered—not only the first time a user appears on the server? :)

**Comment by belfedia** [comment]
I want an event on first login, not first registrer or first time on server.
With inventory protect, i can give to new player item, only when they make a sucessfull /login.

**Comment by SaitDev** [comment]
+1 for this

**Comment by ljacqu** [comment]
hi @belfedia @SaitDev this is available on newer builds (n. 1880 and above) at http://ci.xephi.fr/job/AuthMeReloaded/
I would be thankful for some feedback - is something not how you expect it, or can we close this issue?

**Comment by SaitDev** [comment]
its avaible on release 5.4 version too?

**Comment by ljacqu** [comment]
It's not, it was added right after the 5.4 release

**Comment by belfedia** [comment]
Thanks i try it :)
