### ISSUE TITLE
Remove 'removeSpeed' option

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1054]
The fly speed which set by Authme is more than the default. (Walk speed is okay)

**Comment by sgdc3** [comment]
@DNx5 Any ideas? :/

**Comment by Twonox** [comment]
I've say bullshit, sorry.
`removeSpeed: true` just doesn't work... :/

**Comment by sgdc3** [comment]
Could you post your plugin list?

**Comment by Twonox** [comment]
Authme and Essentials.
Idk if you know but to reset my speed it's necessary to reset speed data stored by authme AND by the main world (playerdata.dat).

**Comment by sgdc3** [comment]
@DNx5

**Comment by ljacqu** [comment]
@Twonox `settings.restrictions.removeSpeed` only has effect if `settings.restrictions.allowMovement` is set to false. Might this be the issue?

**Comment by Twonox** [comment]
@ljacqu #1036 
So, this issue is solved if we no longer need `removeSpeed` setting.

**Comment by ljacqu** [comment]
@Twonox `removeSpeed` has been removed — speed is now removed if `settings.restrictions.allowMovement` is enabled.
