### ISSUE TITLE
Bungee teleport setting break AuthmeBridge

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1061]
When `bungeecord` setting is `true`, a new registered player must type his login after the teleportation in other server by authme.

**Comment by sgdc3** [comment]
That's because we deleted all the plugin message listeners

**Comment by sgdc3** [comment]
We need to implement them again

**Comment by sgdc3** [comment]
I just closed #197 as we should implement a new bukkit <-> bukkit and bukkit <-> bungee protocol

**Comment by Twonox** [comment]
Any solution? It's urgent :/

**Comment by sgdc3** [comment]
@Twonox AuthMeBridge should work fine, could you test it?

**Comment by Twonox** [comment]
OK, I will redo my test.

**Comment by Twonox** [comment]
There is still this problem.
I remind that there is this issue only for players who have just been registered. If they join after his registration, they are successful login with AuthmeBridge.

**Comment by sgdc3** [comment]
@ljacqu this is the last issue we need to fix to release, what do you think about it? Maybe caching issue?

**Comment by ljacqu** [comment]
@sgdc3 Nothing comes to mind currently, if I look at the registration code I see in three clicks where we update the DB to set logged = TRUE... Hmm. But please keep in mind I know very little about the Bungee part

**Comment by Twonox** [comment]
Any solution ?

**Comment by sgdc3** [comment]
We completely changes how this work, this issue is now invalid

**Comment by ljacqu** [comment]
I'm conflicted about keeping this in the milestone because we didn't do any work for this issue, but is this bug fixed (players don't have to use /login anymore after registering)? If so, fine for me to keep it in 5.4 milestone, since the bug was fixed somehow.
