### ISSUE TITLE
Commands.yml new command event: onSessionLogin

### ISSUE THREAD

**Issue by HLF-Raideer** [AuthMe/AuthMeReloaded#1090]
Hello!

I want to suggest you a new command event to the commands.yml file.
Actually there is onLogin, onJoin, onRegister, my idea is to add a new **onSessionLogin** event to identify players who were already logged in. I want to execute commands if they are logged in during the login.

That's all! Thank you for maintaining this awesome plugin :)

**Comment by molor** [comment]
another improvement: Make the ability to limit these events for some players only.
For example, **onLogin** event will be executed only in case if the player has a nickname **plaaayer**.

**Comment by ljacqu** [comment]
@molor Thanks for your input. To keep some order I created a new issue with your suggestion. You (and everyone else) is very welcome to post more examples you would find useful :)

**Comment by ljacqu** [comment]
@sgdc3 Would this be a good story for you? :) It would be nice if someone else worked on the forced commands to share the knowledge.

**Comment by sgdc3** [comment]
@ljacqu It's fine for me, if you want i can work on this, i'm just a little busy this weekend ;)

**Comment by ljacqu** [comment]
@sgdc3 It would be nice! :) And there's no hurry :smile:

**Comment by ljacqu** [comment]
@sgdc3 Is this on your radar? ;) :smile:

**Comment by sgdc3** [comment]
yep!

**Comment by HLF-Raideer** [comment]
And when do you want to add it to the plugin? :D
.. because i posted this ticket 2 months ago xD

**Comment by sgdc3** [comment]
When i'll have time, maybe today, maybe the next week, who knows :P

**Comment by sgdc3** [comment]
Ok, i'll try to do that this weekend

**Comment by sgdc3** [comment]
@HLF-Raideer Does it work? ;)

**Comment by ljacqu** [comment]
It might be worth to note that these commands are run at a time when the player is not yet logged in.

**Comment by sgdc3** [comment]
I think we can close that.

**Comment by ljacqu** [comment]
tested successfully
