### ISSUE TITLE
Implement Redis Database

### ISSUE THREAD

**Issue by Xephi** [AuthMe/AuthMeReloaded#110]

**Comment by sgdc3** [comment]
Bump

**Comment by sgdc3** [comment]
@ljacqu @DNx5 @games647 What do you think about this? ;)

**Comment by ljacqu** [comment]
kicking this out of 5.3 in favor of issues marked as critical. If someone wants to do this or if there is some demand for this from our users, it can be added back

**Comment by sgdc3** [comment]
Ok ;)

**Comment by sgdc3** [comment]
Closing, no demand for this featue

**Comment by Xephi** [comment]
@HexelDev

**Comment by sgdc3** [comment]
Closing this issue as there is no point in using a redis db as the main datasource, redis could be useful to implement a messaging service to keep instances in sync instead.
