### ISSUE TITLE
Sign interaction during /register

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1111]
During register process a player can interact with a sign, but he shouldn't.

**Comment by ljacqu** [comment]
What's the sign type? i.e. from which plugin?

**Comment by Twonox** [comment]
BungeeSign

**Comment by sgdc3** [comment]
Maybe the plugin is listening at the event at lowest priority for no reasons -_-

**Comment by Twonox** [comment]
Woups, same issue during /login ... :/

**Comment by Twonox** [comment]
Is there any solution ?

**Comment by sgdc3** [comment]
Can't do anything about that, that's a problem with BungeeSigns code: the devloper should add ignoreCancelled = true to the interact listener
