### ISSUE TITLE
Email message duplication

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1117]
<a href="https://www.noelshack.com/2017-09-1488409928-2017-03-02-001032.png"><img src="https://image.noelshack.com/minis/2017/09/1488409928-2017-03-02-001032.png" border="0" alt="1488409928-2017-03-02-001032.png - envoi d'image avec NoelShack" title="1488409928-2017-03-02-001032.png"/></a>
<a href="https://www.noelshack.com/2017-09-1488409930-2017-03-02-001047.png"><img src="https://image.noelshack.com/minis/2017/09/1488409930-2017-03-02-001047.png" border="0" alt="1488409930-2017-03-02-001047.png - envoi d'image avec NoelShack" title="1488409930-2017-03-02-001047.png"/></a>

**Comment by ljacqu** [comment]
@Twonox, thanks for bringing this up—

I've removed `email_exists` from all files, as well as `unsafe_spawn`. They've been unused since at least 5.2 Beta 3. I created a technical task to easily search for unused message keys in the future.

OK to close?
