### ISSUE TITLE
Security for /email show

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1119]
A player who hack an account with a register email can easily see the registered email to be able to change it using /email change
So, I don't have any solution to suggest... just to remove that command but idk if this command is used frequently.

**Comment by sgdc3** [comment]
we should move it to the admin permissions subgroup

**Comment by ljacqu** [comment]
/email show was requested because there's no way for a user to see his own email address otherwise. We could add a permission to it (in the `authme.player.*` branch) so it may be disabled.

**Comment by sgdc3** [comment]
Yeah, you're right

**Comment by Twonox** [comment]
Other thing:
The email commands are not hidden. If that's normal, I think you should add those commands to the list of hidden commands for security reasons.

**Comment by Maxetto** [comment]
I'll also add this security issue as another case for this.
If you hack an Account who has email, you can unregister it and register it back in order to give it another email and make it impossible to recover.

**Comment by sgdc3** [comment]
@HexelDev i'm a bit busy with my network atm, could you fix this in the meantime?
