### ISSUE TITLE
Authme And Xenforo/IPS

### ISSUE THREAD

**Issue by MrErne** [AuthMe/AuthMeReloaded#1122]
### What behaviour is observed:
Hello, we can't use xenforo with authme because the user information is in 2 different tables

### Steps/models to reproduce:
I have a Xenforo forum and an Ips forum to. I want use Ips ou Xenforo with authme but xenforo support doesn't work and Ips are not supported.

### Environment description
MySql - Linux

### AuthMe build number:
Latest

### Error Log:
Wrong Pass word

**Comment by Krokit** [comment]
@MrErne Hi, so you have 2 forums, one is with XenForo others is with IP Board(IPS) and you want to use Authme on both?
Ip board is self hosted or paid from their service(IPS)?
If IPB is paid you can't use authme. If is self hosted and version of IPB is 4.x.x script will work(I make some improves, right now i m working on xenforo).

**Comment by MrErne** [comment]
Hello, 
I have IPB 4.1.18 and i finaly find the config to make authme great with the BD.
However the register are so difficult, because I can't fix the default group of the user for example and if I want to use Email verification, the plugin doesn't register the line into the right table.

If you want I cant give you the Sql schema of the different table.

Yes, Xenforo need maybe some update :) 👍 

So if you can make configuration to register people from the game to the forum (With api or directly with on the BD) I I will be very grateful

Thank you :)

**Comment by Krokit** [comment]
@MrErne See this [pull](https://github.com/AuthMe/AuthMeReloaded/pull/228).  😄  I' m working on Xenforo but forum script is little s***.  Also i will check this for email verification.

**Comment by ljacqu** [comment]
@MrErne how is the IPB 4 integration now? @Krokit submitted some changes a few weeks back.
