### ISSUE TITLE
Bungee offline all countrys banned

### ISSUE THREAD

**Issue by woodzykiler** [AuthMe/AuthMeReloaded#1123]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
What happened? User tries to login gets Your country is banned

### What behaviour is expected:
What did you expect? the user to login just fine

### Steps/models to reproduce:
The actions that cause the issue
Bungee based setup with Bungee offline, and sub servers Offline

### Plugin list:
This can be found by running `/pl`
[17:04:26 INFO]: Plugins (15): NoCheatPlus, WorldEdit, VotingPlugin, ServerSelec
torX, PermissionsEx, BuycraftX, Vault, Votifier, WorldGuard, BungeePortals, Esse
ntials, EssentialsProtect, EssentialsSpawn, AuthMe, AuthMeBridge
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungee, MySQL
### AuthMe build number:
This can be found by running `/authme version`
AuthMeReloaded V5.2 Build: 1542
### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
http://pastebin.com/vxLmCqnj
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
http://pastebin.com/yRUJWCL5

**Comment by sgdc3** [comment]
could you post your bungee and spigot config files? (remember to remove any personal data)

**Comment by sgdc3** [comment]
@woodzykiler
