### ISSUE TITLE
Authme Bridge (bungee)

### ISSUE THREAD

**Issue by Bodyash** [AuthMe/AuthMeReloaded#1130]
Hi, few days ago i found a fork of AuthmeBridge by Authme team, but its not working. Bungee part is ok, i think. But Authme bukkit plugin doesnt send correct data to bridge, so players cant do nothing after login.

**Comment by ljacqu** [comment]
Hi, indeed, we scrapped the BungeeCord code in AuthMe a while back. We desperately need a developer to create a bungeecord integration.

**Comment by ljacqu** [comment]
@sgdc3 Can we close this, since we have the new BungeeSender and BungeeReceiver now?

**Comment by sgdc3** [comment]
yes
