### ISSUE TITLE
sendTo 'server' and sessions

### ISSUE THREAD

**Issue by Dimatert9** [AuthMe/AuthMeReloaded#1133]
sendTo 'server' dont work with sessions enable. When you join and session active you will not teleport to other server.

**Comment by BabelSolea** [comment]
upd more datail case:
if in config sessions: true with some timeout

1. join to server 1
2. enter reg/login
3. not moved to server 2
4. disconnect server 1
5. join to server - ure loading in needed server 2 =)
but anyway that bad user expirience.

**Comment by BabelSolea** [comment]
i think would be awesome if ure add option instead of sendto server:

execute command after reg/login.

we put there server X and thats will work 100% and if somewhen syntax of command will changed - we can change it with out needed wait update plugin)

**Comment by sgdc3** [comment]
It sounds very strange, @ljacqu do you have any ideas why session breaks the normal join process?

**Comment by Dimatert9** [comment]
Maybe player dont fully join to server and player.sendPluginMessage() dont work?

**Comment by Dimatert9** [comment]
Changed this code https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/service/BungeeService.java#L44-L47 to
```
        Bukkit.getScheduler().runTaskLater(plugin, new Runnable() {
            
            @Override
            public void run() {
                ByteArrayDataOutput out = ByteStreams.newDataOutput();
                out.writeUTF("Connect");
                out.writeUTF(bungeeServer);
                player.sendPluginMessage(plugin, "BungeeCord", out.toByteArray());                
            }
        }, 5L);
```
and now sessions work good.

**Comment by Dimatert9** [comment]
https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/
`Keep in mind that you can't send plugin messages directly after a player joins(Eg. in PlayerJoinEvent). You have to include a slight delay.`

**Comment by sgdc3** [comment]
Nice catch, i'll commit this change right now ;)

**Comment by Dimatert9** [comment]
I think it need change to 10L or 15L, because players with low internet speed can has issues.

**Comment by sgdc3** [comment]
I hope 1 second is fine xD

**Comment by BabelSolea** [comment]
I didn't changed any in code or config/versions/server build, but now plugin send players without any problems!

But I found another case:
With bungee player sended can join to bengee with second acc with another name And play multiple accounts with ip-per-player=1 in authme config :(
I think ure all know that case, so how ure (pls) can help me fix that case?

**Comment by Dimatert9** [comment]
@sgdc3 why there is no jenkins build?
