### ISSUE TITLE
Create Wiki page about LimboPlayers

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1139]
I need an issue for this so I don't forget... :)

**Comment by ljacqu** [comment]
Hi @Gnat008 , could I ask you to have a look? I'm especially interested in a review of the first link, which is aimed at users of AuthMe (no technical background).

https://github.com/AuthMe/AuthMeReloaded/wiki/Limbo-players <- aimed at users
https://github.com/AuthMe/AuthMeReloaded/wiki/Limbo-architecture <- aimed at devs

**Comment by Gnat008** [comment]
In the Timing / Overriding Issue section of the first page, maybe a good idea to tell users where in the config the restoring options are (for easier Ctrl+F'ing, perhaps).

Other than that, both look good to me!

**Comment by ljacqu** [comment]
Thanks a lot for the feedback! I've added:

> You can find these settings in your config.yml under "limbo".

If this is OK, I invite you to close the issue, otherwise I'll need to revise the page again ;)
