### ISSUE TITLE
Conversion from Sqlite to MySql not works, no errors

### ISSUE THREAD

**Issue by Behoston** [AuthMe/AuthMeReloaded#1143]
### What behaviour is observed:
What happened?
Migratoion from Sqlite to MySql convert only last players

### What behaviour is expected:
What did you expect?
Convert whole database from Sqlite and upload to mysql or generate .sql file

### Steps/models to reproduce:
The actions that cause the issue
Existing database using Sqlite, then configure mysql connection (with ssl) and type `authme conv sqliteToSql` 

### Plugin list:
This can be found by running `/pl`
` AuthMe, WorldEdit,` (I have two servers, this plugins I have on both of them, and both don't work)

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone and bungee, from SQLite to MySql

### AuthMe build number:
This can be found by running `/authme version`
1542

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
no errors 
```
>authme conv sqliteToSql
[10:32:02 INFO]: [AuthMe] Successfully started sqliteToSql
[10:32:02 INFO]: [AuthMe] SQLite driver loaded
[10:32:02 INFO]: [AuthMe] SQLite Setup finished
[10:32:03 INFO]: [AuthMe] Skipped conversion for players which were already in MYSQL: chwast, behoston # this two players has been saved, don't know why
[10:32:03 INFO]: [AuthMe] Database successfully converted from SQLITE to MYSQL
```

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
http://pastebin.com/14QDigNx 

I have valid table with group and salt columns

**Comment by ljacqu** [comment]
Note that using the `sqliteToSql` converter requires the SQLite database file to be in AuthMe's plugin folder under the name configured in `DataSource.mySQLDatabase`. In the config you post, this means your SQLite file needs to be called `minecraft.db`. Is this what you have been trying to do so far or might this be the source of the issue?

**Comment by sgdc3** [comment]
@Behoston

**Comment by sgdc3** [comment]
@Behoston
