### ISSUE TITLE
Conversion to AuthMe

### ISSUE THREAD

**Issue by XxEnder12xX** [AuthMe/AuthMeReloaded#1144]
I'm changing my auth plugin to AuthMe, actually I'm using CrazyLogin (MYSQL) and I want to convert all the data to AuthMe, but I can't beacuse the Authme conversor only is able to be used with flat file (.db).

Any ideas?

Thanks

**Comment by ljacqu** [comment]
I think this can be done easily~ If you allow me up to two weeks to do this I can deliver ;) Is that OK?

**Comment by XxEnder12xX** [comment]
Okay, how can I send you the database?

Thanks

**Comment by ljacqu** [comment]
Sorry for the wait – could you send me a dump to my email? It's my Github username @ hotmail.com

**Comment by ljacqu** [comment]
Haven't heard back + no one else requested this -> closing
