### ISSUE TITLE
Merge SingleFilePersistenceHandler with SegmentFilePersistenceHandler

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1147]
SingleFilePersistenceHandler uses a single file to store all limo players, this is basically the same as the `SegmentFilePersistenceHandler` with a size of `ONE`.

The only difference is that the former stores all limbo players into memory, which could be done within SegmentFilePersistenceHandler if the size is ONE.

Advantage of removing SingleFilePersistenceHandler is that it's confusing to the user to have two possibilities to store all data into one file, and SegmentFilePersistenceHandler is able to migrate all data if its segment size changes, whereas changing from SingleFilePersistenceHandler will lose all data. 

Edit: changed "holder" to "handler"

**Comment by ljacqu** [comment]
@sgdc3 Goal of this issue is to make the configs as clear as possible to the user. 
One thing I wonder about is: should I rename segments to something else? I consciously tried to avoid using "group" because it's not a natural group like permission groups, it's just a distribution based on the uuid

**Comment by sgdc3** [comment]
What about distribuited holder?

**Comment by ljacqu** [comment]
xD Just realized in this entire issue I keep calling them holders—they're actually _handlers_.  I like the idea of distributed and will rename it accordingly, thank you! :)

**Comment by ljacqu** [comment]
@sgdc3 Please check if it looks OK? :)

**Comment by sgdc3** [comment]
@ljacqu It looks ok, look at the comments on the first commit. ;)

**Comment by ljacqu** [comment]
Thank you for looking over it! :smile: Your comments are replied to
