### ISSUE TITLE
Error on forceLogin with FastLogin

### ISSUE THREAD

**Issue by hsombini** [AuthMe/AuthMeReloaded#1151]
Exception on login with premium account using FastLogin, it used to work on ealier builds, it's already reported to the manager of FastLogin and he confirmd that the bug it's on AuthMe side.

### Environment description
Waterfall / TacoSpigot 1.8.8 + Some V2 Timings cherypick, also tested with PaperSpigot 1 .8.8

### AuthMe build number:
Build 1634

### Error Log:
https://hastebin.com/tuqexuheti.sql

**Comment by ljacqu** [comment]
@games647 May I ask you for an initial analysis? What's weird is from the stacktrace it seems to me that we restore "allow flight" in sync mode, so I'm surprised at the error. The last AuthMe code lines:
[LimboService#restoreData](https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/data/limbo/LimboService.java#L106)
[AllowFlightRestoreType#restoreAllowFlight](https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/data/limbo/AllowFlightRestoreType.java#L41)

**Comment by games647** [comment]
Then it's my bad. Previously the API scheduled a new task instead of directly executing it.

**Comment by games647** [comment]
Correction:
@ljacqu FastLogin calls the NewAPI async where it calls the **AsynchronousLogin**. This is what I expected, but then it jumps into a sync task and executes it in a async context. 

I think  [scheduleSyncTaskFromOptionallyAsyncTask](https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/service/BukkitService.java#L83) doesn't work as expected.

**Comment by ljacqu** [comment]
@games647, thank you!

I understand the issue now. FastLogin calls our NewAPI#forceLogin in async mode, and because @hsombini has set `async` to `false` in AuthMe, `scheduleSyncTaskFromOptionallyAsyncTask` won't create a sync task (because it assumes it can't be coming from an async source).

I'll only be able to look at this into detail in two or three days and I'm not quite sure how this should be fixed right now. Do you have a suggestion?

**Comment by games647** [comment]
What do you think https://github.com/AuthMe/AuthMeReloaded/compare/thread-check ?

**Comment by sgdc3** [comment]
@games647 Nice fix, i didn't know bukkit had such method.

**Comment by ljacqu** [comment]
@games647 Excellent, that looks really nice! Thank you
