### ISSUE TITLE
Group isue with Pex

### ISSUE THREAD

**Issue by sgdc3** [AuthMe/AuthMeReloaded#1155]
From a comment on the devbukkit page:

> We use Pex permissions, and we have some players which are in multiple groups at once. When they relog they loose one of their groups, I presume it is because of this:
Permissions group switching on un-logged-in
Is there a way to fix this?

> Solution. Turn enablepermissioncheck to false in the config.

**Comment by ljacqu** [comment]
I've been working on this within #761. I would like the user to check with a newer build and to provide feedback. The reason it's still open is that I want to test it more.

**Comment by sgdc3** [comment]
Thank you
