### ISSUE TITLE
Multiple logins for the same player

### ISSUE THREAD

**Issue by hsombini** [AuthMe/AuthMeReloaded#1158]
Some players are getting weird multiple clones on login, these clones stay on the spawn logged in and do not disappear after the original player logout, on player lookup with tab, it show the player with same nick multiple times, on tab list, it shows the original player plus a number suffix as you can see on the screenshots, I don't know if it's related to AuthMe or not, but I really need help with this issue, the players loses the inventory on logout when this happens.

[Lookup for with tab on a player with this problem](https://files.gitter.im/Xephi/AuthMeReloaded/puzo/WhatsApp-Image-2017-04-01-at-10.48.00-PM.jpeg)
[Duplicated player on spawn](https://files.gitter.im/Xephi/AuthMeReloaded/HHKM/duplicated.jpeg)
[Look for Heineken](http://i.imgur.com/tFB2W5N.jpg)

### Things I already done
* Tested without the plugin SkinRestorer
* Disabled limbo on authme
* Wiped all UUID folder (playerData)
* Tested without the AntiBotDeluxeEx

### Plugin list:
https://hastebin.com/nusewiribi.diff

### Environment description
Standalone server on MySql

**Comment by Twonox** [comment]
Mhmm...
I remember exactly the same issue in my server, but the cause was SkinRestorer and a little incompatibility with SuperVanish & SkinRestorer.
Could you remove SkinRestorer AND VanishNoPacket to see if the issue persist ?

**Comment by Twonox** [comment]
Your issue is it solved ?

**Comment by hsombini** [comment]
@Twonox I just fixed few hours ago, the problem was related with the plugin Instant Respawn plus any combatlog, I think that this issue may be closed, it was not related to AuthMe but your advice gave me some directions.

Thanks!
