### ISSUE TITLE
Other players can register with my account using upper/lower case character

### ISSUE THREAD

**Issue by cengiz77** [AuthMe/AuthMeReloaded#1161]
Hi! I run a spigot 1.8.8 minecraft server and I'm the owner of my server. Someone registers with my account using lower case character (My nickname is YuzdeYuzTavuk and he registered with yuzdeyuztavuk). He/She destroyed everything and griefed all maps of my server. Do you devs have any solution for this? Best regards! :)

**Comment by sgdc3** [comment]
Sure, in 5.2 we introduced a new option: "preventOtherCase" if i remember well ;) Just enable it and restart your server!
