### ISSUE TITLE
Drop usage of the old API, rename NewAPI

### ISSUE THREAD

**Issue by sgdc3** [AuthMe/AuthMeReloaded#1162]
Will break support with many plugins, but we have to do that at some point!

**Comment by ljacqu** [comment]
Can we at least keep NewAPI's name in 5.3 and mark it as deprecated? Along with the new name so devs can make the switch

**Comment by sgdc3** [comment]
Sure ;)

**Comment by timvisee** [comment]
I'd recommend to name any new APIs with a version number, for example `ApiV2` or give it it's own package like `api.v2.Api`. That wouldn't require the need to rename it again any time in the future ;)

**Comment by sgdc3** [comment]
@ljacqu @timvisee

**Comment by ljacqu** [comment]
@sgdc3 Thanks for doing this, left some individual comments.

I don't expect we'll change much to the v3 API, so I would suggest to make NewAPI extend from v3.AuthMeAPI:

```java
public class NewAPI extends AuthMeAPI {
  // we get all the static methods like this!
  //  Only need to keep the "getInstance" method
}
```

**Comment by Xephi** [comment]
As i've said on discord, we'll push a 5.2.1 Release with this breaking change on api, to allow dev make the transition before we release a 5.3 ;)

**Comment by ljacqu** [comment]
Why not just release the current state as 5.3 soon?

**Comment by sgdc3** [comment]
> I don't expect we'll change much to the v3 API in 5.3, so I would suggest to make NewAPI extend from v3.AuthMeAPI:

public class NewAPI extends AuthMeAPI {
  // we get all the static methods like this!
  //  Only need to keep the "getInstance" method
}

How to handle the constructor?

**Comment by ljacqu** [comment]
@sgdc3 Aye, good point, the v3 API constructor would have to be public for it to work... OK, fine to keep both classes as they are in my opinion.

**Comment by sgdc3** [comment]
Ok! I think we can close now ;)
