### ISSUE TITLE
Converting auths.db in authme.db

### ISSUE THREAD

**Issue by yooteri56** [AuthMe/AuthMeReloaded#1163]
I put the latest version of the plugin and authme started the conversion.
All the names are now with lowecase letters (example: A name in auths.db is "Whisper", in authme.db it becomes "whisper", so he can't log in with "Whisper"). I tried to disable preventOtherCase, but if i do it, hackers'll grief my server. Do you devs have any solution for this? Best regards! :)

**Comment by sgdc3** [comment]
So you did the FLATFILE -> SQLITE convertion, right?

**Comment by yooteri56** [comment]
Yes, by an older version of authme to the newest version

**Comment by sgdc3** [comment]
What's your plugin version?

**Comment by sgdc3** [comment]
It have been fixed in this commit: https://github.com/AuthMe/AuthMeReloaded/commit/009d82c0a944c1ae278d28deff1403d9a927cf72

**Comment by sgdc3** [comment]
Just use latest dev build from our jenkins server
