### ISSUE TITLE
Not Teleporting on login

### ISSUE THREAD

**Issue by LoXR** [AuthMe/AuthMeReloaded#1168]
####Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

### What behaviour is observed:
What happened? **Using the latest DEV build. But the plugin use to teleport players back to their location after login, but its not teleporting players back to last location on login.**

### What behaviour is expected:
What did you expect? **Authme 5.2 teleported players back to their last location on login, 5.3 Dev doesn't**

### Steps/models to reproduce:
The actions that cause the issue **Unsure**

### Plugin list:
This can be found by running `/pl` **Kept Private**

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ... **Spigot 1.11**

### AuthMe build number:
This can be found by running `/authme version` **AuthMeReloaded v5.3-SNAPSHOT (build: 1651)**

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any) **None**

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data) **https://hastebin.com/fotoqajowi**

**Comment by sgdc3** [comment]
We changed the behaviour of some options, @ljacqu could you check the config file please?

**Comment by LoXR** [comment]
I think its fixed itself actually, I logged on to see if its all good. And it teleported me to last location after login. Will let you know if it doesnt do it, in the latest DEV Build.

**Comment by ljacqu** [comment]
Hello, @sgdc3 is right that we changed the behavior of a configuration. You have "saveQuitLocation: false" in your config, which now has the consequence that we don't save the quit location. If you set it to `true` it should behave like before ;)
