### ISSUE TITLE
Wrong password after conversion from CrazyLogin

### ISSUE THREAD

**Issue by XxEnder12xX** [AuthMe/AuthMeReloaded#1170]
Hello! I've converted all my CrazyLogin database to AuthMe, but when I try to log on with my account It says that the password is wrong, there is no errors in console, also the database is large, it weights 110mb (400k<) accounts.

https://hastebin.com/ovucegebib.bash

https://hastebin.com/ketuvixojo.bash

Thanks.

**Comment by XxEnder12xX** [comment]
I followed this steps: https://github.com/ST-DDT/CommandHelper-CrazyLogin/issues/1

**Comment by Twonox** [comment]
Please put your config here: https://hastebin.com/ and replace your current config text (by editing).

**Comment by XxEnder12xX** [comment]
I've changed that. Please help.

**Comment by Twonox** [comment]
Thanks @XxEnder12xX 

Try yo eplace `passwordHash: 'CRAZYCRYPT1'` by `passwordHash: 'SHA256'` and `legacyHashes: []` by
```
legacyHashes:
- 'CRAZYCRYPT1'
```

**Comment by Twonox** [comment]
@XxEnder12xX Any news ?
