### ISSUE TITLE
Add Premium Mode Support

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1173]
Please add premium mode support on this plugin.

Example : /premium true & /premium false.
On player is accepting /premium true command, kick from the server, after join the server with premium account, and login not required.

İmportant : Need to add /premium confirm command.
İmportant : Is required player is registered on the server.

**Comment by Eufranio** [comment]
FastLogin is probably what you want: https://www.spigotmc.org/resources/fastlogin.14153/

**Comment by sgdc3** [comment]
Exactly, FastLogin is our "official" solution to the problem ;)

**Comment by linsaftw** [comment]
There's also AuthMe Premium which is a modern solution to it.
