### ISSUE TITLE
Taking a backup

### ISSUE THREAD

**Issue by Darko266** [AuthMe/AuthMeReloaded#1175]
Greetings,

I know thats not a error or a bug but i need your help...

So how do i take a backup of a Database that is on the mysql (phpmyadmin) ?

Do i type /authme converter mysqltosqlite ?

If i do that, will the mysql continue to work as it is or it will change in the config from mysql to sql ?

Thanks, hope you can help me :100:

**Comment by sgdc3** [comment]
mysqldump is the best way in my opinion ;)

**Comment by sgdc3** [comment]
Backup: mysqldump –u [username] -p[password] [database name] > outputFile.sql
Restore: mysql -u [username] -p[password] < sourceFile.sql (remember to delete the db first)

**Comment by sgdc3** [comment]
in -p[password]  the absence of spaces is intentional

**Comment by sgdc3** [comment]
@ljacqu what would you prefer to do?

**Comment by Darko266** [comment]
So, do i type this in the console or thru minecraft ?
Or in the phpmyadmin ?

**Comment by sgdc3** [comment]
system console ;)

**Comment by sgdc3** [comment]
also phpmyadmin, look for the export button ;)

**Comment by Darko266** [comment]
The authme (or the HUB) is on a Shared hosting...

So export button works?

**Comment by Darko266** [comment]
So thats it ?
http://prntscr.com/ezt02a

How do i now import it to authme when i want ?

(want to change host's so asking how to do that)

/authme converter sqlitetosql ??

**Comment by ljacqu** [comment]
I thought we had a command for it, turns out we don't

**Comment by ljacqu** [comment]
pphMyAdmin export function would be my suggestion for now :)

**Comment by Darko266** [comment]
But i have now a .sql file
how do i convert it to .db and from .db to mysql (changing hosts)

**Comment by ljacqu** [comment]
There's an Import tab in phpMyAdmin. Otherwise I think you can just run the sql code otherwise :)

**Comment by Darko266** [comment]
Let me try that

**Comment by Darko266** [comment]
The import doesent work...
No data was received to import. Either no file name was submitted, or the file size exceeded the maximum size permitted by your PHP configuration. See FAQ 1.16.

**Comment by ljacqu** [comment]
In phpMyAdmin open the database you want to export, click on the Export tab and just export as SQL. This will generate a SQL file—download it, open the phpMyAdmin page of the server you want to import to, this time select the Import tab and upload that SQL file again.
If you have a large number of entries you can select the "Custom" checkbox while exporting and under "Compression" you can select "zipped" or "gzipped." The import procedure remains the same.

**Comment by ljacqu** [comment]
Failing that, you can convert your MySQL to SQLite and download the resulting auths.db file and copy it over to the other server. Start AuthMe and then you can convert back from SQLite to MySQL.
If I re-read this again I suspect you tried to import the SQLite file into phpMyAdmin.

**Comment by sgdc3** [comment]
Just convert from mysql to sqlite, download the db file and then convert it again to mysql. @Darko266
