### ISSUE TITLE
Server Closed

### ISSUE THREAD

**Issue by Bedesh** [AuthMe/AuthMeReloaded#1176]
When I put this plugin in my server spigot 1.9 it closes only and when I remove the server runs with ease how can I add this plugin without my server shutting itself down?

http://prntscr.com/ezoj4r

**Comment by Twonox** [comment]
Is it Spigot or Legacy version of Authme that you use ?

**Comment by Bedesh** [comment]
I use the version spigot 5.2

**Comment by ljacqu** [comment]
Could you share the contents of authme.log please? (If it's empty/missing please enable logging to authme.log in your config.yml and run tue server again)

Switching to a newer build typically solves this issue but I'm really interested in the authme.log error

**Comment by Bedesh** [comment]
https://pastebin.com/cTVMfGcG

**Comment by ljacqu** [comment]
It's missing Gson — once http://ci.xephi.fr/job/AuthMeReloaded/ is back up, kindly download the legacy.jar

**Comment by Bedesh** [comment]
Page not found

**Comment by ljacqu** [comment]
"Once ... is back up"

**Comment by Bedesh** [comment]
Can you pass a version that works for 1.9 without errors?

**Comment by sgdc3** [comment]
Online now ;)
