### ISSUE TITLE
[SOLVED] Authme says that I owe all the accounts, whitch belongs to other players.

### ISSUE THREAD

**Issue by IsRealMe** [AuthMe/AuthMeReloaded#1177]
### What behaviour is observed:
On login to my server getting message, that I own all players accounts, but i don't.

### Plugin list:
`TTA, UploadSkins, WorldEdit, AnimatedScoreboard, OpenInv, Essentials, PEX-Rankup, NoLagg, LogBlock, PlaceholderAPI, PacketListenerApi, AutoMessage, Multiverse-Core, WorldGuard, ProtocolLib, BestAdminInventory, ChatReaction, SkinsRestorer, ChopTree3, iDisguise, EssentialsChat, PermissionsEx, Vault, TokenManager, PvPManager, MyCommand, EssentialsSpawn, Orebfuscator4, HeadHunter, AuthMe, Auctions, LWC, SilkSpawners, Fe, CTSNC, ChestCommands, Residence, CTSNC_Tablist, MyPet, ChestShop, CTSNC_DisplayName`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
build: 1542

### Configuration:
[https://pastebin.com/R9hx8gmB](https://pastebin.com/R9hx8gmB)

![accerr](https://cloud.githubusercontent.com/assets/27916876/25313495/63e47d78-2838-11e7-8887-7ced632f7a8a.png)

**Comment by ljacqu** [comment]
Localhost server?

**Comment by Eufranio** [comment]
Or BungeeCord with ip-forwarding disabled maybe?

**Comment by jeremy100** [comment]
You may have to activate the "ip-forwarding"

**Comment by IsRealMe** [comment]
@ljacqu yes, it is localhost server.
@Eufranio @jeremy100  it is bungeecord server with ip-forwarding enabled.

**Comment by jeremy100** [comment]
@IsRealMe Do you still get your players' accounts as if they were yours?

**Comment by IsRealMe** [comment]
@jeremy100 yes, i did not changed anything, it was set to ip forwarding to true.

**Comment by jeremy100** [comment]
@ljacqu Ok, possible authme bug?

**Comment by sgdc3** [comment]
Almost impossible, we haven't changed that piece of code recently.

**Comment by sgdc3** [comment]
@IsRealMe you have also to enable bungeecord in the spigot config

**Comment by ljacqu** [comment]
I'm guessing all players have ip 127.0.0.1 in the DB. If it's run locally it's expected behavior. 

Btw on newer builds you can do /authme debug to view DB data and that of online players.

**Comment by IsRealMe** [comment]
@sgdc3 not sure about that, will update when i get to check this.

**Comment by Hissam1048v** [comment]
Hold up not fixed yet, I am getting this problem again
