### ISSUE TITLE
Create backup command

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1180]
Via #1175, we should implement a command that performs a backup.

**Comment by ljacqu** [comment]
If anyone wants to look the code over or test it, please do so and we can close the issue ;)

**Comment by Darko266** [comment]
Did you add that to Authme so i can download and test it out ?

**Comment by Darko266** [comment]
Hm, it works but with mysql not http://prntscr.com/f086oz

Do i need to configure this = http://prntscr.com/f086tz ?
If so, how ?

**Comment by Darko266** [comment]
https://pastebin.com/gTBfubRR the authme.log

**Comment by sgdc3** [comment]
> Do i need to configure this = http://prntscr.com/f086tz ?
If so, how ?

Only if you are using windows as OS

**Comment by Darko266** [comment]
Why is it then not working ?

**Comment by sgdc3** [comment]
Do you have access to the server console? (OS Terminal, not mc console)

**Comment by Darko266** [comment]
Nope, its a shared hosting.

**Comment by sgdc3** [comment]
That's why it can't work

**Comment by sgdc3** [comment]
it works only on self hosted servers
