### ISSUE TITLE
[BungeeCord client]Gateway V0.02

### ISSUE THREAD

**Issue by TheMindaugas** [AuthMe/AuthMeReloaded#1185]
Hello there!
There's an experimental release of BungeeCord AuthMe integration.
Compatible with:
**Any AuthMe version which supports ForceLogin() method and NewAPI constructor, and PlayerLogEvent event**
**Spigot(and Bukkit/Craftbukkit)**
How to install:
-Decompile and readjust build paths accordingly
-Export to /plugins folder of all your backend servers
-Enjoy!
This plugin requires nothing on the BungeeCord side, however, any plugin altering Bukkit-Bungeecord message service is likely to break this client as well.
[Gateway.zip](https://github.com/AuthMe/AuthMeReloaded/files/965323/Gateway.zip)

**Comment by ljacqu** [comment]
Hi, could you maybe provide some context? What does this fix, where does this come from (any links besides an attached zip file?), and what do you expect from us?

**Comment by sgdc3** [comment]
@ljacqu It's just a simple bungeecord integration, the zip seems safe, check it out.

**Comment by ljacqu** [comment]
@sgdc3 OK, so what do we with this?

**Comment by sgdc3** [comment]
Idk, just keep this open if someone needs this feature? xD

**Comment by TheMindaugas** [comment]
As I had said, just throw the JAR file in /plugins folders in all your backend servers.
There's an official resource on Spigot too - and it is here: https://www.spigotmc.org/resources/gateway-authme-bungeecord-client-for-bukkit-spigot.40151/

**Comment by ljacqu** [comment]
Creating an issue typically suggests that you expect some action from our side. Still unsure what your goal is for us to do with this issue.
