### ISSUE TITLE
Startup validation of settings not performed on reload

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1190]
We don't allow to set data source to Flat file anymore, nor do we allow the PLAINTEXT hash algorithm. On start up we notice such cases and perform a mandatory migration.

However, if such values are configured and a reload is performed, AuthMe accepts these values without batting an eye*. We need to perform the same validation as we do on startup in ReloadCommand.

\* the data source cannot be changed on reload so flat file is not an issue

**Comment by ljacqu** [comment]
Hi @HexelDev , OK to close this?

**Comment by HexelDev** [comment]
Yeah, well done ;)
