### ISSUE TITLE
API to access GeoLiteAPI (getCountryName)

### ISSUE THREAD

**Issue by kangarko** [AuthMe/AuthMeReloaded#1194]
Hello,

in the former versions of AuthMe, it was possible to get player's country name by the following methods:

* a) fr.xephi.authme.util.GeoLiteAPI#getCountryName
* b) fr.xephi.authme.util.Utils#getCountryName

Neither of this is present in the current AuthMe. Is there a way to use this in the latest AuthMe please? 

Thank you!

**Comment by sgdc3** [comment]
@kangarko Done ;)

**Comment by kangarko** [comment]
Thanks!
