### ISSUE TITLE
Auth room > Logged room (how? where?)

### ISSUE THREAD

**Issue by BabelSolea** [AuthMe/AuthMeReloaded#1208]
Hello.
How manage config and other files of Authme to get this:

1. when player join to server:
if he not logged
he teleport to room where he can nly /rergister /reg /login /l

after player logged
he auto teleported to spawnpoint in same world

if player join with logged session (sessions > timeout: 180)
he will auto teleported to spawnpoint in same world

---------------

i tried make it but i didnt found where need put this coordinates:

        ForceSingleSession: true
        ForceSpawnLocOnJoin:
            # If enabled, every player that spawn in one of the world listed in
            # "ForceSpawnLocOnJoin.worlds" will be teleported to the spawnpoint after successful
            # authentication. The quit location of the player will be overwritten.
            # This is different from "teleportUnAuthedToSpawn" that teleport player
            # to the spawnpoint on join.
            enabled: true
            # WorldNames where we need to force the spawn location
            # Case-sensitive!
            worlds: 
            - 'world'

where thats ForceSpawnLocOnJoin.worlds ???
![image](https://cloud.githubusercontent.com/assets/23665302/25819942/3d6b9e86-3438-11e7-9b9b-80cadbd2d0c0.png)

**Comment by Twonox** [comment]
There is a file which allow you to add commands on login/register events. It's `commands.yml` in Authme folder. So, you can set authme's spawn in auth room, and `onLogin` event you set a teleportation command like `/tp`.
