### ISSUE TITLE
Add command to find accounts by IP address

### ISSUE THREAD

**Issue by friishon** [AuthMe/AuthMeReloaded#1217]
Can you make an option to find the ip and see how many ip there are similar and what accounts belong?

**Comment by ljacqu** [comment]
Could you make an example please? The command you want to have and the expected output.

**Comment by friishon** [comment]
the command 
/authme ip-search <ip> or <starter ip>
example:
/authme ip-search 41.100

and the output
all the ips which start with this number and the accounts of this ip

ip1 --> account
ip2 --> account
etc

**Comment by ljacqu** [comment]
Thanks for the feedback, @friishon, this is now clear to me.

**Comment by Twonox** [comment]
This is a very good idea that you suggest. I agree.

**Comment by SaitDev** [comment]
Essentials has this with command /seen

**Comment by friishon** [comment]
@SaitDev not all people use essentials, and is different, i suggest to find ip, but not necesary put the all ip, only one part, and then show ips that start as you put and show ip and account
