### ISSUE TITLE
[Security] Make 2FA tokens one use only

### ISSUE THREAD

**Issue by janvostry** [AuthMe/AuthMeReloaded#1219]
It appears that the same 2FA token can be used more than once within a window of 3 minutes, this shouldn't be happening. I think reuse of OTP tokens is a security flaw.
I suggest TwoFactor class should be tracking used tokens in memory and reject any used ones.
(list of <secret,time,token>, so old tokens can be purged from memory, and same tokens, but with different user/secret, are accepted)

**Comment by Xephi** [comment]
Usually, token are time based, i haven't develop on this feature but i know how to implement Google Authenticator compatible TOTP easily, i'll take a look soon an fix that issue

**Comment by ljacqu** [comment]
@Xephi see TwoFactor:

```java
        // Window is used to check codes generated in the near past.
        // You can use this value to tune how far you're willing to go.
        int window = TIME_PRECISION;
```

this could be adapted. I would not suggest to keep track of any used tokens, or to revisit this idea after #1141 as I expect there will be some changes to the whole handling of 2FA.

**Comment by Jamaic230** [comment]
@ljacqu by a definition, OTP (one-time password) is a password that is valid only for one transaction. If you want to follow this definition, you have to keep track of already used tokens, so you can reject them.

**Comment by ljacqu** [comment]
Alright, then I propose to do this after #1141.

**Comment by games647** [comment]
AuthMe implementation uses TOTP-passwords they are time-based and not counter-based.

**Comment by ljacqu** [comment]
hi @janvostry , two years later, but this is now available on the latest dev builds at https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ We're happy to get your feedback on it (if still relevant) and otherwise on no answer we'll consider this resolved in 9 days :)
