### ISSUE TITLE
[Feature request] Add player nickname to commands file.

### ISSUE THREAD

**Issue by RikoDEV** [AuthMe/AuthMeReloaded#1220]
My suggestion is to add player nickname/uuid to commands file.

```
onJoin PLAYER:
onLogin PLAYER:
onRegister PLAYER:
```

**Comment by ljacqu** [comment]
Not sure if your issue is wrongly formatted or if you need to elaborate more

**Comment by ljacqu** [comment]
Is the idea that a command be only run for a certain player?
