### ISSUE TITLE
Double log in

### ISSUE THREAD

**Issue by aescraftbr** [AuthMe/AuthMeReloaded#1223]
### What behaviour is observed:
When you log in, the welcome message is displayed, some seconds later, you are teleported back where you logged in and another welcome message is displayed.
The "logged-in due to session re-connection" message appears too.

### What behaviour is expected:
Expect to not double connect, nor teleport me back to the same place after some seconds

### Steps/models to reproduce:
/login password
you are logged in
welcome messages is shown
you walk some blocks
you are teleported back into the place you some seconds ago logged in
you get the reconnection message
the welcome message is shown again too

### Plugin list:
Coreprotect, bookshelves, dynmap, world edit, 2F4U_windupe, chatmessenger, antiraildupe, skript, openinv, armorstandeditor, SkQuery, AnvilPatch, protocollib worldguard, deathmessagesprime, skellet, skrayfall, shopkeepers, permissionsex, skutilities, vault, simplesit, openaudiomc, authme, changeskin, lwc, openaudiomcskript, actionhealth, signcolors, vanishnopacket, chatex, purpleIRC, SkStuff.

### Environment description
Standalone server

### AuthMe build number:
AuthMeReloaded v.5.2 (build: 1542)

### Error Log:
No error.

### Configuration:
https://pastebin.com/c8GMsKJw

**Comment by sgdc3** [comment]
Try the latest dev build: http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by aescraftbr** [comment]
Yep, it's fix'd.
Thanks!

**Comment by aescraftbr** [comment]
Some players are reporting a no speed bug. 0 walk speed after login. They can only "walk" jumping.

**Comment by jeremy100** [comment]
The temporary fix is: /speed 1
