### ISSUE TITLE
Authme and Buildcraft : problem with quarry

### ISSUE THREAD

**Issue by Floroger** [AuthMe/AuthMeReloaded#1224]
Hi,

I was on a Cauldron server and to use the latest Authme version (5.2 legacy), I have changed to a kCauldron server (1.7.10-1614.201) to use java 8.

On my latest version with Authme 3.4, Buildcraft was ok, Quarry worked with the UnrestrictedName config: 
        UnrestrictedName:
        - '[BuildCraft]'

Today, I have use the same configuration but it doesn't work. Tried few names, but quarry don't break blocks : 

        UnrestrictedName:
        - '[BuildCraft]'
        - [BuildCraft]
        - 'BuildCraft'
        - BuildCraft
        - buildCraft

Could you help me ?

I'm using Buildcraft 7.1.21 (previously worked with buildcraft 6)

Many thanks.

**Comment by Eufranio** [comment]
Use [Thermos](https://github.com/CyberdyneCC/Thermos).

**Comment by Floroger** [comment]
No other soluce ?

**Comment by Floroger** [comment]
Someone can confirm me that this 5.2 is ok with Buildcraft ? Thx

**Comment by Floroger** [comment]
No reply ? I close the ticket, no help, no informations. I will searche the soluce myself or I will use another plugin with support. Thx.

**Comment by sgdc3** [comment]
@Floroger It should work, just try it.

**Comment by Floroger** [comment]
I'm very sorry, I have tried all the things possible like to OP the "user" Buildcraft but I'm not ok with that. I have used the same config that my Authme 3.4, perhaps the problem is with my new Buildcraft version I don't know. This night I will test with the debug log (I haven't try that before because I waited a reply).

**Comment by sgdc3** [comment]
By looking at BC source: https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/BuildCraftCore.java#L200

**Comment by sgdc3** [comment]
what's the exact BC version?

**Comment by Floroger** [comment]
I'm a web developper and I manage my Debian server since more than 10 years. I'm doing this Minecraft server for my nephew and all bugs with all plugins or mod, it's not vey simple for me because I don't know how to code in java.

Like the BC Source, I'm using the [BuildCraft] name on Authme and I have op this fake player.
I have launch the server to test the debug mode (hope it will help me to understand what is the problem, read logs is my life :) )

**Comment by Floroger** [comment]
The debug mode don't help me.

[Buildcraft] user is op : 

  {
    "uuid": "816a2b0d-de09-3d09-b61e-2c1754725ba2",
    "name": "BuildCraft",
    "level": 3
  },
  {
    "uuid": "c1fc3ace-e6b2-37ed-a575-03e0d777d7f1",
    "name": "[BuildCraft]",
    "level": 3
  },

I will search a debug mode with BuildCraft.

My exact BC version as I said on my first post is 7.1.21

**Comment by sgdc3** [comment]
> My exact BC version as I said on my first post is 7.1.21

Whoops, sorry, i missed that.

**Comment by Floroger** [comment]
I'm comparing the Buildcraft configs (with my previous versions). If nothing I will try to use another version of Buildcraft. I have read The Githug issues of Buildcraft and on few tickets, the reply is simple : see with Authme support.

I think, like my previous test server, If I'm disabling Authme the Quarry will work (I have worked a lot for the previous version to work fine with Buildcraft and Authme, but for this new version I have no idea I have tried all).

**Comment by sgdc3** [comment]
It's strange, we allow any action made by unrestricted users, it seems like a BC issue, i should check how they handle the quarry in new versions.

**Comment by Floroger** [comment]
I can use another version. I have changed Because one pipe will crash the server. I'm making test without Authme. But Like as I said 20 days ago, I was just searching someone else with Buildcraft 7.x and Authme 5.2 that can confirm me it works.

**Comment by Floroger** [comment]
If Authme is disabled, Buildcraft is ok with the quarry. It works.

I have the time and the possibility to make tests, if you have a real debug log version I'm ok to use it. Just the thing that I can say, the soluce to use Thermos wasn't the good soluce. If Builcraft works, that's not the problem. kCauldron and Authme is it ok ?

**Comment by sgdc3** [comment]
Should be fine. This is a jar a debug message (when a player breaks a block)
[AuthMe-5.3.2-SNAPSHOT-legacy.zip](https://github.com/AuthMe/AuthMeReloaded/files/1089705/AuthMe-5.3.2-SNAPSHOT-legacy.zip)
