### ISSUE TITLE
(Question) Does it convert SQLite to MySQL Automatically?

### ISSUE THREAD

**Issue by KKosyfarinis** [AuthMe/AuthMeReloaded#1226]
I was wondering if AuthMe converts from SQLite to MySQL automatically, meaning that the players don't have to use /register again after the conversion to MySQL happens, right? (latest at the time of this post version)

**Comment by sgdc3** [comment]
You have to use a command, more infos at https://github.com/AuthMe/AuthMeReloaded/wiki/Converters
