### ISSUE TITLE
Internal error.

### ISSUE THREAD

**Issue by Tanimsiz** [AuthMe/AuthMeReloaded#1228]
Users try join and Server say 'An internal error occured while attempting to perform this command'
users can't join my server. Please help.

**Comment by sgdc3** [comment]
Please post your server log on pastebin.

**Comment by Tanimsiz** [comment]
https://pastebin.com/bw5VEsth

**Comment by sgdc3** [comment]
Authme 3.4 is not supported anymore, please update to 5.2

**Comment by Tanimsiz** [comment]
My server ownership does not support java 8.

**Comment by Tanimsiz** [comment]
So I can't update to 5.2

**Comment by ljacqu** [comment]
hi @Tanimsiz, if you're paying someone to host your server and are limited to Java 7, I highly recommend taking your business elsewhere. Java 7 has been deprecated since April 2015. https://java.com/en/download/faq/java_7.xml

**Comment by Tanimsiz** [comment]
I will start using another company when the server is over.
