### ISSUE TITLE
Error while entering register command

### ISSUE THREAD

**Issue by Mr-Krab** [AuthMe/AuthMeReloaded#1230]
Plugin version 5.3 latest

See the log

Successful registration

Error while entering command
/reg pass confirm-pass

Only this plugin is installed

Spigot local server

Version: AuthMeReloaded v5.3-SNAPSHOT (build: 1694)

Error log
https://pastebin.com/6bvzUWtF 
or see file
[latest.txt](https://github.com/AuthMe/AuthMeReloaded/files/1034419/latest.txt)

Standart config file

**Comment by sgdc3** [comment]
Seems like an issue on 1.12

**Comment by sgdc3** [comment]
Guava version mismatch may be the cause

**Comment by ljacqu** [comment]
Guess 1.12 uses Guava 21. Some stuff from `Objects` has been dropped. https://github.com/google/guava/wiki/Release21

**Comment by sgdc3** [comment]
We need to fix that, 1.12 support is critical atm

**Comment by sgdc3** [comment]
@Mr-Krab does it work now? ;)

**Comment by Mr-Krab** [comment]
Yes, it's working now.
I noticed one more bug, from time to time the players' speed drops to 0 and the move becomes possible only by jumping. The cause could not be identified, there are no errors in the console, it was corrected by clearing the statistics of the players in the folder with the world.
I'm writing with the help of Google translator, so I apologize if my message is not read correctly.

**Comment by sgdc3** [comment]
@Mr-Krab does it work if you set restoreWalkSpeed to RESTORE_NO_ZERO?

**Comment by Mr-Krab** [comment]
While everything seems to be normal. There is one more bug, the function 'ProtectInventoryBeforeLogIn' does not work correctly with the plugin 'VanishPlayerTool'. She does not hide the item. There are no errors in the console.

**Comment by sgdc3** [comment]
@Mr-Krab Could you please open a new issue for that ;)
