### ISSUE TITLE
Error SPigot 1.11.2 Java 8 LATEST DEV BUILD.

### ISSUE THREAD

**Issue by TheIntelloBox** [AuthMe/AuthMeReloaded#1232]
https://hastebin.com/zumajipahu.bash
https://hastebin.com/robecopija.bash

**Comment by sgdc3** [comment]
You have to use the legacy build now, (from 1.7.10 to 1.11.2 -> legacy jar) (from 1.12 -> spigot jar)

**Comment by TheIntelloBox** [comment]
Where can I find it ?

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by TheIntelloBox** [comment]
Fantastic thanks ! :) And what is HikariCP ?

**Comment by ljacqu** [comment]
Thanks for the feedback! HikariCP is the library we use to interact with the MySQL database.
