### ISSUE TITLE
Can you add a permission for the /email show command too? I don't want players to be able to see their own email too.

### ISSUE THREAD

**Issue by netlangthien** [AuthMe/AuthMeReloaded#1235]
### What behaviour is observed:
What happened?

### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
No content
