### ISSUE TITLE
Errror on login

### ISSUE THREAD

**Issue by Superdarco** [AuthMe/AuthMeReloaded#1237]
### What behaviour is observed:
What happened?
Hi, i have this error for pu /login,

### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number: AuthMe v5.3.1-b1702
This can be found by running `/authme version`

### Error Log: https://pastebin.com/ivAUuffR
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
Please use the legacy jar from now on. More info at #1232
