### ISSUE TITLE
Commands do not work in 1.11.2

### ISSUE THREAD

**Issue by SnowyTSW** [AuthMe/AuthMeReloaded#1242]
Whenever any command is run via the console or in-game, such as /authme reload, it causes an internal error to occur and be projected to console:
https://pastebin.com/hED1Cfk2

I expected the command(s) to be run normally and cause no errors. I run a standalone server without a database, I've used AuthMe before on my server when it was on 1.8, but it doesn't work when switched to 1.11.

After the server is booted up, when any player attempts to login/register or any commands are used in the console, it will cause an internal error. I'm using AuthMe Reloaded version 5.3-legacy (AuthMe-5.3-legacy.jar).

Here is the config data, though not much has changed:
https://pastebin.com/Qmid41FQ

I hope that this can be solved as soon as possible. I really like this plugin for adding an extra layer of protection to my server. :)

**Comment by sgdc3** [comment]
Not authme fault

**Comment by ljacqu** [comment]
Please report this to https://dev.bukkit.org/projects/perworldplugins, thanks :)
