### ISSUE TITLE
Stop using isLogged, use loginExpirationDate instead

### ISSUE THREAD

**Issue by ReaperAngels** [AuthMe/AuthMeReloaded#1243]
Hi, this is not strictly speaking a spigot issue, as I'm accessing your database from Forge. 

Forge has not offline-authentication, and we need something for our forge server. So I looked at your database, and isLogged seemed to be the right choice. However, while being logged into the spigot server, the isLogged field stayed on 0. I spoke to sgdc3 on discord, and he recommended that I start an issue. 

The mod I wrote is very simple, it checks the "realname" field and the "isLogged" field. 

If you require any information, I'll be quite happy to supply it.

Warm regards,

CraftySailor

**Comment by ReaperAngels** [comment]
CraftSailor - Yesterday at 11:12 PM
@sgdc3 Hi, do you have a moment to chat?
sgdc3 - Yesterday at 11:12 PM
Yeah
CraftSailor - Yesterday at 11:12 PM
Need some info about authme please
Specifically the database
sgdc3 - Yesterday at 11:13 PM
Sure
CraftSailor - Yesterday at 11:13 PM
You have a field called "isLogged". Is it not being used anymore?
sgdc3 - Yesterday at 11:13 PM
It should still be updated
CraftSailor - Yesterday at 11:14 PM
OK, let me rather give you some background
I need an authentication mod for forge, and as a quick patch I thought of hooking up with the authme database
sgdc3 - Yesterday at 11:15 PM
You should open an issue on our issuetracker
CraftSailor - Yesterday at 11:16 PM
I looked at the database, and isLogged caught my eye. So the thinking was to just check realname and isLogged to see if someone logged into the spigot server, and then alllow the player access or not
sgdc3 - Yesterday at 11:16 PM
As it's a while since i looked at the db code
CraftSailor - Yesterday at 11:16 PM
This is not really a problem, so I thought I\d just speak to one of you
sgdc3 - Yesterday at 11:16 PM
i think the other devs like ljacqu should be able to tell you if isLogged is still reliable
CraftSailor - Yesterday at 11:16 PM
Well, I tested it
I logged into my test server, I have bungee, spigot and forge setup, same as on the real server
While I was logged in on the spigot server, I checked the database. The field isLogged stayed at 0
My main problem is that there are no updated forge/spongeforge mods for authentication
So that will mean if I can\t use the authme database, I will have to write my own mod for authentication
sgdc3 - Yesterday at 11:20 PM
Probably something is wrong in our code, opening an issue report is the first thing to do
CraftSailor - Yesterday at 11:20 PM
Like I said, it's not for spigot, it's for forge, which you guys don't support
sgdc3 - Yesterday at 11:21 PM
It doesn't matter, the database should contain a consistent value
please open a report, we'll try to figure out the problem asap
CraftSailor - Yesterday at 11:22 PM
Thanks, I'll do so.
And thank you for the time
sgdc3 - Yesterday at 11:23 PM
I'll start looking at the code right now
CraftSailor - Yesterday at 11:23 PM
Thanks. I was thinking the isLogged would contain 1 or 0, to indicate logged in or not
I did leave a message for ljacqu as well
sgdc3 - Yesterday at 11:37 PM
"I was thinking the isLogged would contain 1 or 0, to indicate logged in or not" It should
CraftSailor - Yesterday at 11:37 PM
It should?
OK, so my logic wasn't flawed.
I saw a post on Sponge that you guys will be porting authme to sponge. Is that still in the works?
sgdc3 - Yesterday at 11:55 PM
No, we have no interest in Sponge
I'm building a jar with s simple debug message
CraftSailor - Yesterday at 11:55 PM
Ah, so I might as well write the mod then
sgdc3 - Yesterday at 11:55 PM
"[DATABASE] USER " + user + " SET AS LOGGED"
"[DATABASE] USER " + user + " SET AS UNLOGGED"
CraftSailor - Yesterday at 11:58 PM
Want me to run it?
sgdc3 - Yesterday at 11:59 PM
AuthMe-5.3.2-SNAPSHOT-legacy.jar
5.42 MB
June 7, 2017
CraftSailor - Today at 12:00 AM
Give me a few secs please
sgdc3 - Today at 12:00 AM
While you are online (INGAME) isLogged should be 1(edited)
CraftSailor - Today at 12:00 AM
I'll check
Authme is not hooking up to the database, gives a lot of errors. Are you using mariadb?
sgdc3 - Today at 12:11 AM
it should be compatible with mariadb
CraftSailor - Today at 12:11 AM
0:09:21 WARN]: [Server thread] INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[00:09:23 WARN]: [Server thread] ERROR fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Exception during pool initialization.
[00:09:23 WARN]: java.sql.SQLException: Trying to connect with ssl, but ssl not enabled in the server
[00:09:23 WARN]:        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:682)
[00:09:23 WARN]:        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:397)
[00:09:23 WARN]:        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1013)
[00:09:23 WARN]:        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:481)
I prefer mariadb connecter. I'll delete the config and restart the mysql server
sgdc3 - Today at 12:12 AM
ok just to see if it is a compatibility issue with maria
CraftSailor - Today at 12:12 AM
I actually have mysql server 5.7 installed
That did the trick, fresh mysql server and fresh config
That might have been me, as I missed the ssl
[00:17:40 INFO]: [AuthMe] [DATABASE] USER craftysailor SET AS LOGGED
Checking database
'1', 'craftysailor', 'CraftySailor', '$SHA$d766396fcf40ce8f$51b448d86c0646834614984d613b9ee4013836d907a2ed009e1f08ac1b3c67e6', '127.0.0.1', '1496787460486', '0', '0', '0', 'world', 'your@email.com', '1', NULL, NULL
It shows a 1 now
What did you change?
Logged out, and it stayed a 1
1    craftysailor    CraftySailor    $SHA$d766396fcf40ce8f$51b448d86c0646834614984d613b9ee4013836d907a2ed009e1f08ac1b3c67e6    127.0.0.1    1496787460486    0    0    0    world    your@email.com    1
Ran the query after the logout, waited about 5 seconds
And the 2 NULL's are gone from the back
sgdc3 - Today at 1:01 AM
column names? i'm from mobile
i did't change anything
CraftSailor - Today at 1:01 AM
OK, give me  a second
id, username,realname,password, ip, lastlogin, x,y,z ,world,email, islogged,yaw,pitch
so the last 2 were the null's
sgdc3 - Today at 1:05 AM
yaw and pitch
doesn't matter
CraftSailor - Today at 1:05 AM
third last is isLogged, which has a value of 1
Nope, they are not really important
sgdc3 - Today at 1:05 AM
do you have session enabled?
CraftSailor - Today at 1:05 AM
Yes
sgdc3 - Today at 1:05 AM
ok
CraftSailor - Today at 1:06 AM
Try it without?
sgdc3 - Today at 1:06 AM
so isLogged remains at 1 eveb when you aren't ingame
could you test?
CraftSailor - Today at 1:06 AM
Well, as soon as I logged in, it changed to 1. But stayed at 1 even agter the logout
Sure, shall I disable sessions?
OK, now this is weird.
On login, nowthing changed, as it was showing 1 already.
On logout, it changed to 0
On dc, it changed to 0
But that's not the weird part
This is
[01:08:28 INFO]: [AuthMe] MySQL setup finished
On the previous run, the mysql setup should have been done? Or is that a debug message?(edited)
Let me check something. I was logged in with a forge client before
Nope, forge or spigot, it works now
I tried dc, normal logout. Quite a few times. It updates correctly
Going to try the "old" one quick
I've tested it all the ways I can think of, and more.
Seems to be updating just fine.
Thank you for the help.
Someone called Corda616 says you guys do an amazing job. I have to agree.
sgdc3 - Today at 1:47 AM
one last thing:
enable session but set the expire period to the minimum
like 1 minute
then login
then disconnect
isLogged should be 1
wait 5 minutes
CraftSailor - Today at 1:48 AM
Ah, and check if it changes after 5 minutes?
sgdc3 - Today at 1:48 AM
and check isLogged again
yeah
CraftSailor - Today at 1:48 AM
OK, will do
sgdc3 - Today at 1:49 AM
i think it will remain 1
that could be a security break on your server
CraftSailor - Today at 1:49 AM
With that I would have to agree
sgdc3 - Today at 1:49 AM
probably we should change is logged to something like: session expire date
CraftSailor - Today at 1:50 AM
My main concern is players changing names on forge.
sgdc3 - Today at 1:50 AM
then you check if the expire date is past
what do you think about that?
CraftSailor - Today at 1:50 AM
So I'm hooking into the join event, so when that happens, it fires the event, and the mod fires
Expire date or expire time?
It actually changed to 0 nearly right away
Yes, it changes right away
Is that the field you check for "isAuthenticated"?
sgdc3 - Today at 1:58 AM
yes
the issue i think is that if the server crashed the value is kept to 1
CraftSailor - Today at 1:59 AM
Ah, yes, then it can happen
sgdc3 - Today at 1:59 AM
that's why an expire date would fix any problem
CraftSailor - Today at 2:00 AM
Yes, that makes sense yes
sgdc3 - Today at 2:00 AM
could you please copy and paste our conversation into the issue report? (or just sum up what we said)
CraftSailor - Today at 2:00 AM
The whole thing?
Not a problem.

**Comment by sgdc3** [comment]
If a player is logged in the isLoggedIn value in the datasource is set to 1, if session is enabled this value is kept to 1 until the session expires. If the server crashes before the session expires the isLoggedIn value remains 1. That may cause security issues with external services (like a cms) that relies on the isLoggedIn value consistency.

**Comment by sgdc3** [comment]
@ljacqu what do you think about that?

**Comment by ljacqu** [comment]
Without having read the convo above, I agree with you. AuthMe handles the isLoggedIn column well and we reset it on startup in some cases. 

For **us** so far it's been safe, but not for others to use without checking if the server is up, basically. 

Do you have any idea how this could be improved? The only thing I can think of right now is to have an option to disable the isLoggedIn column for AuthMe. In many cases like plain MySQL or SQLite it serves no purpose anyway

**Comment by DNx5** [comment]
If player leaving from the server which authme is running it will logged out, right?
so in this case, if the players switched from the spigot server into the forge server, they will marked as unloggedIn.
@ReaperAngels maybe you could try to enable bungeecord hook, and then handle the plugin message that sent by authme when player logged in by using your mod.

**Comment by ReaperAngels** [comment]
Hi, thanks for the include. I finished the mod using your database, it works nicely. I then decided to start a full authentication mod, similar to authme in function. That has progressed well, to the point where the basics work. Now I must just add some more features, although I'm not going to code something like the full authme. 

Thank you for all the help!
