### ISSUE TITLE
Add Huzuni check

### ISSUE THREAD

**Issue by friishon** [AuthMe/AuthMeReloaded#1244]
like the title
https://www.spigotmc.org/resources/proantihuzuni.41954/
this plugin allow for player to write in the chat .something for verify if they have hack client or not.
but i have more problems with spam messages and kick for fly
can you make something similar
when player succesfull register or login, then they have to write in chat " .walk " for example to verify if they have hack client or not, if they have, the plugin kick him, but if they haven't can walk (if the player doesn't write " .walk " he can't move.

and how i can pute more than one line on message? it was with /n??

**Comment by ljacqu** [comment]
If the other plugin could be controlled with commands it would work out of the box with AuthMe using commnds.yml

Failing that, this sounds like a "captcha before login/register" to me. We already have a request for captcha on register and it's a good idea

I think the new line is %nl%

**Comment by friishon** [comment]
This is not a captcha, hacked client can't write        " .something " but normal player can, on the chat if you put ./tp for example, the chat show ./tp
But hacked client can't write . Because it executed all commands start with . 
Now understand me?

**Comment by ljacqu** [comment]
It's clear to me, thanks for the clarification

**Comment by friishon** [comment]
I think it's better to force the player to write "./" (For example) before register and login to start to play, if they can't write it, the server kick him, is for block hack client, could be nice

**Comment by Eyremba** [comment]
> This is not a captcha, hacked client can't write " .something " but normal player can, on the chat if you put ./tp for example, the chat show ./tp

Dude, how stupid are you? That's just completely useless. Every hack client out there supports ".say", so they can just type ".say ./tp" and it would send "./tp" into the chat.

Everyone can bypass this easily. Also, most of the users change the command anyway to "#help" or something else.

**Comment by friishon** [comment]
Nop, i can put .casa and player have to put ".casa" for move, but hacked client execute all command start with "." and this isn't command so they can't write it and the plugin kick them, please test the plugin and then write again your opinion

**Comment by Eyremba** [comment]
> Nop, i can put .casa and player have to put ".casa" for move,

And? Then the player types into the chat ".say .casa" and it will send into the chat ".casa".

Dude wtf did you not understand?! All after ".say" is directly sent into the chat without problems. The ".say" command is made for this purpose. And this command exists in all clients.

**Comment by friishon** [comment]
Oks i will try

**Comment by friishon** [comment]
@Eyremba Ohhhh you are right, wow, all hacks can bypass this, hahah i'm goint to close this XD
