### ISSUE TITLE
Upgrading from SQLITE to MYSQL

### ISSUE THREAD

**Issue by blijgozertje** [AuthMe/AuthMeReloaded#1246]
Hey,

I wanted to upgrade the Authme database from SQLITE to MYSQL. But of course I don't want a password reset and all my files to be gone. Is there any way to transfer the data or is this automatic?

**Comment by Xephi** [comment]
Hi ! Take a look at our wiki : 
https://github.com/AuthMe/AuthMeReloaded/wiki/Converters#authme
