### ISSUE TITLE
AuthMe + XenForo

### ISSUE THREAD

**Issue by notariuss** [AuthMe/AuthMeReloaded#1247]
Passwords and usernames are in different tables. How to connect AuthMe with XenForo?

**Comment by Xephi** [comment]
Can you take a look and try these step ?

https://github.com/AuthMe/AuthMeReloaded/issues/957#issuecomment-264682674

**Comment by notariuss** [comment]
It seems to me that this unfinished solution

**Comment by ljacqu** [comment]
Agreed but still going to close it as a duplicate of #137 #957. 

Essentially right now we're stuck because we don't have access to the code. Someone tech-savvy with access to a Xenforo schema needs to provide us the information to imlement this programmatically
