### ISSUE TITLE
Improvement suggestion: Additional security option: Bind database to server

### ISSUE THREAD

**Issue by Eyremba** [AuthMe/AuthMeReloaded#1248]
Hello, I have an idea to improve the security against brute-force attacks furthermore: Binding the AuthMe database to hardware!

How would this work?
Well, let me explain...

AuthMe could generate a hardware ID, for example a string with a lenght of 32 chars. This hardware ID is generated based on processor IDs and other hardware IDs.
Then, as soon as a user uses "/register", Authme will combine his password with the hardware ID of the minecraft server (Basically "HWID + Password"), then hash it, and store it to the database.

With this method, someone who "hacks" FTP to get access to download the database (in case of a sqlite file), or someone who "hacks" phpMyAdmin for example to get access to the hashes in the MySQL database, would not success, and all would stay safe, because the attacker has no chance to get the hardware ID of the server, which means he has NO chance to brute force the hashes.

This should be an additional security feature which is disabled by default, and can be enabled by admins which want this advanced and enhanced security feature, and are aware of the fact that the database is then bound to the server and that this means that they have to create a new database if they move their server to another hoster.

**Comment by ljacqu** [comment]
Although I like the general idea I would vote not to implement this because of the imminent risk of losing all data. People who use a hosting company to run their servers can't control if/when their hardware gets changed, and that's the situation of most servers out there.

**Comment by Eyremba** [comment]
> This should be an additional security feature which is disabled by default, and can be enabled by admins which want this advanced and enhanced security feature, and are aware of the fact that the database is then bound to the server and that this means that they have to create a new database if they move their server to another hoster.

Yes I know, that's the problem. However, that's why I wrote:

> This should be an additional security feature which is disabled by default, and can be enabled by admins which want this advanced and enhanced security feature, and are aware of the fact that the database is then bound to the server and that this means that they have to create a new database if they move their server to another hoster.

:D

**Comment by sgdc3** [comment]
I think it would be an useless feature, just secure your server with strong passwords and you are ready to go.

**Comment by ljacqu** [comment]
Sorry @Eyremba but I'm with sgdc3 on this. I think when we consider the cost of implementing this (and having to maintain it) vs. the benefit the addition doesn't add up.
It's nevertheless a nice suggestion and we thank you for making it. :)
