### ISSUE TITLE
Improve API

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1253]
The API introduced in 5.3 is a copy of the old one. Yet, some important improvements could have been made, like removing duplicate functions. 

I would still suggest to do it now.

**Comment by sgdc3** [comment]
> like removing duplicate functions

Any example?

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
Sorry, I'll look at this this evening ;)

**Comment by ljacqu** [comment]
Completely forgot this, sorry— 
Obvious duplicates are the registration methods. Given the releases we've pushed IMHO it's not worth to annoy plugin writers with breaking changes -> wontfix. Sorry for the back & forth and the spam 😅

**Comment by DNx5** [comment]
atleast we could mark it as deprecated, and explain why.

**Comment by ljacqu** [comment]
@DNx5 Counter proposition that doesn't introduce any breaking changes: I'll spend some time writing more info on the methods (they're API methods, after all). My main beef was with `forceRegister(Player player, String password)` vs. `forceRegister(Player player, String password, boolean autoLogin)` (where the first one is exactly the same as the latter, except it provides a default value). But really the best option seems to be to keep it for now. Should we `@Deprecate` it to signal that it probably won't survive the next API version? (Though I _hope_ the next API version will come in the distant future)

**Comment by DNx5** [comment]
I think we should not deprecate if we don't have the replacement. For that methods, I prefer to keep it too, its not a big deal.
