### ISSUE TITLE
SQLITE to MYSQL

### ISSUE THREAD

**Issue by blijgozertje** [AuthMe/AuthMeReloaded#1257]
I follow the steps but for some reason, it won't work.

DataSource:
    # What type of database do you want to use?
    # Valid values: sqlite, mysql
    backend: 'MYSQL'
    # Enable database caching, should improve database performance
    caching: true
    # Database host address
    mySQLHost: 'SERVERADDRESS'
    # Database port
    mySQLPort: '3306'
    # Username about Database Connection Infos
    mySQLUsername: 'SOMETHING'
    # Password about Database Connection Infos
    mySQLPassword: 'MYPASSWORD'
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: 'ADATABASE'
    # Table of the database
    mySQLTablename: 'authme'
    # Column of IDs to sort data
    mySQLColumnId: 'id'
    # Column for storing or checking players nickname
    mySQLColumnName: 'username'
    # Column for storing or checking players RealName
    mySQLRealName: 'realname'
    # Column for storing players passwords
    mySQLColumnPassword: 'password'
    # Request mysql over SSL
    mySQLUseSSL: true
    # Column for storing players emails
    mySQLColumnEmail: 'email'
    # Column for storing if a player is logged in or not
    mySQLColumnLogged: 'isLogged'
    # Column for storing players ips
    mySQLColumnIp: 'ip'
    # Column for storing players lastlogins
    mySQLColumnLastLogin: 'lastlogin'
    # Column for storing player LastLocation - X
    mySQLlastlocX: 'x'
    # Column for storing player LastLocation - Y
    mySQLlastlocY: 'y'
    # Column for storing player LastLocation - Z
    mySQLlastlocZ: 'z'
    # Column for storing player LastLocation - World Name
    mySQLlastlocWorld: 'world'
    # Overrides the size of the DB Connection Pool, -1 = Auto
    poolSize: -1

**Comment by ljacqu** [comment]
> I follow the steps

What steps? What are you trying to achieve?

config.yml looks fine but if you want to convert from SQLite to MySQL (which only your issue title would suggest!) you need to use the appropriate converter command: `/authme convert sqliteToSql` — https://github.com/AuthMe/AuthMeReloaded/wiki/Converters
