### ISSUE TITLE
"mySQLUseSSL" doesn't work

### ISSUE THREAD

**Issue by RaynLegends** [AuthMe/AuthMeReloaded#1261]
The console gets spammed by AuthMe with the following message:
`Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

Setting mySQLUseSSL to "false" in the config should fix this problem since it should set useSSL in the MySQL connection to "false", but it seems to change nothing.

### Steps/models to reproduce:
1) Update MySQL to either 5.5.45+, 5.6.26+ or 5.7.6+
2) Start the server
3) Join and look at the console

### Environment description
- MySQL 5.7.18
- AuthMe-5.3.1-spigot.jar
- Spigot 1.12

### AuthMe build number:
1702

**Comment by sgdc3** [comment]
@RaynLegends Sorry foir the delay, could you post your config?

**Comment by sgdc3** [comment]
Whoops, could you try with build 1724 please? http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by RaynLegends** [comment]
Seems to be working fine now, thanks!
