### ISSUE TITLE
issue with registering by website

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [AuthMe/AuthMeReloaded#1262]
### What behaviour is observed:
I have registration by web, which adds new record to MySQL database with username, realname, password and everything like in other records vreated by normal registration on server. If I try to login to server after registering on web with "kickNonRegistered: true" enabled is says that only registered players can join, so it dont read the new database with new records. I have to restart server to let new users join.

### What behaviour is expected:
When someone new tries to connect while "kickNonRegistered: true" plugin checks if he is in database.

### AuthMe build number:
v.5.3.1 build:1702

I can't let unregistered people join my server, so i have to reload somehow accounts database every join or something like that.
Is there any solution to this problem?

**Comment by sgdc3** [comment]
Try to disable 'caching' from the config.
