### ISSUE TITLE
Fix spigotmc.org links

### ISSUE THREAD

**Issue by Kapakulia** [AuthMe/AuthMeReloaded#1263]
Can you fix Countries code link, or send all code? :)

**Comment by sgdc3** [comment]
Where is the broken link?

**Comment by ljacqu** [comment]
"Countries code" link on https://www.spigotmc.org/resources/authme-reloaded.6269/ goes to a Bukkit page that just refers to our config.md page on Github.

**Comment by ljacqu** [comment]
Same for "List of all single permissions​" and "Command list and usage​" & others. I think all of the page's links need to be checked.

**Comment by sgdc3** [comment]
@Xephi is the only one with acces to the spigot page.

**Comment by sgdc3** [comment]
@Xephi bump

**Comment by Xephi** [comment]
On my way too

**Comment by ljacqu** [comment]
I see that everything is fixed, thank you.
