### ISSUE TITLE
resolved No /register messages

### ISSUE THREAD

**Issue by noesd** [AuthMe/AuthMeReloaded#1269]
Theres no /register messages !

**Comment by sgdc3** [comment]
Please explain your issue

**Comment by noesd** [comment]
When a player connect to my server he hasn’t got the  register with /register password password

**Comment by noesd** [comment]
And it’s the same for /login

**Comment by ljacqu** [comment]
Do the commands not work? Is there an error on startup? What's your MC version? Which JAR are you using (spigot vs legacy)?

**Comment by jeremy100** [comment]
Are you using permissions plugin? If so, you must include the registration and login permission in the configuration.

**Comment by noesd** [comment]
The commands works, i Go eat and i test for the permissons

**Comment by noesd** [comment]
I use 1.12 spigot

**Comment by noesd** [comment]
I give the permissons but it doesn’t Work :(

**Comment by sgdc3** [comment]
What's your authme version?

**Comment by noesd** [comment]
The last

**Comment by noesd** [comment]
5.3.1

**Comment by sgdc3** [comment]
Do you have any error in the console log? Could you post your plugin list, please?

**Comment by noesd** [comment]
I haven’t got error
Plugins list
Admin GUI tools plus
Area shop 
Authme 5.3.1
CsCoreLib1.5.15
EssentialsX 2.0.1
Grief Prevention 
Group managerX
Guilds 1.5.7
Infernal Mobs
Jobs 3.9.4
Lottery 
Lucky Blocks
Magic wands
ModYourTablist
RPGhealthplus
RewardPro
Server TP
Shop chest
Skins restorerv13.1.1
Slimefun 4.1.9
Trollcommandsplusplus 3.10.30
Vault
Citizens 2.0.22
Dtltrader3.5.3
Dynmap2.5
STablist
worldedit6.1.7.2
Worldguard 6.2.1

**Comment by sgdc3** [comment]
Does it happen with only authme?

**Comment by noesd** [comment]
Yes

**Comment by sgdc3** [comment]
Could you post your configuration file and your server log?

**Comment by noesd** [comment]
https://www.mediafire.com/?navo9e6c5p703hl

**Comment by sgdc3** [comment]
Could you try using latest dev build? http://ci.xephi.fr/job/AuthMeReloaded/lastSuccessfulBuild/

**Comment by noesd** [comment]
nothing change

2017-07-02 12:54 GMT+02:00 Gabriele C. <notifications@github.com>:

**Comment by noesd** [comment]
I find a solution
I create NPC who says to the player /register password password to register blablabla

Sorry for my bad english, i'm french

**Comment by sgdc3** [comment]
Probably the issue was caused by an invalid language file.
