### ISSUE TITLE
Console contain error while register

### ISSUE THREAD

**Issue by Cheikotesu** [AuthMe/AuthMeReloaded#1270]
player can't registered in my server. i'm using spigot 1.10.2 and run AuthMe-5.3.1-spigot. after player do register it doesn't work and if i see the console it's caused some error in console like this: https://pastebin.com/McUFF3Hi

**Comment by sgdc3** [comment]
Please update to latest dev build: http://ci.xephi.fr/job/AuthMeReloaded/
