### ISSUE TITLE
At least one of my players on my server (One of my 4 characters) is unable to run, can only walk

### ISSUE THREAD

**Issue by chillerkraft** [AuthMe/AuthMeReloaded#1272]
### What behaviour is observed:
What happened?

player is stuck in walk mode and can not run

### What behaviour is expected:
What did you expect?

i expect to be able to run like i can on all my other characters

### Steps/models to reproduce:
The actions that cause the issue

well i just log in and then i can't run i can only walk

### Plugin list:
This can be found by running `/pl`

03.07 01:54:53 [Server] INFO Plugins (57): ChatColor2, AntiCreeper, ErrorSink, PlaceholderAPI, WorldResourcepacks, AdvancedLogger, AntiFire, Note, SimpleAPI, AsyncWorldEditInjector, LuckPerms, dynmap, OpenInv, ChatControl, CrackShot, WorldBorder, SmartSignEditor, ProtocolLib, Multiverse-Core, LibsDisguises, AdvancedPortals, MVdWPlaceholderAPI, NoFireworkDamage, AsyncWorldEdit, Tab, Vault, EpicRename, ChatItem, WowSuchCleaner, WorldEdit, Essentials, Scoreboard, GuiStats, DragonSlayer, OnTime, WorldGuard, EssentialsGeoIP, EssentialsSpawn, TitleManager, RandomCoords, InventoryFull, ConditionalPerms, SimplePets, CrackShotPlus, Residence, CraftBook, mcMMO, ChestShop, AuthMe, LockettePro, MobHunting, CompatNoCheatPlus, ChestShopNotifier, mcMMOAction, McMMOExtras, NoCheatPlus, TreeAssist

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

Standalone server, MySql

### AuthMe build number:
This can be found by running `/authme version`

03.07 01:55:50 [Server] INFO ==========[ AuthMeReloaded ABOUT ]==========
03.07 01:55:50 [Server] INFO Version: AuthMeReloaded v5.3.1 (build: 1702)
03.07 01:55:50 [Server] INFO Developers:
03.07 01:55:50 [Server] INFO Alexandre Vanhecke // xephi59 (Original Author)
03.07 01:55:50 [Server] INFO Lucas J. // ljacqu (Main Developer)
03.07 01:55:50 [Server] INFO Gnat008 // gnat008 (Developer)
03.07 01:55:50 [Server] INFO DNx5 // DNx5 (Developer)
03.07 01:55:50 [Server] INFO games647 // games647 (Developer)
03.07 01:55:50 [Server] INFO Tim Visee // timvisee (Developer)
03.07 01:55:50 [Server] INFO Gabriele C. // sgdc3 (Project manager, Contributor)
03.07 01:55:50 [Server] INFO Website: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/
03.07 01:55:50 [Server] INFO License: GNU GPL v3.0 (See LICENSE file)
03.07 01:55:50 [Server] INFO Copyright: Copyright (c) AuthMe-Team 2017. All rights reserved.

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

none

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

https://pastebin.com/ULr1TWKX

**Comment by sgdc3** [comment]
@ljacqu any idea?

**Comment by ljacqu** [comment]
No idea :/ We don't do anything that affects running, hmm

**Comment by chillerkraft** [comment]
its happening to even more of my players now, specifically 2 of mine. haven't tested on third character yet..

**Comment by chillerkraft** [comment]
i'll see if it happens still when i remove authme

**Comment by chillerkraft** [comment]
it happens without authme, and any other plugin..

**Comment by sgdc3** [comment]
Not an authme issue then, probably some plugin glitched your playerdata.
