### ISSUE TITLE
Error while converting authme 3.4 version to authme latest version

### ISSUE THREAD

**Issue by Kuroyabumozu** [AuthMe/AuthMeReloaded#1275]
I want to convert authme version 3.4 to latest version ( 5.3.2 )
and I've see the [wiki page](https://github.com/AuthMe/AuthMeReloaded/wiki/Converters), but 3.4 version does not have "/authme converter sqliteToSql" to let me type in, can someone help me to figure out how to do that? I want to the most detailed statement to tell me how to do that please !!!

**Comment by sgdc3** [comment]
Just replace the jar, authme will convert everything by itself.

**Comment by Kuroyabumozu** [comment]
No, when I replace it will be errir and stuck right loading

**Comment by ljacqu** [comment]
Please provide the error log

**Comment by Kuroyabumozu** [comment]
ok, First, this is my original looks
> <img src="https://i.imgur.com/dzqcpfT.png"></a>

and I ran the console, console ran normal

> [22:28:52] [Server thread/INFO]: [AuthMe] Enabling AuthMe v3.4
[22:28:52] [Server thread/INFO]: [AuthMe] Loading Configuration File...
[22:28:52] [Server thread/INFO]: [AuthMe] Set Language: en
[22:28:52] [Server thread/INFO]: [AuthMe] LICENSE : This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com
[22:28:52] [Server thread/INFO]: [AuthMe] Authme 3.4 enabled

and @sgdc3  says just replace the jar, authme will convert everything by itself.
ok, I don't know what I did is what he means? 
I replace the authme latest version in my plugins folder and del original authme like this
> <img src="https://i.imgur.com/SJUYL3q.png"></a>

and ran the console, logs shows me like this
https://paste.ubuntu.com/25065915/
and then when I get in my server I got time out, and I click the X button to close my server directly.
because I can't type stop command to close my server,
and after close I run my server again, the console shows me like this

> [23:45:10] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.3.2-SNAPSHOT-b1723
[23:45:11] [Server thread/WARN]: [AuthMe] FlatFile backend has been detected and is now deprecated; it will be changed to SQLite... Connection will be impossible until conversion is done!
[23:45:11] [Server thread/INFO]: [AuthMe] SQLite driver loaded
[23:45:11] [Server thread/INFO]: [AuthMe] SQLite Setup finished

Note：authme version 3.4 did not support command `/authme converter sqliteToSql`

**Comment by DNx5** [comment]
You need to wait until the conversion finished. Just, be patient.

**Comment by sgdc3** [comment]
We should add a warning message while the forced flatfile to sqlite converter is running, could you do that @DNx5 please?

**Comment by DNx5** [comment]
@sgdc3 we already have that
>[23:29:59] [Server thread/WARN]: [AuthMe] FlatFile backend has been detected and is now deprecated; it will be changed to SQLite... Connection will be impossible until conversion is done!

**Comment by sgdc3** [comment]
Whoops missed that, thank you, my memory is bad ;)

**Comment by Kuroyabumozu** [comment]
Thanks you all!!!
