### ISSUE TITLE
[Bug] tempban : try count not reset after minutesBeforeCounterReset minutes

### ISSUE THREAD

**Issue by Spiikesan** [AuthMe/AuthMeReloaded#1276]
### What behaviour is observed:
My players gets banned from the server with only one login try, but I have
maxLoginTries: 3
in the config. Se same thing appears before with a limit of 10.
I have "minutesBeforeCounterReset: 10" but it doesn't work. The fail count is never reset.

### What behaviour is expected:
The fail count to be reset and have 3 login tries as expected.

### Steps/models to reproduce:
just /login with the wrong password.

### Plugin list:
AutoSaveWorld, LuckPerms, WorldEdit, iDisguise, Essentials, EssentialsChat, Vault, EssentialsSpawn, ChatColor, ProtocolLib, WorldGuard, Multiverse-Core, SkinsRestorer, Orebfuscator4, Residence, EssentialsProtect, Multiverse-Inventories, AuthMe, VillageInfo, Multiverse-Portals, JSONAPI

### Environment description
MySql on localhost.
Dedicated server.

### AuthMe build number:
V5.3.2-SNAPSHOT (build: 1725)

### Configuration:
https://pastebin.com/aE1C2829

**Comment by ljacqu** [comment]
hi @Spiikesan , thanks for the report. We accidentally multiplied the configured minutes by 60'000, ouch :) This should be fixed with build n. 1737 or above, http://ci.xephi.fr/job/AuthMeReloaded/ We'd appreciate a quick reply to know if this can be closed.

**Comment by sgdc3** [comment]
@Spiikesan bump
