### ISSUE TITLE
A bug happens after a sudden server crash

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1277]
### A bug happens after a sudden server crash:
"SaveQuitLocation: true" — There is a reset location.
AuthMe v5.3.3, Minecraft v1.12

Already reported this problem earlier, but you ignored: https://www.spigotmc.org/threads/authme-reloaded.62079/page-39#post-2497900

**Comment by ljacqu** [comment]
Please provide us the following.
- steps to reproduce (including what server type you use)
- observed behavior
- the behavior you expected

**Comment by Roper89** [comment]
Friends, I told you about the problem, and then you yourself. I do not have time to do this. I find it difficult to communicate through translate.google.com
This problem is not only for me

**Comment by ljacqu** [comment]
Ok, then we close

**Comment by sgdc3** [comment]
We can't help you if you don't tell us the required informations.
