### ISSUE TITLE
Strange mysql behaviour.

### ISSUE THREAD

**Issue by sambadime** [AuthMe/AuthMeReloaded#1279]
[Craft Scheduler Thread - 16] WARN fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@1d210141 (No operations allowed after connection closed.)

http://prntscr.com/ftgnub

Please help me

**Comment by games647** [comment]
Which AuthMe version do you use?

**Comment by sambadime** [comment]
Latest version

**Comment by sambadime** [comment]
f

**Comment by games647** [comment]
Just post the exact version. The have multiple "latest" version. You could mean the latest released version on spigot/bukkit or latest dev-build on ci.xehpi.fr. So please just post the complete version text.

**Comment by sambadime** [comment]
Version: AuthMeReloaded v5.3.2 (build: 1726)

**Comment by DNx5** [comment]
could you provide the ``authme.log`` file inside AuthMe's plugin folder?

**Comment by sambadime** [comment]
https://pastebin.com/LBkbydvL

**Comment by games647** [comment]
How often do you get this error like every 30 minutes?

**Comment by sambadime** [comment]
When there's no one login or register for more than 5 minutes i think

**Comment by DNx5** [comment]
@ljacqu @games647 maybe we should add option to define connection ``maxLifetime``.
or we can just ask @sambadime to increase the database connection timeout.
AuthMe currently is using the default value (30 minutes).

**Comment by games647** [comment]
>maybe we should add option to define connection maxLifetime.

I think so.[ It seems to be related to it. ](https://github.com/brettwooldridge/HikariCP/issues/917)

**Comment by sgdc3** [comment]
Could you guys work on that? @DNx5 @games647

**Comment by DNx5** [comment]
@sambadime download latest build of AuthMe available [here](http://ci.xephi.fr/job/AuthMeReloaded/)
Run it once, and a new setting would appear right ``DataSource.maxLifetime``.
Since you say the error is happen after 5 minutes, try to set it to ``240`` (4 minutes).
If you still experience this error, you should try lower the value, depending on your mysql server configuration.

**Comment by sambadime** [comment]
It seems that the error does not show up again, i tried to register and it worked but when i tried to login it appear Wrong password although i use the right password

**Comment by DNx5** [comment]
Is there any error message? could you provide the ``authme.log`` file?

**Comment by sambadime** [comment]
Nope, there is no error in the authme.log file

**Comment by DNx5** [comment]
That's so weird. I am sure that is not related to this issue, but try to reset your password.

**Comment by sambadime** [comment]
I do, i deleted all data in the database i even use other database and the result is same

**Comment by sgdc3** [comment]
please describe your setup (mc version, bukkit/spigot/paper, other plugins, authme build number)

**Comment by sambadime** [comment]
MC Version : 1.11.2
Spigot version : 1.11.2
Other plugins : http://prntscr.com/furn56
Authme build number : 1740

**Comment by DNx5** [comment]
closing this, as he said via PM that it has been solved

**Comment by FataLeeer** [comment]
@DNx5 @sambadime how to fix?

**Comment by sgdc3** [comment]
@FataLeeer open a new issue report and fill the module
