### ISSUE TITLE
Please don't touch fly state 

### ISSUE THREAD

**Issue by Platinteufel** [AuthMe/AuthMeReloaded#1280]
From Discord:

Since I've updated to the latest AuthMe version today it doesn't restore the flying state properly (if I logout in the air while flying, it will disable fly at next login and the players will get fall damage)
I'm using the default config. I've tried everything. After login my fly is disabled and I fall to bottom.

It was fine in 5.2 .. Essentials just enabled fly for me if I was in the air and had the permission essentials.fly.safelogin. But it seems like AuthMe overrides this Essentials feature after /login and sets the flying state back to false.
If I deinstall AuthMe, Essentials does its job again, as you can see here: https://youtu.be/EI2wuZs4ON4

Correct me if I'm wrong, but all AuthMe should do is setting players speed to 0 and restore it back to its old value as soon as the player is logged in .. ? I don't really know why it touches things like flying state 😄

**Comment by Platinteufel** [comment]
Please also take a look at my comment referenced above. Maybe an option to do nothing would do it?

**Comment by ljacqu** [comment]
Hi @Platinteufel , a new option `NOTHING` has been added. When it is chosen, AuthMe will not manipulate the allow flight property of the player in any way. Available in build n. 1739 and above at http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Platinteufel** [comment]
Hi @ljacqu,
it works like a charm, thanks a lot for implementing this special case!

**Comment by ljacqu** [comment]
Well, thanks for the detailed report and for the prompt feedback :) In that case I close this issue.
