### ISSUE TITLE
Function Hidechat in config.yml is not working

### ISSUE THREAD

**Issue by notariuss** [AuthMe/AuthMeReloaded#1282]
In config function Hidechat turns on, but when i join server, when i arent authorized, i see messages from automessage. Earlier with such did not collide

### AuthMe build number:
This can be found by running `/authme version`
5.3.2

**Comment by sgdc3** [comment]
What do you mean with 'Earlier'? Could you tell us the version number of your previous version?

**Comment by notariuss** [comment]
I don't remember, it was year ago..

**Comment by notariuss** [comment]
Can I hide auto messages before authorization?

**Comment by sgdc3** [comment]
What do you mean as "Auto messages" ?

**Comment by notariuss** [comment]
automessages its plugin https://dev.bukkit.org/projects/automessage. I see msg from this plugin but i arent authenticated

**Comment by sgdc3** [comment]
Yeah, we only block messages from other players
