### ISSUE TITLE
pls help me :(( 

### ISSUE THREAD

**Issue by FlexVN** [AuthMe/AuthMeReloaded#1291]
how to fix errors on mysql?
INFO fr.xephi.authme.libs.zaxxer.hikari.pool.PoolBase - AuthMeMYSQLPool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)
how to fix?

**Comment by games647** [comment]
See https://github.com/AuthMe/AuthMeReloaded/issues/622

You can ignore it.
