### ISSUE TITLE
How to make /email recover send newpassword not code?

### ISSUE THREAD

**Issue by LapizSeller** [AuthMe/AuthMeReloaded#1293]
I'm just update from old version to newest version, now command /email recover mail send code instead of newPassword to player.
How can i  make this command send newPassword to player, instead of code? new method of recover password seem to be too much complicated with my players.
I see in Authme folder still has email.html
Sorry my bad English.

**Comment by ljacqu** [comment]
Hi @LapizSeller ,
this can be easily configured in config.yml:
```
    recoveryCode:
        # Number of characters a recovery code should have (0 to disable)
        length: 0 # <-- Set this to 0
```

**Comment by LapizSeller** [comment]
Ok. Thank you very much.
