### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by Pijanista** [AuthMe/AuthMeReloaded#1295]
So I have a problem with session. Sessions are disabled in config, bungee hook is disabled, auto login in authme bridge is disabled, caching disabled but session still happens between changing the servers which use the same database. Well to be exact, if I log in on server 1 and change to server 2, a session will be restored, now if I move from server 2 to server 1, session won't be restored. Same thing happens when I log in on server 2 and change to server 1....

I'm using latest authme version 5.3.2, but I've tried with latest snapshot 5.3.3 too.

I tried with bungee hook on true and same thing is happening.

Session won't be restored in any way if I exit the server and join again, only changing between them.

**Comment by sgdc3** [comment]
Does it happen if you disable useAsyncTasks?

**Comment by sgdc3** [comment]
@Pijanista any news?

**Comment by sgdc3** [comment]
Fixed
