### ISSUE TITLE
Permissions not removed when purging player's data

### ISSUE THREAD

**Issue by IceString3** [AuthMe/AuthMeReloaded#1298]
### What behaviour is observed:
Permissions and groups of player aren't removed when purging a player's data

### What behaviour is expected:
Permissions and groups of player removed

### Steps/models to reproduce:
1. Register a player
2. Change their group
3. /authme purgeplayer %player% force

### Plugin list:
CoreProtect, LuckPerms, antiraildupe, Skript, OpenInv, ClearLag, SkQuery, ConsoleSpamFix, PowerNBT, Skellett, RecipeBookDupePatch, FastAsyncWorldEdit, Reloader, skUtilities, LagMonitor, ViaVersion, MelonDamageLib, Vault, ViaBackwards, BungeeTabListPlus, LightAPI, WorldEdit, CityWorld, Essentials, SkStuff, WorldGuard, ProtocolLib, AAC, skRayFall, ASkyBlock, LockettePro, EssentialsChat, EssentialsSpawn, LargeSk, StackMob, CreativeParkour, SilkSpawners, Multiverse-Core, SkinsRestorer, Umbaska, GriefPrevention, AntiXRay, AuthMe, TuSKe, SharpSK

### Environment description
Server connected to a Bungeecord

### AuthMe build number:
AuthMeReloaded v5.3.3-SNAPSHOT (build: 1749)

### Error Log:
https://pastebin.com/4rrxpY2k

### Configuration:
https://pastebin.com/7B5UBGCK

**Comment by sgdc3** [comment]
@IceString3 Please try the latest dev build ;) Does it work now?
