### ISSUE TITLE
Missing API methods from 3.4

### ISSUE THREAD

**Issue by Darkfield** [AuthMe/AuthMeReloaded#1304]
API.database.getAuth(name.toLowerCase()).getIp()
API.database.getAllAuthsByIp(ip)
API.hookAuthMe().database.removeAuth(key)
API.database.getAuth(name.toLowerCase()).getLastLogin()

**Comment by sgdc3** [comment]
removeAuth -> https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/api/v3/AuthMeApi.java#L239

**Comment by sgdc3** [comment]
i'll add String getLastIp(String name), List<String> getUsersByIP(String address), and Date getLastLogin(String name)

**Comment by sgdc3** [comment]
@Darkfield Done, is that ok? ;)

**Comment by Darkfield** [comment]
I think ty :)
