### ISSUE TITLE
SQLite UnsatisfiedLinkError

### ISSUE THREAD

**Issue by PanCakev2** [AuthMe/AuthMeReloaded#1309]
### What behaviour is observed:
when I start the server, authme is shouting down it - it's default config, i don't change the mysql options.

[08-10 16:56:45]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[08-10 16:56:45]: [INFO] AuthMe 5.3.1-b1702 disabled!

### What behaviour is expected:
What did you expect?
fix that :P
### Steps/models to reproduce:
The actions that cause the issue
hmm, start the server.
### Plugin list:
This can be found by running `/pl`
authme, worldedit and guard, essentials.
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
1.12 server, spigot, without any database

### AuthMe build number:
This can be found by running `/authme version`
for 1.12 - i cant check it, so its the first of this: https://dev.bukkit.org/projects/authme-reloaded/files
### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
https://pastebin.com/M9MZ8d8A
### Configuration:
https://pastebin.com/gfSDNbqJ

**Comment by ljacqu** [comment]
Interesting, it's a version conflict with Spigot. What's your exact Spigot version?

**Comment by PanCakev2** [comment]
b1229 for 1.12, and when the plugin isn't work i changed for official spigot for 1.12.1.

**Comment by games647** [comment]
Could you try to set this as a startup parameter

>java [...] ]-Dorg.sqlite.tmpdir=PATH_TO_THE_SPIGOT_FOLDER -jar spigot.....
