### ISSUE TITLE
Minor issues when running with Glowstone 

### ISSUE THREAD

**Issue by yangm97** [AuthMe/AuthMeReloaded#1313]
### What behaviour is observed:
Sensitive commands (like /login and /register) are not being censored. Glowstone uses a different logging engine than Spigot;
Player IP is detected incorrectly when running Glowstone with Bungeecord by AuthMe. This issue possibly has more to do with Glowstone, so I opened an issue there as well: GlowstoneMC/Glowstone#547

### What behaviour is expected:
Censoring sensitive commands and storing correct player IPs.

### Steps/models to reproduce:
Run AuthMe on Glowstone; run AuthMe on Glowstone behind a Bungeecord server. 

### Plugin list:
AuthMe, AuthMeBridge, ProtocolSupport (mcpemeta branch)

### Environment description
MySQL storage.

### AuthMe build number:
v5.3.2 (build: 1726)

### Error Log:
Bungeecord:

```
06:28:30 [INFO] [/187.180.212.96:39420] <-> InitialHandler has connected
06:28:30 [INFO] [TheticalFlyer97] <-> ServerConnector [lobby] has connected
```

Glowstone:

```
06:28:30 [INFO] UUID of player TheticalFlyer97 is a6462498-08d5-37c4-bfbb-158cac0008f2
06:28:30 [INFO] TheticalFlyer97 [/187.180.212.96:43947] connected, UUID: a6462498-08d5-37c4-bfbb-158cac0008f2
06:28:30 [INFO] TheticalFlyer97 joined the game
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: FML
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: AuthMeBridge
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: FML|HS
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: FORGE
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: BTLP/Bridge
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: BungeeCord
06:28:30 [INFO] TheticalFlyer97[/187.180.212.96:43947] registered channel: BAuthMeBridge
06:28:42 [INFO] TheticalFlyer97 issued command: /register (censored)
```

AuthMe database:

![screen shot 2017-08-13 at 03 55 16](https://user-images.githubusercontent.com/4412002/29246869-60ee637c-7fdb-11e7-9d87-807093f5de8e.png)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by sgdc3** [comment]
>Sensitive commands (like /login and /register) are not being censored. Glowstone uses a different logging engine than Spigot;

We can't fix that
