### ISSUE TITLE
AuthMe with spigot 1.8.8

### ISSUE THREAD

**Issue by Kiwis2451** [AuthMe/AuthMeReloaded#1314]
help me pls
`[12:15:12] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[12:15:12] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!`

My config as default

**Comment by sgdc3** [comment]
What's your authme version?

**Comment by Kiwis2451** [comment]
lastest version on spigot

**Comment by sgdc3** [comment]
Use this version: http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Kiwis2451** [comment]
tks you very much
