### ISSUE TITLE
Problem with assigning players another's accounts

### ISSUE THREAD

**Issue by AIphaDragon** [AuthMe/AuthMeReloaded#1315]
Hello,
We are using the latest version of your plugin - 5.3.2.
The problem is, that recently our AuthMe plugin strated to assign players the accounts, which don't belong to them and count it, as their's "twins".
So please, help us solve this problem.
We are looking forward to your answer

- Our server use Spigot 1.11.2 core.
- Our database is SQLite.
- Here is the list of our plugins:
https://pp.userapi.com/c836732/v836732077/6ec5d/ShB4f0foDuQ.jpg

- Here is a pastebin of our config.yml:
https://pastebin.com/nuzgFuWW

**Comment by sgdc3** [comment]
Please explain your issue with some valid examples

**Comment by AIphaDragon** [comment]
Well,
As it can be seen in our config, we have limited an amount of maximum accounts to only 2. Players, that have 2 accounts, complaining, they have 3 or more. After checking the "3rd" assigned account, it shows, that this account have no twins and is single account. The assigned accounts cannot be hacked or stolen, as players enter game normaly and from their's IP.
What type of examples or evidences you need?

**Comment by sgdc3** [comment]
are you using bungeecord?

**Comment by AIphaDragon** [comment]
No, not yet

**Comment by sgdc3** [comment]
I still can't understand your issue, @ljacqu @HexelDev any idead?

**Comment by ljacqu** [comment]
We have a feature that limits the number of users an Ip address may register. He is seeing this limit being reached for users he doesn't expect. 

@AlphaDragon, could you look at the ip addresses of those users with /authme debug db? It would be interesting to see if e.g. all have the ip address 127.0.0.1 or something

**Comment by AIphaDragon** [comment]
We have discovered what the problem was. 
The matter was in routers, when two different players, which use routers, had the similiar IP's. So, thanks for your help

**Comment by ljacqu** [comment]
Thanks for letting us know! Glad you could get to the bottom of your issue.
