### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by blijgozertje** [AuthMe/AuthMeReloaded#1316]
Having some lag issues and I think it is because of Authme.

https://timings.aikar.co/?id=f1907ea3a6ec4e7fb9b64132e3113d13

**Comment by sgdc3** [comment]
lag issues? you have 20 tps 100% of the time :/

**Comment by blijgozertje** [comment]
Look at the random TPS loss. I have 11.7 TPS right now but it doesnt show the good tps in the timings

**Comment by blijgozertje** [comment]
New timings and did catch the TPS drops.
https://timings.aikar.co/?id=d9f97f93643749f2a07cfaeb29c603f4

**Comment by sgdc3** [comment]
could you describe your setup? bungee/standalone mysl/sqlite mysql server location, etc...

**Comment by blijgozertje** [comment]
A hub server on Bungeecord with sqlite.

**Comment by sgdc3** [comment]
How many registered users do you have?

**Comment by sgdc3** [comment]
@blijgozertje

**Comment by blijgozertje** [comment]
152321
