### ISSUE TITLE
Problem whit lagging plugin when join 10 players / s

### ISSUE THREAD

**Issue by pjorun** [AuthMe/AuthMeReloaded#1318]
### What behaviour is observed:
What happened?
Serwer has huge lag and tps down. In my server today play 800/1000 players.

### What behaviour is expected:
What did you expect?
Plugin have problem whit handling connection ?

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
BungeeCord / MySQL 5.6.36 connected to, 3 lobby

### AuthMe build number:
This can be found by running `/authme version`
I Try 5.3.2 and now i check 5.4 snapshot but this same problem.

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
https://timings.spigotmc.org/?url=taxuyokanu

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://gist.github.com/pjorun/e9fe426dda0bbae0e412b0cf7e041bf5

**Comment by sgdc3** [comment]
Have you tried with useAsyncTasks: true?

**Comment by pjorun** [comment]
Nothing change, to reduce lag i must use Authme addons to teleport after login.

**Comment by ljacqu** [comment]
Thanks for the timings! One question here – do you have any other plugins? I don't see them in the timings but it would have made an interesting comparison.

**Comment by pjorun** [comment]
Yes, but this is a normal global plugin like Essentials, Worldedit, WorldGuard, Vault, MultiVerse, PermissionsEx, LagMeter and nothing else.

**Comment by pjorun** [comment]
Nothing change, same problem whit huge lag. Maybe problem is in MySQL 5.6.36 ?

**Comment by sgdc3** [comment]
is the mysql server in the same machine?

**Comment by pjorun** [comment]
Yes, Authme is connected in localhost. Authme have 400k player account.

**Comment by pjorun** [comment]
I do not know what are you add to Authme but plugin is totally broken...
All dedicated server whit Intel  Xeon E3-1225v2 and 32 gb ram on ssd disc and timings:
https://timings.spigotmc.org/?url=quguhipibu

**Comment by sgdc3** [comment]
You are the first one that reports such issues, i'll try to figure out the cause

**Comment by sgdc3** [comment]
Timings v1 are misleading, do you reallynotice tps issues or are you just concerned avout the timings report?

**Comment by sgdc3** [comment]
A timings v2 report would help finding the real cause

**Comment by pjorun** [comment]
Today i add authme from 2016 and issue dissapeared. Now all work fine.

**Comment by ljacqu** [comment]
@pojrun Interesting, what version of AuthMe was that?

**Comment by pjorun** [comment]
5.2 work perfect

**Comment by sgdc3** [comment]
Is the mysql database on the same machine of the spigot instance?

**Comment by pjorun** [comment]
Ofcourse is in this same machine...
screen java -Xms32M -Xmx8000M -jar spigot.jar nogui

**Comment by sgdc3** [comment]
Try with java -Xms8G -Xmx8G -jar spigot.jar always use fixed memory size allocation

**Comment by pjorun** [comment]
So I wonder maybe authme 5.3 / 5.4 is not compatible with PacketListnerAPI? And that is the problem?.

**Comment by sgdc3** [comment]
@pjorun i don't think so, could you truy disabling non critical plugins and see if the problem persists?

**Comment by ljacqu** [comment]
Hi @pjorun do you think you could re-add the version you were using previously and check whether it creates this sort of lag again? We didn't change that much in terms of scheduling tasks / interactions with the database etc. from 5.2 to 5.3 so I'm a little surprised that switching versions resulted in such an improvement for you.

**Comment by pjorun** [comment]
@ljacqu Sorry, but I will not risk the lag and the possibility of losing some players.

**Comment by sgdc3** [comment]
@pjorun Do you have any news about that?
