### ISSUE TITLE
Expect teleport behavior or bug?

### ISSUE THREAD

**Issue by SaitDev** [AuthMe/AuthMeReloaded#1320]
### What behaviour is observed:
What happened?
- With `teleportUnAuthedToSpawn` set to true, players wont be teleported back to their normal position unless `SaveQuitLocation` also set to true. But with SaveQuitLocation it will bypass `ForceSpawnLocOnJoin`, players werent forced teleport to spawn after login

### What behaviour is expected:
What did you expect?
- With older version, both teleportUnAuthedToSpawn + ForceSpawnLocOnJoin worked well while SaveQuitLocation is false. I hope `SaveQuitLocation` wont bypass `ForceSpawnLocOnJoin`

### Steps/models to reproduce:
The actions that cause the issue
- Set teleportUnAuthedToSpawn, SaveQuitLocation, ForceSpawnLocOnJoin.enabled to true
- Login then logout while being in any of ForceSpawnLocOnJoin.worlds
- Relog, after success, I'll be teleported that previous world

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone server
### AuthMe build number:
This can be found by running `/authme version`
- AuthMeReloaded v5.4-SNAPSHOT (build: 1758)
### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/XMexrbwu

**Comment by sgdc3** [comment]
This is a jar with some debug code, please let me know if you see the "Limbo destination world was null!" message in console.
[AuthMe-5.4-TPDEBUG.zip](https://github.com/AuthMe/AuthMeReloaded/files/1272596/AuthMe-5.4-TPDEBUG.zip)

**Comment by sgdc3** [comment]
@SaitDev

**Comment by sgdc3** [comment]
Maybe related to #1207 ?

**Comment by SaitDev** [comment]
I guess its the same with 1207. But I'll try your debug build

**Comment by ljacqu** [comment]
Hi @SaitDev , how did it work with the debug build?

**Comment by SaitDev** [comment]
Sorry for late reply, I tried with logLevel is DEBUG, there isnt any message like "Limbo destination world was null!"

**Comment by SaitDev** [comment]
Just test with the newest dev build 1778. It works fine now, seem like its same with 1207. I'll close this issue. Thanks for your work

**Comment by ljacqu** [comment]
Thanks for the update!
