### ISSUE TITLE
Authme - LoginSecurity Converter Error

### ISSUE THREAD

**Issue by JavyMC123** [AuthMe/AuthMeReloaded#1322]
What happened?
Hi, this plugin is amazing! But i have a problem... I put the plugin authme to convert the login security data to the new authme, because its better. The problem is that i put the command to convert from login security and the players when they put /login and his password, authme say password incorrect!. Sorry for my english. 

What did you expect?
The Convertion have a error

 Plugin list:
Plugins (50): PlugMan, Announcer, YouTubeBridge, SkinsRestorer, KillMoney, MaxBans, StopProxy, LeaderHeads, StaffPlus, WorldEdit, FastRespawn, killStats, Essentials, ClearLag, BuycraftX, Votifier, ProtocolLib, Multiverse-Core, NoCheatPlus, ChestRestock, CustomServerMessages, EssentialsChat, 40ServidoresMC, PermissionsEx, TAB, CustomHelp, AntiBotAttack, Vault, BlockParticles, FastLogin, HolographicDisplays, WorldGuard, AuctionHouse, ChestCommands, EssentialsProtect, PlayerVaults, SimpleVoteListener, EssentialsSpawn, CratesPlus, TitleManager, CustomEnderChest, CombatLog, CommandSigns, SimpleClans, Citizens, Shopkeepers, RealScoreBoard, ArmorStandTools, AuthMe, CommandNPC

 AuthMe build number:
This can be found by running `/authme version`
5.3.2

 Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/7vktLvCB

**Comment by sgdc3** [comment]
which version of loginsecurity are you using?

**Comment by ljacqu** [comment]
> passwordHash: 'SHA256'

Try BCRYPT? What was Loginsecurity configured to use?

**Comment by sgdc3** [comment]
@JavyMC123 please try @ljacqu 's solution
