### ISSUE TITLE
Do you intend to upgrade it to use for sponge?

### ISSUE THREAD

**Issue by kizza5161** [AuthMe/AuthMeReloaded#1326]
I'm using a sponge server but a lot of players use a cracker that wants to participate in the game experience but in sponge they do not intend to create a plugin that allows off-mode mode. I would like to ask if you can upgrade auth to use for sponges?

**Comment by sgdc3** [comment]
Maybe in the future, not in our todo list atm.

**Comment by ljacqu** [comment]
See also #837
