### ISSUE TITLE
Error in AuthmeReloaded / RepeatingLogin Message

### ISSUE THREAD

**Issue by MarvanCZ** [AuthMe/AuthMeReloaded#1327]
Hello i found new bug.

When i login on game and send command for login.
login is successful but these errors occur rarely after login.

IMG: (https://imgur.com/m0aS1G8)

Error (https://pastebin.com/0J8d3DcB);
AuthmeReloaded version is v5.4S-NAPSHOT Build 1770 

Please Fix it

**Comment by sgdc3** [comment]
@games647 could you please take a look if we do some wrong async stuff with permission group changes?

**Comment by games647** [comment]
@sgdc3  I found none. I looked up the usages of `PermissionManager` methods and `setOP(boolean)`. **Maybe** it's another plugin. We could maybe add a patch to Spigot for another AsyncCatcher or a create Java proxy to find the source.

@MarvanCZ What permissions plugin do you use and what plugins do you have that modifies permissions.

**Comment by MarvanCZ** [comment]
permissionsEx 1.23.4

**Comment by MarvanCZ** [comment]
Plugins (58): ShadowDog, AdvancedClearlag, PlaceholderAPI, NametagEdit, FixPlugin, ChatReaction, OldCombatMechanics, CensorReloaded, Realistic_World, CoreProtect, dynmap, Skript, QuickBoard, Votifier, Multiverse-Core, ProtocolLib, DeathMessagesPrime, LibsDisguises, VotingPlugin, FastAsyncWorldEdit, PermissionsEx, mcMMO, MassiveCore, HolographicDisplays, HideAndCustomPlugins, AAC, SkinsRestorer, CratesPlus, WorldEdit, ConditionalCommands, WorldGuard, React, EchoPet, CombatTagPlus, AuthMe, KillerMoney, Factions, LockettePro, ChestCommands, MyCommand, Statz, TitleManager, Essentials, EssentialsGeoIP, EssentialsSpawn, pStaffList, EssentialsChat, Autorank, ServerlistMOTD, Vault, PenizeNotes, ChestShop, LiteBans, Citizens, BossMessenger, JLib, CarlTheCreeper, CitizensCMD

**Comment by games647** [comment]
It's SkinsRestorer. They run an async where they change the OP status. Related ticket https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/209

**Comment by sgdc3** [comment]
@games647 i love you just because you made possible to replace that shitty plugin ;) ChangeSkin id way better!

**Comment by MarvanCZ** [comment]
Thank you for clarifying the problem.

**Comment by DoNotSpamPls** [comment]
Hello,

We are in the process of fixing this in SkinsRestorer. Can you give us more information, so we can reproduce the bug?
Thanks!
