### ISSUE TITLE
Message when wrong password

### ISSUE THREAD

**Issue by SzymoonDev** [AuthMe/AuthMeReloaded#1329]
Hi,
this is not a bug, maybe offer.
When i use wrong password for my account, authme send me text message "Forgot your password? Please use the command: /email recovery <yourEmail>", but i dont have email added to account.
In other words, authme doesn't have to send me text message ("Forgot your password? Please use the command: /email recovery <yourEmail>"), when i dont have added email to account.
When i have added email to account, authme must send this message (on use wrong password).

Version: AuthMeReloaded v5.3.2

Sorry for my bad english :(
I hope you understand.

**Comment by sgdc3** [comment]
Please post your configuration file. (Remove your db credentials)

**Comment by SzymoonDev** [comment]
https://hastebin.com/okagabobin.bash
AuthMe configuration.

**Comment by sgdc3** [comment]
@SzymoonDev Should have been fixed ;)

**Comment by sgdc3** [comment]
Reminder: use Utils.isEmailDefined

**Comment by SzymoonDev** [comment]
Works correctly, thanks :)
