### ISSUE TITLE
[Question] Where are the country codes?

### ISSUE THREAD

**Issue by RoinujNosde** [AuthMe/AuthMeReloaded#1330]
https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md redirects me to https://dev.bukkit.org/projects/authme-reloaded/pages/countries-codes but this page cannot be found...

**Comment by SzymoonDev** [comment]
http://dev.maxmind.com/geoip/legacy/codes/iso3166/

**Comment by RoinujNosde** [comment]
Thanks!
(I am gonna leave this open so they can fix it)

**Comment by sgdc3** [comment]
We have to change the url in the configuration
