### ISSUE TITLE
Request: add "PSW PSW_CONFIRM EMAIL" registration type.

### ISSUE THREAD

**Issue by renzotom** [AuthMe/AuthMeReloaded#1334]
Can we have also third argument, when players register? I want create something like /register password password email (email is optional, but will be wrote there).

And when will be released authenticator app? https://github.com/AuthMe/AuthMeReloaded/wiki/Registration Can we see somewhere some progress?

**Comment by renzotom** [comment]
Can someone reply?

**Comment by sgdc3** [comment]
About the app: no news atm, we are currently too busy to work on it.

**Comment by sgdc3** [comment]
@ljacqu What do you think about that? Probably we shoudnìt add the psw confirmation if we already have the recovery email :/

**Comment by ljacqu** [comment]
To be honest I'm really not "feeling" this issue ;) The reason being it seems annoying for me to use as a user, and it would bloat our config even more. If this was a popular demand I wouldn't mind. If only one person wants this I'd vote to skip it. 
Essentially this could easily be done by a dev by overrriding the register cmd and checking the confirmation there before passing on the data to our API

**Comment by sgdc3** [comment]
I agree
