### ISSUE TITLE
Add /authme registeredlist command on AuthMe 5.4

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1335]
I Have a idea:
Can you add the /authme registeredlist command on version 5.4?
This command show the all registered players.

Example:
IGN İssued server command: /authme registeredlist
Server: total registered users: 7643

Thanks!

**Comment by ljacqu** [comment]
It's available under /authme debug (don't know which one by heart). I think that should be enough and doesn't require a dedicated command

**Comment by krusic22** [comment]
/authme debug stats
Should do the job.
