### ISSUE TITLE
Teleport unAuthenticated player to spawn broke

### ISSUE THREAD

**Issue by SaitDev** [AuthMe/AuthMeReloaded#1336]
After fix #1207 option `teleportUnAuthedToSpawn : true` seem not work anymore. When join and havent login with password, players arent teleported to spawn

AuthMeReloaded v5.4-SNAPSHOT (build: 1782)
Paper Spigot 1.11.2

**Comment by sgdc3** [comment]
Do you have any error in the console log?

**Comment by SaitDev** [comment]
Sorry for missing info. There isnt any error in the console

**Comment by sgdc3** [comment]
@SaitDev Could you post your configuration file please?

**Comment by SaitDev** [comment]
Same with my old one on privious report https://pastebin.com/XMexrbwu

**Comment by krusic22** [comment]
Related to #592 
I think

**Comment by SaitDev** [comment]
@krusic22 not really. by that report `teleportUnAuthedToSpawn` still works but got some delay so that other player can get *real location* of any account without login with password. 
for me `teleportUnAuthedToSpawn` totolly not work, player stay where they were and authme wait for them type /login password

**Comment by krusic22** [comment]
I'm saying that the patch for #592 broke teleportUnAuthedToSpawn for me at least.

**Comment by SaitDev** [comment]
i see. u should told it first 😅

**Comment by sgdc3** [comment]
@SaitDev Could you check latest build please? ;)

**Comment by krusic22** [comment]
Fixed for me (using a 1.12.2 server)

**Comment by SaitDev** [comment]
`teleportUnAuthedToSpawn` works fine with latest build but #1207  come back :((

**Comment by sgdc3** [comment]
@SaitDev what do you mean? ForceSpawnOnLogin is applied only after the login.

**Comment by SaitDev** [comment]
yes, after login success player are teleported back to worlds that are in ForceSpawnLocOnJoin.worlds instead of stay at spawn

**Comment by sgdc3** [comment]
@SaitDev so it works as intended, what's the issue?

**Comment by SaitDev** [comment]
I dont think it works as intended. In my config file https://pastebin.com/XMexrbwu there is `Dungeon` in section ForceSpawnLocOnJoin.worlds.
When player connect to server, they r teleported to spawn by `teleportUnAuthedToSpawn: true`. After enter password and login successfully, they r teleported back to `Dungeon`. So `ForceSpawnLocOnJoin` does no job when teleportUnAuthedToSpawn is actived

**Comment by sgdc3** [comment]
@SaitDev could you check the latest dev build? ;)

**Comment by SaitDev** [comment]
both `teleportUnAuthedToSpawn` and `ForceSpawnLocOnJoin` work fine with 1790

**Comment by sgdc3** [comment]
Nice, thank you @SaitDev
