### ISSUE TITLE
[Request] AuthMe /email command translate

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1338]
Can you add the translate for command: **/email** on the version 5.4?
http://prntscr.com/grl4yc

**Comment by ljacqu** [comment]
Hi @Pluginsel , you can translate all of the help commands with help_xx.yml in your messages folder. At the top there are some comments on the format.

**Comment by sgdc3** [comment]
@Pluginsel let us know if we can close this issue or if you have more questions ;)

**Comment by Pluginsel** [comment]
translate for help_xx is very hard.
I working, wait before close this issue.
Thanks @sgdc3 and @ljacqu

**Comment by Pluginsel** [comment]
I need help for translate the /email command.
Can you send example?

**Comment by MineSAT** [comment]
I vote for that! where can I find the list of commands by defect with the English descriptions already made to be able to translate it easier?

**Comment by sgdc3** [comment]
@Pluginsel just look at the help_en one, it should be easy to understand.

**Comment by sgdc3** [comment]
https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/resources/messages/help_en.yml

**Comment by ljacqu** [comment]
We could generate a fully complete help YML file. Would suggest to keep this issue open for doing that. It's been on my mind for a while... :)

**Comment by MineSAT** [comment]
@ljacqu Yes please! generates the whole file so that it is easier to translate. Thanks ;)

**Comment by ljacqu** [comment]
Hi @MineSAT, we'll offer a command soon that will extend the current help YML file to include all possible entries. It's not in the latest JAR yet, but if you want to get started, here's how the generated file would look:
https://hastebin.com/obefedibof.vbs

**Comment by MineSAT** [comment]
Hi @ljacqu Thanks you for the YML. I'm go to Translate it

**Comment by MineSAT** [comment]
Hi @ljacqu Thanks you for the YML. I'm go to Translate it :)

**Comment by ljacqu** [comment]
The command is available (`/authme messages help`) in newer builds; if there's anything not good please comment and we'll reopen this issue. I close for now. :)

**Comment by Pluginsel** [comment]
Thanks! I testing.

**Comment by Pluginsel** [comment]
@ljacqu the translate of all messages_en.yml file is available on the new builds of AuthMe?
because the hastebin link is broken.

**Comment by ljacqu** [comment]
Yep! Just run `/authme messages help` and your help_xx.yml file in messages/ will be updated to contain all possible entries.

**Comment by Pluginsel** [comment]
command /authme messages help is available on the version 5.3.2?

**Comment by ljacqu** [comment]
No.
It's available on newer dev builds at http://ci.xephi.fr/job/AuthMeReloaded/ Build n. 1814 and above

**Comment by Pluginsel** [comment]
@ljacqu & @sgdc3 I tested this, and work correctly.
But can you add translate this: 

**Unknown Command!
Did you mean /<command>?
Use the command /<command> to view help.**

to messages_en.yml file?

**Comment by ljacqu** [comment]
Thanks for the feedback!
I kindly invite you to create a new issue for your request, since it's independent of the work we've done here. This helps us keep track of our work better ;) Thanks
