### ISSUE TITLE
unrestrictions

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1343]
In **config.yml** there is a setting for the exceptions "**unrestrictions**". But there are no commands to add to the list. I want to add players to "unestricts" through the console. For premium users to login without authorization. 

_P.S. I understand that this is not safe_

**Comment by Roper89** [comment]
?

**Comment by sgdc3** [comment]
@ljacqu what do you think about this?

**Comment by ljacqu** [comment]
Hmm, unrestriction basically means that AuthMe will ignore the player altogether (i.e. for him the experience is as if AuthMe didn't exist: no restrictions, no need to log in). 
If you want premium players to be logged in automatically, have a look at https://github.com/games647/FastLogin

**Comment by sgdc3** [comment]
@ljacqu yeah, i think it would be a security risk too

**Comment by ljacqu** [comment]
If we need to support unrestricted users "dynamically" I'd rather go with a permission than a command -> no need to change the config on runtime or worry about persistence another way

**Comment by Roper89** [comment]
If you did not have this function, then there were no questions.
Function is available, but poorly implemented.
Do it for use or discard it.

I want to add players to "unrestrictions" even if it's not safe, but it's done through config.yml is extremely inconvenient

**Comment by ljacqu** [comment]
The function is meant for NPC players that have a predefined name. To me it sounds like you're trying to solve a problem with unrestrictions where there might be a more appropriate solution.
