### ISSUE TITLE
Non-forced registration inconsistencies

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1344]
1)

With these settings config.yml:

_registration:
  enabled: true
  force: **false**_

does not work "useWelcomeMessage: true" for unregistered users.
This is very inconvenient, I have to use other plugins for WelcomeMessage

2) 

customJoinMessage:
"# {DISPLAYNAME}: the player name (with colors)" — Color codes do not work

**Comment by sgdc3** [comment]
1) Fixed

2) Try with {PLAYERLISTNAME}, if it doesn't work then you have an issue with another plugin.

**Comment by Roper89** [comment]
1.

{PLAYERLISTNAME} also does not work.
Please check by yourself.  Even without other plugins, color codes do not work.
Screenshot:  https://i.imgur.com/HLHjvQ5.png


2. 

With these settings config.yml:

_registration:
enabled: true
force: **false**_
       **+**
              _ProtectInventoryBeforeLogIn: **true**_

Not registered players can not take anything

**Comment by Roper89** [comment]
Addition to the first message: 

"customJoinMessage" is also not shown if:
_registration:
  enabled: true
  force: **false**_

**Comment by Roper89** [comment]
Another bug.
If you use these settings:

_registration:
enabled: true
force: **false**_

Ignore the setting — "_SaveQuitLocation: **true**_"

**Comment by sgdc3** [comment]
Fixed the welcome message colors

**Comment by ljacqu** [comment]
Can we split this into multiple issues? Whatever was reported initially has been fixed within this issue — reappropriating it leaves no log of the initial bug.

**Comment by sgdc3** [comment]
@ljacqu no, we need to find out a better way to handle non registered players with force mode disabled.. We should handle it like we do with sessions.

**Comment by ljacqu** [comment]
I'm talking about issues in GitHub. This was initially about player display names.

**Comment by Roper89** [comment]
> # {DISPLAYNAME}: the player name (with colors)
>   customJoinMessage
Tell me, has not this been fixed yet?

I write: _customJoinMessage: 'Hi **&5**{DISPLAYNAME}  ^_^'_ 
The name does not get colored ...

**Comment by sgdc3** [comment]
You probably have a plugin that adds &r in the displayname.

**Comment by sgdc3** [comment]
@Roper89 try with {DISPLAYNAMENOCOLOR} (update to latest dev build first)

**Comment by Roper89** [comment]
Does not work. The name does not become colored. Color codes do not work... 
Screenshot https://i.imgur.com/m8mUa0O.png
Downloaded version from here http://ci.xephi.fr/job/AuthMeReloaded/
I tried with {DISPLAYNAME} and {DISPLAYNAMENOCOLOR}

P.S. did not understand why you suggested using {DISPLAYNAMENOCOLOR}
My goal is to get a color name :)

**Comment by sgdc3** [comment]
Yeah sorry i found the cause, i'll fix that asap

**Comment by Roper89** [comment]
I have a problem player who, when connected, does not admit to the server with an error _"lost connection: Timed out"_
If I disable the plugin, it can connect...

**Comment by sgdc3** [comment]
Are you sure? There is an issue with spigot 1.12.2 that causes that randomly.

**Comment by Roper89** [comment]
Yes. This problem is only for one player. Until I disconnect the plugin, it will not be able to log on to the server

**Comment by sgdc3** [comment]
Are you 100% sure it doesn't happen without authme?

**Comment by Roper89** [comment]
No. Too few tests were.

**Comment by Roper89** [comment]
I did the test.
For a day, I turned off AuthMe and installed LoginSecurity.
The person who played during the disabled AuthMe was unable to log in to the server the next day when I turned on AuthMe

**Comment by sgdc3** [comment]
Seems like any plugin that delays the login process causes random disconnection, related to https://github.com/PaperMC/Paper/issues/895

**Comment by Roper89** [comment]
I want to continue tests, can you advise me any plug-in authorization? 
It's strange that AuthMe and LoginSecurity do not let in different people, and not the same people. 
Who comes with LoginSecurity - can not go with AuthMe and vice versa

**Comment by sgdc3** [comment]
@Roper89 That doesn't make any sense :/ Please test again.

**Comment by Roper89** [comment]
_registration:
enabled: true
force: **false**_

it still does not work?

**Comment by sgdc3** [comment]
@Roper89 Could you try with the latest paper builds?

**Comment by sgdc3** [comment]
Whoops, sorry xD

**Comment by Roper89** [comment]
I do not quite understand you. Test the plugin on PaperSpigot? I just do not use it.
We had a problem with the plug-in when changing the settings, but then we started to discuss another question and deviated from the original problem.

Please read the beginning of the correspondence, there were a lot of bugs caused because of this:

_registration:
enabled: true
force: **false**_

**Comment by sgdc3** [comment]
I'm talking about 

>I have a problem player who, when connected, does not admit to the server with an error "lost connection: Timed out"
If I disable the plugin, it can connect...

Since this is a craftbukkit bug that the paper team tried to fix or at least reduce i think using paper would be helpful to understand the real cause of the issue.

**Comment by sgdc3** [comment]
>Please read the beginning of the correspondence, there were a lot of bugs caused because of this:
registration:
enabled: true
force: false

About the original issue: to fix the issue we have to rewrite how authme handles the join and login process.

**Comment by Roper89** [comment]
Notify me when you fix it:

> registration:
> enabled: true
> force: false

**Comment by Roper89** [comment]
New bug with _/authme unregister <player>_
When we cancel a player registration,  his expended attempt in **maxRegPerIp** not restored.
Even if we cancel the registration, **maxRegPerIp** - will consider it registered

**Comment by sgdc3** [comment]
@Roper89 Could you open a new issuw for that? Just to keep the original issue clear. :)

**Comment by Roper89** [comment]
ok :)

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by ljacqu** [comment]
Work was done for this issue within 5.4 -> moving back. Please create a follow-up issue if needed.

**Comment by sgdc3** [comment]
We didn't fix this at all, we just fixed some minor related issues

**Comment by ljacqu** [comment]
This brings me back to a comment I wrote earlier: https://github.com/AuthMe/AuthMeReloaded/issues/1344#issuecomment-334366634 Fact is work was done here, and I'd like an issue in 5.4 to account for it. What do you suggest?

**Comment by sgdc3** [comment]
Moved to 5.5
