### ISSUE TITLE
Missing SQL permissions

### ISSUE THREAD

**Issue by GeigerCounter** [AuthMe/AuthMeReloaded#1352]
Unsure why, but the check to see if the table exists is failing with my particular config.

### What behaviour is observed:
What happened?
AuthMe tries to recreate the table I'm integrating it into even though it already exists and should be configured correctly.
### What behaviour is expected:
What did you expect?
I expected AuthMe to hook into the SMF table and allow registration through SMF.

### Environment description
Standalone Spigot 
### AuthMe build number:
AuthMe 5.4

### Error Log:
https://somethinghub.com/magicant/spigoterror.log

### SQL Table:
https://somethinghub.com/magicant/sql.html

### Configuration:
https://somethinghub.com/magicant/config.yml

**Comment by ljacqu** [comment]
Could you post the full error from authme.log please? I'm interested in seeing the stack trace so we know when this happens exactly.

**Comment by GeigerCounter** [comment]
@ljacqu https://somethinghub.com/magicant/authme.log

**Comment by sgdc3** [comment]
@GeigerCounter The authme user doesn't have the required permissions.

Try running this command in the mysql console:
`GRANT ALL PRIVILEGES ON smf.* TO 'authme'@'%' WITH GRANT OPTION;`

**Comment by GeigerCounter** [comment]
Yeah, that fixed it.
