### ISSUE TITLE
API: missing RegisterEvent

### ISSUE THREAD

**Issue by SzymoonDev** [AuthMe/AuthMeReloaded#1357]
Hi, 
Can you add to AuthMeApi on login event? I know, i can add command to be executed on player login/register, but i want to listen event. Maybe this is already added to AuthMe, but i cant find this.
Sorry for my bad English,
Regards.

**Comment by ljacqu** [comment]
Hi, I think you're looking for our [LoginEvent](http://ci.xephi.fr/job/AuthMeReloaded/javadoc/fr/xephi/authme/events/LoginEvent.html). I don't think we have an event for registration, though.

**Comment by SzymoonDev** [comment]
I don't need RegisterEvent, because on succesfully player register, LoginEvent is called. Thank you!

**Comment by ljacqu** [comment]
Excellent, in that case I close this issue :) Thanks
