### ISSUE TITLE
1.13 Version Support

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1361]
Dinnerbone has announced the first snapshot of 1.13 is will releasing next week.
Probabily the 1.13 is will releasing before 2018.
Can you WAIT and add SUPPORT for 1.13 version on AuthMe 5.4?

**Comment by sgdc3** [comment]
We can't until spigot 1.13 is released xD

**Comment by Pluginsel** [comment]
@sgdc3 probabily 1.13 is will released on the next 2-3 weeks. 
And after this, is will released for Spigot. :)

**Comment by sgdc3** [comment]
@Pluginsel We don't know anything about 1.13 yet.

**Comment by Bjornskjald** [comment]
Is there any work in progress on 1.13?

**Comment by krusic22** [comment]
It's already updated to work with 1.13.

**Comment by Bjornskjald** [comment]
It doesn't say so on spigotmc nor bukkit, so i thought it's not working yet
