### ISSUE TITLE
New players spawning for the first time on the highest Y axis

### ISSUE THREAD

**Issue by MithrandirCraft** [AuthMe/AuthMeReloaded#1362]
This is a very old issue that has now somehow returned.

All new players appear above the defined spawnpoint, at the highest possible block on the Y axis.
It's happening on each of my servers. The first time a player enters a server with authme installed, he/she is sent to the highest possible position.

Config file for one server (Factions): https://hastebin.com/zusihejaza.bash

Authme v: 5.4-SNAPSHOT (build: 1797)
Spigot: 1.12.1

**Comment by sgdc3** [comment]
works fine on my server, could you provide more infos?

**Comment by MineSAT** [comment]
Maybe you have misconfigured the Spawn server, do you use any particular plugin or Essentials?

**Comment by MithrandirCraft** [comment]
@MineSAT 
Well it started happening after I updated authme.
What do you mean by "Spawn server"? There are many diverse spawns.

**Comment by MithrandirCraft** [comment]
@sgdc3 Currently added Config and Version.

**Comment by sgdc3** [comment]
Does it happen with the latest builds?

**Comment by MithrandirCraft** [comment]
Updating*

**Comment by MithrandirCraft** [comment]
May have been fixed. Will request re-open if else.

**Comment by MithrandirCraft** [comment]
Reopening issue still persists.

**Comment by ljacqu** [comment]
Closing as @MithrandirCraft said in #1591 that this hasn't been observed in a long time
