### ISSUE TITLE
Improve /authme debug mysqldef 

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1367]
With `/authme debug mysqldef` it's possible to view the "NOT NULL" status of MySQL columns. However, the command only checks for the `NOT NULL` status and fails to check if there is a default value in the definition.

This is relevant, as for instnace a database generated from our 5.2 release will have the email column to be defined as `VARCHAR(255) DEFAULT 'your@email.com'` — nullable but with a default value, so effectively `NOT NULL`.

**Comment by ljacqu** [comment]
This seems to be important when people will migrate from 5.3 so moving into milestone

**Comment by sgdc3** [comment]
Any news?

**Comment by ljacqu** [comment]
Please verify ;)

**Comment by sgdc3** [comment]
lul

**Comment by ljacqu** [comment]
As in if you have time you can check it out to see if you have any feedback ;3

**Comment by sgdc3** [comment]
Seems working as intended ;)
