### ISSUE TITLE
API: Get player information

### ISSUE THREAD

**Issue by DevNatan** [AuthMe/AuthMeReloaded#1373]
Well I'm making a plugin that it should show some information that are in AuthMe, like password, email ... But I do not find any method in the API that shows the email for example.

I searched the AuthMe code and found "PlayerAuth" and "PlayerCache" only they have an annotation "@Inject" which I do not know for what it is, I just wanted to have a way of invoking "PlayerCache" and get the information of the players, returning in a "PlayerAuth".

My authme version: 5.3.2 (b1726)

**Comment by ljacqu** [comment]
When we add this I'd like whatever new methods we add to return an interface, that PlayerAuth can implement (or some other class), but I'd just like our PlayerAuth class not to be directly coupled with API methods.

**Comment by DevNatan** [comment]
I understand, but is not there any way to get a player's email through your name or unique id?

**Comment by ljacqu** [comment]
At the moment, there isn't.

**Comment by DevNatan** [comment]
I urgently ask YouTube to add methods that can do such a function of obtaining information. Be it not necessarily encrypted. It would greatly increase the number of plugins that can use your API.

Sorry for persistence, but i'm Brazilian, and we're known for It... 😁😂😋

**Comment by ljacqu** [comment]
This was solved within #1448, so marking as a duplicate for our bookkeeping purposes (although this is the original issue and it's more general)
