### ISSUE TITLE
Question - Command for event OnJoin

### ISSUE THREAD

**Issue by SaitDev** [AuthMe/AuthMeReloaded#1378]
We have onLogin and onRegister events. So what is OnJoin. Its anytime player enter server but not yet login or first time player enter the server?

Thank in advance

**Comment by sgdc3** [comment]
Yes

**Comment by SaitDev** [comment]
What do you mean? my first option or 2nd

**Comment by sgdc3** [comment]
Sorry, the first one ;)

**Comment by SaitDev** [comment]
Thank you
