### ISSUE TITLE
Help: Communications link failure

### ISSUE THREAD

**Issue by barruMC** [AuthMe/AuthMeReloaded#1379]
### What behaviour is observed:
The server drops after starting the .run from Debian since it can not start the mySql database but everything is correct.

### What behaviour is expected:
Solve the problem.

### Steps/models to reproduce:
We do not know, everything is fine, less that mistake.

### Plugin list:
AsyncWorldEditInjector
WorldEdit
AsyncWorldEdit
IPWhitelist
LampControl
Essentials
UUIDSpoof_-_Fix
PermissionsEx
PlugMan
DiscordMC
ViaVersion
Vault
BungeeTabListPlus
Multiverse-Core
Citizens
SkinsRestorer
ChestCommands
UltraCosmetics
AuthMe
AuthMeBridge

### Environment description
BungeeCord

### AuthMe build number:
AuthMe-5.3.2

### Error Log:
https://pastebin.com/raw/UsHD2eii

### Configuration:
https://pastebin.com/raw/nGR3Y7r9

**Comment by games647** [comment]
AuthMe doesn't start the MySQL it only connects to it. So you get this kind of error if AuthMe cannot connect to it.

**Comment by barruMC** [comment]
@games647 I'm not sure that you've seen the error line, I'll mark it for you to see.

> [21:01:54] [Server thread/WARN]: [AuthMe] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure
> 
> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
> [21:01:54] [Server thread/WARN]: [AuthMe] Please check your database settings in the config.yml file!
> [21:01:54] [Server thread/WARN]: [AuthMe] Could not create data source: [CommunicationsException]: Communications link failure

**Comment by games647** [comment]
That's exactly what I meant. It means that the driver cannot reach your MySQL/MariaDB server. Plugins only connect to running MySQL/MariaDB servers. The server should already be installed and running when you start up the Minecraft server.

**Comment by barruMC** [comment]
But our problem has been nothing more than the server fell, before it worked properly, I do not know because now it comes out as well. @games647 Any solution?

**Comment by games647** [comment]
Check if the MySQL/MariaDB is running and if your connection details (host and port) in the AuthMe config are correct.

**Comment by barruMC** [comment]
Yes, the host and port are correct, I do not know why I get the error.  @games647

**Comment by barruMC** [comment]
Can it work with InnoDB? @games647

**Comment by games647** [comment]
Do you checked if the MySQL/MariaDB is running?

**Comment by barruMC** [comment]
Yes, it is checked, they are working. @games647

**Comment by barruMC** [comment]
Clearly the database exists, and if it is running perfectly mysql but follow the error of the linked. @games647

**Comment by games647** [comment]
Connection refused is a message that there is no service running on that host and port combination. You can event try it on your own with `curl 127.0.0.1:3306`.

Please check `service mysql status` or maybe MySQL server really runs on a different port. Then login into MySQL (`mysql -u user -p`) and run `SHOW VARIABLES LIKE 'port'`

**Comment by barruMC** [comment]
Whats 'port'? @games647

**Comment by games647** [comment]
That's not a placeholder. Just this exact SQL statement.

**Comment by barruMC** [comment]
The following when putting the show variables as 'port'
https://gyazo.com/5312f9b89eae0d2164bf2019ec239321 @games647

**Comment by games647** [comment]
Then please check if the MySQL is running on the same host as the Minecraft server. I guess you use a game server hoster?

**Comment by barruMC** [comment]
Yes it's a gamehosting. @games647

**Comment by barruMC** [comment]
It's a VPS @games647 Debian Minimal.

**Comment by games647** [comment]
Then please try the curl command, maybe it's a wrong firewall rule that applied to the localhost too.

**Comment by barruMC** [comment]
we have Debian Minimal and, therefore, we have neither iptables nor ufw @games647

**Comment by barruMC** [comment]
When doing the curl it stays in white and after a while says I do not know what of q can not connect. @games647

**Comment by games647** [comment]
Please try out to use '127.0.0.1' instead of localhost inside the AuthMe config.
