### ISSUE TITLE
Mail API is not set error

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1389]
I used /email recover <email> command, but on console I have this error:
[AuthMe] Mail API is not set

How to set Mail API?

**Comment by ljacqu** [comment]
In your config.yml the `Email:` section needs to be filled.

**Comment by Pluginsel** [comment]
@ljacqu How do I fill?

**Comment by Pluginsel** [comment]
I did. Thanks.
