### ISSUE TITLE
bug with /authme unregister

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1391]
When we cancel a player registration, his expended attempt in **maxRegPerIp** not restored.
Even if we cancel the registration, **maxRegPerIp** - will consider it registered

**Comment by sgdc3** [comment]
Strange, could you try to disable caching? (datasource.caching in our config.yml)

**Comment by sgdc3** [comment]
As "When we cancel a player registration" you mean unregister, right?

**Comment by Roper89** [comment]
> you mean unregister, right?
Yes, `/authme unregister <player>`
I changed to `caching: false`   and now works :+1:

**Comment by sgdc3** [comment]
@ljacqu @HexelDev Caching is completely broken xD

**Comment by HexelDev** [comment]
Nice ahahahha!
I need to give it a look and understand how it's built, after that I'll try to figure out some improvements xD

**Comment by sgdc3** [comment]
@Roper89 How did you remove the user? /authme unregister or directly from the db?

**Comment by Roper89** [comment]
I used the command `/authme unregister <player>`

**Comment by sgdc3** [comment]
Do you have multiple servers with authme?

**Comment by Roper89** [comment]
No, only one

**Comment by sgdc3** [comment]
Was the player online when you performed /authme unregister?

**Comment by Roper89** [comment]
Sorry, but `caching: false` did not help
I was mistaken because I had a registered account earlier from another ip 
`/authme unregister <player>` in **maxRegPerIp** not restored.

**Comment by sgdc3** [comment]
Ok, that makes more sense now xD

**Comment by sgdc3** [comment]
SQLite, right?  @Roper89

**Comment by Roper89** [comment]
I do not use it

**Comment by sgdc3** [comment]
MySql? @Roper89

**Comment by Roper89** [comment]
No. 
I do not even know what it is.

**Comment by Twonox** [comment]
@Roper89 sgdc3 want know what you use for authme's database.
So there is two way: SQLite (default) and MySQL. If you don't know what MySQL is, you probably use the default way, which is SQLite.

**Comment by Twonox** [comment]
@sgdc3 I have tried to reproduce this issue: unregistration works fine, I can register me again and I can register with other account, with latest build (and in a online server, not crack (idk if it change anything)).
What build are you using @Roper89 ?

**Comment by Roper89** [comment]
spigot-1.12.2-R0.1-SNAPSHOT-b1421
AuthMe-5.4-SNAPSHOT

**Comment by Twonox** [comment]
What is the build number of authme? You can see it with the command` /authme version`

**Comment by Roper89** [comment]
build: 1822

**Comment by Twonox** [comment]
Please try the latest build http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Roper89** [comment]
Problem solved.

After the last update, I started receiving a message in the console: "[SpigetUpdate] Invalid SemVer versions specified [450-SNAPSHOT] [450-SNAPSHOT]"  — What does it mean?

**Comment by sgdc3** [comment]
@Roper89 This isn't related to authme: we don't use the spiget updater.
