### ISSUE TITLE
Authme Crashing server.

### ISSUE THREAD

**Issue by Theboss81** [AuthMe/AuthMeReloaded#1392]
So im not using format because im not confortable with it.

So, here is a back story.. 
i moved host.. everything is fine but when i login, server crashes....
i used old fancy trick in which i disabled the plugins one by one and checked
(for example renaming authme.jar to authme.jarold) 
and i found authme was culprit..

i also tried other things with it.. when i removed my "old" authme.db it made a new one and authme and server work perfectly... but that means i lost my old authme passwords which is bad... and i need them!
please send help..

Plugins:
>pl
> [07:10:16 INFO]: Plugins (62): WildTP, PlaceholderAPI, PlayTimeRewardsRecoded, NametagEdit, Broadcaster, PvPToggle, ChatReaction, OldCombatMechanics, DeluxeTags, SuperTrails, VoxelSniper, ViaVersion, StaffPlus, ViaBackwards, WorldEdit, CustomWhitelist, OreAnnouncer, CustomList, CombatLog, ClearLag, WorldBorder, BuycraftX, Interactables, Votifier, Multiverse-Core, ProtocolLib, NightVision, eZProtector, PermissionsEx, FeatherBoard, SuperbVote, FishBowls, ServerListPlus, Vault, CapAFK, Rankup, Parties, HolographicDisplays, WorldGuard, AAC, SkinsRestorer, ChestCommands, HeadShot, AreaShop, MobStacker2, PortalCommands, Essentials, SafeTrade, CrateReloaded, CoinFlipper, SilkSpawners, Citizens, EssentialsChat, CrazyAuctions, GriefPrevention, Bookshelves, CommandNPC, EssentialsSpawn, ShopGUIPlus, TitleManager, AuthMe, LiteBans

>authme version
> [07:10:41 INFO]: ==========[ AuthMeReloaded ABOUT ]==========
> [07:10:41 INFO]: Version: AuthMeReloaded v5.3.2 (build: 1726)
> [07:10:41 INFO]: Developers:
> [07:10:41 INFO]: Alexandre Vanhecke // xephi59 (Original Author)
> [07:10:41 INFO]: Lucas J. // ljacqu (Main Developer)
> [07:10:41 INFO]: Gnat008 // gnat008 (Developer)
> [07:10:41 INFO]: DNx5 // DNx5 (Developer)
> [07:10:41 INFO]: games647 // games647 (Developer)
> [07:10:41 INFO]: Tim Visee // timvisee (Developer)
> [07:10:41 INFO]: Gabriele C. // sgdc3 (Project manager, Contributor)
> [07:10:41 INFO]: Website: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/
> [07:10:41 INFO]: License: GNU GPL v3.0 (See LICENSE file)
> [07:10:41 INFO]: Copyright: Copyright (c) AuthMe-Team 2017. All rights reserved.

This error comes whenever i login-

> A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x000000000000a53e, pid=23, tid=0x00007f7416570ae8
 JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
 Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
 Derivative: IcedTea 3.4.0
Distribution: Custom build (Fri Jun 16 13:41:54 GMT 2017)
 Problematic frame:
 C 0x000000000000a53e
 Core dump written. Default location: /home/container/core or core.23
 An error report file with more information is saved as:
 /tmp/hs_err_pid23.log
If you would like to submit a bug report, please include
instructions on how to reproduce the bug and visit:
http://icedtea.classpath.org/bugzilla
/entrypoint.sh: line 17: 23 Segmentation fault (core dumped) ${MODIFIED_STARTUP}
PTDL_CONTAINER_ERR: There was an error while attempting to run the start command.
this shit

**Comment by games647** [comment]
Please append your config and a pastebin / gist link to the crash dump. Segmentation fault means there is either a bug in the JVM or in any native library that is used. In case it's a JVM bug, you could try to update to 1.8.0_152, Java 9 or switch to OracleJre.

**Comment by Theboss81** [comment]
my config- https://hastebin.com/nipakubaba.bash also, server is cracked.

**Comment by Theboss81** [comment]
https://hastebin.com/nipakubaba.bash

**Comment by Theboss81** [comment]
i closed it by a mistake, above is my config link

**Comment by games647** [comment]
And the crash dump please at /tmp/hs...

**Comment by Theboss81** [comment]
sorry, but there is just one of that file which is because of an old plugin, which i removed

**Comment by Theboss81** [comment]
https://hastebin.com/iveqakozen.go

**Comment by Theboss81** [comment]
its old, just telling

**Comment by games647** [comment]
This what the error says it created a new file at /tmp/hs_err_pid23.log. We need that specific file.

**Comment by Theboss81** [comment]
umm

**Comment by Theboss81** [comment]
[hs_err_pid23 (2).log](https://github.com/AuthMe/AuthMeReloaded/files/1427065/hs_err_pid23.2.log)
there

**Comment by Theboss81** [comment]
How can you say its not your fault? server runs perfectly when authme isn't there.

**Comment by Theboss81** [comment]
Letme tell what i think is a problem-
authme encrypts the passwords and data...
which needs public and private key..
because of host change(and ip change of server) it broke itself, and that's why when i use new DB (like remove old DB and reload server)
it work's perfectly.. i need some way to DE-ENCRYPT USER PASSWORDS.

**Comment by Theboss81** [comment]
here is my latest.log
tell me the problem if authme isn't causing problem
[latest (2).log](https://github.com/AuthMe/AuthMeReloaded/files/1427086/latest.2.log)

**Comment by games647** [comment]
>How can you say its not your fault?

Because Segmentation faults doesn't really happen in Java. The error (hs_..) you uploaded is from "Fri Jun 16 13:41:54" and shows a bug in the SQLite driver after Jobs tries to load it. 

>tell me the problem if authme isn't causing problem

Is that the log after the server crashed? Does only the Minecraft server crash or the complete JVM? Do you have a reference to crash file hs_* (not an old one)?

**Comment by Theboss81** [comment]
well, i don't get what you mean
about 2nd answer

**Comment by Theboss81** [comment]
also jobs is already disabled

**Comment by Theboss81** [comment]
okay, its spigot(normal) then i use ubandu 64 bit,

**Comment by Theboss81** [comment]
Please answer this:
Letme tell what i think is a problem-
authme encrypts the passwords and data...
which needs public and private key..
because of host change(and ip change of server) it broke itself, and that's why when i use new DB (like remove old DB and reload server)
it work's perfectly.. i need some way to DE-ENCRYPT USER PASSWORDS.

also, i already posted list of my plugins

**Comment by Theboss81** [comment]
Why im sure its authme? because when i deleted old authme.db and restarted server, it worked just fine.

**Comment by Theboss81** [comment]
remove those labels please

**Comment by sgdc3** [comment]
Authme uses many libraries and relies on many internal java utilities, please update to the latest java 8 version.

**Comment by Theboss81** [comment]
okay, thanks

**Comment by Theboss81** [comment]
i'll try

**Comment by Theboss81** [comment]
okay, i installed latest java 8 and still the problem dosen't fixes

**Comment by Theboss81** [comment]
why isn't this answerd-
Please answer this:
Letme tell what i think is a problem-
authme encrypts the passwords and data...
which needs public and private key..
because of host change(and ip change of server) it broke itself, and that's why when i use new DB (like remove old DB and reload server)
it work's perfectly.. i need some way to DE-ENCRYPT USER PASSWORDS.

**Comment by ljacqu** [comment]
We don't encrypt passwords—we hash them. No keys involved and different concept. No way of _decrypting_ them. Maybe your db file is somehow corrupt but that shouldn't cause a segfault anyhow.

**Comment by Theboss81** [comment]
So, how do i fix this problem, i want to restore passwords...

**Comment by Theboss81** [comment]
if DB is wrong, it will no longer work..

**Comment by games647** [comment]
1) Please post the missing spigot version.
2)

>well, i don't get what you mean about 2nd answer

I meant whether the process hang, only the minecraft implementation crashed like "Server stopped responding..." or the JVM - the java process - crashed (A fatal error has been detected by the Java Runtime Environment). If you meant the last one, we need the **associated** crash report file to find the source - not some old files from June you sent previously. 

If you use docker (container as username?), then you have to search for that report files in that docker container.

3) 

>Why im sure its authme? because when i deleted old authme.db and restarted server, it worked just fine.

I **expect** it's a bug inside the SQLite driver we use to store the user data into the db file. This could be fixed by a SQLite driver update, but it could also be bug that isn't reported or fixed yet. 

Segmentation faults happens if a program with memory control () tries to read something from memory that doesn't exist. This could have multiple sources like unexpected content of the database file, hardware issues, programmer mistake, etc.

**Comment by Theboss81** [comment]
well, i use spigot 1.12, and is there a way to check if suthme.db is currupted or migrate to a new db?

**Comment by krusic22** [comment]
Try migrating it to MySQL?

**Comment by Theboss81** [comment]
sure it'll work?

**Comment by ljacqu** [comment]
You can open the file with a sqlite db viewer. Could you check if that works?

**Comment by Theboss81** [comment]
it opens

**Comment by Theboss81** [comment]
what now?

**Comment by games647** [comment]
>well, i use spigot 1.12

Which exact version? Spigot recently updated the driver.

**Comment by ljacqu** [comment]
If you can open the file I'd like to ask you to try and save it as another file, then use that file as your authme.log to try if it works then. 

Who knows at this point :/ I mean besides you sending one of us your database (which you probably don't want to, understandably) all we can do is make shots in the dark

**Comment by Theboss81** [comment]
i will just reinstall server. thankyou
