### ISSUE TITLE
Authme and essentials-spigot

### ISSUE THREAD

**Issue by mattymatty97** [AuthMe/AuthMeReloaded#1394]
when a server has a version of essntials-spigot the authme hooking fails whit a "null pointer exeption" or a "InjectorReflectionException".

https://pastebin.com/hw3dzAhd

I've installed mv-core and other plugins but i've tested removing one by one that are not they fault.

**Comment by ljacqu** [comment]
Can you post the exception from your error log abd your authme version?

**Comment by mattymatty97** [comment]
The versions i've tryed are 5.3.2, 5.3.1, 5.3
I've not tryed older builds

Error log? How to find it?

**Comment by ljacqu** [comment]
authme.log in plugins/AuthMe/  Without it we're not sure where the error happens

**Comment by mattymatty97** [comment]
[authme.log](https://github.com/AuthMe/AuthMeReloaded/files/1437095/authme.log)

it might be enough, but there are the same messages of the mclog simply purged from non AUTHME ones, right?

**Comment by sgdc3** [comment]
@mattymatty97 still happening?

**Comment by sgdc3** [comment]
Stop using essentials-spigot, use EssentialsX instead.

**Comment by sgdc3** [comment]
Essentials-Spigot is very outdated and glitched, EssentialsX is another fork, i'm surr it works just fine ;)

**Comment by mattymatty97** [comment]
ok i'll try it and send a feedback
