### ISSUE TITLE
New config.yml file ?

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1397]
Hi,

https://github.com/AuthMe/AuthMeReloaded/blob/master/samples/NewConfig.yml

@sgdc3 Will you not continue that ? :)

**Comment by sgdc3** [comment]
Since we changed many options it needs to be updated xD

**Comment by ljacqu** [comment]
We should definitely revisit the config, but imho not in the next milestone. If we add a lot of features in the next milestone we'll add more configurations, then when we have a good base it will be worth it to restructure things. This will also allow us to have time to think about it in detail. We need to be careful when we change the config to have something that is future-proof.

**Comment by ljacqu** [comment]
To be handled with #448, so closing this ;)
