### ISSUE TITLE
The number of IP registrations cannot be restricted

### ISSUE THREAD

**Issue by Zhb1508444061** [AuthMe/AuthMeReloaded#1399]
Config.yml already has the # maxRegPerIp: 1
But he could not limit the number of IP registrations
Is there any solution?
Authme version: 5.3.2
Test clothes with your own machine.
The IP limit of your own computer test.
But you can have an unlimited number of accounts.
Ask for help
I'm a Chinese, I'm not good at English...

**Comment by sgdc3** [comment]
>Authme version: 5.3.2

Please update to the latest dev build.

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Zhb1508444061** [comment]
@sgdc3 
Thank you, I will test tomorrow afternoon plug-in IP restrictions. The plugin is very good. hope to do better

**Comment by Zhb1508444061** [comment]
@sgdc3  
limit The local IP?
5.4 version not limit local IP?
local IP： 127.0.0.1

**Comment by sgdc3** [comment]
localhost is not limited

**Comment by Zhb1508444061** [comment]
@sgdc3
好的 非常感谢... 

Ok thank you very much...
