### ISSUE TITLE
Question - countriesBlacklist

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1403]
`Protection:`
    `enableProtection: false`
    `enableProtectionRegistered: false`
    `countries:` 
    `- US`
    `- GB`
    `countriesBlacklist:` 
    `- A1`

I want to block only one country, what settings do I need to set?
also does not work link https://dev.bukkit.org/projects/authme-reloaded/pages/countries-codes

**Comment by sgdc3** [comment]
Where did you find this link? I was sure i already changed it everywhere.

**Comment by sgdc3** [comment]
You have to add the country you want to block to the countriesBlacklist section.

**Comment by ljacqu** [comment]
More specifically, for whitelist / blacklist stories, whenever the whitelist is not empty, we go through the whitelist, otherwise we consider the blacklist.

**Comment by sgdc3** [comment]
@ljacqu are you sure?

**Comment by ljacqu** [comment]
Yes, it's the only thing that makes sense (well, kind of): if a whitelist is defined by definition we can't allow anything that is not inside it

**Comment by Roper89** [comment]
> Where did you find this link?

 In my configuration (`config.yml`) file from the latest build. 
Where can I get a working link?

If I want to use only a black list. 
I must in "countries:" delete all the lines completely or change them to empty ones?

Screenshot — https://i.imgur.com/fVVnrxZ.png

**Comment by sgdc3** [comment]
2 should be fine

**Comment by ljacqu** [comment]
I think it should be `countries: []`, FYI.

Btw, with `/authme debug cty` you can test the country restriction with your configuration.
