### ISSUE TITLE
AuthMe opens too many MySQL connections

### ISSUE THREAD

**Issue by DoNotSpamPls** [AuthMe/AuthMeReloaded#1405]
### What behaviour is observed:
When AuthMe is set to MySQL, it opens too many connections and overloads the MySQL server.
I have even tried to increase the connections limit, same deal.

### What behaviour is expected:
Not disrupting MySQL for me and other users of the same server.

### Steps/models to reproduce:
* Set your AuthMe plugin to use MySQL
* Put in your data
* AuthMe opens too many connections

I have confirmed that it happens with and without SSL connections.

### Plugin list/version:
![here](https://bitcoin.is-serious.business/383e7e.png)

### Environment description
It's a BungeeCord network, in this enviroment it was only the proxy and the server. I was using MySQL.

### Error Log:
Log of AuthMe startup messages - https://hastebin.com/opawowinaw.sql

### Configuration:
https://hastebin.com/usimihimuz.bash

**Comment by DoNotSpamPls** [comment]
Update: I have tried the latest build from the CI, same issue.

**Comment by sgdc3** [comment]
try with poolSize: 10

**Comment by DoNotSpamPls** [comment]
That worked! Thanks for the fast answer.
I guess auto didn't work all that well :(

**Comment by sgdc3** [comment]
Probably you have a cpu with a huge core count, auto uses the core count as poolsize

**Comment by DoNotSpamPls** [comment]
I guess so, it's on a shared hosting provider. They probably have a lot of cores on their machines.
