### ISSUE TITLE
Error output 

### ISSUE THREAD

**Issue by KorkugunuB** [AuthMe/AuthMeReloaded#1406]
### Plugin list:
This can be found by running `/pl`
https://hastebin.com/zomopusato.md

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord network, MySql

### AuthMe build number:
This can be found by running `/authme version`
AuthMeReloaded v5.3.2 (build: 1726)

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
https://hastebin.com/hufunonoxu.md

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://hastebin.com/ihopuluzeg.bash

**Comment by sgdc3** [comment]
Do you have any error related to authme before the thread dump?

**Comment by sgdc3** [comment]
Please update to the latest authme dev build and try again http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by sgdc3** [comment]
@KorkugunuB Bump
