### ISSUE TITLE
Registration does not work correctly

### ISSUE THREAD

**Issue by Dimatert9** [AuthMe/AuthMeReloaded#1407]
Hello. I am use AuthMe-1865. When new player join authme says that it need register(https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/resources/messages/messages_en.yml#L2). When player use register command, authme send message that he was successfully registered and player is not registered(https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/resources/messages/messages_en.yml#L25). After register authme does not automatically login player and continue sends message that player needs register. If try to register again it will send message that player already registered.

Config: https://hastebin.com/furukisose.bash
I use sqlite database
Video with this issue: 
https://youtu.be/aTnXBreBswA

**Comment by sgdc3** [comment]
Do you have any error in the console log?

**Comment by Dimatert9** [comment]
No. There is no errors.

**Comment by Dimatert9** [comment]
Somethink wrong with async tasks?
useAsyncTasks: false
useAsyncPreLoginEvent: false
this is solve my problem.

**Comment by DarkFort** [comment]
I have the same problem, very much to fix.

**Comment by sgdc3** [comment]
Does it work with 
>useAsyncTasks: true
>useAsyncPreLoginEvent: false

?

**Comment by Dimatert9** [comment]
```
useAsyncTasks: true
useAsyncPreLoginEvent: false```
This is does not help.

If false;true or false;false registration works good.

**Comment by sgdc3** [comment]
do you have caching enabled?

**Comment by Dimatert9** [comment]
If true;true and caching false registration works good.

**Comment by sgdc3** [comment]
Do you use bungeecord?

**Comment by Dimatert9** [comment]
Yes. I use bungeecord. Also i use auto redirect to other server after login/register.

**Comment by sgdc3** [comment]
how many server with authme do you have?

**Comment by Dimatert9** [comment]
One.

**Comment by sgdc3** [comment]
very very strange O_o do you use authmebridge or authmebungee?

**Comment by Dimatert9** [comment]
No. I dont use authme-bridge/bungee

**Comment by sgdc3** [comment]
Very strange, seems like async tasks breaks caching...

**Comment by sgdc3** [comment]
@ljacqu any idea? :/

**Comment by ljacqu** [comment]
I'll have a look in a bit

**Comment by DarkFort** [comment]
I have AuthMe and AuthMeBridge on two servers. Messages are displayed several times.

**Comment by ljacqu** [comment]
On Spigot 1.11.2 I cannot reproduce the issue :/ Used the exact same config as posted in the bug report.

**Comment by Dimatert9** [comment]
Hm.. I tried to reproduce this bug on my PC. And registration works good, but when  i put sqlite database from my servers, registration broken again.

**Comment by Dimatert9** [comment]
Threre is video https://youtu.be/X4s7tB2XMWE

**Comment by Dimatert9** [comment]
Maybe i can give to you my database? Just give me link to you where i can post download links.

**Comment by sgdc3** [comment]
@Dimatert9 does it happen with the latest build?

**Comment by Dimatert9** [comment]
No. Now when i join and register i recieved 'registered' and 'unknown_user' messages and was teleported to other server. But when i try to rejoin session is not work and i need login. After login all good.

**Comment by Dimatert9** [comment]
https://www.diffchecker.com/lM97d3SN
https://www.diffchecker.com/tCDf8K7h

if run asynchronousLogin.forceLogin(player) with small delay, registration will work correctly. But idk, can this be a good solution?https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/process/register/executors/AbstractPasswordRegisterExecutor.java#L92

**Comment by ljacqu** [comment]
Database delay. I'm assuming it takes longer to write into the database than we wait before we start the force login process, at which point the first thing we'll do is tell the database "hey give me that user"

**Comment by sgdc3** [comment]
@ljacqu Damn, how should we handle that?

**Comment by ljacqu** [comment]
Maybe really go with the small delay that @Dimatert9 proposes? No other ideas ATM :/

**Comment by ljacqu** [comment]
Based on our Discord chat, if this only happens because you have a SQLite database with 100k entries I would vote not to fix this

**Comment by Dimatert9** [comment]
But if you support sqlite database i think you need fix it :)
Maybe add a delay only to sqlite and with config option?

**Comment by ljacqu** [comment]
To be fair you're ignoring an all caps warning because of your SQLite size ;) We do NOT support it to be used with more than 5k entries.

**Comment by pCosminV** [comment]
**# SOLVED:** 

    _registration:
        # Enable registration on the server?
        enabled: true
        # Send every X seconds a message to a player to
        # remind him that he has to login/register
        messageInterval: 5
        # Only registered and logged in players can play.
        # See restrictions for exceptions
        force: true
        # Type of registration: PASSWORD or EMAIL
        # PASSWORD = account is registered with a password supplied by the user;
        # EMAIL = password is generated and sent to the email provided by the user.
        # More info at https://github.com/AuthMe/AuthMeReloaded/wiki/Registration
        type: 'PASSWORD'
        # Second argument the /register command should take: NONE = no 2nd argument
        # CONFIRMATION = must repeat first argument (pass or email)
        # EMAIL_OPTIONAL = for password register: 2nd argument can be empty or have email address
        # EMAIL_MANDATORY = for password register: 2nd argument MUST be an email address
        secondArg: 'CONFIRMATION'
        # Do we force kick a player after a successful registration?
        # Do not use with login feature below
        forceKickAfterRegister: false
        # Does AuthMe need to enforce a /login after a successful registration?
        forceLoginAfterRegister: true_

**You need to set "forceLoginAfterRegister" to true and then it'll say "Please login..." not "Please register".**

**Comment by Dimatert9** [comment]
I think do /login after /register is not good and uncomfortable. If you have this issue, just mirgate to mysql. Also you can set caching to false or useAsyncTasks to false.

**Comment by sgdc3** [comment]
>Also you can set caching to false or useAsyncTasks to false.
No, async and caching should be fine

**Comment by Dimatert9** [comment]
It is fine, when sqlite does not have a 300k rows.
