### ISSUE TITLE
AuthMe Purge crashes server

### ISSUE THREAD

**Issue by LinsaFTW** [AuthMe/AuthMeReloaded#1411]
### What behaviour is observed:
AuthMe Purge crashes the server after some time and seems not to be deleting anything.

### What behaviour is expected:
I expected it to delete old user data but it just crashes.

### Steps/models to reproduce:
Doing /authme purge 90

### Environment description
BungeeCord Network - Paperspigot using MySQL

### AuthMe build number:
5.3.2

**Comment by games647** [comment]
Please add the crash report

**Comment by LinsaFTW** [comment]
I cannot replicate the error because i had it 3 days ago and i resetted my sql today. I delete logs of the server daily so i dont have any crash reports or server logs.

**Comment by sgdc3** [comment]
Please retry with latest builds (disable datasource.caching, it has some issues with bungee atm) and provide more infos.

**Comment by ljacqu** [comment]
Please open a new issue. This was closed six months ago
