### ISSUE TITLE
Allowing AuthMe only for certain groups

### ISSUE THREAD

**Issue by StrafeZ** [AuthMe/AuthMeReloaded#1416]
Allow Authme RL to only work for certain groups.

**Comment by ljacqu** [comment]
Hi @StrafeZ, I went ahead and removed the issue template since it only contained one sentence by you. Maybe could you expand on it a little so we know what you're really trying to have?

**Comment by StrafeZ** [comment]
So for example, I have my donor ranks and my 4 Staff ranks.

I want to make it so that people who have Donor ranks do NOT get the /register and /login, however the Staff ranks do. You hould make it so that anyone who has a permission such as authme.register and authme.login are ONLY able to get it, anybody else bypasses, and doesnt even get the message.

Thanks. Sorry if it was too brief before :)

**Comment by ljacqu** [comment]
Thanks for your comment.

I just realized that #1387 is essentially the same request as in this issue, so I'll close this in favor of the other issue (keeps our tracking a little clearer). Your feedback, however, is appreciated and noted.
