### ISSUE TITLE
Prevent chat for specific groups only

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1417]
I want to use the function "`allowChat: true`" to help players who can not register.
But players abuse this opportunity. 
They come on behalf of the administrator and write an advertisement that the server has changed the address.

I want the function to work for everyone except OP.

**Comment by Maxetto** [comment]
We might just add a config option specifically for unregistered people.
`allowChatForUnregistered: true`

**Comment by sgdc3** [comment]
@Maxetto would you like to work on it? If you want to become active again i'll readd you to the staff ;)

**Comment by ljacqu** [comment]
Hi @Roper89 this is available as of build n. 2076 on https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
Would you kindly give us some quick feedback whether we can close this, or if something doesn't conform to your expectations?
