### ISSUE TITLE
[EmailException]: Sending the email to the following server failed : smtp.gmail.com:465

### ISSUE THREAD

**Issue by comonier** [AuthMe/AuthMeReloaded#1422]
23.11 05:05:47 [Server] INFO comonier issued server command: /authme debug mail
23.11 05:05:48 [Server] INFO DEBUG: JavaMail version 1.5.6
23.11 05:05:48 [Server] INFO DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
23.11 05:05:48 [Server] INFO DEBUG: Tables of loaded providers
23.11 05:05:48 [Server] INFO DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle]}
23.11 05:05:48 [Server] INFO DEBUG: Providers Listed By Protocol: {imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]}
23.11 05:05:48 [Server] INFO DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
23.11 05:05:48 [Server] INFO DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
23.11 05:05:48 [Server] INFO DEBUG SMTP: need username and password for authentication
23.11 05:05:48 [Server] INFO DEBUG SMTP: protocolConnect returning false, host=smtp.gmail.com, user=mc126, password=<null>
23.11 05:05:48 [Server] INFO DEBUG SMTP: useEhlo true, useAuth true
23.11 05:05:48 [Server] INFO DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL false
23.11 05:05:48 [Server] WARN [AuthMe] Failed to send a mail to [comonier@gmail.com]: [EmailException]: Sending the email to the following server failed : smtp.gmail.com:465

**Comment by comonier** [comment]
why its saying wrong user and password ?
on config.yml i have setupted the right informations
"23.11 05:05:48 [Server] INFO DEBUG SMTP: protocolConnect returning false, host=smtp.gmail.com, user=mc126, password="
that is not that i have put on config

**Comment by comonier** [comment]
it was working fine, but after i register some accounts with the same email it stop to works.

**Comment by sgdc3** [comment]
@comonier have you enabled unsafe gmail app access?

**Comment by ljacqu** [comment]
@sgdc3 please stop mass-assigning people, then no one feels responsible for it

**Comment by comonier** [comment]
@comonier have you enabled unsafe gmail app access?
yes i did

**Comment by comonier** [comment]
https://hastebin.com/utitadizoc.vbs

**Comment by sgdc3** [comment]
@ljacqu sorry, the thing is that idk if you or @HexelDev are available, that was just to notify you guys.

**Comment by comonier** [comment]
the most strange is, it was working, i received email on gmail, and yahoo, doing change password to receive code, etc... all was working fine, and just stop to works. after i do something or not.

**Comment by comonier** [comment]
look at that working on yahoo:
https://hastebin.com/fudipixafi.vbs

**Comment by comonier** [comment]
email config
https://hastebin.com/rafidopofe.bash

**Comment by comonier** [comment]
found a error on authme log:

https://hastebin.com/roteholaru.vbs

**Comment by comonier** [comment]
i think it stop to work after i edit 
verification_code_email.html
there is some problem with that ?

**Comment by sgdc3** [comment]
Could you please post your verification_code_email.html file? Try to regenerate the default file and check if it works.

**Comment by comonier** [comment]
same problem after restore:
original recovery_code_email.html file
original email.html file
original verification_code_email.html file

**Comment by comonier** [comment]
look the log 

why he is trying to login using wrond datas ?
user=mc126, password=<null>

**Comment by comonier** [comment]
maybe that is the problem ?

**Comment by comonier** [comment]
23.11 05:05:48 [Server] INFO DEBUG SMTP: protocolConnect returning false, host=smtp.gmail.com, user=mc126, password=

**Comment by comonier** [comment]
after change port 465 to 25 received diferente error msg

https://hastebin.com/noxofikane.vbs

still not working

**Comment by sgdc3** [comment]
Strange, i checked the code, we p4ovide

**Comment by sgdc3** [comment]
Very strange, i'll check the code again

**Comment by comonier** [comment]
/authme debug mail
Test email sent to comonier@gmail.com with success

it back and work alone 
probaly some host issue ?

**Comment by ljacqu** [comment]
Hi @comonier, glad your problem could be resolved! Thanks for the update.
