### ISSUE TITLE
CMI spawn integration

### ISSUE THREAD

**Issue by arturek1666** [AuthMe/AuthMeReloaded#1423]
There is plugin called CMI with is like essentials however the problem is that it doesn't use CMI spawn and firstspawn of CMI becouse spawnPriority: 'authme,default,essentials,multiverse', Can you add to it CMI

**Comment by sgdc3** [comment]
CMI is closed source, can't you just invoke the cmi spawn command using the commands file?

**Comment by sgdc3** [comment]
@Zrips Could you provide some sort of public api?

**Comment by Zrips** [comment]
Working on this, will add source code to github and will post API plugin version in main page. As this is already been requested couple times. Check it in couple hours.
And to help out with code it self in finding out spawn and first spawn locations
`	CMI.getInstance().getConfigManager().getSpawnPoint();
	CMI.getInstance().getConfigManager().getFirstSpawnPoint();`

**Comment by ljacqu** [comment]
Hi @arturek1666 , this has been added by @sgdc3 quite a while ago. Could we ask you for some feedback?

**Comment by arturek1666** [comment]
Looks like it works fine :), Didn't notice any issues yet. So yea works well :). Good job :).
