### ISSUE TITLE
requires authorization on all servers

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeReloaded#1424]
In the Latest update requires authorization on all servers

**Comment by sgdc3** [comment]
Please explain your issue.

**Comment by DarkFort** [comment]
There are two servers: Survival, Auth. authorizing on the server Auth, teleporting to Survival, requires entering a login. With this is AuthMeBungee

**Comment by sgdc3** [comment]
@DarkFort I still can't understand your issue

**Comment by Dimatert9** [comment]
I think he mean that he use authmebungee and two servers with authme. After login on first and connect to second, session will not apply and player need again use login command.

**Comment by DarkFort** [comment]
😌

**Comment by sgdc3** [comment]
@DarkFort are you using authmebridge or authmebungee?

**Comment by DarkFort** [comment]
authmebungee

**Comment by sgdc3** [comment]
Could you post your authme and authmebungee config files?

**Comment by DarkFort** [comment]
[AuthMeBungee](https://hastebin.com/epedelipuw.pas)
[AuthMeReload](https://hastebin.com/ufudaboniy.bash)

**Comment by kacperduras** [comment]
```
autoLogin: false
```

**Comment by sgdc3** [comment]
> autoLogin: false

You have to enable this.

**Comment by DarkFort** [comment]
oh, yes, I have true, I accidentally threw off
