### ISSUE TITLE
add visible MailName for E-mail recovery system.

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1436]
If player send the e-mail recovery code, the mail name is mailaddress@gmail.com etc. Can you change this to official mail name ? Or add the e-mail name option to config.yml like a mailsubject option.

Example:
    # Mail Name
    mailName: 'Authme Reloaded'

**Comment by ljacqu** [comment]
Isn't that what this does?

```yml
    # Custom sender name, replacing the mailAccount name in the email
    mailSenderName: ''
```

**Comment by Pluginsel** [comment]
Oh... I did not see it, I tested it and it works.

**Comment by ljacqu** [comment]
Thanks for the feedback :)
