### ISSUE TITLE
mysql goes on comunication link failure with non localhost host

### ISSUE THREAD

**Issue by mattymatty97** [AuthMe/AuthMeReloaded#1439]
### What behaviour is observed:
What happened?
when connecting to a mysql database the plugin stops saying "Communications link failure"

### What behaviour is expected:
What did you expect?
plugin correctly connect to mysql database as other plugins do

### Steps/models to reproduce:
The actions that cause the issue
mysql

### Plugin list:
This can be found by running `/pl`
 ActionBarAPI-1.5.3
 AddLight-4.2.0
 AsyncWorldEdit-ActionBarAPI
 AsyncWorldEditInjector
 AsyncWorldEdit
 AuthMe-5.5.0-SNAPSHOT
 AuthMeBridge-1.6.2
 ConsoleSay
 EssentialsX-2.0.1
 EssentialsXChat-2.0.1
 FastLogin
 Holograms-2.5.0-SNAPSHOT
 Multiverse-Core-2.5
 NametagEdit
 PermissionsEx-1.23.4
 PluginManager-Reloaded-1.0.2
 ProtocolLib
 SkinsRestorer-v13.1.4-BETA
 Vault
 VoidGenerator-1.1.0
 WirelessRedstone
 worldedit-bukkit-6.1.7.3
 worldguard-legacy-6.2.2-SNAPSHOT-dist

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
spigot server networked by bungeecord but authme is server side

### AuthMe build number:
This can be found by running `/authme version`
AuthMe-5.5.0-SNAPSHOT

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)

https://pastebin.com/CSfyaP2Z

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/AL3E5W9v

**Comment by sgdc3** [comment]
Is the mysql server on the same machine?

**Comment by mattymatty97** [comment]
no its on a vps

**Comment by mattymatty97** [comment]
other plugins like pex, worldguard and skin restorer
correctly conntects and from my laptop i can connect whit the authme credentials to authme datatabase

**Comment by sgdc3** [comment]
MySql or MariaDB?

**Comment by mattymatty97** [comment]
actually mysql

**Comment by sgdc3** [comment]
> maxLifetime: 200000000000000

Wtf? Set it back to 1800...

**Comment by mattymatty97** [comment]
sorry it a bit old config i'v tried expanding timeout value but the error hannes also whit normal one

**Comment by sgdc3** [comment]
try with 300

**Comment by mattymatty97** [comment]
trying it now

**Comment by mattymatty97** [comment]
nope same error

**Comment by sgdc3** [comment]
Sounds very strange, set poolSize to 4

**Comment by mattymatty97** [comment]
nope error repeats again

**Comment by sgdc3** [comment]
uh, found it: disable mySQLUseSSL

**Comment by sgdc3** [comment]
@mattymatty97

**Comment by mattymatty97** [comment]
ssl is active on mysql and the connection is stable, one is on optic fibre and the other on a vps in germany.
one think is the verify-server-certificate that i've had to diable it for hide some warning in other plugins

**Comment by mattymatty97** [comment]
ps: sorry for my wrong spellings😌

**Comment by mattymatty97** [comment]
like this
uri: mysql://84.201.37.95/PermissionEx?verifyServerCertificate=false&useSSL=true

**Comment by mattymatty97** [comment]
bump, no one have found a solution?

**Comment by krusic22** [comment]
Can you connect using a normal mysql client?

**Comment by mattymatty97** [comment]
yes normal mysql clients and other plugins correctly connect and modify

**Comment by mattymatty97** [comment]
err 1th what qestion is unanswered?
and 2th is still not working sadly

**Comment by HexelDev** [comment]
Which is your SSL provider? 
Which version of Java are you using?
Can you list me all the plugin that are correctly connecting to your mysql server?
