### ISSUE TITLE
Error while shutting down server

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeReloaded#1442]
https://hastebin.com/jojexodesa.css

**Comment by sgdc3** [comment]
@ljacqu What do you think? when onDisable is called the bungee channel is already closed :(

**Comment by DarkFort** [comment]
The error was gone, thank you!

**Comment by ljacqu** [comment]
Sorry for the late reply @sgdc3 , looks good! I think this isn't the first time we need to check if the server has shut down, so next time we have such  a case we should check if we can somehow make it more generic. But for now this is OK IMHO.

OK to close this issue?

**Comment by sgdc3** [comment]
Ehm atm it doesn't sync the player data when the server is stopped, so if the player connects to another server he will spawn at the old location (if caching is enabled).

**Comment by sgdc3** [comment]
Is that fine?

**Comment by ljacqu** [comment]
Sorry for not replying to this yet again, lol. Essentially imho if there's no clear idea for this I'd say close, because it's kind of a corner case, no? I'm not saying it's great to have this but if there's no clear way to circumvent this, then I don't know.

**Comment by sgdc3** [comment]
Right, i agree with you
