### ISSUE TITLE
Question with bukkit coding.

### ISSUE THREAD

**Issue by Pluginsel** [AuthMe/AuthMeReloaded#1444]
this code isn't working with the AuthMe plugin before the login.
Do you have any idea what I need to do for this?

**Comment by sgdc3** [comment]
Does it happen with only your code + authme installed?

**Comment by Pluginsel** [comment]
@sgdc3 What? AuthMe is installed yes.

**Comment by sgdc3** [comment]
@Pluginsel No, i mean, could you try to test it on an environment with only authme and your plugin?

**Comment by Pluginsel** [comment]
@sgdc3 I already tested only with my plugin and AuthMe.

**Comment by Pluginsel** [comment]
@sgdc3 Spigot 1.12.2

**Comment by Pluginsel** [comment]
@sgdc3 I understand the error, because the arguments of commands such as login and register exist, and this error occurs because I can not add an argument to it. How can I add as an argument?

**Comment by ljacqu** [comment]
The switch is wrong. You want to check for `startsWith` but instead by using a check you perform an equality check

**Comment by Pluginsel** [comment]
exactly what do i have to do?

**Comment by sgdc3** [comment]
switch(message.substring(1).split(" ")[0])

**Comment by Pluginsel** [comment]
@sgdc3 Is worked, thanks. :)

**Comment by Pluginsel** [comment]
@sgdc3 @ljacqu I have another question with the bukkit coding:
https://hastebin.com/zukunedinu.swift
I want the players to automatically transfer to the other server after logging in, I did this with the code I threw and it succeeded. But with AuthMe I get an error, if the player is not logged in and only uses the / login command to execute the command, it still passes the main lobby. I want you to fail if the player does not log in / use the / lobby command automatically when using the / login command, or even if you do not use it.

**Comment by Dimatert9** [comment]
AuthMe allready has function to teleport player to another server after login/register. See 'hooks' section in config. 
 You can not check this in PlayerCmdPreproccesEvent.
