### ISSUE TITLE
AuthMe warn

### ISSUE THREAD

**Issue by SlipGoda** [AuthMe/AuthMeReloaded#1445]
### What behaviour is observed:
Warn

### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
PermissionsEx, Vault, ProtocolSupport, ProtocolLib, NoCheatPlus, AuthMe, AuthServer

### Environment description
Bungeecord network,MySql

### AuthMe build number:
AuthMe-5.4.0

### Error Log:
https://hastebin.com/zagehiqeya.md

https://hastebin.com/idiraculuk.md

### Configuration:

https://hastebin.com/ziwoviseyu.bash

**Comment by sgdc3** [comment]
> https://hastebin.com/idiraculuk.md

This is just an info message, it is shown as WARN but it is normal.

**Comment by sgdc3** [comment]
>https://hastebin.com/idiraculuk.md

That looks strange, @ljacqu any idea? ;)

**Comment by SlipGoda** [comment]
https://hastebin.com/zagehiqeya.md

**Comment by ljacqu** [comment]
> And this?

They're the same messages. They don't ring a bell for me :/ Can you continue to play or is the database closed, as the messages would suggest?

**Comment by SlipGoda** [comment]
Thanks for answering))

**Comment by ljacqu** [comment]
Unfortunately all hastebin links don't work for me anymore. Again my question: does the plugin actually work after, or is the connection to the database closed after those messages?
