### ISSUE TITLE
restriction hide chat : true does not work

### ISSUE THREAD

**Issue by comonier** [AuthMe/AuthMeReloaded#1451]
Version: AuthMeReloaded v5.4-SNAPSHOT (build: 1873)
Spigot: 1.8.8

The function does not work has 1 player logging staff account to stay reading the private chat of the staffs until the authentication time expires

**Comment by ljacqu** [comment]
Essentials' social spy?

**Comment by comonier** [comment]
staffs have no permission on social spy

**Comment by ljacqu** [comment]
Aha, so if "bobby" joins and I do "/msg bobby hey man" he will see this even before he logs in. Is this what you're trying to prevent?
