### ISSUE TITLE
How to disable feature email?

### ISSUE THREAD

**Issue by croderdai** [AuthMe/AuthMeReloaded#1453]
I want disable this!

**Comment by sgdc3** [comment]
It is disabled by default :/

**Comment by ljacqu** [comment]
More specifically, in [config.yml](https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md) you can set registration to `PASSWORD` so you don't have email registration. And if you want to disable the /email command you can do so by negating [its permissions](https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md).
