### ISSUE TITLE
Error otherAccountsCmd

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeReloaded#1454]
Error in console: https://hastebin.com/meyogexezi.md

In config:
otherAccountsCmdThreshold: 2
        otherAccountsCmd: 
        - 'coins take %playername% 20'
        - 'eco take %playername% 2000'

**Comment by ljacqu** [comment]
Thanks for the bug report. Fix is available in build n. 1900 and above at https://ci.xephi.fr/job/AuthMeReloaded/

Please close if this is solved on your end also or let us know what's still open.

**Comment by DarkFort** [comment]
Commands are not executed

**Comment by ljacqu** [comment]
Try with one command only. You posted a list in the issue description but the setting only takes one command.
