### ISSUE TITLE
Lag when doing /login or /register

### ISSUE THREAD

**Issue by LinsaFTW** [AuthMe/AuthMeReloaded#1459]
### What behaviour is observed:
Everytime i run /register or /login it takes like 5 - 10 seconds to succesfully login.

### What behaviour is expected:
A instant / semi instant login and register.

### Steps/models to reproduce:
Do /login or /register.

### Plugin list:
AAC, AACAdditionPro, AdvancedPortals, AuthMe, AutoRestart, ChestCommands, CustomJoinItems, DisableChat, Essentials, FastAsyncWorldEdit, HideAchievements, HidePlayers, HolographicDisplays, LiteBans, LuckPerms, MicroJump, ProtocolLib, ProtocolSupport, ProtocolSupportStuff, SpawnTP, VoidtoSpawn, WorldEdit, WorldGuard

### Environment description
Bungeecord network with MySql (Everything under the same machine / localhost)

### AuthMe build number:
1888

### Error Log:
N/A

### Configuration:
http://hastebin.com/usoneviyef.bash

I think authme reloaded needs more SQL optimization for small servers like mine. I think the traffic is too high for a non ssd network.

**Comment by krusic22** [comment]
Enable caching also this is probably a SQL server issue.

**Comment by LinsaFTW** [comment]
How do i enable that? @krusic22

**Comment by krusic22** [comment]
In the AuthMe config enable `caching: true`.
Also look at optimizations for your SQL server.

**Comment by ljacqu** [comment]
Hi @LinsaFTW , still relevant? If so we could provide you with a JAR that has additional debug statement and we could see where most of the time is lost on your server.
