### ISSUE TITLE
Bug report after executing a command

### ISSUE THREAD

**Issue by Fargus5** [AuthMe/AuthMeReloaded#1460]
14:20:56 CONSOLE: [INFO] Fargus5 issued server command: /authme recent
14:20:56 CONSOLE: [INFO] AuthMe - ERROR REPORT - NullPointerException
14:20:56 CONSOLE: LINE 45 in FILE RecentPlayersCommand.java (fr.xephi.authme.command.executable.authme.RecentPlayersCommand.formatPlayerMessage)
14:20:56 CONSOLE: LINE 35 in FILE RecentPlayersCommand.java (fr.xephi.authme.command.executable.authme.RecentPlayersCommand.executeCommand)
14:20:56 CONSOLE: LINE 122 in FILE CommandHandler.java (fr.xephi.authme.command.CommandHandler.executeCommand)
14:20:56 CONSOLE: LINE 81 in FILE CommandHandler.java (fr.xephi.authme.command.CommandHandler.handleCommandResult)
14:20:56 CONSOLE: LINE 68 in FILE CommandHandler.java (fr.xephi.authme.command.CommandHandler.processCommand)
14:20:56 CONSOLE: LINE 353 in FILE AuthMe.java (fr.xephi.authme.AuthMe.onCommand)
14:20:56 CONSOLE: LINE 44 in FILE PluginCommand.java (org.bukkit.command.PluginCommand.execute)
14:20:56 CONSOLE: LINE 141 in FILE SimpleCommandMap.java (org.bukkit.command.SimpleCommandMap.dispatch)
14:20:56 CONSOLE: LINE 89 in FILE CustomCommandMap.java (gyurix.commands.CustomCommandMap.dispatch)

This server is running CraftBukkit version git-Spigot-8cbfc85-202da97 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Authme Version 5.5.0

**Comment by ljacqu** [comment]
Hi @Fargus5 , thanks for the bug report. This should be fixed from build n. 1898 and above at https://ci.xephi.fr/job/AuthMeReloaded/

Could you tell us if it's fixed on your side?
