### ISSUE TITLE
Migrate to maxmind's Geo-IP 2

### ISSUE THREAD

**Issue by games647** [AuthMe/AuthMeReloaded#1471]
>The free versions of the GeoLite Legacy databases available at https://dev.maxmind.com/geoip/legacy/geolite/ will no longer be updated and free downloads of GeoLite Legacy using the geoipupdate program will no longer be available starting April 1, 2018.

Source: https://support.maxmind.com/geolite-legacy-discontinuation-notice/

The new project is located [here](https://github.com/maxmind/GeoIP2-java), but contains a lot of dependencies. The EssentialsX project noticed that [too](https://github.com/EssentialsX/Essentials/pull/1748).

**Comment by sgdc3** [comment]
We tried to migrate, i remember we had issues with it

**Comment by sgdc3** [comment]
@DNx5 worked on it

**Comment by sgdc3** [comment]
#539

**Comment by ljacqu** [comment]
A check with `InternetProtocolUtils#isLocalAddress` and wrapping the new call in a try-catch should be sufficient to handle the issues we encountered in #539. 

As for the dependency size, either we live with an additional ~1 MB in our JAR file, or we start talking about having individual modules, kind of like Essentials has (you can use Essentials alone or you can add in EssentialsSpawn, etc. for additional features)

**Comment by sgdc3** [comment]
Nah i mamaged to make it download the db correctly for another project, we don't need to include the db

**Comment by ljacqu** [comment]
No one said we need to include the db

**Comment by sgdc3** [comment]
the lib is 1mb? O_o sorry i misread your message xD

**Comment by k-jiang** [comment]
The libs are 1.2mb minimum even with shade-plugin. You can check the [Essentials' PR](https://github.com/EssentialsX/Essentials/pull/1748) for details.
The new Maxmind's Java API requires serval `jackson` libs, which are huge, to work properly. And they use tar.gz to pack their db so you will need `javatar` too.

You can ask my help if you meet any problems. I have used AuthMe for over 6 years and would happy to support it.

**Comment by sgdc3** [comment]
@k-jiang I already implemented the new api in a private project, i think it would be better to provide a separate module, in order reduce the final jar size, it would allow us to remove other huge libraries like the email one. @ljacqu

**Comment by Maxetto** [comment]
I've implemented it too with ease in one of my projects, but the real issue is the Jar size. For me it went from 52 KB to 1.8 MB, with shading.
