### ISSUE TITLE
AuthMe logging user password when using "/email setpassword"

### ISSUE THREAD

**Issue by k-jiang** [AuthMe/AuthMeReloaded#1474]
AuthMe logging user password when using `/email setpassword` in server console.

AFAIK AuthMe should NEVER log or display any kind of user password.
Test with Spigot/Paper 1.12.2 with AuthMeReloaded 5.4.0.

**Comment by ljacqu** [comment]
You are right. Thanks for bringing it to our attention

**Comment by ljacqu** [comment]
Hi @k-jiang , thanks again for the report. This is fixed form build n. 1918 and above at https://ci.codemc.org/job/AuthMeReloaded/ . Please comment if something is still open :)
