### ISSUE TITLE
Custom Join Message is not showing with colors

### ISSUE THREAD

**Issue by iskandarluqman** [AuthMe/AuthMeReloaded#1482]
### What behaviour is observed:
Custom Join Message is showing without colors

### What behaviour is expected:
Custom Join Message with colors

### Steps/models to reproduce:
In config: customJoinMessage: '&a[&2+&a]&r {PLAYERNAME}'

### Plugin list:
PlaceholderAPI, BetterChairs, ConsoleInGame, NametagEdit, Lockette, DeluxeTags, SuperTrails, CoreProtect, OpenInv, ClearLag, XrayInformer, WorldBorder, BuycraftX, Votifier, Multiverse-Core, ProtocolLib, LibsDisguises, NoCheatPlus, FastAsyncWorldEdit, BlocksHub, PermissionsEx, SignEditor, ConditionalCommands, GAListener, Vault, Rankup, HolographicDisplays, VoteParty, SkinsRestorer, AuctionHouse, PlayerVaults, MyCommand, WorldEdit, Essentials, BeastWithDraw, CrateReloaded, DiscordSRV, AdvancedAchievements, DeluxeMenus, mcMMO, SuperVanish, WorldGuard, EssentialsSpawn, TitleManager, Guilds, Jobs, SilkSpawners, TreeAssist, GriefPrevention, ChestShop, CombatTagPlus, AuthMe, EnchantsPlus, PlayerWarpGUI, GPRealEstate, RandomTeleport, ShopGUIPlus, ChatControl, LiteBans, TradeMe

### Environment description
Standalone server

### AuthMe build number:
Version: AuthMeReloaded v5.4.0 (build: 1877)[21:11:31 INFO]: Developers:[21:11:31 INFO]:  Alexandre Vanhecke // xephi59 (Original Author)[21:11:31 INFO]:  Lucas J. // ljacqu (Main Developer)[21:11:31 INFO]:  Gnat008 // gnat008 (Developer)[21:11:31 INFO]:  DNx5 // DNx5 (Developer)[21:11:31 INFO]:  games647 // games647 (Developer)[21:11:31 INFO]:  Tim Visee // timvisee (Developer)[21:11:31 INFO]:  Gabriele C. // sgdc3 (Project manager, Contributor)[21:11:31 INFO]: Website: http://dev.bukkit.org/bukkit-plugins/authme-reloaded/[21:11:31 INFO]: License: GNU GPL v3.0 (See LICENSE file)[21:11:31 INFO]: Copyright: Copyright (c) AuthMe-Team 2017. All rights reserved.

### Error Log:
None

### Configuration:
https://pastebin.com/yC5CLZNY

**Comment by Twonox** [comment]
Just as information (if you don't know), you can use essentials to change join and leave messages.

Other thing about one of yours plugins (unrelated with authme), I see that you use NoCheatPlus and it seems that you are able to buy premium plugins, so I suggest you to use a premium anticheat like Spartan.

**Comment by sgdc3** [comment]
@iskandarluqman Fixed

**Comment by ljacqu** [comment]
Hi @iskandarluqman could we ask you for some feedback on this issue so we know that it's fixed on your side?

**Comment by iskandarluqman** [comment]
Just tested it. Issue fixed. Thanks for the great job!
