### ISSUE TITLE
Bug Config Authme

### ISSUE THREAD

**Issue by FairyOne** [AuthMe/AuthMeReloaded#1484]
Hi, I have a problem I use authme on my server and when I activate ForceSurvivalMode and teleportUnAuthedToSpawn it does not work. Thank you for your reply
my server is under Thermos 1.7.10

**Comment by ljacqu** [comment]
> it does not work

Kindly include what you expect to happen and what is currently happening

**Comment by FairyOne** [comment]
For example if a player connects with the account of an administrator he has access to the creative tab and has that possition before the disconnection

**Comment by sgdc3** [comment]
@FairyOne 
Please provide us the required informations like your plugin version and the hastebin link to your config file.

**Comment by ljacqu** [comment]
More than 9 days without answer -> closing.
