### ISSUE TITLE
NullPointerException when getting groups from Vault

### ISSUE THREAD

**Issue by minecraft7net** [AuthMe/AuthMeReloaded#1488]
### What behaviour is observed:
What happened?
errors in logs

### What behaviour is expected:
What did you expect?
check and maybe fix

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`
[12:29:54] [Server thread/INFO]: [Vault] Loading Vault v1.6.1
[12:29:54] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.4.0-b1877

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
spigot 1.8.8 behind bungeecord

### AuthMe build number:
This can be found by running `/authme version`
[12:29:54] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.4.0-b1877

### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
https://pastebin.com/KMxaraHn

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
I think this has been reported in #1440
