### ISSUE TITLE
Why lagg

### ISSUE THREAD

**Issue by jboss23** [AuthMe/AuthMeReloaded#1489]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
everything is good. No console errors. My host told me it was probably authme so here i am
### What behaviour is observed:
What happened?
Some players are having login issues as they lagg and can't login
### What behaviour is expected:
What did you expect?
no lagg
### Steps/models to reproduce:
The actions that cause the issue
/login
### Plugin list:
This can be found by running `/pl`
about 50 of them. aint nobody got time for that
![image](https://user-images.githubusercontent.com/35966696/35576376-b868a94c-05d6-11e8-995c-73aa62ff4fa6.png)

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
standalone
### AuthMe build number:
This can be found by running `/authme version`
5.4.0
### Error Log:
Pastebin/Hastebin/Gist link of the error logo or stacktrace (if any)
none
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://hastebin.com/atonekerov.bash

**Comment by sgdc3** [comment]
Could you please post some timings report? ("/timings on" and after 5 minutes "/timings paste")

**Comment by jboss23** [comment]
https://timings.spigotmc.org/?url=nekolupuwe
sorry for the delay

**Comment by sgdc3** [comment]
Your server isn't lagging, authme isn't causing any lag as you can see in the timings report.
