### ISSUE TITLE
Performance and messaging issue

### ISSUE THREAD

**Issue by BoomEaro** [AuthMe/AuthMeReloaded#1491]
### What behaviour is observed:
1. If you have mail attached and you will, for example, type /unregister pass the server will hang

2. The message about the offer to install mail after registration is sent 2 times

3. If you attached the mail, and when you enter the game, try to enter the command /email show, it will be written that the mail has not been attached.
If you enter this after logging in, the mail will show, but if there is an enableEmailMasking: true setting, it will show the hidden one.

### What behaviour is expected:
1. Sending to the player's mail should be in another thread as with /email recovery

2. There should be one message about the recommendation of mail binding

3. A person does not need to know the full version of the mail when entering /email show at the authorization stage, there must be a hidden version. After successful authorization, when you enter this command, the mail should be fully visible.

### Steps/models to reproduce:
Action described along with the problem above (so it turned out more convenient)

### Plugin list:
[17:22:51] [Server thread/INFO]: Plugins (16): JoinEffect, AutoSaveWorld, WorldEdit, authserver, PermissionsEx, AutoMessage, tpLogin, Vault, CCLogger, BungeeTabListPlus, ProtocolLib, NoCheatPlus, BungeePortals, AuthMe, AuthMeBridge, HolographicDisplays

### Environment description
The server is on the BungeeCord network; authme uses sqlite database

### AuthMe build number:
Build 1968

### Error Log:
None

### Configuration:
https://pastebin.com/Fq42Gaq6

(sorry for my english)

**Comment by sgdc3** [comment]
@HexelDev isVerificationCodeRequired and codeExistOrGenerateNew are blocking calls, we should schedule them ;)

**Comment by HexelDev** [comment]
Oke, I'll work on it soon ;)

**Comment by sgdc3** [comment]
@BoomEaro is this still an issue?
