### ISSUE TITLE
Logged players can see players in vanish

### ISSUE THREAD

**Issue by iskandarluqman** [AuthMe/AuthMeReloaded#1494]
### What behaviour is observed:
If theres a player online on my server, they can see me in tab although Im in vanish. They can only see me if they have been on the server before me. If the player logout and login, They wont see my name anymore. They will see my name in tab (Still in vanish) if I do relog. I tried without AuthMe, SuperVanish works fine.

### What behaviour is expected:
I didnt expect my name to be shown in tablist although Im in vanish

### Steps/models to reproduce:
Be sure to have atleast a player online so they can see you in tab. Then after they login. you login. They can see your name in tab. If they leave dan rejoin, then they wont see my name. Unless I leave the server and rejoin. Then they will see my name again. (Never leaved vanish mode, SuperVanish)

### Plugin list:
PlaceholderAPI, BetterChairs, ConsoleInGame, NametagEdit, Lockette, ChatReaction, DeluxeTags, CoreProtect, OpenInv, ClearLag, XrayInformer, WorldBorder, Votifier, Multiverse-Core, ProtocolLib, LibsDisguises, NoCheatPlus, FastAsyncWorldEdit, BlocksHub, PermissionsEx, SignEditor, ConditionalCommands, Vault, Rankup, HolographicDisplays, SkinsRestorer, AuctionHouse, PlayerVaults, MyCommand, WorldEdit, Essentials, BeastWithDraw, CrateReloaded, AdvancedAchievements, DeluxeMenus, mcMMO, SuperVanish, WorldGuard, EssentialsSpawn, TitleManager, Guilds, Jobs, SilkSpawners, TreeAssist, GriefPrevention, ChestShop, CombatTagPlus, AuthMe, PlayerWarpGUI, GPRealEstate, RandomTeleport, ShopGUIPlus, ChatControl, LiteBans

### Environment description
Standalone server

### AuthMe build number:
AuthMeReloaded v5.5.0-SNAPSHOT (build: 1968)

### Error Log:
None

### Configuration:
https://pastebin.com/maudcm2r

**Comment by sgdc3** [comment]
@games647 maybe related to the tablist stuff? I remember you worked on it the last your.

**Comment by iskandarluqman** [comment]
@sgdc3 Wrong reply Im assuming.

**Comment by games647** [comment]
Well, ...; We removed [tablist hiding](https://github.com/AuthMe/AuthMeReloaded/commit/bc9717d6501fbc639d97e4ad636c47fd3963eacb), because it produced too many issues.

**Comment by sgdc3** [comment]
Oh right, i forgot about that xD

**Comment by sgdc3** [comment]
At this point we don't have any feature tgat may cause this issue, what do you think @ljacqu ?

**Comment by iskandarluqman** [comment]
Bump. Can you guys solve this issue?

**Comment by ljacqu** [comment]
@sgdc3 Nothing comes to mind right now

@iskandarluqman Please be patient

**Comment by games647** [comment]
@iskandarluqman Does the issue still exist after uninstalling SkinsRestorer?

Maybe relevant ticket: https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro/issues/218

**Comment by iskandarluqman** [comment]
Since my server is cracked, I do need SkinsRestorer. I tried without SkinsRestorer, players that joined earlier than me cant see me. Which what I expect. So tried without AuthMe but with SkinsRestorer,  players that joined earlier than me can see me? Didnt get that result when I tried before. I will close this issue here. I can say this problem got something to do with SkinsRestorer. Thanks everyone.

**Comment by ljacqu** [comment]
Thanks for the update, and thanks to @games647 for the hint! :)

**Comment by Remigio07** [comment]
Bump. In newer versions the issue is still present.
Please fix!

**Comment by ljacqu** [comment]
Given the age of this issue, please open a new one.
