### ISSUE TITLE
I need help configuring AuthMe, my server always stop after turning it on

### ISSUE THREAD

**Issue by ProblemsSender** [AuthMe/AuthMeReloaded#1495]
### What behaviour is observed:
What happened? - Its just stops after turning it on

### What behaviour is expected:
What did you expect? - I'm not sure

### Steps/models to reproduce:
The actions that cause the issue - I'm not sure

### Environment description
Standalone server, SQLite

### AuthMe build number:
This can be found by running `/authme version` - This happened in all version, I tried 5.4.0 and older-even with the server that's first run this type of plugin

### Error Log:
https://hastebin.com/ricazoqahi.md
I'M SURE THAT THIS GLITCH HAPPENED ONLY WITH THIS PLUGIN, I WAS RUN IT STAND ALONE AND THE SAME GLITCH APPEAR

### Configuration:
https://hastebin.com/ikeyecuvek.bash
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data) - This config.yml is from the "test" server

**Comment by ljacqu** [comment]
Please post your authme.log, there will be a more detailed error in there. From a quick glance might be an old Essentials version but it would be good for us to investigate this

**Comment by ProblemsSender** [comment]
Here's my aume.log at the link below:
https://hastebin.com/qunideyuha.sql

**Comment by ProblemsSender** [comment]
Here it is:
https://hastebin.com/tazorinoyi.makefile

**Comment by Dimatert9** [comment]
line 40. starts with ' ends wits "

**Comment by ProblemsSender** [comment]
Oh my Thank you So much sir!!!!!!!!! You just saved my day, thank you thank you!!!!!!!! OMG that piece of character just made me headache xD
