### ISSUE TITLE
Permission 'authme.bypasspurge' does not work with LuckPerms

### ISSUE THREAD

**Issue by Hdadaw** [AuthMe/AuthMeReloaded#1498]
### What behaviour is observed:
Permission 'authme.bypasspurge' does not work with LuckPerms.
And setting 'removePermissions' causes 'java.util.concurrent.TimeoutException'.
LuckPerms version: v4.0.117
LuckPerms linked to MySql.

### What behaviour is expected:
That certain groups of players will not be removed from the database.

### Steps/models to reproduce:
https://ci.lucko.me/job/LuckPerms/516/

### Plugin list:
LuckPerms, WorldEdit, ViaVersion, Vault, ProtocolLib, WorldGuard, AuthMe, LiteBans

### Environment description
Bungeecord network, MySql, LuckPerms

### AuthMe build number:
AuthMeReloaded v5.5.0-SNAPSHOT b1969

### Error Log:
https://pastebin.com/vSqPxKDY

### Configuration:
https://pastebin.com/B1iZ8rjD

**Comment by sgdc3** [comment]
The player permission data needs to be loaded before checking.

**Comment by Hdadaw** [comment]
![image](https://user-images.githubusercontent.com/32250813/36147329-cb4c05dc-10f2-11e8-8b3b-5757e03218f9.png)
still removing all players

**Comment by sgdc3** [comment]
could you post your luckperms config file?

**Comment by Hdadaw** [comment]
https://pastebin.com/WbTq7kYT

**Comment by Hdadaw** [comment]
Any progress?

**Comment by sgdc3** [comment]
@Hdadaw does it work with the latest dev build?

**Comment by Hdadaw** [comment]
@sgdc3 nope, still deleting all accounts
https://pastebin.com/qQe9yuvr

**Comment by sgdc3** [comment]
Try with this setup:
https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/2039/
https://ci.lucko.me/view/LuckPerms/job/LuckPerms/594/

**Comment by Hdadaw** [comment]
@sgdc3 https://pastebin.com/DXKhnAuc

**Comment by Hdadaw** [comment]
@sgdc3 so?

**Comment by sgdc3** [comment]
We need to rewrite the permission system to handle that correctly.

**Comment by sgdc3** [comment]
We are working on this, but will take a while.

**Comment by Hdadaw** [comment]
so?

**Comment by sgdc3** [comment]
Duplicate of #1544
