### ISSUE TITLE
IPB4 special chars in password (different hash)

### ISSUE THREAD

**Issue by xCraftRayX** [AuthMe/AuthMeReloaded#1501]
Hi, I used this code for ipb4: https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/security/crypts/Ipb4.java and all was working good but when I using this password "zaq1@WSX" I successfully registered account. But when I try login with that password: "zaq1@WSX", I get other hash...

With other password with that char "@" I haven't problem.

**Comment by ljacqu** [comment]
>  But when I try login with that password: "zaq1@WSX", I get other hash...

When you try to log in into Minecraft or on the forum? I just tested in Minecraft and it worked fine for me.

**Comment by xCraftRayX** [comment]
Hmm, I am try to register on the forum and login with the MC or forum and all was ok... I do not know what I'm doing wrong.

I register player from plugin like that:
`								
								if(Config.ipsIsEnabled)
								{
									Ipb4 ipb4 = new Ipb4();
									String salt = ipb4.generateSalt();
									hp = new HashedPassword(ipb4.computeHash(ap.getPassword(), salt, ap.getUsername()));
									String hashPass = hp.getHash();
								}`

**Comment by ljacqu** [comment]
So everything is OK?

**Comment by ljacqu** [comment]
In your code you're generating a HashedPassword but only taking the hash. If you look at that class you see that the HashedPassword class contains a hash as well as a salt. That salt is important. You can't just discard it. It needs to be saved into the database as well.

**Comment by xCraftRayX** [comment]
Yes, then I save it in the database.
`MySQL.register(ap.getUsername(), hp.getHash(), hp.getSalt(), ap.getEmail(), ap.getIp(), ap.getLastLogin(), ap.getJoined(), ap.getSessionExpire(), ap.isOnline());`

ap is my AuthPlayer object
And in login function i can register but I don't knwo why only "zaq1@WSX" password can't work.. but zaq1WSX@ working... I don't know where is problem but it seems to me that there is a problem somewhere during encryption.

**Comment by ljacqu** [comment]
I wrote a unit test for this:
```java
    @Test
    public void shouldHashCorrectly() {
        for (int i = 0; i < 10; ++i) {
            // given
            String password = "zaq1@WSX";
            Ipb4 hash = new Ipb4();
            HashedPassword hashedPassword = hash.computeHash(password, null);

            // when / then
            assertThat(hash.comparePassword(password, hashedPassword, null), equalTo(true));
        }
    }
```

which passes just fine. If there's a way to reproduce this with IPB4 and/or AuthMe, please share the steps to create a situation where an invalid login is shown. Otherwise I'm voting to close again as it seems to be an integration issue in your code.

**Comment by ljacqu** [comment]
We perform some additional stuff for IPB4 to make sure everything works. See https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/datasource/mysqlextensions/Ipb4Extension.java

So again, can you somehow provide a unit test where a certain password fails, or anyhow else have a way for us to reproduce this? Especially just by using AuthMe's commands and IPB4.

**Comment by xCraftRayX** [comment]
Can I send to you all my plugin on the private message / email and next you will try find problem?

**Comment by ljacqu** [comment]
I'm already short on time to make some progress on AuthMe, so pragrammatically I have to decline if the problem lies outside of AuthMe. I'm not trying to be a dick I'm just pressed for time to do some actual development work

**Comment by xCraftRayX** [comment]
okay I understand you, maybe someone will have a similar problem and sometime give a solution.

**Comment by ljacqu** [comment]
Thanks a lot for your understanding! I hope you'll be able to resolve your problem. :)

**Comment by xCraftRayX** [comment]
I think it is maybe a my problem :P
In Ipb4.class:
... @Recommendation(Usage.DOES_NOT_WORK) ...
So, algorithm don't work properly, because is damaged.

**Comment by xCraftRayX** [comment]
And this test what you wrote always return TRUE.
