### ISSUE TITLE
Add "CRYPT_BLOWFISH" password hash algoritm

### ISSUE THREAD

**Issue by iBars** [AuthMe/AuthMeReloaded#1505]
One of the most popular CMS (especially in Russia) "DataLife Engine" using new very strong password hash algorithm: CRYPT_BLOWFISH. Add it please in AuthMe

**Comment by games647** [comment]
@iBars Could you try BCrypt2y. This is a blowfish variant.

**Comment by iBars** [comment]
Yes, it works! Thanks so much for answer
