### ISSUE TITLE
Errors on MySQL when User Connect/Disconnects

### ISSUE THREAD

**Issue by zAnonimo** [AuthMe/AuthMeReloaded#1508]
### What behaviour is observed:
Sometimes when someone connects or disconnects some errors appears in my console. I can't figure why yet, so that's why I ask you guys.

### What behaviour is expected:
No errors

### Steps/models to reproduce:
User connect/disconnect

### Plugin list:
`[17:13:23 INFO]: Plugins (60): CommandsXL, DiscordMC, MDCQuestioner, Arconix, TitleAPI, AutoRestart, RewardVoting, EpicWorldGenerator, Essentials, PacketListenerApi, AutoMessage, ChatControl, MapManager, Votifier, Multiverse-Core, GuiRedeemMCMMO, FastAsyncWorldEdit, VoidGenerator, EssentialsChat, PermissionsEx, RelayItToDiscord, elyby-skinsystem, mcMMO, Vault, ColoredAnvils, MassiveCore, FastAsyncVoxelSniper, AnimatedFrames, SignColors, VoxelSniper, EssentialsGeoIP, ViaVersion, TreeFeller, ViaBackwards, EssentialsSpawn, WorldEdit, ProtocolLib, LibsDisguises, Citizens, KitPreview, CrazyAuctions, FastLogin, AuthMe, HolographicDisplays, HideAndCustomPlugins, WorldGuard, Factions, MythicMobs, ChatItem, Shop, CompatNoCheatPlus, Jobs, mcMMOAction, SilkSpawners, NoCheatPlus, WildTP, FactionChat, DungeonsXL, MythicArtifacts, Quests`

### Environment description
MySQL (MariaDB actually), Spigot.

### AuthMe build number:
`Version: AuthMeReloaded v5.4.0 (build: 1877)`

### Error Log:
https://pastebin.com/cy8dhtvd

### Configuration:
https://pastebin.com/2U0kxrGA

**Comment by sgdc3** [comment]
Try to set poolSize to 8

**Comment by sgdc3** [comment]
And update to the latest build: https://ci.codemc.org/job/AuthMeReloaded/
