### ISSUE TITLE
[1.7.10] AuthMe and BuildCraft - quarry cannot mine

### ISSUE THREAD

**Issue by ciekals11** [AuthMe/AuthMeReloaded#1510]
Server: Thermos-1.7.10-1614-57
Mod buildcraft - latest for 1.7.10
plugin: AuthMe - latest for 1.7.10 (5.2 leagacy bc 5.3.2 for all versions isn't working)

Quarry cannot dig, there is only animation of digging but nothing else.

there is my authme config:
UnrestrictedName:
            - '[BuildCraft]'
            - [BuildCraft]
            - 'BuildCraft'
            - BuildCraft
            - '[Mekanism]'
            - '77456a1f-b9f9-3f84-8863-ddef5b8e2209'
when i disable authme it works perfect
any ideas?

**Comment by sgdc3** [comment]
I think buildcraft changed the fake player name, do you know it?

**Comment by ciekals11** [comment]
i have no idea why but somehow after a couple of restart i made it finally work
`UnrestrictedName: 
          - '[Mekanism]'
          - '[BuildCraft]'`

**Comment by sgdc3** [comment]
Thank you for the info
