### ISSUE TITLE
Updateing Authme 3.4 to 5.4.0 -> auths.db vs. authme.db

### ISSUE THREAD

**Issue by o0Julia0o** [AuthMe/AuthMeReloaded#1511]
hi, I updated a old bukkit-server 1.72 Authme 3.4 to spigot 1.12.2 and the new authmeReloaded 5.4.0 getting this:

```
00:46:53 [WARNING] [AuthMe] Aborting initialization of AuthMe: [YAMLException]: java.nio.charset.MalformedInputException: Input length = 1
00:46:53 [WARNING] [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
```

If putting the new 5.4.0 jar in the old bukkit-folder overwriting the old one i get: 
`[WARNING] [AuthMe] Aborting initialization of AuthMe: [ReaderException]: special characters are not allowed
`
I don´t want to loose all the logins. What can i do?

If i let the new AuthMeReloadet create the folder and files and copy the old db-file(auths.db) into the new folder and rename it to authme.db, i get this error:
`
00:51:57 [WARNING] [AuthMe] Error during SQLite initialization: [SQLiteException]: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)`

Can you help me?

**Comment by sgdc3** [comment]
any idea @ljacqu ?

**Comment by o0Julia0o** [comment]
hm no one knows how to convert the old db into the new db?

**Comment by ljacqu** [comment]
For the first two errors you mention: 

> 00:46:53 [WARNING] [AuthMe] Aborting initialization of AuthMe: [YAMLException]: java.nio.charset.MalformedInputException: Input length = 1

> [WARNING] [AuthMe] Aborting initialization of AuthMe: [ReaderException]: special characters are not allowed

Could you please look up these errors in your authme.log? There should be a larger block of text with this error and it will show us which YML file it relates to.

When does which error exactly happen? 

---

For the database one:

> 00:51:57 [WARNING] [AuthMe] Error during SQLite initialization: [SQLiteException]: [SQLITE_NOTADB] File opened that is not a database file (file is not a database)

You speak about an auths.db. Were you using `backend: FILE` in your config.yml for 3.4? To me this error looks like the new config.yml has `backend: SQLITE` in it and you just changed the database name to `auths.db`. Or something went wrong in the migration and it kept the old database name but didn't take over the FILE value for the DataSource.backend setting.

Either way, please set `backend: FILE` in your config.yml and try to start the server again. On startup it should automatically migrate your auths.db to a SQLite file. If that fails, please post the full error from your authme.log and we'll see from there.

**Comment by o0Julia0o** [comment]
o.k., now it worked:
[code]
01:19:16 [INFO] [AuthMe] Enabling AuthMe v5.4.0-b1877
01:19:16 [WARNING] [AuthMe] FlatFile backend has been detected and is now deprecated; it will be changed to SQLite... Connection will be impossible until conversion is done!
01:19:17 [INFO] [AuthMe] Created column 'regdate' and set the current timestamp, 1520122757000, to all 0 rows
01:19:17 [INFO] [AuthMe] SQLite Setup finished
01:19:24 [INFO] [AuthMe] Database successfully converted from FILE to SQLITE
01:19:24 [INFO] [AuthMe] Hooked into LuckPerms!
[/code]
But the login failes. Aber converting the backend has automatically set to SQLITE. But Logins don´t work. The passwords are told are wrong. But the aren´t.

Can i open the db an show what the passwords are? The playernames i can see in the converted authme.db(converted from the auths.db). They seem to be correct. But the passwords not.

**Comment by ljacqu** [comment]
Great, thanks for the feedback!

> 01:19:17 [INFO] [AuthMe] Created column 'regdate' and set the current timestamp, 1520122757000, to all 0 rows

Just noticed that SQLite always says "0 rows" there. But I tested locally and the migration worked for me, so this is an issue with the SQLite API or our usage thereof. So nothing to worry about (I was initially worried that nothing was migrated for you).

I use [SqliteBrowser](http://sqlitebrowser.org/) for viewing SQLite databases. Note that you can't view the passwords directly but you can view their hashes. So the first question is do the usernames show up that we expect? 

If so, then what password hash do you use (`passwordHash` in your config.yml)? Assuming it's SHA256 I can give you some hashes we know. Now, if you had password as PLAINTEXT in 3.4, note that we've also introduced a mandatory migration from PLAINTEXT to SHA256 in 5.2. Maybe the combination of flat file to SQLite and plaintext to SHA256 has some issues.

**Comment by o0Julia0o** [comment]
thank you ljacqu! The usernames are as expected - but all in lower case. The passwords are all 140 characters long. But not the normal passwords - so theay are hashed.

The old 3.4-config says: passwordHash: XAUTH
The new 5.4-config says: passwordHash: 'SHA256'

So i changed it in 5,4-config tu passwordHash: 'XAUTH'
and now it´s all working!

Thank you a lot! A lot!

**Comment by sgdc3** [comment]
@ljacqu shouldn't it be automatically imported from the old config? :/

**Comment by ljacqu** [comment]
Thanks for the update, @o0Julia0o.

@sgdc3 is right, we'd have expected these configurations to be taken over. This might depend on how you upgraded - maybe you ran it alone first and then didn't copy over the old config, or maybe we have an issue with our migration (though now we have at least two quite stable properties that have lost their value). Could you maybe shed some light on this? We should look into it if you've lost all your configurations from 3.4 to 5.5.

**Comment by sgdc3** [comment]
@ljacqu We should open a follow-up issue

**Comment by ljacqu** [comment]
I kind of suspect that this is a case of not having taken over the config.yml so I'd suggest to wait until we get feedback from @o0Julia0o.

**Comment by o0Julia0o** [comment]
Hi, what do you need from me? For me it´s working now.

**Comment by ljacqu** [comment]
The last question we have for you is if you left your old config.yml from 3.4 in the same folder when you updated to 5.4? Because you shouldn‘t have lost those settings. 
If you moved the old files into another folder first then the case is clear but otherwise we ought to open a follow-up bug

**Comment by o0Julia0o** [comment]
I have saved the backup of my old authme-jar and authme-folder. So i can easy test all you need. I deleted the new authme-folder(renemad it ^^). And copied the 3.4-folder in the pluginsfolder. Now starting spigot 1.12.2(with the old 3.4-folder i used bukkit for mc 1.7.2). And i get this:
[code]
10:11:38 [INFO] [AuthMe] Enabling AuthMe v5.4.0-b1877
10:11:38 [WARNING] [AuthMe] Aborting initialization of AuthMe: [YAMLException]: java.nio.charset.MalformedInputException: Input length = 1
10:11:38 [WARNING] [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
10:11:38 [INFO] [AuthMe] Waiting for 0 tasks to finish
10:11:38 [INFO] [AuthMe] AuthMe 5.4.0-b1877 disabled!
10:11:38 [INFO] Server permissions file permissions.yml is empty, ignoring it
10:11:38 [INFO] Done (3.727s)! For help, type "help" or "?"
10:11:38 [INFO] Stopping server
[/code]

**Comment by ljacqu** [comment]
OK, this is something we should look into. Since this is a different issue I'll close this one (as suggested by @sgdc3; it keeps our tracking clean) and you're very welcome to create a new issue if you want us to pursue this (we'd be interested in it since obviously we have some sort of bug somewhere).

Should you decide to open a new issue, please include the error as given in the authme.log: it will have a more detailed error and will allow us to know which YML file is causing the issue (since we have at least a config.yml and a messages_xx.yml in 3.4).

Thanks ;)

**Comment by o0Julia0o** [comment]
thank you. For me, all is good now. I have to thank. I created a new issue over here: https://github.com/AuthMe/AuthMeReloaded/issues/1519

But i am sorry - no logfile is created.
