### ISSUE TITLE
[1.12.2] Probably authme crashes the server

### ISSUE THREAD

**Issue by LosTigeros** [AuthMe/AuthMeReloaded#1514]
### What behaviour is observed:
After some time the server gets timed out and it crashes.

### Steps/models to reproduce:
Im just using latest Spigot server for few hours.

### Plugin list:
Plugins (34): AsyncWorldEditInjector, Bookshelves, dewdd_empty, SaturationPreview, PacketListenerApi, PlugMan, MapManager, ProtocolLib, Multiverse-Core, SkinsRestorer, MVdWPlaceholderAPI, AsyncWorldEdit, PermissionsEx, FeatherBoard, TAB, PingMOTD, Vault, WorldEdit, Essentials, AnimatedFrames, Mine, HolographicDisplays, WorldGuard, Citizens, IslandWorld, DiscordSRV, SBFB, EssentialsChat, Shop, IslandWorldChallenges, EssentialsSpawn, HolographicScoreboard, ChestShop, AuthMe

### Environment description
- Bungee (git:BungeeCord-Bootstrap:1.12-SNAPSHOT:74e077e:1301)
- Lobby (git-Spigot-4bd94dc-fb414fe)
- Main server (git-Spigot-4bd94dc-fb414fe)
- MySQL (MySQL Community Server 5.7.20)

### AuthMe build number:
1877

### Error Log:
https://pastebin.com/Xy5rPu7u

### Configuration:
https://pastebin.com/auLxBsEm

**Comment by Maxetto** [comment]
I think your machine gets overloaded and therefore crashes.

AuthMe and DiscordSRV reports thread starvation on the connection to the database, while the main thread is doind a world save.

**Comment by LosTigeros** [comment]
Load average: 1.48 1.60 1.53

**Comment by sgdc3** [comment]
@LosTigeros Is this still happening with latest dev builds?

**Comment by LosTigeros** [comment]
It didn't crashed since 4 days so I think that it's solved.
