### ISSUE TITLE
Suggestion: Username whitelist for country ban bypassing

### ISSUE THREAD

**Issue by DeusNinja** [AuthMe/AuthMeReloaded#1516]
Rather than using just the "enable protection registered: t/f" option, I believe it would be more practical to retail positive players after issuing country bans by having the message the players receive during their connection denial have an email and a message for example mine is 
'Due to increased ban evasion the country you are connecting from is being refused'
'If you believe you are seeing this message in error, please email support@domainnamehere.com'

That way players can email me their usernames, and if everything checks out with our log files and their name they can be added to the whitelist to bypass the country ban. Rather than players from the country not being able to connect if they are not registered.

**Comment by ljacqu** [comment]
Would a permission node also be OK?

**Comment by DeusNinja** [comment]
If there is a way to do that, I do believe it would suffice.

**Comment by Maxetto** [comment]
Since the most common use of this feature is to block bots, would be good if we reuse the permission "authme.bypassantibot" for country login too?

**Comment by DeusNinja** [comment]
if there is a way of cloning that permission node for country ban bypass would be great. That way the permission node can be used specifically for this desired goal a bit more clearly for the end user?

**Comment by Maxetto** [comment]
Nevermind, turns out there's already a permission node.

Could you try to give "authme.bypasscountrycheck" to players joining from a not-allowed country?

**Comment by DeusNinja** [comment]
I'll give that a try. However this would not protect against players who use the online players list as a reference point of usernames to try and use for connection to bypass the country ban.
 
I'll post back after I try out that node. thanks for the inputs :)

**Comment by Maxetto** [comment]
You have to give this permission to users, not groups.

Example: For PermissionsEx `/pex user Maxetto add authme.bypasscountrycheck`

**Comment by DeusNinja** [comment]
Tested it by adding perm to players specifically. Would this not work for groups? For example if I were to add it to my staff groups?

**Comment by Maxetto** [comment]
It works too but it's more insecure and you said you need to use it on people that can't connect from a country.
