### ISSUE TITLE
Update from 3.4 to 5.4

### ISSUE THREAD

**Issue by o0Julia0o** [AuthMe/AuthMeReloaded#1519]
I have saved the backup of my old authme-jar and authme-folder. So i can easy test all you need. I deleted the new authme-folder(renemad it ^^). And copied the 3.4-folder in the pluginsfolder(where only authme 5.4 is(all other plugins, i have removed for the test). Now starting spigot 1.12.2(with the old 3.4-folder i used bukkit for mc 1.7.2). And i get this:
```
10:11:38 [INFO] [AuthMe] Enabling AuthMe v5.4.0-b1877
10:11:38 [WARNING] [AuthMe] Aborting initialization of AuthMe: [YAMLException]: java.nio.charset.MalformedInputException: Input length = 1
10:11:38 [WARNING] [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
10:11:38 [INFO] [AuthMe] Waiting for 0 tasks to finish
10:11:38 [INFO] [AuthMe] AuthMe 5.4.0-b1877 disabled!
10:11:38 [INFO] Server permissions file permissions.yml is empty, ignoring it
10:11:38 [INFO] Done (3.727s)! For help, type "help" or "?"
10:11:38 [INFO] Stopping server
```

No logfile has been created.

**Comment by ljacqu** [comment]
Thank you for creating the issue. Could you post your config.yml (remembering to remove sensitive data such as database and email credentials) please? Probably this is the file that cannot be loaded, given that it seems to happen at the very beginning of the initialization of AuthMe.

**Comment by o0Julia0o** [comment]
oh uups. That worked!!! Had been ANSI before. Do you need the config.yml anyway?

**Comment by sgdc3** [comment]
@o0Julia0o i don't think so, thank you anyway ;)
