### ISSUE TITLE
Website problem

### ISSUE THREAD

**Issue by haer0248** [AuthMe/AuthMeReloaded#1522]
How do I display "registration date" on the web page?
I can get time but I don't know how to convert. please help me ;(

**Comment by ljacqu** [comment]
It‘s a unix timestamp. Convert it with whatever functions your language offers

**Comment by haer0248** [comment]
But I use "echo date("Y年m月d日 H時i分s秒", $row[10]);"
regtime is today, but show "1980年04月22日 17時51分38秒"

**Comment by haer0248** [comment]
oh is my problem, sorry!
