### ISSUE TITLE
No build tests Argon2 anymore

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1541]
Since the [removal of TravisCI](https://github.com/AuthMe/AuthMeReloaded/commit/e0e926354615dca377bb714e270c819612af4b86) we no longer have a build that tests with Argon2 libraries. The Argon2 stuff is skipped in the CodeMC Jenkins build and also on CircleCI.

**Comment by Eyremba** [comment]
Also, we could switch to the full standalone Java version of Argon2.
I posted the url in the other issue long time ago.

**Comment by sgdc3** [comment]
@ljacqu i installed argon2 in the jenkins instance the other day :/

**Comment by sgdc3** [comment]
Fixed in https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/2040/

**Comment by sgdc3** [comment]
nope, still happening even if i installed libargon2-0-dev :/

**Comment by games647** [comment]
@sgdc3 Java only searches for libraries without a version suffix. You could workaround this by creating a symlink to `/usr/lib/x86_64-linux-gnu/libargon2.so`

**Comment by ljacqu** [comment]
Hi @sgdc3:

> 13:01:40 [INFO] Running fr.xephi.authme.security.crypts.Argon2Test
13:01:43 [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.641 s - in fr.xephi.authme.security.crypts.Argon2Test

Am I right to assume that the Jenkins build now runs the Argon2Test successfully? Can we close this?

**Comment by sgdc3** [comment]
Sure! ;)
