### ISSUE TITLE
Fastlogin /register delay request

### ISSUE THREAD

**Issue by LoXR** [AuthMe/AuthMeReloaded#1552]
### What behaviour is observed:
When Premium users join, they are auto-registered/logged in by the addon FastLogin. But the problem is when its done all that, it has the /register (password) still after all of thats done from FastLogin.

### What behaviour is expected:
When FastLogin autoregisters players, it'll autolog in, and not needing to show the /register afterwards.

### Steps/models to reproduce:
Premium accounts being auto-registered/logged in by FastLogin.

### Plugin list:
FastLogin, AuthMe, AuthMeBridge

### Environment description
Bungee Server

### AuthMe build number:
AuthMe version 5.4.0-b1877

**Comment by sgdc3** [comment]
@games647 isn't this the current behavioirm

**Comment by ljacqu** [comment]
Hi @games647, I agree with @sgdc3 that the expected behavior is what should be happening now anyway, right?

**Comment by games647** [comment]
@sgdc3 @ljacqu  I think it's because of an bug in FastLogin. I'm waiting on @LoXR for a response on SpigotMC.

**Comment by LoXR** [comment]
I havent got around to updating to the recent jenkins. But will let you know by tomorrow if its all good :)
