### ISSUE TITLE
[Suggestion] /email setpassword <pass> just once with  setting passwordChangeTimeout: 0

### ISSUE THREAD

**Issue by YellowZaki** [AuthMe/AuthMeReloaded#1557]
When a user introduces the /email setpassword after the code, they can use /email setpassword everytime they want until `passwordChangeTimeout` finishes.

I suggest that setting `passwordChangeTimeout: 0` let the player use /email setpassword just once.

**Comment by ljacqu** [comment]
/email setpassword indeed should only work once successfully. Thanks for pointing this out.

**Comment by ljacqu** [comment]
This is available from build n. 2075 onward. https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
New behavior is that once the player uses /email setpassword successfully, he can no longer use it. OK to close this issue?
