### ISSUE TITLE
ip connected

### ISSUE THREAD

**Issue by MikhailY** [AuthMe/AuthMeReloaded#1562]
http://prntscr.com/j844e7

I have 1 ip address but I log in

### Environment description
Bungeecord network, MySql

### AuthMe build number:
2058

**Comment by sgdc3** [comment]
have you enabled bungeecord in the spigot config?

**Comment by MikhailY** [comment]
But now for some reason I can't log in with 2 account

**Comment by MikhailY** [comment]
Again I was able to log in with 2 accounts(

**Comment by ljacqu** [comment]
If the IP is localhost we don't perform the check. So if you're testing in a local server vs. one that gets hosted elsewhere you might notice discrepancies.

**Comment by MikhailY** [comment]
My server has localhost, but it is connected to bungeecord

**Comment by ljacqu** [comment]
We can provide you with a custom JAR that will log more if you want. But essentially if your players' IP address is 127.0.0.1 then these checks will be skipped.

**Comment by sgdc3** [comment]
@MikhailY do you have ip_foward enabled in your bungee config?

**Comment by MikhailY** [comment]
@sgdc3 Yes

**Comment by sgdc3** [comment]
@ljacqu maybe we check the ip before spigot replaces the ip :/
