### ISSUE TITLE
2FA: Add setting for server name displayed in authenticator

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1574]
For the new two factor feature (#1141) it would be great to have a setting that can define the server name. Currently the IP is taken and this may not be satisfactory for all use cases.

## To do
- Add a new setting for server URL/name to config.yml 
- Use the setting in TotpAuthenticator#generateTotpKey
   - Should probably still fall back to `bukkitService.getIp()` if the setting is empty

**Comment by AmazedMender16** [comment]
Any status update on the Server Name/URL?

**Comment by ljacqu** [comment]
I'll add it in the days to come. It's a small thing and you are right. Thanks for bumping this :+1:

**Comment by AmazedMender16** [comment]
Lovely man, thanks!

**Comment by ljacqu** [comment]
Hi @AmazedMender16 , now the server name is taken that is set in AuthMe's config.yml under settings > "serverName". This new behavior is available as of build nr. 2286 https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
I'm happy to receive some feedback whether we can close this or if something can still be improved. :)

**Comment by AmazedMender16** [comment]
@ljacqu 

Is it possible to add the display name to it?

**Comment by ljacqu** [comment]
@AmazedMender16 I'm using Google authenticator and most of the sites I use are like this:

> **Dropbox**
 123 456
 my-email@example.tld

Including hotmail, or Facebook... Some lesser known websites I use do this:

> **Sitename**
 123 456
 ljacqu@Sitename

^ Is this what you want? That's fine for me, though I'd rather not have the user name on the bold line if that's OK seeing as I don't have any example that does it as such.

**Comment by AmazedMender16** [comment]
@ljacqu 

Lets say my server name is | Minecraft2019

I would like it to showup as

Minecraft2019
123 456
Username: AmazedMender16

Or

123 456
Mincraft2019: AmazedMender16

**Comment by ljacqu** [comment]
@AmazedMender16, How is it shown now for you? Are you saying you want the text "Username" hardcoded? Because for me it currently shows like this:

> **Minecraft2019**
 123 456
 ljacqu

**Comment by AmazedMender16** [comment]
@ljacqu 

Sorry havent tried it haha, about to now ( was answering you )

**Comment by AmazedMender16** [comment]
Hello @ljacqu,

Perfect, looks good thanks!


Regards,
Glenn R.

**Comment by ljacqu** [comment]
@AmazedMender16 That's great news—thanks for taking the time to test it. That's always appreciated :)
