### ISSUE TITLE
verification issue

### ISSUE THREAD

**Issue by arturek1666** [AuthMe/AuthMeReloaded#1580]
When players do /changepassword (old) (new) they will get message to verify they email. With is good they get the code and everything is fine however when comes to actually typing the code to the server this is where the issue is showing up. I type in /verification xxxxxxxx and it say that this command don't exists. The problem is that I did add permission with is: - authme.player.security.verificationcode i even add - authme.player.* and still it say that this command don't exists however it does work when I am an OP our have all permissions. Don't get that. 

### Steps/models to reproduce:
Just a basic steps: Email configuration so players if they add email will get verification code and try to type verification in the server. 

### Plugin list:
![pllist](https://user-images.githubusercontent.com/1558228/40873213-29d0b0b0-6654-11e8-952b-a3f34d75553b.png)

### Environment description
git-Paper-1428
HexaCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:b5f17e7:190 by md_5

### AuthMe build number:
AuthMeReloaded v5.5.0-SNAPSHOT (build: 2079)

### Error Log:
No error in console

### Configuration:
https://pastebin.com/FZ3BKDEJ

**Comment by sgdc3** [comment]
@Hex3l

**Comment by Hex3l** [comment]
I have some exams in this weeks so I'll try to reproduce the issue asap

**Comment by arturek1666** [comment]
Find an problem looks like chatcontrol pro was the issue. After removing the plugin the command work as it should not really sure why tho.

**Comment by Hex3l** [comment]
So it seems not an Authme issue, thank you for the feedback!
