### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Matthysse** [AuthMe/AuthMeReloaded#1585]
Just a little thing, is there a way to disable offline players that take premium accounts names? Just premiums can connect with their accounts, cracked have a error message when connecting to server like "This name is already used by a premium account, please choose another one"
It would be cool to prevent fake accounts, like offline players who choose a Youtuber's name.

**Comment by sgdc3** [comment]
@games647 doesn't fastlogin have such feature?

**Comment by Matthysse** [comment]
Fast login don't work for me...

**Comment by Matthysse** [comment]
I said nothing, FastLogin have a feature like this

**Comment by Hex3l** [comment]
@Matthysse have you find a solution? Can we close this issue?

**Comment by Matthysse** [comment]
Yes

**Comment by Hex3l** [comment]
Perfect, thank you for the feedback!
