### ISSUE TITLE
Client problem on connection (Fixed)

### ISSUE THREAD

**Issue by LoXR** [AuthMe/AuthMeReloaded#1588]
### What behaviour is observed:
What happened?
Players are hit with the Kicked whilst connecting to Hub: '&4The same username is already playing on the server!' on reconnect with a 1.12.2 client on a 1.8.8 spigot server.

### What behaviour is expected:
What did you expect?
To be able to reconnect fine with no problems.

### Steps/models to reproduce:
The actions that cause the issue
Unsure, but i've tried everything to figure a way around this, but sadly it keeps occuring.

### Plugin list:
This can be found by running `/pl`
Hub: Plugins (22): icJukeBox, SquidHQ, Citizens, SkinsRestorer, PremiumHub, IPWhitelist, ChestCommands, HideAchievements, PlaceholderAPI, GroupManager, PandoraChatFilter, CommandNPC, ProtocolSupport, ProtocolLib, EnjinMinecraftPlugin, NoCheatPlus, eZProtector, FastLogin, AuthMe, AuthMeBridge, HolographicDisplays, LiteBans

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungee

### AuthMe build number:
This can be found by running `/authme version`
Version: AuthMeReloaded v5.4.0 (build: 1877)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/KeUbfauV

**Comment by LoXR** [comment]
The Server I tried to connect to was a Spigot 1.8.8, and only had two plugins at the time, Factions & ViaVersion.

**Comment by LoXR** [comment]
Possibly found the problem, may be due to ViaVersion: https://pastebin.com/zqUSF4Kz

**Comment by LoXR** [comment]
Can confirm it was part of ViaVersion

**Comment by Hex3l** [comment]
@LoXR I'm gonna close this because it's not related to authme, thank your for the feedback!
