### ISSUE TITLE
There's a small chance users may lose their movement speed on server access permanently.

### ISSUE THREAD

**Issue by MithrandirCraft** [AuthMe/AuthMeReloaded#1591]
Spigot for MC: 1.12.2

### What behaviour is observed:
Players sometimes lose their speed randomly, and sometimes do not recover from the speed loss, when they access the server. I suspect this is a bug related to the speed removal for the movement blocking before login, which is configured on my server when you access the hub.

### What behaviour is expected:
The player should move freely after login.

### Steps/models to reproduce:
I haven't got a single clue on how to reproduce this. It's seemingly random. I'd suggest a workaround to be considered.

### AuthMe build number:
Version Authme: 5.5.0-SNAPSHOT-b2080

### Error Log:
No errors.

**Comment by sgdc3** [comment]
@MithrandirCraft please post your current config

**Comment by MithrandirCraft** [comment]
https://hastebin.com/pineloqoze.bash

**Comment by krusic22** [comment]
There is a workaround for this bug.  
Set allowMovement to true and allowedMovementRadius to 1

**Comment by sgdc3** [comment]
have you tried the RESTORE_NO_ZERO mode?

**Comment by krusic22** [comment]
Never tried it (it was added after the first similar bug report). 
It should fix the problem since every time that happened if you looked into the players data file you could see both his speeds were set to 0.

**Comment by sgdc3** [comment]
I just added some debug messages, please enable debug in your config, check your authme.log file when the bug happens. I hope this will help us find out what's going on :/

**Comment by MithrandirCraft** [comment]
Hard. Very hard xD it happens randomly. But I'll try to catch it.

**Comment by ljacqu** [comment]
A year later and we haven't heard of other reports, let's either close this or introduce some detailed logging where relevant to hopefully gain more information from the authme.log of a server exhibiting this. What do you suggest, @MithrandirCraft?

**Comment by MithrandirCraft** [comment]
Close it. I haven't managed to reproduce this a single time more since I reported this. It even happened to me at that time, but not any more. 

And feel free to preventively close this one too, since I haven't reproduced it either in a long time (It simply stopped happening with newer versions): https://github.com/AuthMe/AuthMeReloaded/issues/1362

Please check out my other open ticket: https://github.com/AuthMe/AuthMeReloaded/issues/1207

**Comment by ljacqu** [comment]
Thanks for the update, closing this one in that case. :)
