### ISSUE TITLE
Delay problem.

### ISSUE THREAD

**Issue by NeximaOzi** [AuthMe/AuthMeReloaded#1600]
Hello,

When joined on server just waiting 10 20 second and after login message coming. If you not see this message can't join with "/login password" command. This issue was no problem but now have. Why like this im really don't know.

**Video link:**
https://vk.com/video246456789_456239017

**Version:**
AuthMeReloaded v5.5.0-SNAPSHOT (build: 2094)

**Plugin list:**
AntiWDL, ViaVersion, Skript, ScoreboardHotfix, BungeeBlockProxy, ViaBackwards, HideAchievements, PlayerReset, ProtocolLib, NoCheatPlus, AuthMe

**Server status;**
Bungeecord, Mysql

**config.yml**
https://hastebin.com/xudotosoma.bash

**Server log;**
https://hastebin.com/zubagopiso.md

**Authme log;**
https://hastebin.com/faraliqapu.md

**Spigot version:**
1.12.2

**Comment by krusic22** [comment]
This is not really a AuthMe problem. This happens when chunks are being send to the client and/or the server is lagging to the point where it delays other commands/plugins.
You could drop the server view-distance to fix this issue or find out whats keeping the server busy.

**Comment by NeximaOzi** [comment]
It is not about view-distance or etc. I'm pretty sure. Because i will not any changes in my bukkit or spigot.yml or server-properties folders. Maybe this problem in bungeecord settings ?

**Comment by krusic22** [comment]
In your video you can see the world loading. After it finished loading, you got your position reset and received your first login message.

**Comment by NeximaOzi** [comment]
Yes but i'm try bukkit and spigot.yml folders reset. Also try view-distance to set 5-6 etc. But nothing change :(

**Comment by NeximaOzi** [comment]
Also have another problem. Sometimes login succesfully but not teleported still stay in fakelobby. Not always just sometimes.
https://prnt.sc/k7fowb

**Comment by krusic22** [comment]
Might be a Bungee issue 🤔 
What version are you using?

**Comment by NeximaOzi** [comment]
My bungeecord version this;
https://ci.md-5.net/job/BungeeCord/1332/

And authme reloaded version this (latest);
https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/2094/

"Also have another problem. Sometimes login succesfully but not teleported still stay in fakelobby. Not always just sometimes.
https://prnt.sc/k7fowb"

This problem too many players living. Some players try join 25-26 times.

**Comment by krusic22** [comment]
Try using WaterFall instead of BungeeCord it might help with the teleportation bug.

**Comment by NeximaOzi** [comment]
I don't know anything about waterfall. Can i not fixed this teleportation problem with not changed bungeecord ? :)

**Comment by NeximaOzi** [comment]
Because also i use redisbungee.

**Comment by krusic22** [comment]
WaterFall is compatible with every Bungee plugin (since its just a performance oriented fork). It's worth a shot since the only other issue could be that the login server is slow (might as well send /timings ).

**Comment by NeximaOzi** [comment]
Here is the timings;
https://timings.spigotmc.org/?url=bemuwaleje

**Comment by sgdc3** [comment]
Maybe your db connection is slow?

**Comment by NeximaOzi** [comment]
I don't think so i have 10+ servers in same bungeecord too many plugins website etc connect mysql no problem anything plugins.

But i can check if there is a way.

**Comment by NeximaOzi** [comment]
@krusic22 im try now Waterfall also i change my Authmebungee to Authmebridge but my problem still continue :( What can i do for this ?

**Comment by krusic22** [comment]
You should keep using AuthMeBungee. But the issue must be somewhere else. 
Do you have spawn chunks loaded?

**Comment by krusic22** [comment]
The server should keep the spawn chunks loaded in ram. That enables them to be send faster to the client.

**Comment by NeximaOzi** [comment]
i got it the delay problem with in bungee config "network_compression_threshold: -1" this settings was -1 i change to 256 and now delay problem fixed. But still i have sometimes not teleported when players join succesfull.

**Comment by sgdc3** [comment]
Please open another issue.
