### ISSUE TITLE
Conversion from LoginSecurity database resulting incorrect password hash

### ISSUE THREAD

**Issue by KlukCZ** [AuthMe/AuthMeReloaded#1601]
Hello,

I have a small problem. I converted my database from LoginSecutity to AuthMe and everything worked. But then i tried to join my password was always incorrect.  I don't know what to do...

Version:
AuthMe-5.4.0

Plugin list:
Essentials-2.x-SNAPSHOT, EssentialsChat-2.x-SNAPSHOT, AuthMe-5.4.0

Server status:
Standalone server, SQLite

config.yml
https://hastebin.com/pihitaluri.bash

Server log;
https://hastebin.com/yawiratesu.md

Authme log;
https://hastebin.com/ifisitaveb.md

Spigot version:
1.8

**Comment by sgdc3** [comment]
@ljacqu wrong hash type? i don't remember which hash logi security is using...

**Comment by KlukCZ** [comment]
I dont know...

**Comment by ljacqu** [comment]
I don‘t remember, maybe it says in our Wiki. I think it‘s Bcrypt

**Comment by KlukCZ** [comment]
I tried adding BCrypt to the hashes in the config but it didnt work...

**Comment by ljacqu** [comment]
The logs have been removed from hastebin in the meantime, but if we want to move this along we'd need @KlukCZ to create a test user with LoginSecurity (or preferably two) and then we'd need to see the hashes and ensure that they work with our implementation of BCrypt, which we expect should be the case. Is this possible?
