### ISSUE TITLE
Authme => LuckPerms 

### ISSUE THREAD

**Issue by xGlenor** [AuthMe/AuthMeReloaded#1606]
When changing from PermissionsEX to LuckPerms, permissions Authme.admin.register doesn't work

**Comment by ljacqu** [comment]
Did you give `Authme.admin.register` or is it `authme.admin.register`? I wonder if maybe one system is case-sensitive while the other isn't. Failing that, under `/authme debug` there's a command to check one's permissions (as seen by AuthMe). Could you try it out with that permission node that doesn't work and compare it with a permission node that works?
Logs and version info are welcome.

**Comment by xGlenor** [comment]
After the update works

**Comment by xGlenor** [comment]
Authme  if anything

**Comment by ljacqu** [comment]
Strange. If you say it now works we close the issue.

**Comment by xGlenor** [comment]
works :D
