### ISSUE TITLE
[Enhancement] UTF-8 support

### ISSUE THREAD

**Issue by Gophixx** [AuthMe/AuthMeReloaded#1609]
Some translations have special characters that the ANSI codifications not supports. With UTF-8, in addition to supporting more translations, **will support thousands of other special characters**!

**Comment by krusic22** [comment]
UTF-8 is already supported...

**Comment by Gophixx** [comment]
Really? Why when I convert the Portuguese translation file to UTF-8 it is not recognized

**Comment by krusic22** [comment]
What operating system do you use?

**Comment by Gophixx** [comment]
I'm using Windows 10 with AuthMe v. 5.4.0 build 1877

**Comment by krusic22** [comment]
Windows 10 is weird about that it seems. Try messing with the setting (encode in ASCII and try, UTF-16,...).

**Comment by Gophixx** [comment]
For now the conversion to ANSI is functional, but sufficient for the letters á, ç, í, etc for this translation

**Comment by sgdc3** [comment]
UTF8 without bom is the right encoding to use

**Comment by ljacqu** [comment]
Please try upgrading to a latest dev build, too. The configuration library we use in the background was handling files prior to 5.5.0 with whatever default encoding the JVM felt like there was, whereas now we do enforce UTF-8. https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
