### ISSUE TITLE
Error: Found 2 rows updated/inserted by statement, expected only 1

### ISSUE THREAD

**Issue by FabioZumbi12** [AuthMe/AuthMeReloaded#1610]
### What behaviour is observed:
What happened?
When i try to change a passowrd of player, get the error.

### What behaviour is expected:
What did you expect?
Change the passowrd via console.

### Steps/models to reproduce:
The actions that cause the issue
Using the command: /authme changepass <player> <password>

### Plugin list:
This can be found by running `/pl`
 icJukeBox, AutoSaveWorld, AdvancedPortals, WorldEdit, SkinsRestorer, MaxBans, UltraCosmetics, Pe
rmissionsEx, Televator, Lobby, ViaVersion, BetterAlias, BungeeTabListPlus, ProtocolLib, FastLogin, AuthMe, HolographicDisplays, PictureLogin

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecoord in a local host/mysql

### AuthMe build number:
This can be found by running `/authme version`
Version: AuthMeReloaded v5.5.0-SNAPSHOT (build: 2101)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
https://gist.github.com/FabioZumbi12/d3171b0d40a7dc839fe6193373ce9a7d

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by sgdc3** [comment]
@ljacqu

**Comment by ljacqu** [comment]
It looks like you have the user `herbalaifeenois` twice in your database. AuthMe expects this not to be the case.

**Comment by sgdc3** [comment]
Very strange :/

**Comment by ljacqu** [comment]
@FabioZumbi12 Do we need to follow up on this or was this user indeed twice in the database?

**Comment by FabioZumbi12** [comment]
Sorry for late response. It is twice on database. I believed this is not be possible but this was the problem. Removed the duplicate user and fixed the issue.
