### ISSUE TITLE
[Suggestion] Support others plugin for login message.

### ISSUE THREAD

**Issue by Golvore** [AuthMe/AuthMeReloaded#1613]
Could you add some way that other plugins that modify the join / quit message can use delayJoinMessage and remove the output message when a player has not started the section? an api or something like that?

**Comment by ljacqu** [comment]
What if the real join message gets suppressed and instead some other plugin listens to our [LoginEvent](https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/events/LoginEvent.java)? Or is it needed to have access to the join message text?
