### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by felipeleite5w** [AuthMe/AuthMeReloaded#1615]
### What behaviour is observed:
What happened? the server crash

### What behaviour is expected:
What did you expect?continue online

### Steps/models to reproduce: I dont know
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`
AlphaChest             AutoMessage        CombatLog                   HideStream        SetSpawn                   VipZero                           WorldEdit
                NightAttack              
AncientGates           AutoSaveWorld      Essentials                  iConomy          SimpleClans                                     WorldGuard
    OpenInv                     vIUltimatePrefixos           
AntiForceOP            BanItem                       
     BanItem.jar        GriefPreventionData         Legendchat       PluginMetrics            
AntiJoinBot            ChestShop                    ProtocolLib              update                     VoxelSniper
        GroupManager                MaxBans             Updater                    
AuthMe                 ColoredSigns       HideAndCustomPlugins              Rip_ResetKDR             Vault                      WarpPortals
  Multiverse-Core
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone i think
### AuthMe build number:
This can be found by running `/authme version`
AuthMe v3.4
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
https://pastebin.com/euUmvVLz
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: authme
  backend: file
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: '12345'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 2
    maxNicknameLength: 20
    ForceSingleSession: false
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: true
    teleportUnAuthedToSpawn: true
     minNicknameLength: 3
    allowMovement: false
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: false
    displayOtherAccounts: false
    ForceSpawnOnTheseWorlds:
    - spawn
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 2
    maxJoinPerIp: 2
    noTeleport: false
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 5
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: false
    forceLoginAfterRegister: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  forceCommandsAsConsole: []
  useWelcomeMessage: false
  broadcastWelcomeMessage: false
  delayJoinMessage: false
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: true
  OnServerStart: true
  OnServerStop: false
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: false
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: false
  captcha:
    useCaptcha: false
    maxLoginTry: 3
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, <br /><br /> This is your new AuthMe password for
    the server <br /><br /> <servername> : <br /><br /> <generatedpass><br /><br />Do
    not forget to change password after login! <br /> /changepassword <generatedpass>
    newPassword'
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: true
  notifications: true
  disableSocialSpy: true
  useEssentialsMotd: false
Performances:
  useMultiThreading: true
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removeEssentialsFile: false
  defaultWorld: world
  removeLimitedCreativesInventories: false
  removeAntiXRayFile: false
Protection:
  enableProtection: false
  countries:
  - PT
  - BR
  countriesBlacklist: []
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
VeryGames:
  enableIpCheck: false

**Comment by sgdc3** [comment]
AuthMe 3.4 is no longer supported, please update to the latest 5.X release.

**Comment by felipeleite5w** [comment]
ok, but this will fix the bug

**Comment by felipeleite5w** [comment]
How do I change my authme to authmereloaded

**Comment by sgdc3** [comment]
authme 3.4 is already authmereloaded, just backuo your authem folder and replace the jar with the new one :)

**Comment by felipeleite5w** [comment]
the issue continues happening
