### ISSUE TITLE
loopback addresses aren't excludes from country check

### ISSUE THREAD

**Issue by benoitfouc** [AuthMe/AuthMeReloaded#1617]
Hi, i use the last version of Authme and the last version (1.13) of Spigot and i've a little bug.
The feature "protection by country" is broken :
[12:05:07] [User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@69ef5a21[id=268453af-96fc-39a0-a5fe-b25d127e8af4,name=benoitfouc,properties={},legacy=false] (/127.0.0.1:52866): Votre pays est banni de ce serveur
[12:05:28] [Server thread/INFO]: com.mojang.authlib.GameProfile@69ef5a21[id=268453af-96fc-39a0-a5fe-b25d127e8af4,name=benoitfouc,properties={},legacy=false] (/127.0.0.1:52866) lost connection: Votre pays est banni de ce serveur

I'm in France and my config (work in 1.11.2) is :
Protection:
    # Enable some servers protection (country based login, antibot)
    enableProtection: true
    # Apply the protection also to registered usernames
    enableProtectionRegistered: true
    # Countries allowed to join the server and register. For country codes, see
    # http://dev.maxmind.com/geoip/legacy/codes/iso3166/
    # PLEASE USE QUOTES!
    countries: 
    - 'US'
    - 'GB'
    - 'FR'
    # Countries not allowed to join the server and register
    # PLEASE USE QUOTES!
    countriesBlacklist: 
    - 'A1'
    - 'MK'

If i set, the plugin work correctly in 1.13  :
    enableProtection: false
    enableProtectionRegistered: false

**Comment by sgdc3** [comment]
@benoitfouc could you tell me your ip via email? sgdc3.mail@gmail.com

**Comment by sgdc3** [comment]
Try to delete your geoip db file in the authme config and restart.

**Comment by benoitfouc** [comment]
Hi, i've delete the goeip.dat file but the error still here : 
`[22:31:07] [User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@4b3aecc9[id=268453af-96fc-39a0-a5fe-b25d127e8af4,name=benoitfouc,properties={},legacy=false] (/127.0.0.1:56822): Votre pays est banni de ce serveur
[22:31:07] [Server thread/INFO]: com.mojang.authlib.GameProfile@4b3aecc9[id=268453af-96fc-39a0-a5fe-b25d127e8af4,name=benoitfouc,properties={},legacy=false] (/127.0.0.1:56822) lost connection: Votre pays est banni de ce serveur`

I use the last version of essentials (https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/)

**Comment by sgdc3** [comment]
Do you use bungeecord?

**Comment by ljacqu** [comment]
> 127.0.0.1:56822

Somehow his IP comes across as localhost? Adding A1 (I think) to the whitelist should do the trick, but I don‘t know if that would effectively cancel the country protection for everyone if it‘s bungeecord? @sgdc3

Also just to mention that under /authme debug cty you can play around with the country settings and test country lookups

**Comment by benoitfouc** [comment]
I don't use bungeecord, i use Spigot.

Adding A1 doesn't work but i think this bug is only when i try to connect to my server in localhost, so it's not important. Thanks !

**Comment by sgdc3** [comment]
Now you can allow localhost access by adding "LOCALHOST" into your allowed country list! ;)
