### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RandalZ15** [AuthMe/AuthMeReloaded#1619]
Couldn't look up profile properties for com.mojang.authlib.GameProfile@438e4c4b[id=61fb7473-2cbc-35b8-baa7-44364dc05d73,name=ARHANGELFeeD,properties={},legacy=false]
25.08 17:37:01 [Server] INFO com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
25.08 17:37:01 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:177) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:301) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:206) ~[patched_1.12.2.jar:git-Paper-1550]
25.08 17:37:01 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
25.08 17:37:01 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
25.08 17:37:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by sgdc3** [comment]
Not related to authme.
