### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkFort** [AuthMe/AuthMeReloaded#1622]
https://hastebin.com/tuxukabima.bash
Latest AuthMe-5.5.0-SNAPSHOT.jar
Latest PaperSpigot 1.12.2

**Comment by sgdc3** [comment]
Please try again with the latest dev build, i added a warning message to find out which bungeecord plugin message is causing such issue.

**Comment by DarkFort** [comment]
Problem solved

**Comment by sgdc3** [comment]
@DarkFort impossible as i didn't change anything xD are you sure you don't get any warning in the console log?

**Comment by sgdc3** [comment]
@DarkFort any news?
