### ISSUE TITLE
teleportUnAuthedToSpawn has issue when a player logged out in the nether or the end on 1.13

### ISSUE THREAD

**Issue by pentyum** [AuthMe/AuthMeReloaded#1624]
### What behaviour is observed:
When teleportUnAuthedToSpawn is on, a player log in the main world will be teleported to the spawn point first and then after he login successfully,he will be teleported to the place that he logged out at, but if the player log in the nether or the end world, he will be teleported to 0,0,0 and fall down.

### What behaviour is expected:
When teleportUnAuthedToSpawn is on, a player log in the nether or the end world will be teleported to the spawn point first just like the main world.

### Plugin list:
CoreProtect, LuckPerms, WorldEdit, Vault, ProtocolLib, Essentials, EssentialsGeoIP, EssentialsChat, EssentialsAntiBuild, QuickShop, EssentialsSpawn, EssentialsProtect, AuthMe

### Environment description
Standalone server SQLite
Spigot 1.13 b1851

### AuthMe build number:
5.4.0 build 1877

### Configuration:
only set
teleportUnAuthedToSpawn :true
SaveQuitLocation: true

**Comment by tzerber** [comment]
(copy-paste this from #1700 )
I do found a fix, all of this is a config files issue. 
in config.yml make sure authme is the first in spawnPriority
`spawnPriority: authme,essentials,default,cmi,multiverse`
Also this should be enabled
`SaveQuitLocation: true`

Also edit your spawn.yml and doublecheck if the values there(map name / coords) are correct.

**Comment by Hex3l** [comment]
Same as #1700 
I'm closing this since it has been solved with PR #1880
