### ISSUE TITLE
Problem with AuthMe on Version 1.13.1

### ISSUE THREAD

**Issue by EncryptSL** [AuthMe/AuthMeReloaded#1630]
When i added AuthMe on spigot:
[00:50:53 INFO]: This server is running CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

AuthMe version: 5.5.0-SNAPSHOT-b2115

Error with CrashLog: https://pastebin.com/mFLqC1Nc 
When i delete AuthMe server working loading normal without errow and crash. 

Solving of this problem ?

**Comment by EncryptSL** [comment]
On Version 5.5.0-SNAPSHOT-b2114 working.

**Comment by sgdc3** [comment]
@ljacqu this looks very strange, maybe a corrupted jar? :/

**Comment by BoomEaro** [comment]
Similar error. I downloaded the last build from here: https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/2115/
And at the moment the latest version of spigot 1.13.1 
([13:32:05] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-0ede7d0-ee5efeb (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:32:05] [Server thread/INFO]: Checking version, please wait...
[13:32:05] [Thread-11/INFO]: You are running the latest version)
I do not think that the file is damaged.

**Comment by Fader-GumGum** [comment]
Same here. Also crash same as @BoomEaro

**Comment by games647** [comment]
@EncryptSL @Fader-GumGum @BoomEaro Could you please verify if this still happens?

**Comment by EncryptSL** [comment]
@games647 on my side is this problem solved.
