### ISSUE TITLE
Wierd message after login

### ISSUE THREAD

**Issue by KuroSenseii** [AuthMe/AuthMeReloaded#1644]
### What behaviour is observed:
After login a wierd message on chat
![image](https://user-images.githubusercontent.com/8905889/45861550-279b2800-bd3b-11e8-92db-f38fc5644d68.png)

### What behaviour is expected:
think what wrong in config or version

### Steps/models to reproduce:
just login on server

### Plugin list:
This can be found by running `/pl`
![image](https://user-images.githubusercontent.com/8905889/45861574-48637d80-bd3b-11e8-80df-39a3d45b3a27.png)

### Environment description
bungee lasted version with spigot 1.13.1

### AuthMe build number:
5.5.0

### Configuration:
https://hastebin.com/siyaxemusu.bash

**Comment by ljacqu** [comment]
Could you post your messages_fr.yml to hastebin please? Preferrably also any backups you might find (something like messages_fr.yml.20180914)

**Comment by KuroSenseii** [comment]
message_fr: https://hastebin.com/oxesunuhag.bash
backup_messages_fr_20180921_0710: https://hastebin.com/haxohidelo.bash

**Comment by KuroSenseii** [comment]
i have find the bug, its a corumpt file. i have fix it and now working great ^^
