### ISSUE TITLE
Inventory interaction protection whitelist

### ISSUE THREAD

**Issue by Hey** [AuthMe/AuthMeReloaded#1655]
Hi,

Any gui will close immediately but I want a gui to be open when logging in but the plugin is blocking it.
I tried all sorts of settings, project inventory & stuff all disabled.

But I really need this gui to be working.

Thanks!

**Comment by sgdc3** [comment]
that would allow players to mess up with inventories while unlogged

**Comment by Y3cy** [comment]
> that would allow players to mess up with inventories while unlogged

For me not.

**Comment by Y3cy** [comment]
I just want gui's the be openable while not authenticated.

**Comment by Xephi** [comment]
We can maybe add an inventory whitelist before people logged in.
Maybe based on inventory name ?

**Comment by Y3cy** [comment]
That'd be great.

**Comment by sgdc3** [comment]
@Xephi yeah that could world

**Comment by Xephi** [comment]
I wrote a simple Pull Request, changes need live tests
