### ISSUE TITLE
/email recovery Before login

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeReloaded#1656]
Hi,

If I try to type /email recover, before logging in, it does not work.

It only works after logging in, but what if the password?  How do I login?

The /email recover...command must work before login...and recognize the account...

**Comment by ljacqu** [comment]
Make sure /email is in the list of commands allowed before login. Otherwise logically it won‘t work

**Comment by Guest1131** [comment]
It is already in the list, /email and also /email recover, and it does not work the same, it only works after login

**Comment by Guest1131** [comment]
Maybe before the login, it does not work, because it does not recognize the nickname ... and the email ... but only after the login ... but it is not normal ...

/email recover, must work before login ... because if I lose my password, I must have a way to recover.

**Comment by ljacqu** [comment]
It needs to be part of the `allowCommands` list
