### ISSUE TITLE
 Player wasn't online during login process, aborted...

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1660]
> [AuthMe] Player 'FartGarfunkel13' wasn't online during login process, aborted...

What is it?  AuthMe player kicks. 
"kicked for spaming" -- https://pp.userapi.com/c849232/v849232123/91f65/TanuPnPCml8.jpg 

When I remove the plugin, the player can enter.

**Comment by DNx5** [comment]
Could you give more information? what version of your server and the AuthMe plugin?

**Comment by Roper89** [comment]
@DNx5  The problem was resolved.
I think there was a conflict with the plugin ViaVersion (ViaBackwards, ViaRewind)
