### ISSUE TITLE
Authme ip issue 

### ISSUE THREAD

**Issue by Alduuur** [AuthMe/AuthMeReloaded#1661]
When players connect to server i see in bungeecord they original ip and if bungeecord will throw players to hub they will have diffrent ip with same port
so that why players cant register.

**Comment by samyratchet** [comment]
Enable bungeecord and set it true in your bukkit config.

**Comment by sgdc3** [comment]
Enable "ip_forwarding" on bungeecord config file and "bungeecord" on spigot.yml
