### ISSUE TITLE
Authme didn't limit the player accounts

### ISSUE THREAD

**Issue by DrOreo002** [AuthMe/AuthMeReloaded#1670]
### Proof
You can check the proof here : https://imgur.com/a/71F1dWn

I'm not sure why It didn't limit the player's account...

**Comment by ljacqu** [comment]
Is it a local IP, or did you only change it to 10 recently and he had registered previously?
Could you reproduce this somehow?

**Comment by DrOreo002** [comment]
Hmmm, I'm not sure if it a local ip. Well I've changed it 3 or 4 months ago, but I still seing that his account is increasing

**Comment by ljacqu** [comment]
How does that user's IP start?

**Comment by DNx5** [comment]
@DrOreo002 could you give more information about your server setup? is it behind Bungeecord proxy?

**Comment by DrOreo002** [comment]
Hey, sorry for the late response xD

@DNx5 Yes I'm using Bungee

@ljacqu what do you mean?

**Comment by DNx5** [comment]
Have you tried checking one of your player's ip? 
it seems you didn't set up [IP Forwarding](https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/)

**Comment by DrOreo002** [comment]
> Have you tried checking one of your player's ip?
> it seems you didn't set up [IP Forwarding](https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/)

(Sorry for the late response, again... xD. Got a lot of project to do, one of them are publishing my premium plugin)

Well I have IP forwarding enabled, and I see those player's registration IP is same. Not sure why it won't limit the player's account

And I have a question here, is it limiting the account via registration IP or the last IP that player used?

**Comment by DrOreo002** [comment]
Hello?. I still have this issue and its really annoying. Player create like 20 accounts on my server now

**Comment by sgdc3** [comment]
@DrOreo002 are you sure that you enabked the bungeecord mode in the spigot.yml file?

**Comment by lifehome** [comment]
Can you try to list out the prefixes of those IP? like 172.20.xxx.xxx is fine

**Comment by ljacqu** [comment]
Assuming this was a bungee IP forwarding issue or similar
