### ISSUE TITLE
When authorizing, the plugin greatly reduces TPS

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1672]
When authorizing, the plugin greatly reduces TPS.
My other plugins do not reduce TPS as much as your plugin does.
Example: [picture1](https://i.imgur.com/uczHoUo.png), [picture2](https://i.imgur.com/Y5v4D32.png), [picture3](https://i.imgur.com/uvuuwYY.png)

**Comment by sgdc3** [comment]
Please provide proper timings reports and your config.

**Comment by Roper89** [comment]
@sgdc3  [timings](https://timings.spigotmc.org/?url=wuhiteqebu)  and [config](https://pastebin.com/KLTdGfJb)

I do not understand the timings, but they do show an average value. Timings do not show the load in real time.  When I check a TPS in real time, I see a drop in the TPS when players join.

Maybe this is due to the player's teleportation to their location.

**Comment by 7wOv6ySCjo** [comment]
> @Roper89 spigot timings reports are useless, could you try running paper and using timings v2?

So AuthMe only works fine with PaperSpigot?

**Comment by krusic22** [comment]
No. AuthMe works fine with Spigot, Paper, Taco, Akarin, you name it.
It's just that Spigot is using Timing v1 which don't report lag/timings as well as Timings v2.

**Comment by noxturno** [comment]
do you have Orebfuscator by any chance? i though it was this plug creating all the lag on my server but it turn out to be the anti xray , switched to paper and using the build in one and it works fine now.

**Comment by Roper89** [comment]
@sgdc3 , @ljacqu 
Check your plugin. He strongly drops TPS when players connect to the server.

**Comment by sgdc3** [comment]
@Roper89 I run it on my network and i never experienced tps issues due to authme, please provide timing reports and open a new issue.
