### ISSUE TITLE
Block argument command, after login

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeReloaded#1686]
Hello, I would like that on authme...that you can block before login, I do not know for example the command /rtp, but also argument, example "/rtp check" I want that before login does not work "check"

Is there an authme yet?

Thank you

**Comment by ljacqu** [comment]
If the command is not listed in `restrictions` > `allowCommands` list of config.yml the /rtp command shouldn't work, including any subcommands such as /rtp check. 
Is this not the case? If so, please share the information requested in the issue template.
