### ISSUE TITLE
/register wont work properly 

### ISSUE THREAD

**Issue by K3otic** [AuthMe/AuthMeReloaded#1693]
### What behaviour is observed:
What happened?
The /register wont work

### What behaviour is expected:
What did you expect?
To register the player

### Steps/models to reproduce:
The actions that cause the issue
/register

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone server

### AuthMe build number:
This can be found by running `/authme version`
v5.4.0(build 1877)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
I cannot fine the error log
![2ddqpl7](https://user-images.githubusercontent.com/45260995/48900545-a15fa700-ee8d-11e8-93f7-f75f8f6c5c01.png)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
 https://hastebin.com/omakunofat.bash

**Comment by sgdc3** [comment]
You didn't provide the plugin list, also update to the latest dev build available at https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

**Comment by ljacqu** [comment]
Any error in authme.log?
