### ISSUE TITLE
Possible problem teleporting before login

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeReloaded#1694]
### What behaviour is observed:

Hi, there,
I noticed that there is a problem. Another player, if it has permission for /tphere, can teleport me to him, while I'm logging in with authme.

He can teleport me before and after the login.

I want that he can't teleport me before the login, can he?

### What behaviour is expected:

That a player, before logging in, can not be teleported.

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:

#2173

**Comment by sgdc3** [comment]
tphere should be only an admin only command :/

**Comment by Guest1131** [comment]
Yes, in fact tphere and only for admin, but just an admin or who has the permission tphere, can teleport a user just spawned, who has not yet logged in with authme.

Do you solve this?

**Comment by Guest1131** [comment]
I want an admin, can teleport a user, only that the user has logged in to authme

**Comment by Eyremba** [comment]
For this, AuthMe would have to cancel all teleport events before a player is logged in.

**Comment by Guest1131** [comment]
Yes, the user before login, should be exempt to everything, should be able to be carried by an admin, only after

**Comment by sgdc3** [comment]
This will break AuthMe teleporting players itself! No! Your admins needs to know what they are doing.
