### ISSUE TITLE
[bug] After authorization death in nether (teleportUnAuthedToSpawn: true)

### ISSUE THREAD

**Issue by Roper89** [AuthMe/AuthMeReloaded#1700]
@sgdc3 
If use `teleportUnAuthedToSpawn: true` — You will be killed if you leave the game from the worlds: "nether" and "the_end" 
Video [YouTube](https://www.youtube.com/watch?v=9mzHbGn3oA8)

_Minecraft: Latest Spigot 1.12.2
AuthMe-5.5.1-SNAPSHOT (#2181)_

**Comment by sgdc3** [comment]
@Roper89 can you reproduce it with only authme as plugin?

**Comment by ljacqu** [comment]
Perhaps related to #1624

**Comment by Roper89** [comment]
Please fix it. 
If players are kicked out of the "nether" and "the_end" worlds, they die.

**Comment by sgdc3** [comment]
Does it work with this jar? (Test with caution, backup your server FIRST!)
[AuthMe-5.5.1-SNAPSHOT.zip](https://github.com/AuthMe/AuthMeReloaded/files/2805315/AuthMe-5.5.1-SNAPSHOT.zip)

**Comment by Roper89** [comment]
@sgdc3  This does not work.

**Comment by sgdc3** [comment]
please share the configuration

**Comment by Roper89** [comment]
https://pastebin.com/5zUBtgzs

**Comment by sgdc3** [comment]
@Roper89 could you please try enabling debug in authme and send us the log? (it will be saved in the authme folder)

**Comment by tzerber** [comment]
I also suffer from this and i can also attach logs / debug if that's going to help. My setup is VERY close to the setup from #1624 , latest spigot; latest essentials kit; worldedit ; worldguard ; bungeesuite (server is part of a proxy network).

**Comment by tzerber** [comment]
I do found a fix, all of this is a config file issue. 
in config.yml make sure authme is the first in spawnPriority
`spawnPriority: authme,essentials,default,cmi,multiverse`
Also this should be enabled
`SaveQuitLocation: true`

Also edit your spawn.yml and doublecheck if the values there(map name / coords) are correct.

**Comment by Roper89** [comment]
@sgdc3 , debug -- https://pastebin.com/2EsMXfK2

**Comment by Roper89** [comment]
Deaths continue. Sorry, I did a test in a creative :(
If you set spawnPriority: authme
then the player will not be killed while the session lasts.
But if the session is out, the player will die when entering the game!

**Comment by Roper89** [comment]
@sgdc3 @Hex3l  
Please fix it. This is a very serious problem due to which it is impossible to use the plugin.
The plugin kills players who have left the game while in world_nether and world_the_end.

But if you disable teleportation to spawn when logging in, then malicious users will declassify the player bases.

**Comment by Hex3l** [comment]
@Roper89 I've identify the issue but I need a confirmation, can you please post the content of your spawn.yml, thank you :)

**Comment by Roper89** [comment]
@Hex3l  my spawn.yml was the default.
Now my spawn.yml looks like this -  https://pastebin.com/S5G6gRS5 
But I have not encountered this problem for a long time.  
To prevent my players from dying, I had to increase the duration of the session by more than a day.

**Comment by Hex3l** [comment]
Yeah as expected, 

if your spawn.yml is the default one AuthMe can't retrieve the spawn point and it's going to fall back on your world spawn.
Since the nether and end spawns are at 0,0,0 the player will fall under the world and once logged in teleported, causing a fall damage death.

As this is not clear for the end user, I'm going to edit the fallback in order to get a valid spawn point iteratively in the loaded worlds, and print an error/warn to encourage the server admin to Use the "/authme setspawn" command.

Thank you for the feedback ;)

**Comment by sgdc3** [comment]
@Roper89 issue should now be fixed, please verify :D

**Comment by Roper89** [comment]
@sgdc3  All is well. :)
