### ISSUE TITLE
Question: Purgeplayer time and - authme.bypasspurge

### ISSUE THREAD

**Issue by ProblemsSender** [AuthMe/AuthMeReloaded#1711]
As we all know, purge process is based on 2 options:
1/ Using a command to force purging player immediately
2/ Wait for a time period of config.yml, I mean the daysBeforeRemovePlayer: (days) part
To my question, we also know that - authme.bypasspurge only affect to (2), sooooooo......
What happens when we're setting: 
a/ daysBeforeRemovePlayer: 30
b/ set the duration of - authme.bypasspurge to 29 days period
Choose one
A/ (b) will use to bypasspurge, after the period (a) will count, and the player is removed after 59 days
B/ (a) will count first, **if** (b) days period is bigger than (a), the purge process is happening in the next day after (b) is ended
C/ Other. (Your answer)

I'm haven't use the purge process before so I don't know how it work, I hope someone will guide me. Cuz this could take a lot of time to figure it out, just imagine waiting 1 day just to test this function...
Thanks!

**Comment by ProblemsSender** [comment]
Anyone? :(

**Comment by sgdc3** [comment]
the player will be removed the 30th day, not the 59th
