### ISSUE TITLE
Your session has been resumed by the bridge

### ISSUE THREAD

**Issue by iMoonlightxx** [AuthMe/AuthMeReloaded#1713]
When I try to enter a mode of my server, it automatically takes me out and I miss the error of "Your session has been resumed by the bridge" please help fix it.

**Comment by sgdc3** [comment]
@iMoonlightxx Stop using AuthMeBridge, use AuthMeBungee instead!

**Comment by sgdc3** [comment]
Download the latest versions of both AuthMe and AuthMeBungee from our official jenkins: https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
https://ci.codemc.org/job/AuthMe/job/AuthMeBungee/

**Comment by sgdc3** [comment]
Install AuthMe spigot-side, and install AuthMeBungee bungee-side
