### ISSUE TITLE
Add  infinite session

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeReloaded#1719]
Hi, there,

Can you please add the infinite sessions? By infinite I mean the value "-1", the session must be active, until the player has a different IP.

Right now, it only works with time, I've tried to set -1, and deactivate the session so...it asks me to login every time.

Thanks

**Comment by ljacqu** [comment]
Although arguably a security issue I understand the need to have it, just preferably not as -1 since that might change configurations that want to disable the sessions to suddenly have infinite sessions (literally the opposite).

**Comment by Guest1131** [comment]
Can you do that, then, please?  Not as -1 but as 0 , in any way, just that the session becomes infinite, if I do not change IP

**Comment by sgdc3** [comment]
@ljacqu he needs to add compatibility with other plugins, infinite session is the WRONG solution to his problem.

**Comment by ljacqu** [comment]
0 has the same issue
Are you, as sgdc3 says, trying to integrate another plugin?
