### ISSUE TITLE
what is the latest 1.7.10 authmereloaded version

### ISSUE THREAD

**Issue by felipeleite5w** [AuthMe/AuthMeReloaded#1728]
what is the latest 1.7.10 authmereloaded ?

**Comment by krusic22** [comment]
This should be the last version that works with 1.7.10:
https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/2175/

**Comment by felipeleite5w** [comment]
ok thanks @krusic22 is there some bug?

**Comment by krusic22** [comment]
The only real bug in that version is #1650 . 
It's a simple fix if you want to cherry pick some commits.
But everything else should work just fine.
