### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by PrzemoVi** [AuthMe/AuthMeReloaded#1730]
### What behaviour is observed:
My server is crashing every several hours after authme update.

### What behaviour is expected:
Do not crash with ~25 players online :smile: 

### Steps/models to reproduce:
It is happening randomly, everyday :/

### Plugin list:
WorldEdit, komunikaty, DestroyArmorStand, Essentials, NoLag, AutoMessage, PlugMan, TempGameMode, MultiServerChat, RandomTP, SignShop, ProtocolLib, WorldGuard, SkinsRestorer, ImageMaps, IPWhitelist, VoidGenerator, EssentialsChat, PermissionsEx, Gildie, Xur, CS-CoreLib, Vault, EssentialsSpawn, PlayerStatistics, BungeeTp, AuthMe, Slimefun, SlimefunLuckyBlocks, ExoticGarden, SensibleToolbox, SlimeXpansion, ElectricSpawners, ChestTerminal

### Environment description
BungeeCord (AuthMeBungee)
MySQL (MySQL 5.7.24)
Ubuntu server 18.04.1
CraftBukkit version git-Spigot-f56e2e7-7fc66b2 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### AuthMe build number:
AuthMe 5.5.1-SNAPSHOT build n.2200
AuthMeBungee v2.1.0

### Error Log:
Log from console: https://pastebin.com/raw/6HCyMDNh
Crash-raport: https://pastebin.com/raw/HL3yHy9X

### Configuration:
Lobby: https://pastebin.com/raw/6xay2xdZ
Survival: https://pastebin.com/raw/L2RW5NWu
BungeeCord: https://pastebin.com/raw/LmGUN64K

**Comment by sgdc3** [comment]
The crash seems unrelated to AuthMe

**Comment by PrzemoVi** [comment]
So what is causing crash?

**Comment by sgdc3** [comment]
Idk ,try asking in the spigot forum

**Comment by PrzemoVi** [comment]
Again. https://pastebin.com/raw/eP7g4kMX
Looks like server is blocking on authme mysql thread.

**Comment by sgdc3** [comment]
This is the relevant part: https://hastebin.com/zovetaguno.md

It is not related to AuthMe, it uses only async mysql queries!
