### ISSUE TITLE
Bug AuthmeBungee

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeReloaded#1734]
### What behaviour is observed:

After I've updated Spigot, Bungeecord, AuthmeBungee by problems.

I can't do any commands, when I type /command, nothing happens, no message appears, any command, only the commands that are in the whitelist in the authmebungee config work.If I remove authmebungee from the bungeecord, it works perfectly.I tried to update Authmebungee, and it doesn't change anything.

### Plugin list:
Plugins (40): LuckPerms, WorldEdit, VoidTeleport, ShowDisplayText, HubPvP, PlaceholderAPI, PlugMan, MineSecure, RewardBlocks, LogRegister, EasyBackup, fly-permission, WorldGuard, AdvancedHelp, NoPlugins, SkinsRestorer, JoinSlot, MVdWPlaceholderAPI, Reports, VoidGenerator, NoRainReloaded, FeatherBoard, ViaVersion, ActionAnnouncer, CustomJoinItems, LuckPermsMVdWHook, Vault, ViaBackwards, Essentials, GadgetsMenu, ProtocolLib, Citizens, ChestCommands, EssentialsChat, EssentialsSpawn, AuthMe, CommandDoesNotExist, HolographicDisplays, LiteBans, CitizensCMD

### Environment description
Bungeecord / MYSQL

### AuthMe build number:
b2202

**Comment by sgdc3** [comment]
please tell me which authmebungee version are you using

**Comment by Guest1131** [comment]
I use authmebungee, last build: #111

**Comment by sgdc3** [comment]
The issue was caused by ViaBackRewards, we talked about that in DMs.
