### ISSUE TITLE
Add option to disable MySQL connection certificate validation

### ISSUE THREAD

**Issue by akiraic** [AuthMe/AuthMeReloaded#1735]
### What behaviour is observed:
Connection to MariaDB database (local or cloud) works fine with the same configuration (changing only the IP address), but when changing to other remote SQL service it returns the error (check logs).

### What behaviour is expected:
To successfully connect to SQL at remote host using SSL.

### Steps/models to reproduce:
1. Enable SSL in config file
2. Connect to local DB (MariaDB or MySQL) = OK
3. Change IP to new DB in config file = failure

### Plugin list + Environment description + AuthMe build number:
Standalone Spigot Server for 1.13
AuthMe v5.5.1-SNAPSHOT-b2187
MySQL 5.7

### Error Log:
[Pastebin](https://pastebin.com/3YHfCuap)
The error in line 75 happened in other plugins, but after I set SQL variable "verifyServerCertificate: false" the problem was solved. Didn't find a way to insert that to AuthMe configuration tho.

### Configuration:
https://pastebin.com/QSGPXLrN

**Comment by akiraic** [comment]
Manually adding the lines as follow solved the issue:

**> # Connect to MySQL database over SSL
>     mySQLUseSSL: true
> # Verify SSL connection certificate
>     mySQLVerifyServerCertificate: false**

Can you guys confirm this configuration is correct and not just being ignored, thus not causing errors.

Thank you in advance.

**Comment by sgdc3** [comment]
It is ignored

**Comment by akiraic** [comment]
Even the "UseSSL"? 
Because either both of them are ignored, or both of them are working.
If only "mySQLVerifyServerCertificate: false" was ignore, then I should receive errors anyway, but the errors stopped. 

Then again, if "mySQLUseSSL: true" cannot be used or else I get errors, and adding the second one makes both being ignored, then SSL is not possible with SQL 5.7+?

Thank you in advance.

**Comment by sgdc3** [comment]
>Even the "UseSSL"?
No, we DO handle the UseSSL option

**Comment by sgdc3** [comment]
just remove it and you will see it is completely ignored

**Comment by akiraic** [comment]
Hello again.
That's true. It is ignored. Sorry for the confusion.

I created a MySQL 5.7 from zero and i'm using the root user for test, so there is no risk of errors with access permissions or anything related now.

The issue still there: it is trying to verify the server certificate. Same error attached in the first post.

1. Set useSSL to true, it fails verifying certificate
2. Set useSSL to false, it works
3. The server has all firewall and security off (it does not require SSL connection)
4. As said, other plugins are working fine with both dbs after stating **not to check certificate**

The real question: what to do so AuthMe do not check the certificate for validation? 
Should I make a **request** for that functionality so we can use the **mySQLVerifyServerCertificate** in MySQL properties?

Thank you.

**Comment by sgdc3** [comment]
I always feel like the VerifyServerCertificate option turned off makes useless using SSL, what do you think about that @ljacqu ?

**Comment by sgdc3** [comment]
We should add the option, but we should discourage people from using it.

**Comment by akiraic** [comment]
I agree about SSL without certificate validation being useless, but is better than completely unencrypted. Considering several other security layers i'm using, even without the validation, it will be ok.

I'll turn on the VerifyServerCertificate as soon as I learn why Java is not recognizing my Server CA certificates and how to add it to its trusted store.
If you guys have any tips on that, I'll be glad. But as far as issue goes, this ticket can be closed. Just let us know when the update with this option is available :)

Thank you very much. Sorry for the trouble.
