### ISSUE TITLE
Stop mobs from chasing/attacking players at the /login location

### ISSUE THREAD

**Issue by axemwa** [AuthMe/AuthMeReloaded#1743]
Suggestion to add an option in config for mobs to not chase un-authenticated and/or unregistered players at the /login location they are at

**Comment by sgdc3** [comment]
Hmm strange, we already cancel the EntityTargetEvent event. Can you include the steps to reproduce the issue? Can yu reproduce it without any other plugin?

**Comment by axemwa** [comment]
Started new server, added only luckperms, essentialsxvault and authme installed, issue still occurs when I leave the server in front of a skeleton and then re-join skeleton still tries to attack the player(s)

**Comment by ljacqu** [comment]
Hi @axemwa this should be fixed in the latest dev build at https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ . Thanks for the report. We're happy for you to confirm that it's also solved on your side, or to let us know if anything is missing

**Comment by axemwa** [comment]
Thanx it works great! Just tested and mobs are not targeting players that are not authed/logged in yet, awesome!
