### ISSUE TITLE
authme problem

### ISSUE THREAD

**Issue by cocos55** [AuthMe/AuthMeReloaded#1746]
Hello! My server stops immediately after starting.

authme.log error: https://pastebin.com/PvmjVSQJ
console error: https://i.imgur.com/BgiQjv5.png
authmereloaded version: AuthMe 5.4.0-b1877

**Comment by krusic22** [comment]
Update to the latest version from the CI server.

**Comment by cocos55** [comment]
> Update to the latest version from the CI server.

I don`t have the authme.log error again, but
https://i.imgur.com/XhFGyKl.png
https://prnt.sc/mhtwh9

**Comment by cocos55** [comment]
Solved.
