### ISSUE TITLE
If "ProtectInventoryBeforeLogIn:" is set to true before a player registers, after they register and login their inventory doesn't get restored

### ISSUE THREAD

**Issue by axemwa** [AuthMe/AuthMeReloaded#1752]
If "ProtectInventoryBeforeLogIn:" is set to true before a player registers, after they register and login their inventory doesn't get restored. It only restores their inventory on login if they were already registered before the setting was set to true

AuthMe version 5.5.1-SNAPSHOT-b2202

**Comment by sgdc3** [comment]
hmm i think this is by design, but we can improve this

**Comment by axemwa** [comment]
Yeah it's not so bad for new servers but servers that have already been active and have had active players no so much since their inventory and original position before registration doesn't get restored.
I'm pretty sure this is the same case as when a player unregisters and goes to register again

**Comment by Kongolan** [comment]
There is another bug, which refers to this. If you don't force registration, and have ProtectInventoryBeforeLogin on, then you don't see your inventory until you register and login. So basically the ProtocolLib adapter doesn't check for unregistered players, which it should account.

**Comment by ljacqu** [comment]
Hi @axemwa , to the best of my abilities I've tried to change the behavior to make more sense. You can check it with the latest build on https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ I'd be happy for some feedback as there are a lot of cases to consider and you may have different expectations :)

**Comment by axemwa** [comment]
seems to be workin fine now tvym
