### ISSUE TITLE
Error Enabling Authme v 5.3.2 

### ISSUE THREAD

**Issue by Bruneitor123** [AuthMe/AuthMeReloaded#1756]
### Environment description
Cauldron 1.7.10 Server
### AuthMe build number:
AuthMe v5.3.2-b1726 Or Authme v5.4.0

### Error Log:
[AuthMe] Enabling AuthMe v5.3.2-b1726
16.02 12:01:28 [Server] WARN [AuthMe] Aborting initialization of AuthMe: [NoClassDefFoundError]: fr/xephi/authme/libs/google/common/collect/Sets$1
16.02 12:01:28 [Server] WARN [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
16.02 12:01:28 [Server] INFO [AuthMe] Waiting for 0 tasks to finish
16.02 12:01:28 [Server] INFO [AuthMe] AuthMe 5.3.2-b1726 disabled!

This happens when I try to load any Authme version from 5.3.2 to 5.4.0 :/

**Comment by sgdc3** [comment]
1.7 is no longer supported
