### ISSUE TITLE
Can't use sql view

### ISSUE THREAD

**Issue by pegelf** [AuthMe/AuthMeReloaded#1760]
Hello,

I tried to use AuthMe in combination with a Wordpress/Buddypress-Website. Because the Wordpress username can be different than the Minecraft Username, I created a separate Buddypress Profile field with the username. 

As the username and the password are now stored in different tables, I thought creating a database view could be a solution. However, AuthMe seems to have problems when using a database view instead of a regular table.

When I simply use a table, there is no connection problem. But that is not an option, because I want the passwords to be synced.

### Steps/models to reproduce:
Creating a database view instead of using a simple database table.
In my case, I used a view that combines a wordpress user table with a buddypress table and an extra table for all fields that still weren't contained. In this paste, I called it "[authme_table]". 

```
Create view WP_Authme AS
  select
    wp_users.ID as id,
    wp_bp_xprofile_data.value as username,
    wp_users.user_nicename as realname,
    wp_users.user_pass AS user_password,
    wp_users.user_email AS email,
    wp_users.user_registered AS regdate,
    [authme_table]_.salt,
    [authme_table]_.isLogged,
    [authme_table]_.hasSession,
    [authme_table]_.totp,
    [authme_table]_.ip,
    [authme_table]_.lastlogin,
    [authme_table]_.regip,
    [authme_table]_.x,
    [authme_table]_.y,
    [authme_table]_.z,
    [authme_table]_.world,
    [authme_table]_.yaw,
    [authme_table]_.pitch
  from
    (
      (
        wp_users
        join wp_bp_xprofile_data on (wp_users.ID = wp_bp_xprofile_data.user_id)
      ) left join [authme_table]_ on (wp_users.ID = [authme_table]_.ID)
    )
  where
    wp_bp_xprofile_data.field_id = 2
```

### Plugin list:
- Dynmap
- Authme
- WorldBorder

### Environment description
One Server that contains the Minecraft-Server, the Website and the SQL-Server

### AuthMe build number:
AuthMe Reloaded 5.4.0

### Error Log:
```
[Server thread]: INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
[Server thread]: INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Start completed.
[Server thread]: INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown initiated...
[Server thread]: INFO fr.xephi.authme.libs.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Shutdown completed.
[AuthMe]: Can't initialize the MySQL database: [SQLException]: 'lanjugend.WP_Authme' is not BASE TABLE
[AuthMe]: Please check your database settings in the config.yml file!
[AuthMe]: Could not create data source: [SQLException]: 'lanjugend.WP_Authme' is not BASE TABLE
[AuthMe]: Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[AuthMe]: THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
```

**Comment by ljacqu** [comment]
Oof, this is a tough one. The issue with views is that we can't write back to them, so we wouldn't be able to save anything back to the table (last login date, last location, email/password changes) so I'm not sure supporting views is worth the implementation effort... A way more expensive alternative would be to allow columns to be defined from multiple tables and to define how those tables can be joined together... That, however, is a big undertaking :)
