### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by brtamas0** [AuthMe/AuthMeReloaded#1765]
AUTHME CRASHES THE SERVER WHEN I INSTALL...

**Comment by krusic22** [comment]
Could you provide a log?
Also what server version are you running, what version of AuthMe do you have, do you have Bungee?,...

**Comment by brtamas0** [comment]
1.13.2 the server and 1.13 the plugin :D

**Comment by ljacqu** [comment]
> Could you provide a log?
> do you have Bungee?,...
