### ISSUE TITLE
Invisible inventory

### ISSUE THREAD

**Issue by Noob1917** [AuthMe/AuthMeReloaded#1767]
Сделайте невидимый Невидимый инвентарь для неавторизированных игроков

**Comment by Noob1917** [comment]
Make the invisible the invisible gear for rogue players

**Comment by sgdc3** [comment]
Sorry, i don't understand you

**Comment by Noob1917** [comment]
how to make things invisible in your inventory for unauthorized players

**Comment by sgdc3** [comment]
`ProtectInventoryBeforeLogIn: true`

**Comment by Noob1917** [comment]
I need to not be seen things that are in the inventory

**Comment by ljacqu** [comment]
If you set the property to true that @sgdc3 mentions and make sure that you have ProtocolLib installed, the inventory will be hidden from non-authenticated players
