### ISSUE TITLE
Question about the configuration of hiding the name of the mail

### ISSUE THREAD

**Issue by BoomEaro** [AuthMe/AuthMeReloaded#1773]
Before logging in, you can not find out what mail was attached, they say there is no mail.
As I understood it, this was done intentionally to prevent the leakage of private information. However, then it is not clear why the Security.privacy.enableEmailMasking configuration is needed.
If you enable it, the mail will be hidden only for players who are logged in, which is not logical in my opinion.
I think it should be allowed to show mail before entering the system, but covertly. And after entering, show completely.

**Comment by ljacqu** [comment]
We introduced the setting within #1119. The reason for masking the email even when someone is logged in is that, if someone somehow has access to a user in logged in state, he would be able to take over the account by changing the email and performing the password recovery.
