### ISSUE TITLE
se busca ayuda

### ISSUE THREAD

**Issue by kevincondena** [AuthMe/AuthMeReloaded#1781]
No se si es un bug o un problema mío pero necesito ayuda, el problema que yo tengo es que los usuarios que no se loguean no los kickea los dirige automáticamente al lobby o hub, no se porqué pasa eso estoy probando y me encontré con este bug, por ejemplo yo soy un usuario no-premium entro a la zona de logueo de mi server y me pide que me loguee pero yo no lo hago no coloco nada de comandos pero cuando el tiempo pasa debería de kickearme por no iniciar sesión pero no sucede eso me dirige al hub o lobby automáticamente.

**Comment by sgdc3** [comment]
Please use english and follow the issue tamplate.
