### ISSUE TITLE
AuthMe seems to recognize I have multiple accounts

### ISSUE THREAD

**Issue by Raika09** [AuthMe/AuthMeReloaded#1789]
AuthMe-5.5.1-SNAPSHOT
(We're using for a 1.12.2 server that we're setting up)

### What behaviour is observed:
When I first registered, it was successful, no issues whatsoever. When we tried to test out the server with our friends, they registered and told that I own the accounts. We have different IPs and as well using different clients. I use the Orig Java client, while my friends use a cracked client.

### What behaviour is expected:
It will just register as an individual account

### Steps/models to reproduce:
Friend registered as soon as they joined the server

### Plugin list:
Authme 5.5.1
Anti World Download
Compat No Cheat Plus
Crazy Auctions 1.2.7
CreativeGates
EntityLWC
EssentialsX 2.16.1.0
EssentialsXChat
EssentialsXProtect
EssentialsXSpawn
ExtraContext
Factions
FAWE 19.04.06
LuckPerms 4.4.1
MassiveBooks
MassiveCore
MassiveTickets
MCCore
Multiverse Core 2.5.0
Multiverse Portals 2.5.0
MySkin
MythicMobs
NoCheatPlus
Orebfuscator 4.4.3
Plugman
ProtocolLib
QuickShop
SkillAPI
StackMob 2.2.18
Vampire
Vault
VoidGenerator 1.4.2
VoxelSniper
WorldBorder
WorldEdit 6.1.9
WorldGuard 6.2.2
WorldBorder

### Environment description
Standalone server

### AuthMe build number:
AuthMe-5.5.1-SNAPSHOT

### Configuration:
https://pastebin.com/CPXRKLmX

**Comment by sgdc3** [comment]
Is it a local server or a public one?

**Comment by Raika09** [comment]
@sgdc3 
I believe this is public.

**Comment by sgdc3** [comment]
Please try asking support on our discord server, it sounds like a configuration issue, not a bug in the plugin.
