### ISSUE TITLE
saltedsha512 passwordHash does not work with mySQL

### ISSUE THREAD

**Issue by ITZVGcGPmO** [AuthMe/AuthMeReloaded#1795]
behaviour observed:
[WARN]: [AuthMe] Error during SQL operation: [MySQLSyntaxErrorException]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') VALUES ('user','62567baa74ef5f5d9f9d410676a6dfb06082096fbffd7d62657462d09eea31' at line 1

expected: 
successful player registration

reproduction steps:
set passwordHash to 'SALTEDSHA512'
configure to use mySQL
/register abc123 abc123

Plugin list:
AuthMeReloaded v5.4.0 (build: 1877)
protocolsupport.ProtocolSupport$BuildInfo(buildtime: 2018.07.05 at 23:59:41 MSK, buildhost: build.true-games.org, buildnumber: 242)
ViaVersion 2.0.0-SNAPSHOT

Environment:
Paper version git-Paper-1606 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Travertine version git:Travertine-Bootstrap:1.13-SNAPSHOT:207271d:90 by md_5
Bungeecord network + MySQL Ver 14.14 Distrib 5.7.25, for Linux (x86_64)

**Comment by sgdc3** [comment]
Update AuthMe to the latest dev build before reporting issues.
https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

**Comment by ITZVGcGPmO** [comment]
works as of latest dev build
