### ISSUE TITLE
Suggestion/feature request - Captcha prevent bots and consume resource

### ISSUE THREAD

**Issue by Betob89** [AuthMe/AuthMeReloaded#1796]
Hi i see you add this option new captcha on config.

    captcha:
        # Enable captcha when a player uses wrong password too many times
        useCaptcha: true
        # Max allowed tries before a captcha is required
        maxLoginTry: 1
        # Captcha length
        captchaLength: 5
        # Minutes after which login attempts count is reset for a player
        captchaCountReset: 1
        # Require captcha before a player may register?
        requireForRegistration: true

        # This kick a player is try the captcha  incorrect more that 2 times.
     EXAMPLE: maxRegisterCaptchatry: 2

Cant you add for the option registration captcha if you do a captcha incorrect many times (Optional in config how many time) Kick the player. Thats prevents bots consume resource try to do a commands register.

Sorry for my bad english im spanish.

**Comment by Betob89** [comment]
iI tested my bot and bypass de captcha you need add a action, by click chat message to register, thats revolucionary and block attacks bots.

**Comment by Betob89** [comment]
This program attacks bots detect your captcha and bypass.


https://www.minecraftbot.com/login.html

Need add option to click a message on chat to register.  The program detect items click menus etc but not click message on chat.

**Comment by ljacqu** [comment]
I'm afraid I don't understand what is expected from us in this issue. Would you like to see a new option like "maxRegisterCaptchatry" that you've posted in the first post, or something else?
Or is this about allowing some sort of URL template to be configured?
