### ISSUE TITLE
Is it possible to turn off account validation?

### ISSUE THREAD

**Issue by lifehome** [AuthMe/AuthMeReloaded#1798]
https://github.com/AuthMe/AuthMeReloaded/blob/0227cb3f7410223514dacbf99f94ec19a689eb3a/src/main/java/fr/xephi/authme/process/login/AsynchronousLogin.java#L141-L142

This seems enforcing account validation must be in place when the MySQL group column is set.

## Step to reproduce
1) Fresh install of AuthMe
2) Configure AuthMe with MySQL connection details **WITHOUT** changing the connection type to MySQL
3) Spin up the server
4) You get stucked in account validation after registering.

**Comment by ljacqu** [comment]
I mean essentially you could use a bogus value for `NON_ACTIVATED_USERS_GROUP` and then it will never pass the check, thus turning off account validation, right? Or am I missing something?
