### ISSUE TITLE
Suggestion: Save passwords with the UUID of the player instead of the username

### ISSUE THREAD

**Issue by ipozow** [AuthMe/AuthMeReloaded#1800]
Well, there is already a [closed issue](https://github.com/AuthMe/AuthMeReloaded/issues/713) like this, but it's not the same. 
My suggestion is that, instead of using the username to save the password, the plugin should be using the UUID. 
But, why?
Because security. There is a thing called UUID Spoofing, where players can use the nick that they want and the UUID of an administrator. They would use their own password and also have all permissions. So, if AuthMe saves the passwords by UUID, the hacker would have to know the administrator password instead of his own one to have access to all permissions and stuff.

**Comment by sgdc3** [comment]
UUID spoofing isn't applicable on properly configured servers as far as i know, are you able tonprove that this type of attack is applicable?

**Comment by ipozow** [comment]
I would have to search logs of like one year ago to prove it. But what people can do with a proper client that as much I have searched I have not found (at least that is good) is to use any nick and change the UUID with the client. Some plugins like Essentials just detects that there is a UUID change and then it changes the username and because that he have all the permissions. Anyways I am not using Essentials so that isn't the problem, just an example. 
As AuthMe does not even checks the UUID if someone uses his own name and another UUID he will be able to log in and have the permissions of that other UUID. 
I have some videos where people try that in a 1.8 client.
And there isn't any software developed by Spigot to stop this. There are some plugins but they aren't working in 1.14. 
Perhaps in an online-mode server the server can check the UUID with the Mojang servers, but in a not online-mode server is harder and some people that hasn't bought the game can join in. I know that this last one it's a problem of the server owner but I can't change the server to online mode because it would cause a lot of problems

**Comment by krusic22** [comment]
There isn't any software to stop it since Spigot patched the issue way back when.
But there are people still running Spigot 1.8 (not 1.8.8, but 1.8).

**Comment by ipozow** [comment]
Man, I had this issue in spigot 1.12.2. Someone used their nickname with my UUID and the rest of the history isn't necessary. This is the software: https://youtu.be/UW4zeBeNOw8

**Comment by sgdc3** [comment]
@ipozow pls tell us your plugin list

**Comment by ipozow** [comment]
well, in the bungee I am using ABD, AntiUUIDSpoof-1.0.3, ChangeSkin, FastLogin, NuVotifier, PLAN and ViaVersion.
In the proxy where I am using AuthMe: CMI, ProtocolLib, Fastlogin and 2 more

I don't know for what is this but well, there you go

**Comment by games647** [comment]
And you blocked all direct access to the spigot server? So only BungeeCord is accessible to the Internet (considering only the Minecraft protocol)? (Done using a Firewall,  local interface binding or similar)

**Comment by ipozow** [comment]
yes

**Comment by sgdc3** [comment]
We aren't going to switch to an UUID based storage, your issue is unrelated to AuthMe and can't be reproduced on the latest 1.8.8 spigot builds.
