### ISSUE TITLE
Could not load Authme

### ISSUE THREAD

**Issue by giuliotoplad** [AuthMe/AuthMeReloaded#1801]
Authme suddenly doesn't work anymore
Minecraft Server Paper 1.12.2 last version 
Error: https://pastebin.com/CsWVt2Pq

**Comment by krusic22** [comment]
Your plugin is corrupt. 
Replace it with a fresh download.

**Comment by giuliotoplad** [comment]
I've downloaded Authme multiple times and it still doesn't work, I'm using the latest authme build.

**Comment by krusic22** [comment]
What file exactly did you download?

**Comment by giuliotoplad** [comment]
I downloaded this file: https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.6.0-SNAPSHOT.jar
Authme # 2230 Sat Apr 27 12:47:03 CEST 2019
The previous version worked when I downloaded this new version after a few days and stopped working giving me this error.

**Comment by giuliotoplad** [comment]
I worked on it and discovered that it is an error caused by my Server due to a conflict, all solved.
Thanks anyway.
