### ISSUE TITLE
Players with * permission can chat while not logged in

### ISSUE THREAD

**Issue by HgeX** [AuthMe/AuthMeReloaded#1810]
As the title says, players who have * permission can chat without  logging in. This might not seem like a huge issue, but there are some players who discovered this, and now they join with one of our admins account and chat in their names. Of course they cannot login, but still, it's really annoying. But what's most interesting to me is that this issue wasn't present in version 5.4.0-b1877, but in the newer 5.6.0 it is. I've tested this with both PEX and LuckPerms.

**Comment by sgdc3** [comment]
Just negate the "authme.allowchatbeforelogin" permission to users with *

**Comment by HgeX** [comment]
Okay, so then this isn't a bug but a feature? Anyways, I'll do that, thx! ;)
