### ISSUE TITLE
Can't start in 1.14.1

### ISSUE THREAD

**Issue by pentyum** [AuthMe/AuthMeReloaded#1812]
[14:43:20] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta1-b2226
[14:43:20] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[14:43:20] [Server thread/INFO]: [AuthMe] Hooked into LuckPerms!
[14:43:20] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
[14:43:20] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
[14:43:20] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
[14:43:20] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!

My server is Spigot 1.14.1

Other plugin list: 
EssentialsX-2.16.1.156
QuickShop-Reremake.1.4.3.5
Vault-1.7
worldedit-bukkit-7.0.0-rc-2
LuckPerms-Bukkit-4.4.22
dropper_shop-0.0.6-SNAPSHOT
ProtocolLib-4.4.0

**Comment by ljacqu** [comment]
Could you paste the error from your authme.log please? There should be a longer one

**Comment by comonier** [comment]
AuthMe v5.6.0-SNAPSHOT-b2247 

working

**Comment by pegelf** [comment]
I'm having the same error and here is there longer error from authme.log:

> [05-18 15:32:30]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
> [05-18 15:32:30]: [INFO] AuthMe 5.6.0-beta1-b2226 disabled!
> [05-18 15:33:03]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
> [05-18 15:33:03]: [INFO] MySQL setup finished
> [05-18 15:33:03]: [INFO] Hooked into LuckPerms!
> [05-18 15:33:03]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
> [05-18 15:33:03]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
> 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
> 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
> 	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:239)
> 	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:212)
> 	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:127)
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
> 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
> 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
> 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
> 	at java.base/java.lang.Thread.run(Thread.java:844)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
> 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
> 	... 16 more
> Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.mail.EmailService'
> 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
> 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
> 	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
> 	at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
> 	at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
> 	at fr.xephi.authme.command.CommandHandler.<init>(CommandHandler.java:49)
> 	... 21 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
> 	at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
> 	... 36 more
> Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
> 	at fr.xephi.authme.mail.EmailService.<init>(EmailService.java:33)
> 	... 41 more

**Comment by pentyum** [comment]
> I'm having the same error and here is there longer error from authme.log:
> 
> > [05-18 15:32:30]: [WARN] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
> > [05-18 15:32:30]: [INFO] AuthMe 5.6.0-beta1-b2226 disabled!
> > [05-18 15:33:03]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
> > [05-18 15:33:03]: [INFO] MySQL setup finished
> > [05-18 15:33:03]: [INFO] Hooked into LuckPerms!
> > [05-18 15:33:03]: [WARN] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
> > [05-18 15:33:03]: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'
> > at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
> > at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
> > at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:239)
> > at fr.xephi.authme.AuthMe.initialize(AuthMe.java:212)
> > at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:127)
> > at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> > at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
> > at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
> > at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
> > at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
> > at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440)
> > at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
> > at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
> > at java.base/java.lang.Thread.run(Thread.java:844)
> > Caused by: java.lang.reflect.InvocationTargetException
> > at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> > at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> > at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> > at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
> > at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
> > ... 16 more
> > Caused by: fr.xephi.authme.libs.ch.jalu.injector.exceptions.InjectorReflectionException: Could not invoke constructor of class 'class fr.xephi.authme.mail.EmailService'
> > at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:94)
> > at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.StandardInjection.instantiateWith(StandardInjection.java:65)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:158)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
> > at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.newInstance(InjectorImpl.java:77)
> > at fr.xephi.authme.libs.ch.jalu.injector.handlers.dependency.FactoryDependencyHandler$FactoryImpl.newInstance(FactoryDependencyHandler.java:45)
> > at fr.xephi.authme.command.CommandHandler.initializeCommands(CommandHandler.java:109)
> > at fr.xephi.authme.command.CommandHandler.(CommandHandler.java:49)
> > ... 21 more
> > Caused by: java.lang.reflect.InvocationTargetException
> > at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> > at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> > at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> > at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
> > at fr.xephi.authme.libs.ch.jalu.injector.utils.ReflectionUtils.newInstance(ReflectionUtils.java:91)
> > ... 36 more
> > Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
> > at fr.xephi.authme.mail.EmailService.(EmailService.java:33)
> > ... 41 more
> 
> edit:// The error doesn't happen in Snapshot 5.6.0 anymore, so I think it will be fixed on next release.
> 
> @pentyum Maybe you could try to use this version: https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.6.0-SNAPSHOT.jar

It works well, thanks !
