### ISSUE TITLE
Unique ID per user in database.

### ISSUE THREAD

**Issue by iiLearner** [AuthMe/AuthMeReloaded#1813]
Hello!

I've only recently decided to integrate authme with my website and allow users to login on website using their in game credentials, however since I want to integrate other plugins as well such as MySkin and Luckperms (to identify user group) I really needed the user UUID in the database which I noticed is not there. 

is there any workaround to this?

**Comment by ljacqu** [comment]
You're right, it's currently missing. I'd suggest that we add a new optional column to the config.yml for the uuid and that if it's not empty we'll just always populate it with the player's UUID.

**Comment by sgdc3** [comment]
@Xephi thank you for implementing this! :D

**Comment by ljacqu** [comment]
@iiLearner we're happy to get your feedback on this issue :)

**Comment by iiLearner** [comment]
oh neat! thank you! although I  had to look for a workaround back then and im still using that one. but it's still very very useful for other users so thank you again!
