### ISSUE TITLE
Can execute commands /stop on OP account not logged in

### ISSUE THREAD

**Issue by Chilliann** [AuthMe/AuthMeReloaded#1819]
Title says it all.. :( 
I tested a few commands before i logged into my account and was able to use /stop to stop the server /save-all and also OP other players.
I checked the config and edited the perm group part set to true this is my config if im doing something wrong please help sort it out. Thankyou. 
Perm plugin: Ultra permissions (latest)
Spigot: 1.13.2

Config:  https://pastebin.com/3MMrsAti
If you can edit it to a degree if I am doing something wrong and paste a new pastebin config that would be great.

**Comment by ljacqu** [comment]
It's strange because the OP status should always be removed from users before authentication, regardless of your permission settings. If you do `/authme debug limbo <you>` on the console before you log in, does it show that you have the OP status?

**Comment by Chilliann** [comment]
Sorry for the delay have been busy..
This is what i got from the command. I was able to do /stop and stop the server after entering that command without logging in..

https://imgur.com/a/9XNRqZB

**Comment by ljacqu** [comment]
It's strange because as you can see it says that you're not OP at that moment ("false" in the first column for "Is OP"). Is someone who is unopped also able to run /stop? Is there anything special we should know about your permissions setup or so? Because right now the cause is unclear.

**Comment by Chilliann** [comment]
No ive demoted myself from owner rank and only had default rank and removed OP and couldnt stop the server it only seems to do it if im OP

**Comment by ljacqu** [comment]
I just tested locally and cannot reproduce. Something must interfere with your /stop command, either that there's some sort of customization taking place or that some other plugin is interfering with it. I'd suggest to remove all plugins except for AuthMe, see if it still happens, and then gradually add plugins until it occurs again.
