### ISSUE TITLE
ForceLoginAfterRegister doesn't work

### ISSUE THREAD

**Issue by zrdzn** [AuthMe/AuthMeReloaded#1821]
### What behaviour is observed:
When i changed forceLoginAfterRegister to true it doesn't work as it should.

### What behaviour is expected:
I wanted to make "auto-login" when user will register successfully

1. User uses /register <password> <password>
2. Authme automatically performs /login for this user

### Plugin list:
I got: AuthMe, EssentialsX, EssentialsXChat, EssentialsXSpawn, LuckPerms, Vault, WorldEdit, Worldguard

### Environment description
MySQL

### AuthMe build number:
2253

### Error Log:
No errors

### Configuration:
https://pastebin.com/Wpf9fpn7

**Comment by sgdc3** [comment]
> When i changed forceLoginAfterRegister to true it doesn't work as it should.
What happens?

**Comment by zrdzn** [comment]
It's not auto logging an user, after register it's just asking to login with /login command.

**Comment by ljacqu** [comment]
```yml
        # Does AuthMe need to enforce a /login after a successful registration?
        forceLoginAfterRegister: false
```

True means AuthMe will _force_ the user to log in after he registers, so what you're looking for is the opposite, i.e. please set it to _false_ and it should work properly.

**Comment by zrdzn** [comment]
But i want to auto-login user.
I don't want to ask user to login after sign up.

**Comment by ljacqu** [comment]
That‘s what `false` does

**Comment by zrdzn** [comment]
Okay thanks for help. :)
