### ISSUE TITLE
  # Send player to this BungeeCord server after register/login

### ISSUE THREAD

**Issue by leoncp9** [AuthMe/AuthMeReloaded#1823]
# Send player to this BungeeCord server after register/login
    sendPlayerTo: hub

this options don't work!

**Comment by leoncp9** [comment]
build authme Build #2253 (Wed May 29

**Comment by leoncp9** [comment]
on AuthMe-5.4.0 work great

**Comment by sgdc3** [comment]
Please post your authme config file.

**Comment by leoncp9** [comment]
fixed, only my account ca't join to other server, other player yes
