### ISSUE TITLE
Even though, it's duplicated. Unregistered unforced players should have their Inventory shown...

### ISSUE THREAD

**Issue by Kongolan** [AuthMe/AuthMeReloaded#1830]
Version: Build #2256 (Tue Jun 04)

You can "reproduce" it by

1. Turn off the force register. (under # Only registered and logged in players can play.)
2. Turn on the inventory protection. (ProtectInventoryBeforeLogIn: false)
3. Log in with an not registered account.

Players without registration can't access their inventory. The reason for this, is that the ProtocolLib Adapter doesn't account unregistered players and force register FALSE properly.

Please check this out, since I checked into it, but i can't see where the ProtocolLib inventory protection is called, since it's not in the PlayerListener nor in the AsynchronousJoin.

```
        if (isAuthAvailable) {
            // Protect inventory
            if (service.getProperty(PROTECT_INVENTORY_BEFORE_LOGIN)) {
                ProtectInventoryEvent ev = bukkitService.createAndCallEvent(
                    isAsync -> new ProtectInventoryEvent(player, isAsync));
                if (ev.isCancelled()) {
                    player.updateInventory();
                    ConsoleLogger.fine("ProtectInventoryEvent has been cancelled for " + player.getName() + "...");
                }
            }
```
This account it properly, but the event call is strange for me. It seems like the ProtocolLib inventory protection is handled independent of that.

This is a duplicate of:
https://github.com/AuthMe/AuthMeReloaded/issues/1443
https://github.com/AuthMe/AuthMeReloaded/issues/1752

**Comment by Kongolan** [comment]
Using 
```
    public void register(BukkitService bukkitService, boolean hideNow) {
        ProtocolLibrary.getProtocolManager().addPacketListener(this);

        if (hideNow) {
			bukkitService.getOnlinePlayers().stream().filter(p -> playerCache.isAuthenticated(p.getName())
					|| (!service.getProperty(RegistrationSettings.FORCE) && !database.isAuthAvailable(p.getName())))
					.forEach(this::sendBlankInventoryPacket);
        }
    }
```
in InventoryPacketAdapter.java did somehow not work. I have no insight into how the inventory adapter is handled but without ProtocolLib this problems do not appear.

**Comment by ljacqu** [comment]
Hi @Kongolan, I appreciate the analysis. I think all that was missing was also checking this in `onPacketSending`. I opted not to check for the force registration setting at all, as IMHO if a user is unregistered (no matter the circumstances) AuthMe shouldn't interfere with his inventory. The fix is available on the latest dev build at https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ and I'd be happy for any feedback you have.

**Comment by ljacqu** [comment]
Also CC to @games647 , if you'd like to review my change in 81cf14f  that would be fine as well; first time I considerably touch the Protocol Lib features :)

**Comment by games647** [comment]
> Also CC to @games647 , if you'd like to review my change in [81cf14f](https://github.com/AuthMe/AuthMeReloaded/commit/81cf14fbc16aaecf7ac72dfea9a8acbff21f4f6d) that would be fine as well; first time I considerably touch the Protocol Lib features :)

@ljacqu Looks good to me
