### ISSUE TITLE
Building the Javadocs with Java 11 or 12 doesn't work

### ISSUE THREAD

**Issue by Kongolan** [AuthMe/AuthMeReloaded#1831]
The problem is simple, also noted down here:
https://bugs.openjdk.java.net/browse/JDK-8212233

Java 12 doesn't find the correct java docs for Java 8, so setting the compiler to Java 8 isn't enough.

```
    <groupId>org.apache.maven.plugins</groupId> 
    <artifactId>maven-javadoc-plugin</artifactId> 
    <configuration> 
      <source>8</source> 
    </configuration> 
```
is also needed on the javadoc maven plugin argument. No compile errors afterwards with Java 11 or Java 12...

**Comment by ljacqu** [comment]
Curiously it works fine for me with Java 11 but I just ran the build with Java 8 and 11 with the configuration you mention and it works just as good, so I'll gladly add it. Thanks for the detailed explanation and for the link. :smile:

**Comment by ljacqu** [comment]
Does this solve the problem on your end?

**Comment by Kongolan** [comment]
Yeah, it does^^ I only have Java 12 installed right now. That line works^^
