### ISSUE TITLE
Crash when using AuthMe with LuckPerms

### ISSUE THREAD

**Issue by Aaron2550** [AuthMe/AuthMeReloaded#1832]
### What behaviour is observed:
Server crashes

### What behaviour is expected:
Server does not crash and starts up normally

### Steps/models to reproduce:
Starting the Server crashes it almost instantly

### Plugin list:
https://files.catbox.moe/454d1h.jpg

### Environment description
Standalone server, RCON is enabled and a webserver is running on the same System

### AuthMe build number:
The log says AuthMe v5.6.0-beta1-b2226

### Error Log:
latest.log :https://pastebin.com/UY3c9xb5
AuthMe.log :https://pastebin.com/sbSWGmHM

### Configuration:
https://pastebin.com/B3FADtjL

**Comment by ljacqu** [comment]
> Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getServerName()Ljava/lang/String;
    at fr.xephi.authme.mail.EmailService.<init>(EmailService.java:33)
    ... 35 more

Please use the latest dev build. This is an incompatibility with Minecraft 1.14 that was fixed later. https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/
