### ISSUE TITLE
Players are not being sent to a BungeeCord server.

### ISSUE THREAD

**Issue by JasperWorld** [AuthMe/AuthMeReloaded#1833]
### What behaviour is observed:
I have:
`Hooks:
    # Do we need to hook with multiverse for spawn checking?
    multiverse: true
    # Do we need to hook with BungeeCord?
    bungeecord: true
    # Send player to this BungeeCord server after register/login
    sendPlayerTo: l1
    # Do we need to disable Essentials SocialSpy on join?
    disableSocialSpy: false
    # Do we need to force /motd Essentials command on join?
    useEssentialsMotd: false`
And players are not getting sent to another server.
### What behaviour is expected:
The player had to get sent to another server.

### Plugin list:
![image](https://user-images.githubusercontent.com/28309837/59472432-b4908f00-8e3e-11e9-8411-88dbc64f8cf0.png)

### Environment description
Bungeecord, no database for authme.

### AuthMe build number:
2257

### Configuration:
https://pastebin.com/wLPz19kV

**Comment by JasperWorld** [comment]
For people having this issue, you can fix this by unregistering yourself registering again.

Issue fixed, closed.

**Comment by JasperWorld** [comment]
lol, it's not working when I /login, only if I /register.
I'm pretty sure this is a bug that needs fixing.

**Comment by lordgecko27** [comment]
I'm having the same issue, It only sends the player to another server after registering

**Comment by AlexBanPer** [comment]
Same issue, only sends after registering. There is not a fix yet?

**Comment by Hex3l** [comment]
Hello @JasperWorld ,
I'm unable to reproduce the issue.

If the player has the permission `authme.bypassbungeesend` will not be sent to the other server, could this be the cause of your problem?

**Comment by Link0Darck** [comment]
Hello,
I'm sorry to open an old topic but I have the same problem I blocked the permission but me having the founder rank it doesn't want to teleport me and I'm not OP
