### ISSUE TITLE
Authme And bungeecord sane Regip 127.0.0.1 

### ISSUE THREAD

**Issue by Oratoria** [AuthMe/AuthMeReloaded#1834]
I connected AuthMe with database on the BungeeCord Server. I got a problem that all player register ip and all login ip are 127.0.0.1 and it shows massage after login into the server "This player has (5) accounts: list of 5 usernames". after I read some posts. I change spigot.yml and set bongeeCord: true. and In bungeeCord config.yml and set Ip-forwarding:true. I'm able to fix the problem! all player has different ip and join message are gone. The day after My server had a serious Problem, My server has a big lag and big delay. I contact The vps owner he helped me out and he sets the spigot.yml bongeeCord: false again. He said that will make you have a big lag. Do you have any fix? sorry for my bad english. please help me out.

**Comment by sgdc3** [comment]
#1836
