### ISSUE TITLE
Authme with BungeeCord

### ISSUE THREAD

**Issue by Oratoria** [AuthMe/AuthMeReloaded#1836]
### What behaviour is observed:
My server use Bungeecord and Spigot with Authme connected to database. In bungeecord config portforwarding is true; but In spigot.yml bungeecord is false. everyone has a same ip "127.0.0.1".

When user login everyone will see a message "this player has 56 accounts: list of accounts".

But When I put bungeecord: true in spigot.yml. Everyone has different Ip and the loggedin message was gone <--- that's perfected.

But after one day my server got big delay VERY laggy all entity are very slow.

So I put bungeecord to false in spigot.yml.

server got no lag but loggedin message show up

### What behaviour is expected:
I want to remove login message and show user Ip

### Steps/models to reproduce:
put bungeecord to false;

### Plugin list:
This can be found by running `/pl`
authme ipwhitelist

### Environment description
]Bungeecord network, MySql, ...

### AuthMe build number:
This can be found by running `2.6.0 BETA 1`

**Comment by sgdc3** [comment]
Not an authme related issue, probably you have some plugins in spigot spamming plugin messages to bungeecord.
