### ISSUE TITLE
authme ignore ip limit permission

### ISSUE THREAD

**Issue by comonier** [AuthMe/AuthMeReloaded#1838]
Hello, @sgdc3, @ljacqu, I would like to know if there is a Permission setting for the following problem:

On my server I like to only free 1 account per ip. maxjoinip: 1 maxloginip: 1

So I have a problem with 1 family who wants to play together ... lives in the same house and has the same ip. I do not want to release for everyone just for them to log in with the same ip, is there any way I can add a permission to bypass this ip check directly on pex? in the player account? example: authme.ignoreip?

authme.allowmultipleaccounts ( to register )
need somethig permit bypass like antibot
authme.bypassantibot – Permission node to bypass AntiBot protection.
maybe a :

**authme.bypass.maxjoinperip
authme.bypass.maxloginperip**

        # Maximum Login authorized by IP
        maxLoginPerIp: 1
        # Maximum Join authorized by IP
        maxJoinPerIp: 1

**Comment by comonier** [comment]
If I have not been very expressive about what I wish, let me explain, I want to release via permission for certain players to be able to log in, even if there is someone already connected to the server using the same ip. it is possible ? Once the server is configured to only free 1 account per ip?

**Comment by ljacqu** [comment]
Hi, I just checked and I think the permission `authme.allowmultipleaccounts` should take care of this.

**Comment by comonier** [comment]
well 

I have 3 cases of families here in this situation, do I need to add the permission on all the correct accounts? only 1 succeeded the other 2 still can not

**Comment by comonier** [comment]
i ask to both persons do a test: cause it works for a couple names: 
Helton and Milly, - Milly i was looged first so i give permission for Helton... he do login
But Milly after some time disconnect, when she back cant do login [same ip] 
So i ask for Helton do logout, Milly do login first, and Helton do login after and it works.
(see i give permission to both ones)
But it this strategy do not work for other family.
Mika is mother if Gabrielle, i give permission for both, and doesnt matter who do login first of after they cant do login (same ip)

**Comment by comonier** [comment]
Oh i added the permissoin on the group names my bad its working now.

**Comment by ljacqu** [comment]
Glad it ended up working :) Thanks for the feedback~
