### ISSUE TITLE
AuthenticationException: The client has sent too many requests within a certain amount of time

### ISSUE THREAD

**Issue by Acult** [AuthMe/AuthMeReloaded#1850]
### Error Log:
https://pastebin.com/ximKjCTW

### Environment description
Server runs Thermos 1.7.10
Mods: Lotr mod v34.3

### AuthMe build number:
AuthMe Version: 3.4

**Comment by krusic22** [comment]
Nothing to do with us.
Mojang has rate limits for auth.

**Comment by Acult** [comment]
Is there any way to fix the issue?

**Comment by krusic22** [comment]
Make sure that all plugins that use the Mojang API are using some type of proxy or global caching.

**Comment by ljacqu** [comment]
Just to mention that this seems to come from something called LOTRMod
