### ISSUE TITLE
purgebannedplayers doesn't work

### ISSUE THREAD

**Issue by Iwitrag** [AuthMe/AuthMeReloaded#1851]
One of my players got autobanned because he wrote his password wrong. I know that he is the owner of account, so I wanted to remove authme autoban... I've used /authme purgebannedplayers but it did nothing. Player was still unable to login.

Plugins (23): LuckPerms, WorldEdit, SkinsRestorer, PlaceholderAPI, DeluxeMenus, WorldBorder, CommandItems, CoreGenerator, Vault, CommandSigns, FakaHedaMinequery, BanManager, BetterAlias, Holograms, WorldGuard, ProtocolLib, CoreGameplay, Essentials, EssentialsChat, AutoMessager, EssentialsSpawn, Residence, AuthMe

MySQL, standalone server, Authme 5.6.0 snapshot build 2270, CraftBukkit version git-Spigot-d05d3c1-604c8bf (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

No error

**Comment by ljacqu** [comment]
> /authme purgebannedplayers: Purge all AuthMeReloaded data for banned players. 

The command removes the account information for players that have been banned from the server; it doesn't purge the ban status.

**Comment by Iwitrag** [comment]
Oh, okay sorry, description seemed a bit ambiguous to me.

Any way how to unblock temporary banned player? (with authme native banning system)
