### ISSUE TITLE
Feature request. Use NCP API to prevent kick on login

### ISSUE THREAD

**Issue by Nubebuster** [AuthMe/AuthMeReloaded#1853]
When someone logs into a server with authmereloaded and is in a position where they are essentially floating, Authme places them back to login. Servers with NoCheatPlus will have the issue that those players are kicked from the server for survivalfly.

Although plugin developers can use the AuthMe API for fixes, it would be nice to see an official implementation of the fix.

**The solution**
When a player logs in onto the server, AuthMe could use the ExcemptionManagerAPI from NoCheatPlus to exempt them. When they successfully log in, AuthMe can then unexempt the player.

Note: AuthMe should check if the player is already exempted on login to prevent unexempting players who shouldn't be.

**Comment by Nubebuster** [comment]
See https://github.com/AuthMe/AuthMeReloaded/pull/1854

**Comment by krusic22** [comment]
That shouldn't be an issue if the spawn point is set correctly. 
Allowing movement with radius 0 (or 1), already does the trick for servers that still want to spawn users in the air.

**Comment by Nubebuster** [comment]
My server gets a lot of players with high ping. No matter what I did, if I properly spawned them on the ground, they would glitch around. Therefore I spawn them in the air. Does setting the allow movement radius fix the floating? I doubt it. @krusic22

**Comment by krusic22** [comment]
It does, as it allows the users to move from the position join, including dropping to the floor. 
If the players aren't dropping down due to the ping, the issue should be addressed somewhere else.
But I wouldn't mind the feature being added.

**Comment by Nubebuster** [comment]
> It does, as it allows the users to move from the position join, including dropping to the floor.
> If the players aren't dropping down due to the ping, the issue should be addressed somewhere else.
> But I wouldn't mind the feature being added.

I think you're right. The problem persists (much less, but still happens) after I implemented this feature. I'll have to re-experiment with different heights for spawn.

This issue is not fully caused by AuthMe.
