### ISSUE TITLE
ForceSpawnLocOnJoin not working

### ISSUE THREAD

**Issue by Iwitrag** [AuthMe/AuthMeReloaded#1857]
### What behaviour is observed:
I have ForceSpawnLocOnJoin enabled for world called pvp (case sensitive) - but players are still teleported to last loc even in this world when logged in.

### Steps/models to reproduce:
- Quit when in world 'pvp'
- Join and log in
- You are teleported back to quit location to world 'pvp'

### Plugin list:
LuckPerms, WorldEdit, SkinsRestorer, PlaceholderAPI, DeluxeMenus, PluginManager, WorldBorder, CommandItems, Vault, CommandSigns, GreenXGen, FakaHedaMinequery, BanManager, BetterAlias, Holograms, WorldGuard, ProtocolLib, Essentials, EssentialsChat, AutoMessager, EssentialsSpawn, Residence, AuthMe, GreenCore

### Environment description
Standalone server, Mysql

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2270)

### Error Log:
No error

### Configuration:
spawnPriority: authme,essentials,cmi,multiverse,default

**Comment by Hex3l** [comment]
Hello @Iwitrag ,

Can you post the content of your config.yml ?

Thank you
