### ISSUE TITLE
NoClassDefFoundError on logout

### ISSUE THREAD

**Issue by r4nx** [AuthMe/AuthMeReloaded#1863]
### What behaviour is observed:
NoClassDefFoundError on /logout command

### What behaviour is expected:
No error expected

### Steps/models to reproduce:
Just login and then /logout

### Plugin list:
LuckPerms, Vault, ProtocolLib, AuthMe

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Spigot 1.14.3, SQLite, Windows 10

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2275)

### Error Log:
https://pastebin.com/Bi0jTWW3

### Configuration:
https://pastebin.com/qykvbY5N

**Comment by sgdc3** [comment]
seems like a protocollib issue

**Comment by r4nx** [comment]
> 
> 
> seems like a protocollib issue, which software are you using? (spigot/paper/...)

latest spigot, built with buildtools. got same issue with 1.14.2 too

**Comment by games647** [comment]
Development build of ProtocolLib is required for 1.14
