### ISSUE TITLE
When sitting on the boat (on the water), the login will fall into the water.

### ISSUE THREAD

**Issue by roy20001215** [AuthMe/AuthMeReloaded#1864]
### What behaviour is observed:
When sitting on the boat (on the water), the login will fall into the water.

### What behaviour is expected:
Fix this error

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
Plugins (17): SkinsRestorer, OreReplacerPlugin, GroupManager, PlaceholderAPI, PlugMan, RandomSpawn, CommandCooldown, commandeny, NametagEdit, Vault, ProtocolLib, Essentials, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, AuthMe, TitleManager

### Environment description
Have used BungeeCord proxy server IP

### AuthMe build number:
AuthMe-5.6.0-SNAPSHOT and AuthMe-5.6.0-beta1
Have the same problem

### Error Log:
NO

### Configuration:

[config.zip](https://github.com/AuthMe/AuthMeReloaded/files/3393244/config.zip)

**Comment by krusic22** [comment]
Also happens without AuthMe. Tested with Paper 1.14.3.

**Comment by roy20001215** [comment]
So is this a problem with Minecraft itself?

**Comment by krusic22** [comment]
From the version I tested, yes.

**Comment by roy20001215** [comment]
Ok, sorry, I thought this was a mistake of Authme because the player reacted to me because he drowned in the water.

**Comment by Hex3l** [comment]
@roy20001215 you could try to enable `teleportUnAuthedToSpawn` , it will teleport the user in the spawn location, that "should" be a safe spot, before the login ;)

Closing this since it is a minecraft related issue, thanks @krusic22 for the tests ^.^
