### ISSUE TITLE
Join / register players creates terrible LAGGS, timings!

### ISSUE THREAD

**Issue by andfont** [AuthMe/AuthMeReloaded#1865]
Versions:
AuthMe version 5.6.0-SNAPSHOT-b2230
MC Spigot 1.14.3

Problema:
when users enter, they create an incredible laggg that in previous versions did not happen. We have looked at the timings and they are terrible of the authme! example:
https://timings.spigotmc.org/?url=xagatixequ
or
https://pastebin.com/X7Y3Zpy6

### What behaviour is expected:
We do not want to laggee the server for the fact of entering and registering this in previous versions did not happen please fix the problem

### Steps/models to reproduce:
Simply enter a new user we teleport to the correct world and register in our mysql database, it produces terrible timings that lag the entire server !!! but it also happens with normal user inputs but a little less but always very slow! terrible!

### Plugin list:
This can be found by running `/pl`
10:00:48] [Server thread/INFO]: Plugins (109): HiveJumpPads, InvAbf, ParkAbf, BarAPI, objabf, Vehicles, PlugMan, ManReg, ArmasAbf, icJukeBox, AdvancedGenetics, SketchMap, BarAbf, Multiverse-Core, ProtocolLib, MVdWPlaceholderAPI, ChestRestock, ItemAbf, PermissionsEx, FeatherBoard, tumbarseabf, SimpleSit, ColoredSigns, CraftAbf, RareItemHunter, WorldRebuild, PlaceholderAPI, AntiAFKPlus, BetterChairs, CustomPlate, SuperTrails, EventoAbf, EfectoAbf, botabf, AreaAbf, dynmap, WorldEdit, OpenInv, CrackShot, BannerBoard, Votifier, PsABF, LibsDisguises, CommandReg, PocionAbf, EffectLib, CS-CoreLib, MineResetLite, Vault, RankAbf, SignCasinoBlackjack, LuckyBlock, NameTagAbf, HolographicDisplays, Marriage, SignCasinoSlots, ChestCommands, RandomTeleport, Multiverse-NetherPortals, AvenAbf, FancyRoulette, Citizens, DeathChest, GAListener, WorldEditSelectionVisualizer, ItemSlotMachine, PerWorldInventory, WorldGuard, CitizensCMD, AuctionHouse, Slimefun, MysqlEconomyBank, BungeeTabListPlus, AreaShop, Essentials, Towny, ExoticGarden, LockettePro, EssentialsGeoIP, SlimeXpansion, uSkyBlock, CrateReloaded, Sentinel, mcMMO, MiniaturePets, ArmorStandTools, ElectricSpawners, Movecraft, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, MyPet, SensibleToolbox, Magic, AuthMe, Quests, QuickSell, DeluxeChat, ProtectionLib, ShopChest, FurnitureLib, DiceFurniture, Jobs, Friends2_0, MineBackup, Backpack, ServerMinimap, mobabf, ClearLag

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by sgdc3** [comment]
Please use Paper and post proper timings v2 reports... Spigot timings are useless to find out the cause of the issue.

**Comment by andfont** [comment]
seriously? we use spigot no paper this problem sure is easy to replicate because it always happens. we do not know that system and if we can use it for spigot?

**Comment by andfont** [comment]
sincerely with this link you can clearly see the problem even if they are with spigot, we do not use paper we do not like it for many reasons that have nothing to do with this case, please look good and reply:
https://timings.spigotmc.org/?url=xagatixequ

**Comment by andfont** [comment]
I have created a test server with PAPER so you can see the timings, although it is not exactly the same but I think it can help you because it also creates lagas when people want to login, register when entering etc.
https://timings.aikar.co/?id=374c6870d94a478695dea977beaa2f27

**Comment by MineSAT** [comment]
Hola @andfont, veo que tienes el servidor petado de plugins. De verdad necesitas tantos?
Por lo visto veo que hay sobrecarga en el mundo con ciertos plugins, te los listo ya que es posible que tu problema venga de ahí:

1. Essentials (Posible problemas de configuración o necesitas actualizar la versión. Otro de los problemas es la zona donde van los jugadores con el "/warp" veo que está bien sobrecargada.)
2. Playercommands 
3. CommandReg
4. AdvancedGenetics

Por otra parte no veo nada extraño ya que el /login del authme solo carga cuando alguien está haciendo el inicio de sesión. Si usas el authme sobre una DB MYSQL o MariaDB (esta última te la recomiendo ya que está más optimizada) puedes quitar bastante LAG a la hora de registrar e iniciar sesión.

**Comment by andfont** [comment]
No es un problema de los plugins, todos funcionan perfectamente y estan bien optimizados ellos no generan el lag cuando entra una persona nueva si no el authme, lo tenemos mas que comprobado por favor no dar las culpas a otros plugisn porque se ve perfectamente que el authme genera una cantidad de tps elevadisimos como ya hemos demostrado en los reports, si usas un servidor con pocos plugins tambien pasa que el authme genera de masiado consumo cuando en anteriores versiones esto no pasaba con los mismos plugisn o incluso mas plugins por favor solucionar el problema de sincronizacion como vemos en el codigo fuente gracias

**Comment by andfont** [comment]
It is not a problem of the plugins, they all work perfectly and are well optimized they do not generate the lag when a new person enters if not the authme, we have it more than proven please do not blame other plugisn because it looks perfectly that the authme generates a very high amount of tps as we have already shown in the reports, if you use a server with few plugins it also happens that the authme generates a lot of consumption when in previous versions this did not happen with the same plug-in or even more plugins please solve the synchronization problem as we see in the source code thanks.

**Comment by games647** [comment]
Please post the configuration file (like the template says so), so that we can analyze it.

**Comment by andfont** [comment]
Config:
https://pastebin.com/sWp25utd
Commands:
https://pastebin.com/j2hAYW6A
spawns:
https://pastebin.com/NJLCfAme
