### ISSUE TITLE
how to disable salt (sha256)

### ISSUE THREAD

**Issue by arduinka55055** [AuthMe/AuthMeReloaded#1866]
Hello, i want to disable salt feature.
how to make it?
i am using sha256

**Comment by krusic22** [comment]
No. As that would make the hash more insecure.

**Comment by arduinka55055** [comment]
OK, thanks.

**Comment by khang-hoang** [comment]
how to enable salt, my salt column is always null

**Comment by ljacqu** [comment]
@khang-hoang For some of the hashes the salt is just integrated into the hash column, just like SHA256. In other words, the hashes have salts, they're just stored with the hash together.

**Comment by khang-hoang** [comment]
@ljacqu thank you for replying so quickly. I just found some piece of your example code to  integrate into my site.
