### ISSUE TITLE
Server lags whenever a player joins

### ISSUE THREAD

**Issue by DarrylSSY** [AuthMe/AuthMeReloaded#1869]
### What behaviour is observed:
Server lags and chat freezes (while TPS stays at 20) when new player joins.

### Steps/models to reproduce:
Player joining the server.

### Plugin list:
ActionAnnouncer, AsyncWorldEdit, AuthMe, BannerBoard*, Citizens, CommandButtons, CompatNoCheatPlus*, ConditionalCommands, ConsoleSpamFix, CoreProtect, CratesPlus, DeluxeChat, DeluxeCommands, DeluxeJoin, DeluxeTags*, Denizen, DiscordSRV, Essentials, EssentialsGeoIP, EssentialsSpawn, FastLogin, Horizon, Jobs, LuckPerms, LWC, mcMMO, MessageAnnouncer, MiniaturePets*, Multiverse-Core, NoCheatPlus, PlaceholderAPI*, PlugMan, ProtocolLib, React*, ServerListPlus, ShopGUIPlus, TheNewEconomy, Towny, Vault, VoteParty, Votifier, WorldBorder, WorldEdit, WorldGuard

### Environment description
Standalone server and MySql. AuthMe is running on MySql

### AuthMe build number:
2282

### Error Log:
No error is found

### Configuration:
https://pastebin.com/L5m7bjVw

### Timings:
https://timings.aikar.co/?id=fe42263dc6ac4487ac1ab626d3515f57#plugins

**Comment by ljacqu** [comment]
How many registered users do you have in the database?

**Comment by DarrylSSY** [comment]
I have about 120 registered users, and 5 players online on average every time

**Comment by DNx5** [comment]
@DarrylSSY could you send your ``commands.yml`` configuration?

**Comment by DarrylSSY** [comment]
It is the default

```

# This configuration file allows you to execute commands on various events.
# Supported placeholders in commands:
#   %p is replaced with the player name.
#   %nick is replaced with the player's nick name
#   %ip is replaced with the player's IP address
#   %country is replaced with the player's country
# 
# For example, if you want to send a welcome message to a player who just registered:
# onRegister:
#   welcome:
#     command: 'msg %p Welcome to the server!'
#     executor: CONSOLE
# 
# This will make the console execute the msg command to the player.
# Each command under an event has a name you can choose freely (e.g. 'welcome' as above),
# after which a mandatory 'command' field defines the command to run,
# and 'executor' defines who will run the command (either PLAYER or CONSOLE). Longer example:
# onLogin:
#   welcome:
#     command: 'msg %p Welcome back!'
#     executor: PLAYER
#   broadcast:
#     command: 'broadcast %p has joined, welcome back!'
#     executor: CONSOLE
# 
# You can also add delay to command. It will run after the specified ticks. Example:
# onLogin:
#   rules:
#     command: 'rules'
#     executor: PLAYER
#     delay: 200
# 
# Supported command events: onLogin, onSessionLogin, onFirstLogin, onJoin, onLogout, onRegister, onUnregister
# 
# For onLogin and onFirstLogin, you can use 'ifNumberOfAccountsLessThan' and 'ifNumberOfAccountsAtLeast'
# to specify limits to how many accounts a player can have (matched by IP) for a command to be run:
# onLogin:
#   warnOnManyAccounts:
#     command: 'say Uh oh! %p has many alt accounts!'
#     executor: CONSOLE
#     ifNumberOfAccountsAtLeast: 5
# Commands to run for players logging in whose 'last login date' was empty
onFirstLogin: {}
onJoin: {}
onLogin: {}
# These commands are called whenever a logged in player uses /logout or quits.
# The commands are not run if a player that was not logged in quits the server.
# Note: if your server crashes, these commands won't be run, so don't rely on them to undo
# 'onLogin' commands that would be dangerous for non-logged in players to have!
onLogout: {}
onRegister: {}
onSessionLogin: {}
# Commands to run whenever a player is unregistered (by himself, or by an admin)
onUnregister: {}
```

**Comment by JaroSound** [comment]
Same here any fix?

**Comment by sgdc3** [comment]
@DarrylSSY please provide longer timing reports (min 10/15 minutes)

**Comment by sgdc3** [comment]
@JaroSound please provide timings

**Comment by JaroSound** [comment]
How can i do that?

**Comment by sgdc3** [comment]
@JaroSound /timings paste

**Comment by JaroSound** [comment]
https://timings.spigotmc.org/?url=vupiwadufu

**Comment by sgdc3** [comment]
please use paper instead of spigot, spigot's timings reports are useless
