### ISSUE TITLE
AuthMe possibly crashing the server (not exactly crash)

### ISSUE THREAD

**Issue by iiLearner** [AuthMe/AuthMeReloaded#1872]
### What behaviour is observed:
Hello! I'm running a 1.13.2 survival server on paper and im having an issue where my server crashes at least once or twice daily, and i dont really know whats causing it except this report gets generated and authme is all over it.

### What behaviour is expected:
n/a

### Steps/models to reproduce:
This happens once or twice a day.

### Plugin list:
Plugins (34): AntiProxy*, AtlanticCraft*, AtlanticSpawners, AuthMe, Broadcast*, BuycraftX, ClearLag, CoreProtect, DiscordSRV, FastAsyncWorldEdit*, FastLogin*, GriefPrevention, HolographicDisplays, InvRestore2, LiteBans, LuckPerms, MineSecure*, MyHome, MySkin, NerfPhantoms, OpenInv*, PlayerSkulls*, PlugMan, ProtocolSupport, RandomTeleport, Shopkeepers, SuperbVote, SuperVanish, TAB, UberEnchant, Vault*, Votifier*, WorldBorder, WorldEdit

### Environment description
Standalone server/MySql

### AuthMe build number:
2246

### Error Log:
https://pastebin.com/aCcL6n9k

### Configuration:
https://pastebin.com/77xg6Zut

**Comment by sgdc3** [comment]
Seems like your server got stuck while processing the player teleport, it doesn't seem to be directly caused by authme.

**Comment by iiLearner** [comment]
any idea what this could be caused by?

**Comment by sgdc3** [comment]
Try updating the server jar

**Comment by iiLearner** [comment]
I have already done it and it seems like it still keeps crashing and its indeed the teleportation service of authme: https://pastebin.com/2z9XYfLt

**Comment by ljacqu** [comment]
If that stack trace is the problem then your server has an issue getting chunk information. Yes, it's AuthMe that requests to teleport a player that triggers it, but seeing the AuthMe classes so low in the stack trace kind of makes me think your server is having trouble reading world data. It still could be us misusing the Bukkit API but that has not been demonstrated here.

**Comment by iiLearner** [comment]
I'm going to try to disable the authme teleportation service and see if it still crashes, if it doesn't you'll there's something wrong with it.

**Comment by sgdc3** [comment]
Or there is something wrong with the chunk you are trying to load

**Comment by iiLearner** [comment]
It's most likely the spawn chunk, isn't it?

**Comment by RealisticMinecraftToday** [comment]
I keep getting an error saying that it closes the server because it defines it in the configs file
