### ISSUE TITLE
Permissions bug?

### ISSUE THREAD

**Issue by aescraftbr** [AuthMe/AuthMeReloaded#1891]
Hello,

I set "authme.player.unregister" to false to the players of my server, but a player sucefully unregistered even with this perm being negated.

Is the permission on the plugin set correctly? Thanks.

I'm using Luckperms for the permissions, and this is the first issue I had with permissions, but I think this is related not to LuckPerms, but AuthMe.

**Comment by ljacqu** [comment]
Can you confirm with `authme debug perm` that the player really has the permission node negated?

**Comment by aescraftbr** [comment]
I also added the legacy permission (authme.unregister false) to try and see if it was because of this.

About the debug perm:

https://i.imgur.com/gUg225e.png

The perm is negated in the default group (and the player was in the default group).

Do you think this is a bug with LuckPerms? 
Thanks.

**Comment by ljacqu** [comment]
It might be an integration issue of LuckPerms in AuthMe, I wouldn't be sure which one is at fault just yet :) Is there a way to check with LuckPerms if it thinks whether that player has the permission? We obviously do, now the question is what LuckPerms reports.

**Comment by aescraftbr** [comment]
Weird that even with the permission set to "false", the player has the permission when using the:

/lp check USER authme.player.unergister

This is a problem with luckperms.
I'll doublecheck everything with my luckperms permissions, and report to luckperm team if needed.

Thanks!
