### ISSUE TITLE
i can't use methods

### ISSUE THREAD

**Issue by andfont** [AuthMe/AuthMeReloaded#1892]
hello help please try to access through Class <?> cl = Class.forName ("fr.xephi.authme.api.v3.AuthMeApi") to the method "isRegistered" I have managed to access but does not return any value only null? what am i doing wrong?
I have also tried with:
Method m = Util.getMetodo ("fr.xephi.authme.api.v3.AuthMeApi", "isRegistered");
does the method return me but not the value?
example:
m.invoke("player");
Help please because I don't know what I am doing wrong? a small example? Thank you!

**Comment by ljacqu** [comment]
You can get the AuthMeApi from a static method on the class:
```java
 AuthMeApi authmeApi = AuthMeApi.getInstance();
```

Just need to make sure that AuthMe has been loaded beforehand. An integration example is available at https://github.com/ljacqu/AuthMe_integration_demo

**Comment by andfont** [comment]
hello we need to be able to use:
Class <?> Cl = Class.forName
<?> Constructor
.getDeclaredMethod
.invoke
etc..
We do not want the library to only use it if necessary but there is no way as explained above thanks.

**Comment by ljacqu** [comment]
The sample integration also works without AuthMe loaded on a server (I'm happy for you to prove me otherwise, but that's part of the goal of that sample integration). So there's really no need to get classes that way. Just wrap all calls to AuthMeApi in another class that keeps track whether AuthMe is around or not.

**Comment by andfont** [comment]
We are developers and we are interested in being able to do it that way to be able to update all our 100 plugins easily without having to indicate libraries please is there any way to do it that way? Thank you

**Comment by ljacqu** [comment]
This is seriously the wrong approach to do it. Create a wrapper around it. If our API should ever change (not that we plan on it, but you never know) you won't have compile issues if you do everything by reflection, it will just silently fail at runtime instead. As developers you surely understand why this is interesting to avoid.

Failing that please share an executable code block exhibiting the issue and we'll be able to trace the cause. But you're saying you're getting "null" from the method "isRegistered", which, interestingly, returns a primitive boolean :man_shrugging: So if you're getting `null` your reflection code is wrong.

**Comment by andfont** [comment]
Exactly what we don't understand, could you give us an example code to get that value? Thank you

**Comment by ljacqu** [comment]
Sample integration is here: https://github.com/ljacqu/AuthMe_integration_demo

Otherwise please share your code that returns null instead of the expected value.

**Comment by andfont** [comment]
please using reflection without importing the reflection libraries with methods, class etc.

**Comment by andfont** [comment]
it doesn't work for us using "reflection" please a simple example thanks

**Comment by ljacqu** [comment]
Since you already have code in place please share it so we can look at it. I'm not writing code from scratch for an approach I anyway don't recommend; that's bad use of time, to be honest.

**Comment by andfont** [comment]
public static Method getMetodo(String cl,String bus){
try {
Method[] fil = Class.forName(cl).getDeclaredMethods();
for (Method m : fil) {
if(m.getName().equalsIgnoreCase(bus)){
m.setAccessible(true);
return m;
//System.out.println("me:" + m.getName());
}
}
} catch (SecurityException | ClassNotFoundException e) {}
return null;
}
Method m = Util.getMetodo("fr.xephi.authme.api.v3.AuthMeApi", "isRegistered");
m.invoke(null, "nameplayer");
m.invoke("nameplayer");
it always returns us null or void and we don't understand why thanks

**Comment by ljacqu** [comment]
Thanks.

1) Can you print something in the `catch` clause? Maybe it's not finding the class. 
2) Your calls to `invoke` are wrong, the first argument needs to be the instance, then whatever arguments the method takes. Since it's not a static method you can't pass in `null`, it need to be the instance of AuthMeApi. This requires again more reflection:

```java
String authMeApiClass = "fr.xephi.authme.api.v3.AuthMeApi";
Method instanceMethod = Util.getMetodo(authMeApiClass, "getInstance");
Object apiInstance = instanceMethod.invoke(null);
if (apiInstance == null) {
  System.err.println("Could not get AuthMe API instance");
  return;
}

Method isRegisteredMethod = Util.getMetodo(authMeApiClass , "isRegistered");
Object result = isRegisteredMethod.invoke(apiInstance, "playerName");
System.out.println("Is registered: " + result);
```

**Comment by andfont** [comment]
oo perfect! We do not think with the getinstance to null xD thank you very much for the moment we use reflection for reasons of implementation of current code thanks! friend we didn't see the way xDD

**Comment by ljacqu** [comment]
Great, glad that solved your problem :) Good luck with your approach... :P
