### ISSUE TITLE
about the fake player

### ISSUE THREAD

**Issue by zmwwxa** [AuthMe/AuthMeReloaded#1894]
I wonder if there are any commands to add all fakeplayer.because i cant find the name of the fakeplayer..or how should i found the fakeplayer's name.thx

**Comment by ljacqu** [comment]
What‘s a fake player?

**Comment by zmwwxa** [comment]
> What‘s a fake player?

e.g.  mekanism‘s Digital Miner.the machine works as a real player to mine,so called it fakeplayer.the authme plugin will block the machine to mine.because it didnt login

**Comment by ljacqu** [comment]
Ah, thanks. In that case search in config.yml for "Unrestricted" and add the names there that the plugin uses. AuthMe just ignores players that are in that list

**Comment by zmwwxa** [comment]
> Ah, thanks. In that case search in config.yml for "Unrestricted" and add the names there that the plugin uses. AuthMe just ignores players that are in that list

thx for ur reply.i know this method，but i dont  know how to find the fakeplayer 's ID .May I ask what are the fakeplayer ids of these two devices, extrautils2:user and rftools:Builder Block.or can i write a code in it which can contain any fakeplayer

**Comment by zmwwxa** [comment]
or can u give me a method to find ID of  fakeplayer

> Ah, thanks. In that case search in config.yml for "Unrestricted" and add the names there that the plugin uses. AuthMe just ignores players that are in that list

or can u give me a method to find the ID of the fakeplayer,I desire want to know。

**Comment by ljacqu** [comment]
I don‘t understand. It‘s the player‘s _name_ you put in there.

**Comment by zmwwxa** [comment]
> I don‘t understand. It‘s the player‘s _name_ you put in there.

e.g. mekanism‘s Digital Miner.Its ID is [Mekanism],when i write in it ，like below:
UnrestrictedName: ['[Mekanism]']
the Digital Miner can mine. if i dont do this the Digital Miner doesn't work.
Now,i only know the name of the Digital Miner.So is there a way to let the others all be ingnored,like extrautils2:user and rftools:Builder Block.

**Comment by ljacqu** [comment]
I don‘t see how we could offer a command like that but I assume in the logs you‘d see the usernames that tried to connect unsuccessfully.

**Comment by boxchn** [comment]
see https://www.mcbbs.net/thread-1402679-1-1.html
