### ISSUE TITLE
Mysql doesnt work

### ISSUE THREAD

**Issue by omermarvel** [AuthMe/AuthMeReloaded#1895]
[AuthMe] Enabling AuthMe v5.6.0-beta1-b2226
> [00:07:43 INFO]: [AuthMe] Connection arguments loaded, Hikari ConnectionPool ready!
> [00:07:43 WARN]: [Server thread] INFO fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource - AuthMeMYSQLPool - Starting...
> [00:07:43 WARN]: [Server thread] ERROR fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Exception during pool initialization.
> [00:07:43 WARN]: java.sql.SQLException: null, message from server: "Host '152.89.245.10' is not allowed to connect to this MariaDB server"
> [00:07:43 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
> [00:07:43 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
> [00:07:43 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
> [00:07:43 WARN]: at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1116)
> [00:07:43 WARN]: at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
> [00:07:43 WARN]: at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
> [00:07:43 WARN]: at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
> [00:07:43 WARN]: at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
> [00:07:43 WARN]: at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
> [00:07:43 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [00:07:43 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> [00:07:43 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> [00:07:43 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> [00:07:43 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
> [00:07:43 WARN]: at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
> [00:07:43 WARN]: at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
> [00:07:43 WARN]: at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
> [00:07:43 WARN]: at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:163)
> [00:07:43 WARN]: at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:170)
> [00:07:43 WARN]: at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:72)
> [00:07:43 WARN]: at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:66)
> [00:07:43 WARN]: at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:47)
> [00:07:43 WARN]: at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
> [00:07:43 WARN]: at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
> [00:07:43 WARN]: at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
> [00:07:43 WARN]: at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
> [00:07:43 WARN]: at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
> [00:07:43 WARN]: at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:237)
> [00:07:43 WARN]: at fr.xephi.authme.AuthMe.initialize(AuthMe.java:212)
> [00:07:43 WARN]: at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:127)
> [00:07:43 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [00:07:43 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
> [00:07:43 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [00:07:43 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
> [00:07:43 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
> [00:07:43 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
> [00:07:43 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
> [00:07:43 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
> [00:07:43 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
> [00:07:43 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
> [00:07:43 WARN]: at java.lang.Thread.run(Thread.java:813)
> [00:07:43 WARN]: [AuthMe] Can't initialize the MySQL database: [SQLException]: null, message from server: "Host '152.89.245.10' is not allowed to connect to this MariaDB server"
> [00:07:43 WARN]: [AuthMe] Please check your database settings in the config.yml file!
> [00:07:43 WARN]: [AuthMe] Could not create data source: [SQLException]: null, message from server: "Host '152.89.245.10' is not allowed to connect to this MariaDB server"
> [00:07:43 WARN]: [AuthMe] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
> [00:07:43 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
> [00:07:43 INFO]: [AuthMe] Waiting for 0 tasks to finish
> [00:07:43 INFO]: [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!

**Comment by krusic22** [comment]
Your user/ip doesn't have permissions to connect to the SQL server.

**Comment by omermarvel** [comment]
But with the same user, my website connect to the SQL server

**Comment by ljacqu** [comment]
Your website‘s IP is probably whitelisted.

**Comment by omermarvel** [comment]
How can i add my ip to whitelist

**Comment by ljacqu** [comment]
If you‘re hosting it with someone, ask your host. Otherwise google whatever DB / DB system you have with some relevant keywords.
