### ISSUE TITLE
MySQL Error (Beginner)

### ISSUE THREAD

**Issue by samp-pinch** [AuthMe/AuthMeReloaded#1899]
### What behaviour is observed:
I'm new to Spigot/Bungee ( I started yesterday ) and Installed AuthMeBungee (latest) and AuthMe (latest) from Jenkins, I put AuthMe.jar in all servers I have and AuthMeBungee.jar to BungeeCord server, I think i configured it well but I get MySQL error in console and server shut down

### What behaviour is expected:
It to work 🗡 

### Steps/models to reproduce:
I just installed 1.9.4 Spigot and Latest BungeeCord insteance and I got only AuthMe(Bungee) plugins

### Plugin list:
Only AuthMe

### Environment description
BungeeCord + Spigot on W10

### AuthMe build number:
Latest from Jenkins

### Error Log:
https://pastebin.com/sCjhAF2x

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://hastebin.com/ulamutoqac.bash

**Comment by ljacqu** [comment]
```java
 java.sql.SQLException: Unknown system variable 'query_cache_size'
[10:46:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
```

That's a first. What MySQL version & database version are you running?

**Comment by samp-pinch** [comment]
I fixed it, my configuration was bad, ty :)
