### ISSUE TITLE
No load Plugin

### ISSUE THREAD

**Issue by diaverso** [AuthMe/AuthMeReloaded#1902]
### What behaviour is observed:
When the plugin is booting an error comes out and closes it

### What behaviour is expected:
That will work correctly

### Steps/models to reproduce:
1º Install plugin and run it
2º Access config.yml
3º modify backend: MYSQL
4º Start server

### Plugin list:
EssentialsX-2.17.1.0
EssentialsXChat-2.17.1.0
EssentialsXSpawn-2.17.1.0
LuckPerms-Bukkit-4.4.1
SkinsRestorer
Vault

### Environment description
Standalone Server 1.14.4
 phpmyadmin/MYSQL
Database photo: https://i.imgur.com/TvtYtKe.png

### AuthMe build number:
AuthMe-5.6.0-beta1

### Error Log:
https://gist.github.com/diaverso/cd9ab61a2222b6505875ab40bb4817b8

### Configuration:
https://gist.github.com/diaverso/b90581f2da7037cc930f31e782cc2f3d

**Comment by ljacqu** [comment]
Please share the error in your authme.log
(Or enable it first in config.yml if there is none)

**Comment by log4b0at** [comment]
The plugin seems doesn't recognize MySQL database, i have same issue.
3 others plugins on my server login correctly to my database.

**Comment by ljacqu** [comment]
If you want help, post the authme.log. Otherwise we‘re blind and the only thing we can do is close

**Comment by ljacqu** [comment]
Yes, please grab a newer version from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ :)
