### ISSUE TITLE
Authme - unregistered/registered - Interact world permissions.

### ISSUE THREAD

**Issue by Jhezreel708** [AuthMe/AuthMeReloaded#1905]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!
Running latest Build: Yes - Jenkins Build
### What behaviour is observed:
What happened?
I can't seem to make players interact even tho I already gave permissions to the player to interact while on the logged out group: 'registered' and 'unregistered'; 

Using: Luck perms Latest Spigot Build
Authme Config: https://pastebin.com/qj5GrLGg

Video: https://www.youtube.com/watch?v=UauoMsdhvt8&feature=youtu.be

### What behaviour is expected:
What did you expect?
As seen on the video I want my users to be able to press buttons while not logged in or press Holograms..

### Steps/models to reproduce:
The actions that cause the issue
Assign a group in the current GroupPermsCheck 'registered' and 'unregistered'; 
Set the right permissions or equal it to a builder (I tested all permissions with admin level even) but it seemed like it doesn't let me do it eitherway;.
Log in to server and try to interact with button.
### Plugin list:
This can be found by running `/pl`
AuthMe, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, Holograms*, HologramsPlaceholders*, HolographicDisplays, HolographicMenus*, LibsDisguises, LuckPerms, MapManager*, MVdWPlaceholderAPI*, MythicAnimatorStands*, MythicArtifacts, MythicMobs, PacketListenerApi*, PlaceholderAPI*, ProtocolLib, SignBoard, Vault, WorldBorder, WorldEdit, WorldEditSelectionVisualizer
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Paper Latest Build 176;
### AuthMe build number:
This can be found by running `/authme version`
v5.6.0-SNAPSHOT (build: 2304)
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
None
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/qj5GrLGg - 30 days

**Comment by Jhezreel708** [comment]
Bump! is there a fix for this?

**Comment by ljacqu** [comment]
Sorry for the laaate response—I'm not sure what plugin is managing those interact permissions that you mention but it might be worth looking into that plugin's configuration again and then to confirm with `/authme debug perm` whether players have the permissions you expect them to have when they're in the unauthenticated state.
