### ISSUE TITLE
Logging in not sending players to lobby

### ISSUE THREAD

**Issue by JasperWorld** [AuthMe/AuthMeReloaded#1908]
Plugins:
AuthMe, FastLogin and a few more that definitely do not interfiere with AuthMe. (such as skinrestorer, holographicdisplays, TAB, etc...)

Expected behaviour: 
Players would have to get sent to l1 when logging in as well, right?

Video showcasing the issue:
https://youtu.be/cnnCepnwqc4

**Comment by ljacqu** [comment]
Unavailable video and no config.yml -> no way for us to know what's going on.
