### ISSUE TITLE
teleportUnAuthedToSpawn: true

### ISSUE THREAD

**Issue by Ein-Huhn** [AuthMe/AuthMeReloaded#1917]
# Should not logged in players be teleported to the spawn?
        # After the authentication they will be teleported back to
        # their normal position.
        teleportUnAuthedToSpawn: false

If I set teleportUnAuthedToSpawn: true and I join the server I am getting teleported to the spawnpoint I set. But when I log in I won't get teleported to my last position, I get teleported to the spawnpoint

**Comment by Hex3l** [comment]
Hi @Ein-Huhn ,

in order to teleport a player back to logout position you need to set `SaveQuitLocation:  true` in your config.yml.

Let me know if this solve your issue.
Hex3l

**Comment by Ein-Huhn** [comment]
Yeah, it works!

Thx for replying and sorry for bothering you!
