### ISSUE TITLE
Email recovery doesn't work.

### ISSUE THREAD

**Issue by prefislt** [AuthMe/AuthMeReloaded#1923]
### What behaviour is observed:
What happened? "/email recovery" command doesn't work and errors.

### What behaviour is expected:
What did you expect? Get email recovery.

### Steps/models to reproduce:

1. Write /email recovery <email>
2 Get errors on console - [https://pastebin.com/wPtZBZjx](https://pastebin.com/wPtZBZjx)

### Plugin list:
[https://imgur.com/k5zOg6N](https://imgur.com/k5zOg6N)

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

Standalone server with MySQL.

### AuthMe build number:
This can be found by running `/authme version`

Build: 2314

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

[https://pastebin.com/wPtZBZjx](https://pastebin.com/wPtZBZjx)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

[https://pastebin.com/zAksKBsF](https://pastebin.com/zAksKBsF)

**Comment by ljacqu** [comment]
What Java version are you running?

**Comment by prefislt** [comment]
Java 8

**Comment by LoXR** [comment]
Had this issue and tried getting support on Discord, never got a response and was sadly ignored. So watching this issue for a fix.

**Comment by nitu2003** [comment]
Are you using OpenJDK?
It may not contain the class required.

**Comment by LoXR** [comment]
Wonder if this had ever been fixed? Will attempt to see if it has on my Network soon.

**Comment by prefislt** [comment]
**UPDATE:** Tested it again today and everything works fine.

Tested on server with Tuinity (Java 11).
