### ISSUE TITLE
MyBB integration

### ISSUE THREAD

**Issue by MrKatrioPL** [AuthMe/AuthMeReloaded#1938]
Hi!
I have question. How can I integrate the database between AuthMe and MyBB?
I want the account registration to take place on the server, but for the forum to be able to log in from the data on the server.

Thanks in advance and sorry for my english ;p

**Comment by ljacqu** [comment]
In your config.yml, set "passwordHash" to "MYBB" and make sure that you use the MySQL data source and that your table points to the same one as used in the forum.

**Comment by AfkF24** [comment]
#1258 is supposedly a thing.
