### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by Gerolfing** [AuthMe/AuthMeReloaded#1941]
I haven't changed anything exept clothing registration and then after few days opening it back in config file, now after server restart authme can't connect to MySQL database on any version... I tried even old backup from 1.12.2 that wasn't active for several month and has it's own database, still same error.

How this happened:
There's sheduled autorestart of my server at 6 am every day. After server restart there was some mysql failure, because all plugins that use it were not able to connect, so there were many errors in the log, but now if I start server log block and lwc connect to mysql without any problems and authme just can't...

https://pastebin.com/SRENZ34Q - errors in console at 1.14.4 server startup on newest version

Even old copy from 1.12.2, that has separate database and was not active all this time doesn't work
https://pastebin.com/27r3fs5c

Config https://pastebin.com/8P9Wd55G

I guess something is wrong with mysql itself, but how other plugins work with it and how something could go wrong if I haven't touched anything

**Comment by Gerolfing** [comment]
Update
In older 1.12.2 version if I change
mySQLUseSSL: true
to
mySQLUseSSL: false
everything works

but in newest I get this error:
https://pastebin.com/7jBB9h4z

**Comment by Gerolfing** [comment]
Update
I installed lastest snapshot and it works with these settings:
mySQLUseSSL: false
mySQLCheckServerCertificate: false
As I understand security can be compromised, but is this a real issue if database is on localhost and external connections are forbidden?

**Comment by sgdc3** [comment]
@Gerolfing it's not ideal but shouldn't be a huge risk
