### ISSUE TITLE
Authme 5.6.0-beta1-b2226 -> spigot 1.14.4

### ISSUE THREAD

**Issue by Ra1NuX** [AuthMe/AuthMeReloaded#1942]
When start, the server log say this: 

Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'

and then the server STOP.

Please i need help.

**Comment by ljacqu** [comment]
Please post the full log

**Comment by sgdc3** [comment]
Authme 5.6.0-beta1 doesn't support 1.14.4, please use the latest dev build

**Comment by 5GameMaker** [comment]
On reloading plugin through plugman
`
> [18:56:19] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta1-b2226
> [18:56:19] [Server thread/WARN]: [AuthMe] Could not create data source: [IllegalStateException]: zip file closed
> [18:56:19] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
> [18:56:19] [Server thread/INFO]: [AuthMe] Waiting for 0 tasks to finish
> [18:56:19] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-beta1-b2226 disabled!
`

**Comment by ljacqu** [comment]
Please post the full exception from your authme.log

**Comment by 5GameMaker** [comment]
[authme.log](https://github.com/AuthMe/AuthMeReloaded/files/3894707/authme.log)

**Comment by ljacqu** [comment]
It‘s exactly as sgdc3 said, you need to update. https://github.com/AuthMe/AuthMeReloaded/issues/1942#issuecomment-557795209
