### ISSUE TITLE
AuthMe cannot hook on latest version of LuckPerms

### ISSUE THREAD

**Issue by Rosenboum** [AuthMe/AuthMeReloaded#1945]
### What behaviour is observed:
When the server with AuthMe and LuckPerms.5.0.9 starts, AuthMe crashes with ClassNotFoundException about LuckPerms. If version of LuckPerms lower then 5 (4.4.27 for example) all works perfect

### Steps/models to reproduce:
Just try to load server with AuthMe & LuckPerms 5.0.9 (5.x)

### Environment description
Bungeecord + Spigot + MySql (MariaDB)

### AuthMe build number:
latest dev build

### Error Log:
https://pastebin.com/hazvhM1p

### Configuration:
https://pastebin.com/RDVi4YXy

**Comment by starxjys** [comment]
I have this problem tooヽ(´ー`)ﾉ
https://pastebin.com/3NXwB02A

**Comment by BrayaanPS** [comment]
I still have the same error:
https://pastebin.com/MRuQazpF
Based on what I read, authme should update its api :/
https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5

**Comment by krusic22** [comment]
As a temporary fix you can set `forceVaultHook: true`.

**Comment by ljacqu** [comment]
This was fixed a while back.
