### ISSUE TITLE
Masive TPS drop after installing AuthMe

### ISSUE THREAD

**Issue by IMKinano** [AuthMe/AuthMeReloaded#1953]
Hello im running AuthMe-5.6.0-SNAPSHOT

My server have a limit of 30 players and ive been always at 20-19 TPS with 25-29 players online, after i updated the login plugin to AuthMe in my Paper 1.14.4 server, the TPS drop started, i went from 20-19 TPS to 10-14 TPS, players and me dont notice the lag, but it literally says 14 TPS.

I have not configured nothing, i have the standar configuration after installing AuthMe

this are the logs, i dont notice nothing weird
https://pastebin.com/viB8XHHx

**Comment by sgdc3** [comment]
Please provide a timings report

**Comment by IMKinano** [comment]
i sent them to you at discord

**Comment by sgdc3** [comment]
This wasn't related to AuthMe
