### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by xxcodianxx** [AuthMe/AuthMeReloaded#1956]
### What behaviour is observed:
Server crashes because authme fails to load on startup.

### What behaviour is expected:
The server should start normally.

### Steps/models to reproduce:
Start a 1.14.4 spigot server with authme 5.6.0 beta-1

Plugin list:
SkinsRestorer, EssentialsX, EssentialsXSpawn, PermissionsEx

### Environment description
Standalone server

### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
https://pastebin.com/E8NTReZC

### Configuration:
https://pastebin.com/uMnUeB2n

**Comment by xxcodianxx** [comment]
* authme build is b2226

**Comment by ljacqu** [comment]
please grab a newer version from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

**Comment by xxcodianxx** [comment]
Thanks, b2227 seems to load on startup and no errors can be seen.

👍

**Comment by ljacqu** [comment]
That‘s great news, thank you :)
