### ISSUE TITLE
[Question] MyBB forum integration?

### ISSUE THREAD

**Issue by AfkF24** [AuthMe/AuthMeReloaded#1959]
Hey, is something like [this](https://github.com/AuthMe/AuthMeReloaded/wiki/Forum-integrations) possible to do with MyBB forums? I've looked through some threads elsewhere as well as previously opened issues, but none of them describe the procedure in detail. Thanks!

**Comment by krusic22** [comment]
#1938

**Comment by AfkF24** [comment]
Oh, didn't see that. Will be closing this one then.
