### ISSUE TITLE
crash after upgrading to new build

### ISSUE THREAD

**Issue by TheCompieter** [AuthMe/AuthMeReloaded#1969]
### What behaviour is observed:
it crashed after updating to the new build

### What behaviour is expected:
it just too start normally

### Steps/models to reproduce:
idk i just randomly happend maby running the latest build

### Plugin list:
it worked fine bofore the upgrade so no

### Environment description
Bungeecord network, SQLite

### AuthMe build number:
#2346

### Error Log:
https://pastebin.com/rHtm83qy

### Configuration:

[config.zip](https://github.com/AuthMe/AuthMeReloaded/files/3974677/config.zip)

**Comment by krusic22** [comment]
The latest build is using v5 of the LuckPerms API.
I assume you are still using LuckPerms 4.

**Comment by TheCompieter** [comment]
yes sorry for that didn't think about that i'll try with the latest lp build

**Comment by TheCompieter** [comment]
Thanks that worked.
