### ISSUE TITLE
Stopping when the server is booting

### ISSUE THREAD

**Issue by TorSkiZ** [AuthMe/AuthMeReloaded#1976]
When I start the server with the AuthMe plugin, it stops.

Plugin list:
- EssentialsX 2.17.1.0
- Horizon 1.4.6 HOTFIX#8
- PermissionsEx 1.23.4
- RifleChairs
- SkinsRestorer
- Skript
- Vault
- ViaVersion 2.2.2

I don't have any databases, except those created automatically by other plugins.

AuthMe build number: 5.6.0-beta1

Error Log: https://pastebin.com/YqgPJva7

Configuration: https://pastebin.com/KKpZcaL0

**Comment by nedogimov** [comment]
Java version?

**Comment by TorSkiZ** [comment]
Java 11

**Comment by ljacqu** [comment]
please post the full error as in your authme.log or update to the latest version via our Jenkins,  https://github.com/AuthMe/AuthMeReloaded/wiki/AuthMe-Releases-(Jenkins)

**Comment by TorSkiZ** [comment]
Now it works. Thanks!
