### ISSUE TITLE
Authme says I own 2 accounts, this is not true, I believe this is because they both registered from the same IP, how do I fix this?

### ISSUE THREAD

**Issue by EltoCode** [AuthMe/AuthMeReloaded#1977]
### What behaviour is observed:
You own 2 accounts
Account1, Account2

### What behaviour is expected:
You own 1 account
Account1

### Steps/models to reproduce:
register two seperate minecraft accounts with the same IP

### Plugin list:
AuthME
### Environment description
Spigot,MySql, ...

### AuthMe build number:
This can be found by running `/authme version` 5.6.0 SNAPSHOT

**Comment by ljacqu** [comment]
You'd have to change the IP address of one of the accounts in the database. If you're using MySQL you can do so with something like phpMyAdmin, if you have SQLite use the SqliteBrowser.

Alternatively, unregister an account and re-register from another IP address.

**Comment by EltoCode** [comment]
but what if I two accounts (say me and a family member) use the same IP address to play minecraft with two accounts? 

Is there no way to differentiate other than the IP addresss?

**Comment by ljacqu** [comment]
The feature is really just here to keep track of what accounts originated from the same computer, so no, but all restrictions that consider this property can be turned off, so it shouldn't impact your gameplay in any way :)

**Comment by EltoCode** [comment]
> The feature is really just here to keep track of what accounts originated from the same computer

but the two accounts originated from two different computers, connected to the same local network

but if it's not a security issue to have two accounts have the same IP, then it shouldn't be a problem

I was just concerned that one of the accounts could somehow impact the other account.
