### ISSUE TITLE
No more GeoLite2 databases updates since December 30, 2019 available

### ISSUE THREAD

**Issue by chmatse** [AuthMe/AuthMeReloaded#1979]
### What behaviour is observed:
[04:34:13] [Craft Scheduler Thread - 1/INFO]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[04:34:13] [Craft Scheduler Thread - 1/WARN]: [AuthMe] Could not download GeoLiteAPI database [UnknownHostException]: geolite.maxmind.com

### What behaviour is expected:
The download of the latest GEO IP databases.

### Steps/models to reproduce:
According to:
https://dev.maxmind.com/geoip/geoip2/geolite2/#Databases
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

Starting December 30, 2019, we will be requiring users of our GeoLite2 databases to register for a MaxMind account and obtain a license key in order to download GeoLite2 databases. We will continue to offer the GeoLite2 databases without charge, and with the ability to redistribute with proper attribution and in compliance with privacy regulations. In addition, we are introducing a new end-user license agreement to govern your use of the GeoLite2 databases. Previously, GeoLite2 databases were accessible for download to the public on our developer website and were licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.

Starting December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL. See the section below for steps on how to migrate to the new download mechanism.

### AuthMe build number:
https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.6.0-SNAPSHOT.jar

**Comment by MaximeMichaud** [comment]
I agree.
Need to fix or find an alternative.

**Comment by ljacqu** [comment]
Thanks for the bump. You‘re right. They now require a signup and that a key be sent along with the download... As a quick fix we could sign up and just provide the same key for all AuthMe users, until MaxMind shuts us down – a quick search showed that other projects just store the databases elsewhere and download from there. We need to discuss this internally and will fix it then.

**Comment by FabioZumbi12** [comment]
Essentials is using that keys and maded a wiki to help users to get a key and use it, may help you all: https://essentialsx.cf/wiki/GeoIP.html

(i already created a key on maxmind site and its working fine on essentials)

**Comment by bonjourkemal** [comment]
I using CMI instead of Essentials. What should I do? It is absurd to be independent of Essentials.

**Comment by FabioZumbi12** [comment]
Essentials just made the tutorial on how to create the key with maxmind, you can use this tutorial for any plugins (or products) using maxmind geoip.

**Comment by TheSimArchitect** [comment]
Where do we place our license key on authme? I can't find a line on config.yml as suggested on the post that sent me here. Thanks
