### ISSUE TITLE
Authme stop server

### ISSUE THREAD

**Issue by Leodragon08** [AuthMe/AuthMeReloaded#1986]
### What behaviour is observed:
What happened? Authentic stops the server before booting.

### What behaviour is expected:
What did you expect?It should work properly

### Steps/models to reproduce:
Steps / models to reproduce: Install the latest version of Authme and restart the server I think ..

### Plugin list: It is necessary? 
I can't see the plugin list because Authme stop the server

### Environment description
A Spigot Server

### AuthMe build number:
5.6.0

### Error Log:
https://pastebin.com/VHdMg4Q9

### Configuration:
https://pastebin.com/VTL9hF8Q

**Comment by ljacqu** [comment]
This is due to a LuckPerms upgrade, which our newer builds support. Please grab a newer version from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ :)
