### ISSUE TITLE
 count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Escanor2019** [AuthMe/AuthMeReloaded#1989]
i am using authme converter sqlitetosql and look this error
![image](https://user-images.githubusercontent.com/47899748/72668239-922da800-3a03-11ea-86de-a82676030308.png)

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 's950_authme',
string 'authme',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `authme`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 's950_authme',
string 'authme',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `authme`',
NULL,
NULL,
)

**Comment by ljacqu** [comment]
Try upgrading your phpMyAdmin version. Looks like you're running PHP 7 and there was this bug in earlier versions—cf. https://stackoverflow.com/questions/48001569/phpmyadmin-count-parameter-must-be-an-array-or-an-object-that-implements-co

In any case not related to AuthMe :)
