### ISSUE TITLE
Could not download GeoLiteAPI database

### ISSUE THREAD

**Issue by Vejksu42** [AuthMe/AuthMeReloaded#2012]
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2375)
Server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

https://pastebin.com/A8X0mRJB
https://pastebin.com/ZpPJp3Ck

**Comment by ljacqu** [comment]
Please update to the latest version from Jenkins and then once it ran, you‘ll see two new user/key settings you‘ll need to fill in. There‘s a link above the config with a tutorial

**Comment by Vejksu42** [comment]
Error with MaxMind has fixed, but i got the same error in console (logs https://pastebin.com/ZpPJp3Ck)

**Comment by Vejksu42** [comment]
Thanks.
