### ISSUE TITLE
An exceptionCaught() event was fired, and it reached at the tail of the pipeline.

### ISSUE THREAD

**Issue by Vejksu42** [AuthMe/AuthMeReloaded#2013]
When I join the server, I've been kicked with reason on the picture. I tried to start server with 1 plugin, but I got the same result.

Console logs: https://pastebin.com/ZpPJp3Ck
Server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

![1](https://user-images.githubusercontent.com/44622590/74194803-0f4ae680-4c6b-11ea-8340-0f1131d0dfb9.jpg)

**Comment by sgdc3** [comment]
does the issue happen without authme installed?

**Comment by ljacqu** [comment]
Are you using Java 11? Apparently that can be an issue: https://askubuntu.com/questions/789918/unable-to-access-address-of-buffer-minecraft-1-10

**Comment by Vejksu42** [comment]
> 
> 
> does the issue happen without authme installed?

Yes.

**Comment by Vejksu42** [comment]
> 
> 
> does the issue happen without authme installed?

Yes, i'm using java 11. Thanks for the helpful link, it helped me solve my issue. owo
