### ISSUE TITLE
No spaces at nickname

### ISSUE THREAD

**Issue by renkor92** [AuthMe/AuthMeReloaded#2019]
Hello all,

I'd like to configure authme in order to permit all characters (spaces included) at player's nicknames.
But I do not know how.This is the specifyc part:
        # Regex pattern of allowed characters in the player name.
        allowedNicknameCharacters: '[a-zA-Z0-9_]*

**Comment by krusic22** [comment]
`[a-zA-Z0-9_ ]*`

**Comment by renkor92** [comment]
> `[a-zA-Z0-9_ ]*`

Hello,

I wrote an example--> /authme register nick name password and it does not work

**Comment by krusic22** [comment]
That would be due to how we handle arguments in commands.
Not 100% sure, but 'nick name' or "nick name" might work.
Otherwise the user has to join normally.

**Comment by renkor92** [comment]
> That would be due to how we handle arguments in commands.
> Not 100% sure, but 'nick name' or "nick name" might work.
> Otherwise the user has to join normally.

Hello,

I tried both ways. Can a player with spaces at nickname register with authme?

**Comment by krusic22** [comment]
If you change the regex, yes. But that will break other plugins.

**Comment by renkor92** [comment]
> If you change the regex, yes. But that will break other plugins.

Do you mean adding a space, like this?: [a-zA-Z0-9_ ]*

**Comment by krusic22** [comment]
Yes.

**Comment by renkor92** [comment]
It worked, thanks all
