### ISSUE TITLE
Unable to connect to MySQL

### ISSUE THREAD

**Issue by TheMixaDev** [AuthMe/AuthMeReloaded#2020]
MySQL Config part: https://pastebin.com/8RhbXSxh , everything else in confing file is default
Console output: https://pastebin.com/tScGwbnq

My MySQL DB alive for years and properly working with connections via MySQL Workbench, PHP, .NET and J connectors.

Server: Spigot-1.8-R0.1-SNAPSHOT-latest.jar

AuthMe: 5.5.0

**Comment by MrMatttw** [comment]
The same issue!
AuthMeReloaded version: 5.6.0
MySQL version: 8.0.17

**Comment by MrMatttw** [comment]
Found the issue!
set the config.yml file the line for mySQLUseSSL as false:

**Comment by TheMixaDev** [comment]
Already

**Comment by games647** [comment]
Duplicate of #1779
