### ISSUE TITLE
[AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!

### ISSUE THREAD

**Issue by KingsRequin** [AuthMe/AuthMeReloaded#2031]
When I install authme I cannot start my server because it displays: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
I luckperms to install, I saw that it could be the cause. But I don't know enough to solve it, does anyone have a solution ?

Here is the list of plugins I have (without authme because otherwise my server does not work):

Paper on Bukkit 1.12.2-R0.1-SNAPSHOT: 
PlaceholderAPI 2.10.4; 
PerWorldPlugins 1.2.4; 
PluginLoader 1.2; 
ChatCensor 1.9; 
NpcActions 1.0; 
SkinsRestorer 13.7.5; 
OldCombatMechanics 1.7.4; 
AM 1.0; 
VoidTP 1.4; 
LuckPerms 5.0.72; 
LapisLogin 1.1.4; 
ProtocolLib 4.5.0; 
NightVision 2.0; 
FastAsyncWorldEdit 19.11.13-5505943-1282-22.3.5; 
PixelPrinter 1.0.46; 
HubThat 8.2; 
VoidGenerator 1.4.2; 
CraftDisplay 5.3.0; 
HideNSeekReloaded 1.0; 
TnT 1.0; V
ault 1.7.2-b107; 
xInventories 2.5; 
Buttontp 1.2.3; 
SuperiorSkyblock2 1 Pre-3; 
FastAsyncVoxelSniper 19.11.13-5505943-1282-22.3.5; 
Matrix 4.3.2; 
EpicRename 3.6.2; 
EpicHeads 3.0.14; 
VoxelSniper 5.172.0-SNAPSHOT; 
GUIPlus 1.39; 
WorldEdit 6.1.7,dd00bb1; MysqlPlayerDataBridge 3.29.5; 
Essentials 2.17.1.0; 
PlotMe 0.16.3; 
Citizens 2.0.22-SNAPSHOT (build 1487); 
EssentialsChat 2.17.1.0; 
PlotMe-DefaultGenerator 0.16.1; 
BuildBattle 4.2.0;
 WorldGuard 6.2.2-SNAPSHOT,8eeab68; 
EssentialsXMPP 2.17.1.0; 
EssentialsProtect 2.17.1.0; 
EssentialsGeoIP 2.17.1.0; 
EssentialsAntiBuild 2.17.1.0; 
CitizenHats 1.35; 
EssentialsSpawn 2.17.1.0; 
RandomCoords 0.6.2-RELEASE; 
MMOItems 4.7.3; 
EpicSpawners 6.0.2; 
SilkSpawners 6.0.0-SNAPSHOT-b${BUILD_NUMBER}; 
Multiverse-Core 2.5.0-b727; 
MMOItemsAnyItemUpdater 1.1; 
DiscordSRV 1.18.4; 
MMOItemsPerWorldDrops 1.1; 
Multiverse-Portals 2.5.0-b751; 
VarLight 1.8.3; 
MMOItemsMana 1.0; 
ArmorStandTools 2.4.3; 
HolographicDisplays 2.2.6; 
CMI 8.6.19.6; 
MythicMobs 4.7.2-FREE; 
StaffPlus 3.3.1.0; 
ShopGUIPlus 1.19.7; 
BeautyQuests 0.16.1; 
BedwarsRel 1.3.6

The server is in 1.12.2.

I don't know if any information is missing, if so I would give it
Thank you Best regards.

**Comment by ljacqu** [comment]
Please share the full error from the log

**Comment by KingsRequin** [comment]
> Veuillez partager l'erreur complète du journal

[11:21:23]: [WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException] Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@2d8a3b5a
[11:21:23]: [WARN] [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!

**Comment by krusic22** [comment]
Update AuthMe, get the latest build from the build CI.
