### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tomi010817** [AuthMe/AuthMeReloaded#2037]
On AuthMeReloaded v5.4.0 there was a node called "_removePassword_" that if you put "false" you could see the passwords on the console. Now I don't see or find that node anymore on any of the newer versions or dev builds.
What happened with that node? Why isn't there anymore? Could it be there again?

**Comment by games647** [comment]
Admins should never be able to see the passwords of their users. People tend to use the same passwords on multiple services.

**Comment by Tomi010817** [comment]
Then, back in the older versions, why was it there that option?

**Comment by games647** [comment]
Looks like the feature was introduced in the first commit of this repository (or even before). It's hard to tell, because it's such a long time ago. It could be for compatibility reasons, different level of knowledge or something else.
