### ISSUE TITLE
User enter with his real name

### ISSUE THREAD

**Issue by andfont** [AuthMe/AuthMeReloaded#2046]
Problem:
A user enters for example as: maxibon
but then you can enter with the same user with a different name! for example: MaxiBon and the authme accepts it as the same account! creating two different accounts on the server !.
Please I need that each user can only enter with their REAL name! It is a great BUG!

Server version: paper-1.14.4
AuthMe version 5.6.0-SNAPSHOT-b2230

**Comment by ljacqu** [comment]
Do you have the following in your config?
```yml
    preventOtherCase: true
```

or is it set to false for some reason?

**Comment by andfont** [comment]
now it works! but this option is very important! please! it must always be activated! because if they don't hack your server the way they want! :( fixed but please let it come in the activated settings, I have also had to find another plugin for this problem but thanks for everything.
