### ISSUE TITLE
AuthMe Failed To connect to sql and stopped the server

### ISSUE THREAD

**Issue by ChokunPlayZ** [AuthMe/AuthMeReloaded#2048]
### What behaviour is observed:
I finished my authenticate server then I start the server and it stopped itself 

### What behaviour is expected:
Server Start and create new table in MySql

### Steps/models to reproduce:
The sql client is outdated

### Plugin list:
ClickWarp , WorldEdit , Essentials , EssentialsProtect , EssentialsChat , EssentialsGeoIP , GroupManager , EssentialsAntiBuild , ViaVersion , EssentialsSpawn , Multiverse-Core , ProtocolLib , WorldGuard , EssentialsXMPP

### Environment description
MySql and Bungeecord

### AuthMe build number:
5.4.0 and 5.6.0 Beta Problem Have With Both Version

### Error Log:
https://pastebin.com/MGWGvryG

### Configuration:
https://pastebin.com/QRQ4AeTa

**Comment by ChokunPlayZ** [comment]
I put Wrong Log File In the Main Post
This is the new one
https://pastebin.com/R5NJRk7g

**Comment by games647** [comment]
Do you verified that the MySQL is reachable on that port and the username and password combination is correct. You could try to connect to the MySQL server using the shell `mysql -u USER -p`

**Comment by ChokunPlayZ** [comment]
it fixed I move to Xampp Base MySql Server and it works fine
