### ISSUE TITLE
Command /changepassword not working on version 1.15.2 on Spigot

### ISSUE THREAD

**Issue by tomaskremel** [AuthMe/AuthMeReloaded#2050]
Hello, when you activate account by activation command, you cannot change password. It only works when you type command directly into console and change as admin users password.

AuthMe-5.5.0-SNAPSHOT
Spigot 1.15.2
Using MySQL database

**Comment by ljacqu** [comment]
> you cannot change password

Why not? What happens?

**Comment by tomaskremel** [comment]
Hi, it was problem with confirming password. I didnt know, that i need to type same command after i verify change. So it seems that it works :)
