### ISSUE TITLE
No /register an /login messages

### ISSUE THREAD

**Issue by Long-as-Python** [AuthMe/AuthMeReloaded#2051]
Hello I'm running 1.7.10 minecraft server
and i have problem with /register password password messages and /login password
so
i'm running bukkit server with AuthMe-5.2-legacy on board
here is my config an messages files
[config.txt](https://github.com/AuthMe/AuthMeReloaded/files/4361300/config.txt)
[messages_ru.txt](https://github.com/AuthMe/AuthMeReloaded/files/4361301/messages_ru.txt)
in logs i found this:
[WARN] Error getting message with key 'accounts_owned_self'. Please update your config file 'messages_ru.yml' (or run /authme messages)
when i ran this command i got this:
could not update messages: special characters are not allowed
help me please
sorry for english

**Comment by Long-as-Python** [comment]
i put a star to your project
so help me))))

**Comment by DNx5** [comment]
You need to save the file using UTF-8 encoding.

**Comment by Long-as-Python** [comment]
ok I will try

**Comment by Long-as-Python** [comment]
ok I changed encoding to UTF-8 but messages does not appear anyway

**Comment by Long-as-Python** [comment]
I found the problem
I updated permissionsEX and it worked
