### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Darko266** [AuthMe/AuthMeReloaded#2053]
I know this is not an issue but how do i upgrade from Authme 5.5.0 b2102 to the latest version ?
Is there something i should know ?
How do i transfer my OLD database to the new ?

Thanks

**Comment by ljacqu** [comment]
We keep all breaking changes in https://github.com/AuthMe/AuthMeReloaded/wiki/Breaking-Changes
Your version is not so old, it should work out fine :) Whenever you upgrade make sure to keep a backup of your database and the config.yml
