### ISSUE TITLE
LoginSecurity convertion is not working.

### ISSUE THREAD

**Issue by ImHumbug** [AuthMe/AuthMeReloaded#2059]
when I run /authme converter loginsecurity there are no errors in console, in fact it says that accounts are converted succesfully. When any user try to log in it says incorrect password to all of them. Authme was installed fresh and any user tried to register before the convertion to login security. I'm using last dev build.

**Comment by Kesims** [comment]
Hey, I have same issue! Did you solve it somehow? Thanks.

**Comment by sgdc3** [comment]
@ImHumbug
