### ISSUE TITLE
Unable to send mail after AuthMe settings, prompting email to the following server failed

### ISSUE THREAD

**Issue by mannyseete** [AuthMe/AuthMeReloaded#2060]
### What behaviour is observed:
What happened? Sending the email to the following server failed

### What behaviour is expected:
What did you expect? It should send email

### Steps/models to reproduce:
Correct Email and Password
change mailPort to 25, 465, 587
useTls true and false

### Plugin list:
Plugins (7): AdvancedBan*, AuthMe, NoCheatPlus*, SkinsRestorer, WorldBorder, WorldEdit, WorldGuard

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone server, SQLite

### AuthMe build number:
This can be found by running `/authme version`
Version: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2385)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
https://pastebin.com/qVYNw2rM

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/N6Pdch6x

**Comment by mannyseete** [comment]
![image](https://user-images.githubusercontent.com/25744238/78379158-8a45d300-7604-11ea-812c-21586722f243.png)

**Comment by ljacqu** [comment]
> Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m53sm6953312qta.15 - gsmtp

This is clearly something with Gmail that it still doesn't like. This might help here, https://support.google.com/mail/thread/15048240?hl=en, though as I read through it the summary really seems to be "make sure 'allow less secure apps' is on, maybe save it again". As long as it's not just AuthMe having issues we can't really do much more than that on our end
