### ISSUE TITLE
Players password suddenly not working

### ISSUE THREAD

**Issue by LoXR** [AuthMe/AuthMeReloaded#2063]
### What behaviour is observed:
What happened? 
Passwords of players are suddenly not working after many months.

### What behaviour is expected:
What did you expect? For them to have no issues of logging in, as they can do it for many months until its randomly chosen for them to not work.

### Steps/models to reproduce:
The actions that cause the issue 
None.

### Plugin list:
This can be found by running `/pl`
Plugins (26): ajParkour, AuthMe, ChatManager, ChestCommands, Citizens, CommandNPC*, CookieClicker, EnjinMinecraftPlugin, EZLinks*, eZProtector, FastLogin, ForceField*, GroupManager*, HolographicDisplays, icJukeBox, IPWhitelist*, JoinSocialLinks*, NametagEdit*, NoCheatPlus, PlaceholderAPI, PremiumHub, ProtocolLib, ServerSelectorX*, SignBoard, SkinsRestorer, Vault

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord, hooked up to MySQL to sync between two hubs.

### AuthMe build number:
This can be found by running `/authme version`
Version: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2388)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
No errors.

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://mcpaste.io/14d81653061bcd41

**Comment by ljacqu** [comment]
Is it only one player, and you haven't changed anything in the config.yml? Because if that's a no on both counts it's probably a user error, especially if it only affects on person. (User error meaning the player remembers his password wrongly, the player has accidentally reset his password, or an admin has done so)

**Comment by LoXR** [comment]
Im honestly thinking its player issues. Havent had many reports of "forgetting" passwords. So will close this due to it being their own fault on not remembering their own passwords.
