### ISSUE TITLE
IP logging feature

### ISSUE THREAD

**Issue by Homosanians** [AuthMe/AuthMeReloaded#2064]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to check player's IP history for different reasons. The main reason is account steal. In order to check this you need to look for all logins in the minecraft logs. Minecraft server logs are large and decentralized, it is inconvenient to look at them to search for a specific person. AuthMe logs contain only information about the fact of authorization without specifying the IP. It would be convenient if IP will be written to the log whenever player logs in. It won't take up much disk space, but will improve usability for server administrators.

**Describe the solution you'd like**
Log player's IP on log in. Example:
`[02-08 13:01:46]: [FINE] Homosanians logged in 127.0.0.1!`

**Describe alternatives you've considered**
Merging and filtering minecraft server's log.

**Additional context**
When a user registers, this entry records to the log file.
`[08-06 00:34:58]: [FINE] Homosanians registered 127.0.0.1`
At the login, the IP is not being recorded, so this can be regarded as missing functionality.

**Comment by mastermc05** [comment]
but there are a lot of ways to view ip of player ,
/authme getip <nickname>
result:
Database: last IP: 37.**.***.80, registration IP: 37.**.**.230 (thats me who hide the ip , authme shows all ips completly)
/authme lastlogin <nickname>
result:
[AuthMe] %nickname% last login: Thu Apr 30 12:43:42 EEST 2020
[AuthMe] The player %nickname% last logged in 11 days 5 hours 0 mins 54 secs ago
[AuthMe] Last player's IP: 37.**.***.80
/authme recent
result:
[AuthMe] Recently logged in players
- %nickname% (12:43 PM, 30 april. with IP 37.**.***.80)

and if that isn't what you want you can just open the logs with a code editor like visual studio code and with ctrl+f to fiind all lines in log that are relative with his nickname , on login you may fiind his ip

and if all what i said isn't enought i can give you a skript that will store all ips of a player , date and exact hour of login with that ip and will show them all on a command but this feature isn't necesary in authme , features that already exist are enought
(sorry if i made mistakes)

**Comment by Homosanians** [comment]
Well, yes, but AuthMe has its own logging. Why not to make a function to log an IP next to the player’s name? It would be much easier then combining all the server logs.

I can agree, that the history command here will be a redundant. To make it, you would have to create a db for all the actions of the plugin of all players. The second feature requires minimal effort to increase usability.

If you want to share this skript, it would be really great. Thanks in advance. If you want to talk about your skript, but don't want to offtop this issue, contact me via contact.emelyanov@gmail.com or create a repo with it. It would be even better.

**Comment by mastermc05** [comment]
i'll make it,now i have other doings ,but in saturday or sunday i'll post it here

**Comment by mastermc05** [comment]
try [this](https://doc-0c-98-docs.googleusercontent.com/docs/securesc/i8kanlg8bvo015c6hi1ccjuhvr8qovta/ihaq00ir6r0aitaj625kibb5ourijq1e/1589650350000/10002213716923795141/10002213716923795141/1BP7Cj22bXlsfuajBJDVu4IohwRoDS--2?e=download&authuser=0&nonce=0g4hejjfnhlsm&user=10002213716923795141&hash=vg16a8vegb2bbmtgdj15vapkdkeiunf9) or [this](https://drive.google.com/file/d/1BP7Cj22bXlsfuajBJDVu4IohwRoDS--2/view?usp=sharing)
This skript requires Skript and skUtilities
If someone have spam on join take the permission 'skUtilities.error' from that player
This skript add a database for ip on join and command /iphistory %player% [%page%]  to see ips from this database,in default, auto purge will delete the data if it is older than 10 days (configurable) , other configuration you can fiind in this skript
Are you pleased?
If you have questions you contact me on discord (masterbp05#2004) or my email (masmc05@gmail.com)

**Comment by mastermc05** [comment]
i'm bot very sure if it will work on linux,tell me if there will be a problem

**Comment by mastermc05** [comment]
it's a beta version , soon i'll give you a more stable version , if you saw bugs or you know some improvements tell me

**Comment by sgdc3** [comment]
Merged :)
