### ISSUE TITLE
TimeStamp

### ISSUE THREAD

**Issue by fafciox** [AuthMe/AuthMeReloaded#2069]
Hello, I have a problem connecting mybb forum login and server. When I add tables to the database I saw the plugin generates 13 numbers in timestamp. In mybb there are only 10 which doesn't help in synchronizing functions between forum and server. How can I solve this?

**Comment by games647** [comment]
AuthMe uses the current time in milliseconds and MYBB could use the standard Unix timestamps which only uses seconds. So dividing by one thousand will get you there.

**Comment by fafciox** [comment]
Thanks :)
