### ISSUE TITLE
LuckyPerms v5 Crash

### ISSUE THREAD

**Issue by Vizis** [AuthMe/AuthMeReloaded#2073]
What happened?
Authme Crash after adding luckyperms v5 (new dev api)
### What behaviour is expected:
What did you expect?
Not Crashing?
### Steps/models to reproduce:
The actions that cause the issue
Any Authme version (checked on 5.6 - 5.4)
Add any luckyperms v5
### Plugin list:
This can be found by running `/pl`
Authme Reloaded 5.6
Luckyperms  5.x.x.x
### Environment description
Standalone server, authme connected to mysql

### AuthMe build number:
This can be found by running `/authme version`
5.6
### Error Log:
[AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@

I can confirm that authme works perfect with LP v4 that is 4.4.1, but with any version of v5 e.i. 5.x.x.x crashing server

**Comment by ljacqu** [comment]
Works with newer versions of AuthMe, which you can get from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/ :)
