### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by Southum** [AuthMe/AuthMeReloaded#2083]
### What behaviour is observed:
Today i've switched to database register and login. But when a user registers, it says that he succesfully registered then an error (https://prnt.sc/s5o58z). But he can login to the server.

### What behaviour is expected:
To succesfully register the use

### Steps/models to reproduce:
-

### Plugin list:
None, just authme and essentials

### Environment description
Standalone server, MySql

### AuthMe build number:
2388

### Error Log:
None

### Configuration:
https://hastebin.com/fepokiquwi.bash

**Comment by ljacqu** [comment]
There should be errors in the server log if this happens; please post them
