### ISSUE TITLE
[AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION! HELP

### ISSUE THREAD

**Issue by andrei1733** [AuthMe/AuthMeReloaded#2085]
AuthMe my server crashes on startup with this error - 
> [02:51:22 WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke method 'setup' for fr.xephi.authme.permission.PermissionsManager@e37e1e7
> [02:51:22 WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!

**List of plugins**:  NoCheatPlus, LuckPerms, WorldEdit, AlwaysDay, SetSpawn, ViaVersion, WorldBorder, IPWhitelist, HolographicDisplays, bungeeSuitePortals, BungeePortals, bStats, AuthMeReloaded

**Server configuration** - Bungeecord network, SQLite

**error log** - https://pastebin.com/7mZe3Nns
**config.yml** - https://pastebin.com/v2UqJfss

Help

**Comment by Basck** [comment]
Same here!

**Comment by krusic22** [comment]
Works with newer versions of AuthMe, which you can get from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

**Comment by Basck** [comment]
> Works with newer versions of AuthMe, which you can get from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

Thanks bro! Solved!

**Comment by andrei1733** [comment]
> Works with newer versions of AuthMe, which you can get from https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

Thanks! Solved!

**Comment by devomaa** [comment]
No, It Is because you don't have MySQL, you can disable this in the config! I think it was something like:
`crash-on-no-mysql` or smth

**Comment by krusic22** [comment]
Read the error before commenting next time.
