### ISSUE TITLE
Conversion from LoginSecurity to Authme

### ISSUE THREAD

**Issue by KiroxTV** [AuthMe/AuthMeReloaded#2092]
Of course i do use the latest snapshot from discord jenkins chat
It's "successfully" show me the message that convert the users, but nobody can login
how to fix that? I do use the bungeecord (and the plugin for this), idk what's the reason

**Comment by krusic22** [comment]
You need to add BCRYPT as a legacy hash.

**Comment by KiroxTV** [comment]
BCSRYPT where? Can you help me? Im on discord KiroxTV#0755

**Comment by ljacqu** [comment]
in the config.yml search for "legacy"
