### ISSUE TITLE
Remove 2FA or make It optional

### ISSUE THREAD

**Issue by osmansalih** [AuthMe/AuthMeReloaded#2094]
Remove 2FA or make It optional. Because I have a website and I want to link It with AuthMe mysql.
If anyone join server auto register account in server website
my table name is users my rows names are  
id username password email user_type(Server Rank) country discord.

But I have a problem if register Server said Error you need to verify 2FA and I didn't have 2FA because I didn't link my email to account.
Sorry for my bad English because It's not my primary language.

**Comment by osmansalih** [comment]
website link : arabcommc.eb2a.com

**Comment by ljacqu** [comment]
When you say 2fa you mean the email confirmation? You want people to be able to do /register [pass] [email] without having to verify that email address?

**Comment by osmansalih** [comment]
yes :|
