### ISSUE TITLE
SHA256 doesn't work

### ISSUE THREAD

**Issue by epireyn** [AuthMe/AuthMeReloaded#2108]
### What behaviour is observed:
Bad conversion to SHA256 in the Mysql DB

### Steps/models to reproduce:
Use SHA256 with a shared DB between MineWeb and AuthMe
### Environment description
Standalone server, MySql, ...

### AuthMe build number:
5.6.0-beta1

### Error Log:
No errors

It works with bcrypt, so we use it now

**Comment by ljacqu** [comment]
Low effort issue with not enough details
