### ISSUE TITLE
Authme Config Problem

### ISSUE THREAD

**Issue by Appmeurtre** [AuthMe/AuthMeReloaded#2122]
I couldn't figure out where the problem is. I checked up all youtube videos, github sessions, forums etc. I'm new to this things and I am having a hard time to learn. Could somebody help me ?
I have a server that needs to open tomorrow. (and also I wasn't able to find a proper installation guide so I came here)

Pastebin config.yml: https://pastebin.pl/view/b6ef92c3
Pastebin console error: https://pastebin.pl/view/0ec3836a

**Comment by sgdc3** [comment]
> Caused by: java.net.ConnectException: Connection refused (Connection refused)

Looks like your db credentials are invalid
