### ISSUE TITLE
Plan compatibility

### ISSUE THREAD

**Issue by Volgeop** [AuthMe/AuthMeReloaded#2128]
### What behaviour is observed:
Error when using Plan plugin (latest build 5.1 600)
`[18:37:50 WARN]: java.sql.SQLException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support. too`

It throws this error and server shut down.... due to AuthMe problem. When adding softdepent to AuthMe or Plan it works, but maybe you could solve it somehow.... Plan normally works without AuthMe on another servers (I use different databases for them too)

### What behaviour is expected:
Load server without error.

### Steps/models to reproduce:
Install Plan and AuthMe and connect both to Mysql (don't have to be same).

### Plugin list:
It doesns't matter, just these two plugns are doing it.

### Environment description
Auth server, + bungee + Mysql

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2402)

### Error Log:
Here you are https://pastebin.com/E6J17qDA :)

### Configuration:
Probably isn't needed, if yes, I will paste it.

**Comment by sgdc3** [comment]
This is beacuse Plan adds to che classpath a newer version of mysql (https://github.com/plan-player-analytics/Plan/blob/master/Plan/build.gradle#L144)
This is due to Plan's bad design, it should relocate his mysql connector version to a different path.

**Comment by Volgeop** [comment]
ANd couldn't you add them as softdepend? @sgdc3? It could solve it... when I'm doing it manually it works.

**Comment by Volgeop** [comment]
Asked Plan devs about it and they told me that's authme issue that they don't use proper drive.  @sgdc3

**Comment by Volgeop** [comment]
Got respond:
```
Plan already relocates the mysql driver to plan.com.mysql so
They need to provide the driver class to whatever they use to create their connection
```
