### ISSUE TITLE
Show message to add email less times

### ISSUE THREAD

**Issue by JavituRec** [AuthMe/AuthMeReloaded#2129]
**Is your feature request related to a problem? Please describe.**
Hello,

users find it annoying to add email so many times after registration.

Is it possible to reduce the number of times or the time between the appearance of this message?

**Describe the solution you'd like**
Increase time between messages to add mail after registration.

**Comment by JavituRec** [comment]
Hello again, is there no way to do this? Or to stop ths feature. It's pretty annoying for the users.

**Comment by sgdc3** [comment]
Check the Email.delayRecall option
