### ISSUE TITLE
Getting error when the server startups preventing the server from functioning correctly.

### ISSUE THREAD

**Issue by itaquito** [AuthMe/AuthMeReloaded#2132]
### What behaviour is observed:
What happened?
When the server is starting up Authme throws an error.

### What behaviour is expected:
What did you expect?
No errors showing up in the console and the plugin loading correctly.

### Steps/models to reproduce:
The actions that cause the issue
Install AuthMe and start the server.

### Plugin list:
This can be found by running `/pl`
Can't do this since the server is not starting

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord with mySQL

### AuthMe build number:
This can be found by running `/authme version`
Can't do this since the server is not starting

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
https://pastebin.com/dZRXYr0p

Thanks

**Comment by krusic22** [comment]
Get the latest version of AuthMe from the build CI.
