### ISSUE TITLE
[Authme] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure (Help wanted)

### ISSUE THREAD

**Issue by firstnetwork** [AuthMe/AuthMeReloaded#2143]
## I have used iptables to allow port 3306 on the database server side.

**I have added the permission to the username used to connect to the database.**

Database Name: 'player_authentication_on_network'
_(GRANT ALL PRIVILEGES ON player_authentication_on_network.* TO '{username}'@'{host}' IDENTIFIED BY '{password}' WITH GRANT OPTION;)_

**This is information about all errors** -> https://pastebin.com/jRfTk3eH

**And here is my config** -> https://pastebin.com/s0f7ZXXU

**Comment by sgdc3** [comment]
This is 100% a networking / firewall issue, the initial connection timed out.
