### ISSUE TITLE
Authme error bug 1.16.1 chat send

### ISSUE THREAD

**Issue by Flap18** [AuthMe/AuthMeReloaded#2147]
--- What happened?

when you enter to the server and not register you can send chat, the config is send_chat: false

---- AuthMe build number:
 #2​41​1

----Error Log:
any

--- Configuration:
https://pastebin.com/RuDCb5yk

I use paper 1.16.1 latest build
I use the latest build of authme
I dont use Bungee
and its a bug for uploading 1.15.2 to 1.16

**Comment by sgdc3** [comment]
Can you replicate the issue with only authme installed?
