### ISSUE TITLE
Ultra Permissions

### ISSUE THREAD

**Issue by Ironman2M** [AuthMe/AuthMeReloaded#2149]
### What behaviour is observed:
What happened?
After typing any /authme admin command I don't have permission.
### What behaviour is expected:
What did you expect?
The command to run because I have * permission in ultrapermissions and bungeecord.
### Steps/models to reproduce:
The actions that cause the issue
Probably authme not supporting the permission plugin.
### Plugin list:
This can be found by running `/pl`
Titlemanager, skin restorer, Fastasyncworldedit, verus, plugman, easysetspawn, ultrapermissions, protocollib, worldedit, fastlogin, residence, bungeeguard, authme, litebans
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Authme server connected to bungeecord proxy, and setup with mysql
### AuthMe build number:
This can be found by running `/authme version`
2226
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
Nothing
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/raw/xKFrq3Aq

**Comment by sgdc3** [comment]
We use the standard player.hasPermission() method to evaluate command perm nodes.
Please report this issue to the UltraPermissions developers.
