### ISSUE TITLE
PurgeTask can't cancel and spams the logs

### ISSUE THREAD

**Issue by Kongolan** [AuthMe/AuthMeReloaded#2150]
### What behaviour is observed:
I'm getting a lot of spamy errors, filling the whole logs for multiple hours right now. Seems like the PurgeTask can't use cancel() properly, maybe because it never run correctly? Bukkit is suggesting that the cancel() call is illegal at least. Error logs are attached + Config. Hope for a fix soon, since this is going for 1 full day right now.

### AuthMe build number:
AuthMe v5.6.0-SNAPSHOT. Build from Commit df5fdf95958e7fc82251005d0ff22d3cf8c2b208, custom version since I patched one part. 

### Error Log:
https://pastebin.com/dbLuPL2N

### Configuration:
https://pastebin.com/gBijsFLt

**Comment by sgdc3** [comment]
@Kongolan should be fixed now, let us know :)
