### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by maraxaes** [AuthMe/AuthMeReloaded#2152]
### What occurs:
AuthMe caused the server to crash when using MySQL instead of SQLITE.

### What I did:
Just ran the server using MySQL in the `config.yml` file, there were no issues with any of the other plug-ins (that affected the running of the server or this AuthMe plug-in). I know about #1824 and since I was going to be running the database locally, I decided there wouldn't be any issue in not using SSL to connect (`mySQLUseSSL: false`), but that still didn't fix the issue.

### Plug-ins:
```
AuthMe-5.6.0-SNAPSHOT
CoreProtect-19.0
DeadChest-3.5
EssentialsX, Chat, Protect, Spawn, XMPP
GriefPrevention
LuckPerms-Bukkit-5.1.75
mcMMO
SkinsRestorer
Vault
```

### Environment
Paper standalone server, latest build

### AuthMe build number:
5.6.0 SNAPSHOT from [the jenkins build server](https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/), build number #2411

### Server Log:
https://pastebin.com/iVnnwLMh

### Configuration:
https://pastebin.com/p94TwCx2

I don't know anything about SQL and have very limited knowledge on the spigot API, any help you could provide would be appreciated!

**Comment by sgdc3** [comment]
Do you have any other plugin using the same MySql server?

**Comment by zerrium** [comment]
Yes, I have the same issue but the exception is different
[Here](https://pastebin.com/faLUmvaf) is my log
Using MySQL version 8.0.20-0ubuntu0.20.04.1
AuthMeReloaded #2416 and AuthMeBungee #162

**Comment by ConaII** [comment]
Until its done, you can use this:
    tempban:
        # Tempban a user's IP address if they enter the wrong password too many times
        enableTempban: false
        # How many times a user can attempt to login before their IP being tempbanned
        maxLoginTries: 5
        # The length of time a IP address will be tempbanned in minutes
        # Default: 480 minutes, or 8 hours
        tempbanLength: 0.1
        # How many minutes before resetting the count for failed logins by IP and username
        # Default: 480 minutes (8 hours)
        minutesBeforeCounterReset: 0.1
        # The command to execute instead of using the internal ban system, empty if disabled.
        # Available placeholders: %player%, %ip%
        customCommand: 'kick %player% (Message)'

For only kick or:
    tempban:
        # Tempban a user's IP address if they enter the wrong password too many times
        enableTempban: true
        # How many times a user can attempt to login before their IP being tempbanned
        maxLoginTries: 5
        # The length of time a IP address will be tempbanned in minutes
        # Default: 480 minutes, or 8 hours
        tempbanLength: 0.1
        # How many minutes before resetting the count for failed logins by IP and username
        # Default: 480 minutes (8 hours)
        minutesBeforeCounterReset: 0.1
        # The command to execute instead of using the internal ban system, empty if disabled.
        # Available placeholders: %player%, %ip%
        customCommand: ' '
For tempban 6seconds (You can edit the numbers)

**Comment by sgdc3** [comment]
@zerrium is the issue still happening? did you find any solution?

**Comment by zerrium** [comment]
> @zerrium is the issue still happening? did you find any solution?

I just updated to the latest build, downgrade openJDK version to 8, and still using the same MySQL server version, it works fine. It just wont work with JDK11

**Comment by maraxaes** [comment]
Sorry about that, I mixed up PostgreSQL/MySQL. My issue was that I was being a total moron lol (Works fine with my PostgreSQL database)
