### ISSUE TITLE
Data truncation: Data too long for column 'totp' at row 1

### ISSUE THREAD

**Issue by AmazedMender16** [AuthMe/AuthMeReloaded#2154]
### What behaviour is observed:
When user configures 2FA it goes through the process, then once he needs to confirm the code he gets an error to contact administrator
Checking the logs the following occurs:
https://pastebin.com/gYCqSxS5

### Environment description
We use MySQL to store all passwords

### AuthMe build number:
5.6.0 Build 2413

**Comment by sgdc3** [comment]
@AmazedMender16 Please check out the latest dev build :)

**Comment by AmazedMender16** [comment]
@sgdc3 getting the following on the latest build: https://pastebin.com/ryenQfzF

**Comment by radek203** [comment]
Now the server cannot be started
