### ISSUE TITLE
The plugin doesn't start due to an SQL exception on the build 2415 and newer

### ISSUE THREAD

**Issue by christaylor201** [AuthMe/AuthMeReloaded#2158]
### What behaviour is observed
The plugin doesn't start due to an SQL exception on the build 2415 and newer. I think it's because of the changes introduced in [this commit](https://github.com/AuthMe/AuthMeReloaded/commit/a1021f9dc38abb3674ecf54d16c5a459e43061ad).

### What behaviour is expected
The plugin should start properly.

### Steps/models to reproduce
1. Use the build 2415 and newer.
2. Check for the issue mentioned above.

### Plugin list
```
Plugins (53): ActionHealth*, AdvancedPortals, AuctionHouse, AuthMe, BetterRTP, boosCooldowns*, BossShopPro, ChatManager, ChestShop, Citizens, ColoredAnvils, CoreArena, CoreProtect, CraftBook, DiscordSRV, DisplayItem, Essentials, EssentialsChat, EssentialsSpawn, FakaHedaMinequery*, FlightPlus, GameAPI, Harbor, HeadDatabase*, HolographicDisplays, InfernalMobs, Jobs, LeaderHeadsRevamped, LimitPillagers, LiteBans, LuckPerms, Matrix, Multiverse-Core, MyWarp, NoSpawnerChange, PlaceholderAPI, PlayerHeads, PluginManager, ProtocolLib, Residence, SkinsRestorer, SlotMachine, TAB, ThirdCurrency*, TokenManager, TreeFeller, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

### Environment description
Standalone server with SQLite database.

### AuthMe build number
2415

### Error log
https://gist.github.com/christaylor201/858c40c90a41bb009353823b5eff80c6

### Configuration
https://gist.github.com/christaylor201/53d982c6374036d166010d7de328bc80

**Comment by LoXR** [comment]
Had the same issue, 2414 works fine.

**Comment by christaylor201** [comment]
Yes, I had to downgrade to this build, too.

**Comment by sgdc3** [comment]
The issue should have been fixed in the latest dev build, let me know :)

**Comment by christaylor201** [comment]
Yes, the issue has been fixed. Thank you for the quick response!

**Comment by ljacqu** [comment]
I'm  only reading fast but shouldn't the conditions for a migration be ORed together? https://github.com/AuthMe/AuthMeReloaded/blob/e291a0415b71d85693155e76658808fb069cd57a/src/main/java/fr/xephi/authme/datasource/SqLiteMigrater.java#L50

**Comment by sgdc3** [comment]
You're right @ljacqu thank you
