### ISSUE TITLE
Errors and lag

### ISSUE THREAD

**Issue by MithrandirCraft** [AuthMe/AuthMeReloaded#2160]
### What behaviour is observed:
Lag and errors.

### What behaviour is expected:
No lag, and no errors.

### Steps/models to reproduce:
Starting the server, letting players log in.

### Plugin list:
Plugins (26): 40ServidoresMC, AntiXrayHeuristics, AuthMe, BungeeTabListPlus, ClearLag, CoreProtect, CrazyCrates, DisableSuffocation, Essentials, EssentialsSpawn, FastLogin, GriefPrevention, GriefPreventionFlags, LuckPerms, NerfVillages, PlaceholderAPI, ProtocolLib, Shopkeepers, SkinsRestorer, Spartan, SSX-Connector*, Vault, ViewDistanceTweaks, VoidSpawn, Votifier, VotingPlugin

### Environment description
Waterfall + Paper.

### AuthMe build number:
5.6.0-SNAPSHOT-b2416 (didn't use any further because they where marked as unstable, but I'll try to update asap)

### Error Log:
1. https://gist.github.com/MithrandirCraft/c627454ff6a058f1c3d62a7db32633d7
2. https://gist.github.com/Mangonels/459388371e255a146c607ddd66c4fd0b

One may be irrelated to the other.

**Comment by MithrandirCraft** [comment]
Spartan dev seems to attribute this to his own plugin. So judge for yourselves if this ticket should remain open.

**Comment by niqoar** [comment]
Same here: https://pastebin.com/hnLNvFct

**Comment by MithrandirCraft** [comment]
I'll just close this ticket for you. This issue was long solved.
