### ISSUE TITLE
Server immediately closes and places an hs_err_pid.log file in the server directory when ran under screen.

### ISSUE THREAD

**Issue by xxfoofyxx** [AuthMe/AuthMeReloaded#2164]
### What behaviour is observed:
What happened? When a player leaves the server, it immediately closes and proceeds to spit out a hs_err_pid.log file in the server's directory.

### What behaviour is expected:
What did you expect? I expected the server to not close.

### Steps/models to reproduce:
The actions that cause the issue
1. A player joins
2. The player leaves, and the server crashes.

### Plugin list:
This can be found by running `/pl`
Plugins (2): AuthMe, SkinsRestorer

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Standalone server running on a Raspberry Pi 4B, 4GB ram model, Raspbian Lite 32 bit, OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1+rpi1-b01)

### AuthMe build number:
This can be found by running `/authme version`
Version: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2418)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any) https://pastebin.com/30QyszWx

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/qxbmua1h

**Comment by xxfoofyxx** [comment]
Update:
It looks like this behavior only occours when screen is used. Running it outside of screen makes the server not crash. It would really be a bummer if I had to stop using screen just because of this bug. Is there any fix to this already known?

**Comment by games647** [comment]
This appears to be bug in the SQLite driver we use. This driver is shipped with Spigot. The error is about accessing memory that the program is not allowed to do (Segmentation fault).

You could try it out with `tmux`. However it's more advanced.

**Comment by xxfoofyxx** [comment]
> This appears to be bug in the SQLite driver we use. This driver is shipped with Spigot. The error is about accessing memory that the program is not allowed to do (Segmentation fault).
> 
> You could try it out with `tmux`. However it's more advanced.

I'll try out tmux, and tell you if it worked. I'm hoping it works since I was excited for this new server to be up lol.
