### ISSUE TITLE
Provide 5.6.0 Snapshots on Bukkit

### ISSUE THREAD

**Issue by KhushrajRathod** [AuthMe/AuthMeReloaded#2197]
Hi, please provide 5.6.0 Snapshots on Bukkit. I use aternos.org and they do not allow uploading plugins

### What behaviour is observed:
5.5.0 Snapshot is available on Bukkit.
5.6.0-beta (Not functional) is available on Bukkit
5.6.0 Snapshot is **not** available on Bukkit

### What behaviour is expected:
5.6.0 Snapshot is available on Bukkit

**Comment by ljacqu** [comment]
@sgdc3 this would be a good idea since a lot of reports coming are solved when they download the latest jenkins build

**Comment by sgdc3** [comment]
#2216 duplicate
