### ISSUE TITLE
Error with Geyser Plugin while Bedrock user is not identified with AuthmeReloaded Plugin

### ISSUE THREAD

**Issue by Danifoxe** [AuthMe/AuthMeReloaded#2202]
### What behaviour is observed:
When a user in Bedrock Edition enters the server, while not identifying with AuthmeReloaded, an error is presented in the console. The error also occurs when the user logs out.

### What behaviour is expected:
Geyser or Authme should wait until AuthmeReloaded has finished identifying the user, showing no errors to the console.

### Steps/models to reproduce:
1.Bedrock user enters the server
2.AuthmeReloaded asks password to identify itself
3. The console displays the error
4. The error message is kept several times until the user is finished identifying.

### Plugin list:
Plugins (25): AuthMe, BuycraftX, CoreProtect, CourierNew, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, FastLogin, floodgate-bukkit, Geyser-Spigot, GriefPrevention, GriefPreventionFlags, GSit, LuckPerms, ProtocolLib, Quests, QuickShop, SkinsRestorer, TimeVote, Vault, Votifier, VotingPlugin, WorldEdit

### Environment description
This server is running Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

### AuthMe build number:
Version: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2424)

### Error Log:
[console.txt](https://github.com/AuthMe/AuthMeReloaded/files/5283129/console.txt)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
[console2-config.txt](https://github.com/AuthMe/AuthMeReloaded/files/5283202/console2-config.txt)

**Comment by MrIvanPlays** [comment]
Something happened with geyser, not an AuthMe issue. 
Report to geyser.

**Comment by Danifoxe** [comment]
They (Geyser) do not seek to fix errors related to you (Authme).
