### ISSUE TITLE
LoginSecurity import to Authme

### ISSUE THREAD

**Issue by DarknightHD** [AuthMe/AuthMeReloaded#2206]
is it possible to transfer from LoginSecurity to Authme with the same data? so they wont register all over again? i really wanted to switch to authme. thankyou

**Comment by ljacqu** [comment]
Yes, it's possible to do so with the /authme converter command. https://github.com/AuthMe/AuthMeReloaded/wiki/Converters

**Comment by RuskyDev** [comment]
this doesnt work anymore

**Comment by LiteSavage** [comment]
> this doesnt work anymore

It does work, I can still remember how i did it haha. It was a pain back then.
