### ISSUE TITLE
Update Spigot and Bukkit versions

### ISSUE THREAD

**Issue by ConaII** [AuthMe/AuthMeReloaded#2216]
Really good plugin, great work, i like this plugin a lot.

Can you please, please upload a updated version from the devbuils?

The 5.6.0-beta1 its broken

its been more than 1 years from last uploaded version (5.6.0-beta1)
And i am only asking one.

Just upload it like 5.6.0-beta2 or something.

Some servers doesn't allow uploading custom jars.
I know how to host a server with my pc but my internet sucks rn.

This will be useful for people, and you will have less reviews and issues from outdated versions.

Thanks.

**Comment by sgdc3** [comment]
On the way :)
