### ISSUE TITLE
HamsterAPI Support

### ISSUE THREAD

**Issue by MacacoLew** [AuthMe/AuthMeReloaded#2222]
**Is your feature request related to a problem? Please describe.**
Yes, ProtocolLib doens't work with latest netty version (Error on Join and more things)

**Describe the solution you'd like**
Adding HamsterAPI Support (Hook) like this:
config.yml -> use-hamsterapi: boolean

**Describe alternatives you've considered**
Im not good with english so, in blank

**Additional context**
None

**Comment by sgdc3** [comment]
ProtocolLib has been updated, supporting other packet manipulation libraries isn't planned atm.
Thank you for your suggestion anyway. 😃
