### ISSUE TITLE
Authme error causes restart on my server

### ISSUE THREAD

**Issue by vDjgamer** [AuthMe/AuthMeReloaded#2225]
I have this problem. What do i do to fix it

`[05:55:19] [Server thread/WARN]: [AuthMe] Aborting initialization of AuthMe: [InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'`

**Comment by sgdc3** [comment]
Please try using the latest dev-build: https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/

**Comment by HackerSte** [comment]
Hi, I had the same problem, after installing the latest build everything worked fine, but after a few hours my server crashed with a java error that I had never seen, in the very long log that java generated for me I read this piece where authme is named.
![image](https://user-images.githubusercontent.com/68558172/100157124-56c4fb00-2eaa-11eb-8a54-53ef28d64a75.png)

Do you know what happened or how to fix it? This is the message that appeared in the console.
![image](https://user-images.githubusercontent.com/68558172/100157103-4dd42980-2eaa-11eb-8179-ce3a5791274a.png)

The crash did not save anything, not even the worlds ..

**Comment by sgdc3** [comment]
@HackerSte that's a completely different issue, please open a new report.
