### ISSUE TITLE
Change register/login time limit

### ISSUE THREAD

**Issue by LavaHoleD** [AuthMe/AuthMeReloaded#2226]
Hello, so recently i've removed whitelist on my Minecraft Thermos Server (1.7.10)
and added AuthMe Reloaded (v5.3.2). Now, when you join the server you have around 30 seconds to register (new players) or login. The fact is that I want to make the time limit longer but in the config there isn't anything related about changing the time limit.
I don't know if there is a way to change it somewhere or this option doesn't exist but
1) If it exist, where I can find it? 
2) If it doesn't exist I suggest to add it in a future version of AuthMe (possibily also for 1.7)
Hope you can answer me :D
Have a good day-

**Comment by DNx5** [comment]
It's available in config at ``settings.restrictions.timeout`` node
https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md

**Comment by LavaHoleD** [comment]
> It's available in config at `settings.restrictions.timeout` node
> https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md

Ok, thank you very much!
I noticed (I wasn't sure if it was 30 secs) that it wasn't 30 seconds, instead 10!
Well, Have a good day!
