### ISSUE TITLE
Server Hard Crash

### ISSUE THREAD

**Issue by HackerSte** [AuthMe/AuthMeReloaded#2232]
Hi, after installing the latest build (5.6.0-SNAPSHOT) everything worked fine, but after a few hours my server crashed with a java error that I had never seen, in the very long log that java generated for me I read this piece where authme is named.

![image](https://user-images.githubusercontent.com/68558172/100157124-56c4fb00-2eaa-11eb-8a54-53ef28d64a75.png)

Do you know what happened or how to fix it? This is the message that appeared in the console.

![image](https://user-images.githubusercontent.com/68558172/100157103-4dd42980-2eaa-11eb-8179-ce3a5791274a.png)

The crash did not save anything, not even the worlds ..
Also, my server was unable to start after this crash.

This is the complete log file:

[hs_err_pid33.log](https://github.com/AuthMe/AuthMeReloaded/files/5593044/hs_err_pid33.log)

**Comment by sgdc3** [comment]
@HackerSte please provide server version and software name (spigot/paper/etc..)

**Comment by HackerSte** [comment]
Sure.
1.15.2 - Paper

**Comment by ljacqu** [comment]
> in the **very long log** that java generated for me I read this **piece** where authme is named

Not sure it's related to AuthMe then. Your log is a thread dump: the JVM crashes and will output what the threads were doing. Since AuthMe was running on your server, AuthMe will also appear.
