### ISSUE TITLE
Chatting without logining, soon execute commands

### ISSUE THREAD

**Issue by PerchunPak** [AuthMe/AuthMeReloaded#2242]
### What behaviour is observed:
Player can chat without logining in account

### What behaviour is expected:
This player also dm me, and he say soon he will can type commands, but not now

### Steps/models to reproduce:
I am dont know how it reproduse, all questions to Nikita_#9424

### Plugin list:
![image](https://user-images.githubusercontent.com/68118654/101679780-76dae980-3a68-11eb-814b-b5beade53b10.png)

### Environment description
Paper 1.12.2 build 1618

### AuthMe build number:
![image](https://user-images.githubusercontent.com/68118654/101679873-95d97b80-3a68-11eb-814e-f90b82fa7102.png)

### Error Log:
https://pastebin.com/8q5Xn2Xd

### Configuration:
https://pastebin.com/jMzr9Zvt

**Comment by PerchunPak** [comment]
he need 2-3 minutes for do this

**Comment by awgybop1** [comment]
Began experiencing this same issue after I switched from GroupManager to LuckPerms. No idea why this would be permission-based anyway, but it seems like that's the problem.

**Comment by PerchunPak** [comment]
no info for any possible fix

**Comment by sgdc3** [comment]
Why did you close the issue?

**Comment by awgybop1** [comment]
@sgdc3

Welp, since they never fixed it I just patched it myself, and since he closed this issue I uploaded it to Spigot
https://www.spigotmc.org/resources/authmepatch.92158/
