### ISSUE TITLE
Blindness not removed

### ISSUE THREAD

**Issue by Trudster1988** [AuthMe/AuthMeReloaded#2250]
### What behaviour is observed:
Blindness not being removed after user login/register is complete

### What behaviour is expected:
Blindness is removed and player no longer has vision issues

### Plugin list:
Plugins (32): AuthMe, BanManager*, BungeeTabListPlus, Citizens, CitizensBooks, CustomCommands, Essentials, EssentialsChat, EssentialsSpawn, GCoreLegacy, GriefPrevention, HolographicDisplays, IPortal, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, PlaceholderAPI, PluginConstructorAPI, ProtocolLib, RandomTP, ServerSelectorX, UltraBar, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard, zDiscord*

### Environment description
Bungeecord network, MySql

### AuthMe build number:
Build 2440

### Error Log:
Dont receive any errors

### Configuration:
https://pastebin.com/mzxbxxMS

**Comment by rhyswilliamsza** [comment]
Hey @Trudster1988 

What was the solution here?
