### ISSUE TITLE
/changepassword is not actually changing the PW after /verification is successful

### ISSUE THREAD

**Issue by SDpyro** [AuthMe/AuthMeReloaded#2258]
### What behaviour is observed:
/changepassword is not actually changing the PW after /verification is successful

### Steps/models to reproduce:
User Logs In, issues /register email@example.tld
"Your account isn't activated yet, please check your emails!"

receives email, issues /login PasswordFromEmail
"Successful Login!"
Then issues /changepassword OLDpasswordHere YourNewPassword

receives email, issues /verification ######
"Your identity has been verified! You can now execute all commands within the current session!"

Users Exits Server & Re-joins, then issues /login YourNewPassword
"Connection Lost Wrong Password"
User Re-joins, then issues /login TheOldOriginalPasswrodFromEmail
"Successful Login!"

### Plugin list:
AuthMe: 5.6.0-SNAPSHOT-b2440 (and about 5 previous versions)
LuckPerms-Bukkit_5.2.35

### Environment description
tested on:
  spigot-1.16.4-R0.1-b2981-a56d446-7029c0a.jar (and prev versions for a few months)
  paper-1.16.4-400.jar
MYSQL mariadb-server.x86_64 1:5.5.68-1.el7 (CentOS 7)
I also have tested with SQLITE to rule out MySQL vs MariaDB

### Error Log:
No errors on console
using luck perms "/lp verbose on UserName" produces nothing that raises any flags

### Configuration:
https://hastebin.com/amolujabiy

**Comment by Hex3l** [comment]
This is not a bug, as stated in the message that you received after the verification process:

"Your identity has been verified! You can now execute all commands within the current session!"

It means that every command issued after the verification will work properly, commands issued before are not.
