### ISSUE TITLE
Always get same IP when register or login

### ISSUE THREAD

**Issue by aldesrahim** [AuthMe/AuthMeReloaded#2260]
### What behaviour is observed:
Same IP when register or login

### What behaviour is expected:
Correct IP

### Steps/models to reproduce:
Register or Login via Minecraft

### Plugin list:
LuckPerms, SkinsRestorer, Vault, Essentials, EssentialsSpawn, GWarp, EssentialsGeoIP, EssentialsChat, dynmap, AuthMe, LWC

### Environment description
Spigot without bungee, MySql, Ubuntu, Limited IP Port

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2440)

### Configuration:
https://pastebin.com/YedimzWH

**Comment by ljacqu** [comment]
do you have ip_foward enabled in your bungee config?

**Comment by aldesrahim** [comment]
iam not using bungee, just a single spigot server

**Comment by aldesrahim** [comment]
i've checked from the console. the players are from same ip but different port, any solution ?

**Comment by Jiangdonganxia** [comment]
I also need to solve this problem

**Comment by sgdc3** [comment]
Not authme related

**Comment by MiniKLK** [comment]
> There might be some proxy on your hosting if you're using one. You need to disable ip functions on your config

Where can I disable that ip functions? Please I'm having the same problem and there's anything on Internet for help me...

**Comment by MiniKLK** [comment]
@Maks1116
