### ISSUE TITLE
Add queue connected with authme

### ISSUE THREAD

**Issue by xGrabekxpl** [AuthMe/AuthMeReloaded#2272]
hello I have a question. I have 3 servers connected (proxy, lobby and game) and want to add a queue system to the lobby.
After logging in or registering I automatically send the player to the game server, and can it be blocked, add the player to the queue, and when he is first in the queue, just connect him to the game server?

**Comment by sgdc3** [comment]
This sounds out of the scope of the plugin, sorry.
