### ISSUE TITLE
op permissions are lost when register and login

### ISSUE THREAD

**Issue by poly000** [AuthMe/AuthMeReloaded#2278]
Looked wiki, I hope I could restore my op permission after regiteration... if possile

**Comment by poly000** [comment]
Looked wiki, I hope I could restore my op permission after regiteration... if possile

**Comment by ljacqu** [comment]
It‘s disabled for security reasons. Anyone can register a name and so it would be unsafe to grant him op permissions upon registration

**Comment by poly000** [comment]
> It‘s disabled for security reasons. Anyone can register a name and so it would be unsafe to grant him op permissions upon registration

I mean... can op restore their permission after registeration?

**Comment by ljacqu** [comment]
It is. We intentionally do not restore OP status of a player that has just registered.

**Comment by poly000** [comment]
> It is. We intentionally do not restore OP status of a player that has just registered.
> That's regarding _registration_, though. After a normal login it should work

Oh I know. if a non-op registered op's account, this is unsafe
