### ISSUE TITLE
Bypass login

### ISSUE THREAD

**Issue by PerchunPak** [AuthMe/AuthMeReloaded#2281]
### What behaviour is observed:
My server was hacked with using this bug in auth. I pay 2$ hackers for know how they do this

### What behaviour is expected:
Block bungeecord command

### Steps/models to reproduce:
You can write /server [serverName] and authme not block this, if you have admin group in bungeecord

### Environment description
FlameCord 0.4.6 (Bungee) -> Paper 1.12.2 build 1618 (lobby) -> Paper 1.12.2 build 1618 (main server)

### AuthMe build number:
2440

### How fix without update from devs?
Right configurate module AllowRestrictedUser in config.yml

**Comment by krusic22** [comment]
There is a reason AuthMeBungee exists.

**Comment by PerchunPak** [comment]
AuthmeBungee on bungee

**Comment by PerchunPak** [comment]
I am not enable authmebungee....
