### ISSUE TITLE
Add a switch to disable the display of accounts with the same IP when logging in

### ISSUE THREAD

**Issue by poly000** [AuthMe/AuthMeReloaded#2283]
**Is your feature request related to a problem? Please describe.**
My server using frp, and as a result, all the players have the same 'ip' 127.0.0.1
When they login, AMR will show them 'you have xxx accounts, {accounts}'

**Describe the solution you'd like**
I hope there is a way to disable this fucntion

**Describe alternatives you've considered**

**Additional context**
![图片](https://user-images.githubusercontent.com/34085039/107326115-e2334d00-6ae5-11eb-9eb2-b247febe3927.png)

**Comment by HauserGrim** [comment]
displayOtherAccounts option
What is "frp"?

**Comment by ljacqu** [comment]
Remove permission node `authme.player.seeownaccounts` from your players

**Comment by poly000** [comment]
> 
> 
> Remove permission node `authme.player.seeownaccounts` from your players

I even didn't add this to permissions.yml...

**Comment by ljacqu** [comment]
Maybe `authme.player.*` somewhere? As a hint, under /authme debug there is a command to see whether AuthMe thinks a player has a certain permission node

**Comment by poly000** [comment]
> 
> 
> Maybe `authme.player.*` somewhere? As a hint, under /authme debug there is a command to see whether AuthMe thinks a player has a certain permission node

no. 
[permissions.zip](https://github.com/AuthMe/AuthMeReloaded/files/6249940/permissions.zip)

**Comment by poly000** [comment]
> displayOtherAccounts option
> What is "frp"?

frp is a port forwarding tool
thx, displayOtherAccounts=false works
