### ISSUE TITLE
[Feature Request] A possibility to disable the remote GeoIP database checking

### ISSUE THREAD

**Issue by Eric-01** [AuthMe/AuthMeReloaded#2289]
**Is your feature request related to a problem? Please describe.**
Currently, AuthMeReloaded connects to a remote host and tries to download the GeoIP database at every server startup (at every startup because the file does not exist), but every time it fails.

Since I don't use and won't use any of the AuthMeReloaded geolocation features, I disabled all the protection options in the config, and I didn't register for access to the database and fill the `clientId` and `licenseKey` fields, but the remote GeoIP database checking is still performed :/

**Describe the solution you'd like**
As a solution, it would be great to be able to disable the remote GeoIP database checking entirely (on an opt-out basis, of course) if someone doesn't use and doesn't plan to use any of the AuthMeReloaded geolocation features. It will reduce some of the (superfluous) Internet traffic it currently generates, make the logs a bit cleaner, and even save a few CPU cycles.

**Comment by Govindass** [comment]
for now you can use NetworkInterceptor plugin to block the connection

**Comment by WRtux** [comment]
It seems that the problem still exists in the latest dev build. I still get warned during each startup after setting `enableProtection` and `enableProtectionRegistered` to `false`.

```
[INFO]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[INFO]: Done (8.314s)! For help, type "help"
[WARN]: [AuthMe] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[INFO]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[INFO]: Timings Reset
[WARN]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundException]: plugins\AuthMe\GeoLite2-Countr
y.mmdb (系统找不到指定的文件。)
```

How can I disable it?

**Comment by oakwire7** [comment]
I was just trying to get API key, and, firstly, GeoIP didn't list my country, then it said that i use VPN or disposable email (none of which were true), and then it just banned me. So i am not able to use this plugin, untill this feature is released :(

**Comment by games647** [comment]
@oakwire7 you can still use the plugin. Only the GeoIP feature will be disabled for you.

**Comment by oakwire7** [comment]
@games647, unfortunately, server does not start until i provide a token

**Comment by games647** [comment]
@oakwire7 Please post the configuration, plugin version and log file, so we could test it. I just tested it against the default configuration and that worked fine.

**Comment by oakwire7** [comment]
@games647
[authme.log](https://github.com/AuthMe/AuthMeReloaded/files/13780474/authme.log)

Github does not allow yml files, so i renamed it to .txt
[config.txt](https://github.com/AuthMe/AuthMeReloaded/files/13780480/config.txt)

Version: AuthMe-5.6.0-beta2 (currently latest)

**Comment by krusic22** [comment]
Beta2 is from 2021...

**Comment by oakwire7** [comment]
@krusic22
but its the latest release… https://github.com/AuthMe/AuthMeReloaded/releases

**Comment by krusic22** [comment]
Get the latest version from Jenkins: https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/
