### ISSUE TITLE
Converter LoginSecurity

### ISSUE THREAD

**Issue by spedy55** [AuthMe/AuthMeReloaded#2293]
### What behaviour is observed:
when i converter database loginsecurity to authme, password all player will wrong

### Steps/models to reproduce:
i hope this bug can fix

### Plugin list:
Plugins (55): AdvancedGUI, AuctionHouse, AuthMe, BKCommonLib, CMI, CMILib, CMIPaperLib, ChatManager, ChestShop, Citizens, CoreProtect, FarmLimiter, FastAsyncWorldEdit, FastChunkPregenerator, GSigns, GlowAPI, Guilds, HeadDatabase, InvisibleItemFrame, ItemsAdder, LeaderHeadsRevamped, LibsDisguises, LightAPI, LightCleaner, LockettePro, LoneLibs, LuckPerms, MMOCore, MMOItems, Marriage, Multiverse-Core, MythicLib, MythicMobs, NoFlyZone, PacketListenerApi, PlaceholderAPI, PlayerParticles, PlayerPoints, ProtectionStones, ProtocolFirewall, ProtocolLib, RPGInventory, ServerListPlus, ServerUtils, Shopkeepers, ShowItem, SkinsRestorer, SpecializedCrates, TAB, TitleManager, TrMenu, Vault, WorldGuard, antiRedstoneClock and spark

### Environment description
Standalone server

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2440)

### Configuration:
https://pastebin.com/TmYXJsC0

**Comment by krusic22** [comment]
Add BCRYPT as a legacy hash.

**Comment by spedy55** [comment]
thank you for your help i can do it
