### ISSUE TITLE
14th of March update crash

### ISSUE THREAD

**Issue by LucidAPs** [AuthMe/AuthMeReloaded#2303]
Using the build #2445 the server won't start.
https://nekobin.com/kapifolomo

**Comment by sgdc3** [comment]
Please set DataSource.mySQLDriverClassName in your config to "com.mysql.jdbc.Drive"

**Comment by LucidAPs** [comment]
> Please set DataSource.mySQLDriverClassName in your config to "com.mysql.jdbc.Drive", let me know if this fixes the issue :)

I did the change and used the build #2447 this time and the server still crashed.
https://nekobin.com/cazutuyoxu

**Comment by MrKrakenied** [comment]
com.mysql.jdbc.Driver

**Comment by sgdc3** [comment]
Sorry, should be fixed now

**Comment by LucidAPs** [comment]
Yeap it's fixed, thank you :)
