### ISSUE TITLE
Whenever I'm trying to start my server, It crashes because of auth me

### ISSUE THREAD

**Issue by apellido04** [AuthMe/AuthMeReloaded#2311]
The only thing I changed in the file was this "mySQLUseSSL: false" Because I copied from another user with similar error, but still not working.
I'm currently running paper 1.16.5 with plugins both bukkit and spigot. These ones:
![image](https://user-images.githubusercontent.com/81596965/112912765-9c176480-90f8-11eb-850a-43b08aeeb881.png)

And here's my latest log
[latest.log](https://github.com/AuthMe/AuthMeReloaded/files/6225162/latest.log)

**Comment by Maks1116** [comment]
do you even have mysql database?

**Comment by Drc-DEV** [comment]
`[AuthMe] Could not download GeoLiteAPI database [UnknownHostException]: geolite.maxmind.com`

**Comment by Maks1116** [comment]
It seems to have same problem as mine:
[InjectorReflectionException]: Could not invoke constructor of class 'class fr.xephi.authme.command.CommandHandler'

**Comment by sgdc3** [comment]
Caused by an outdated version of the plugin, please update to the latest dev build.
You can download it at https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/
