### ISSUE TITLE
Unable to connect to Google SMTP server.

### ISSUE THREAD

**Issue by rktfier** [AuthMe/AuthMeReloaded#2324]
### What behaviour is observed:
What happened?

User is trying to register using email, user does not recieve email and plugin throws error.

### What behaviour is expected:
What did you expect?

User recieving his password inside the mail successfully

### Steps/models to reproduce:
The actions that cause the issue

1. User trying to register.
2. Trying to send mail using /authme debug mail <mailadress>

### Plugin list:
This can be found by running `/pl`

[22:01:20 INFO]: Plugins (22): AuthMe, ChestShop, Chunky, KeepXP*, LockettePro,
LuckPerms, NexEngine, OnePlayerSleep*, OpenInv, PlaceholderAPI, ProtocolLib, Qua
ntumShop, SetHomes, SimpleTpa*, SkinsRestorer, SkQuery, Skript, SuperVanish, Tim
ber, Trade, Vault, XConomy

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

Standalone server, SQLite

### AuthMe build number:
This can be found by running `/authme version`

Version: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2440)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

https://gist.github.com/rktfier/724335e23df94f69ed44db44917ad6fd

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

https://gist.github.com/rktfier/3f6ee0f50c43829e1bcf1bee0bdf28e3

**Comment by rktfier** [comment]
Just updated to AuthMe-5.6.0-beta2 and issue still exists.

Error Log : 

https://gist.github.com/rktfier/24775961b2bb9fbed3a417c57b5afb0e

Configuration : 

https://gist.github.com/rktfier/b421c1a09db95c6856075a07d6065f94

Nothing else changed other than AuthMe plugin.

**Comment by rktfier** [comment]
Tried a lot of versions with a lot of different configurations and still unable to send message. SSL connection seems impossible because of this line : 

`[04:46:34 INFO]: DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 58
7, isSSL false`

My suspicion is that the mail server does not get the required authentication details because of this line : 

`[04:46:34 INFO]: DEBUG SMTP: protocolConnect returning false, host=smtp.gmail.co
m, user=minecraft, password=<null>`

User and password here is not the same as what it is at the config file. 

As for the suspicions above, i am not exactly sure they are the cause.

If anyone has suggestions i am open for them since i need to get this working.

**Comment by rktfier** [comment]
Also seems like this wasn't in the logs : 
```
System Info: Java 11 (Eclipse OpenJ9 VM openj9-0.24.0) Host: Windows Server 2012
R2 6.3 (amd64)
```

Also i configured the "Less Secure Apps" setting to allow them in Google Mail settings.

**Comment by sgdc3** [comment]
Does it work if you use port 465? (will use SSL instead of TLS)

**Comment by rktfier** [comment]
No it doesn't work. Tried 587, 465 and 25 ports and no results.

**Comment by sgdc3** [comment]
> Also i configured the "Less Secure Apps" setting to allow them in Google Mail settings.

Are you sure you tried port 465 after allowing less secure apps?

**Comment by rktfier** [comment]
I am sure that i tried port 465 multiple times. I allowed less secure apps before i set it up to AuthMe so it was allowed all the time. I did not spent a lot of time after allowing less secure apps so i don't think it disabled itself.

**Comment by rktfier** [comment]
Issue still persists. also a quick question, should i use beta2 or Jenkins Snapshot build?

**Comment by jjackofall** [comment]
> Issue still persists. also a quick question, should i use beta2 or Jenkins Snapshot build?

Is it resolved?
