### ISSUE TITLE
your country is banned from this server

### ISSUE THREAD

**Issue by rapofil** [AuthMe/AuthMeReloaded#2328]
![unknown (4)](https://user-images.githubusercontent.com/75930293/116003653-28854c00-a5ff-11eb-8c0c-989e96425394.png)

Where is problem ? I try eneable "enableProtection: true" with country specifications, but still doesn't work

**Comment by sgdc3** [comment]
You are missing this part of the config:
![image](https://user-images.githubusercontent.com/8779252/117546893-07742080-b02d-11eb-99a8-65f3d3d5f796.png)
