### ISSUE TITLE
Can't initialize the MySQL database

### ISSUE THREAD

**Issue by RUBY-TEARS** [AuthMe/AuthMeReloaded#2331]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues! 
YES

### What behaviour is observed:
Can't initialize the MySQL database

### What behaviour is expected:
Can initialize the MySQL database

### Steps/models to reproduce:
just the Authme can't initialize the MySQL. And I create the table manually it works well

### Plugin list:
Authme, FastLogin, ProtocolLib

### Environment description
Paper1.16.5(lastest), Java11, MariaDB(10.6.0), ManjaroOS(local)

### AuthMe build number:
B2460

### Error Log:
https://pastebin.com/dy7vz3b6

### Configuration:
https://pastebin.com/KvH8qmyB

**Comment by sgdc3** [comment]
Your DB appears to be corrupted, if it is a new installation just drop the authme table and retry
