### ISSUE TITLE
Something is wrong with my config.yml and I couldn't find it

### ISSUE THREAD

**Issue by ProblemsSender** [AuthMe/AuthMeReloaded#2352]
### What behaviour is observed:
What happened? AuthMe forced server to be stopped

### What behaviour is expected:
What did you expect?
I DID checked this config on http://www.yamllint.com/
but did not find anything suspicious.

### Steps/models to reproduce:
The actions that cause the issue
1/ Goto https://pastebin.com/CtnxxtwH
2/ Copy into http://www.yamllint.com/
3/ There's an error that i couldn't find, but when i use this config. AuthMe said something is 
wrong and forced the server to stop.

All of that happens after i messing with the line restrictions.AllowRestrictedUser: true to test

### Plugin list:
EssentialX, AuthMe, ProtocolLib

### Environment description
Standalone server

### AuthMe build number:
latest

### Error Log:
https://pastebin.com/TRSXzA5t

### Configuration:
config.yml
https://pastebin.com/CtnxxtwH

**Comment by krusic22** [comment]
Looks like your config is very very old. Just regenerate it and configure it again.

**Comment by ProblemsSender** [comment]
> Looks like your config is very very old. Just regenerate it and configure it again.

I want to use line restrictions.AllowRestrictedUser: true
and my config is not old at all, it generated on its own and it's the latest version.

**Comment by krusic22** [comment]
It's missing the GeoIP portion of the config. So it's quite old.

**Comment by ProblemsSender** [comment]
Okay... so that must have something to do with my config.yml file right? are you serious?
https://pastebin.com/fzA5Lmex
This is the new one, so let's get back to the real point here.
