### ISSUE TITLE
our username contains illegal characters. Allowed chars: \*?[a-zA-Z0-9_]* on Bedrock (GeyserMC)

### ISSUE THREAD

**Issue by Slddev** [AuthMe/AuthMeReloaded#2367]
### What behaviour is observed:
Instead of allowing the player to join, the player is stopped because of illegal characters. (My name is very simple: TheSappyYT It does not include any of the characters that are considered illegal.)

### What behaviour is expected:
It should allow the player to join.

### Steps/models to reproduce:

1.  Add GeyserMC to your server and join using a bedrock account.

### Plugin list:
AuthMe, DiscordSRV, Essentials, EssentialsChat, floodgate, Geyser-Spigot, LiteBans, LuckPerms, Maintenance, Negativity, ProtocolLib, ServerListPlus*, SkinsRestorer, TAB, TCPShield, Vault

ate### Environment description
PaperMC Server

### AuthMe build number:
2472

**Comment by krusic22** [comment]
You messed with `allowedNicknameCharacters` didn't you?
Floodgate adds a . to Geyser uses by default. 
So you have to add a . to the default regex, to let them join.

**Comment by acastillorobles77** [comment]
I have the same problem.

**Comment by OLEGSHA** [comment]
The solution is to use
```yml
allowedNicknameCharacters: '[a-zA-Z0-9_\.]*'
```
(note the new `\.` at the end)

**Comment by SickProdigy** [comment]
Documentation for this would be nice. Trying to find more information on how to get geyser to work with this plugin the best.

**Comment by xfi7** [comment]
Another issue comes by when the fact that when you look up users by "IP" you can't since the "." detect as an IP basically making it uselesss to search users by IP when using /authme accounts "user".....

**Comment by ShayBox** [comment]
`(\.)?[a-zA-Z0-9_]*` is better, as Geyser only adds a period prefix, this only allows that.
