### ISSUE TITLE
Command cannot be used after login

### ISSUE THREAD

**Issue by 4o4E** [AuthMe/AuthMeReloaded#2372]
### What behaviour is observed:
Command cannot be used after login. After entering the command, there is no response, and there is no message in the console. Other functions are normal.

### What behaviour is expected:
Command can be use

### Steps/models to reproduce:
1.login
2.use command

### Plugin list:
AuthMe

### Environment description
server:
Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
Previous version: git-Paper-"1830de5" (MC: 1.17)

bungeecord:
Command cannot be used on both bungeecord(1590) and waterfall(1.17-438)

### AuthMe build number:
AuthMeReloaded v5.6.0-SNAPSHOT (build: 2480)

### Error Log:
There are no error logs

### Configuration:
server's config is default config
bungee's config https://pastebin.com/9FkgHxcF

**Comment by Link0Darck** [comment]
you wouldn't have enabled the session option so that if you log out and log back in, you don't need to log in because if that's it i have the same problem as you do my solution log out and wait the problem comes from bungeeauth and not authme

**Comment by 4o4E** [comment]
I will submit the issue to authmebungee
