### ISSUE TITLE
[BUG] Virus alert

### ISSUE THREAD

**Issue by vDjgamer** [AuthMe/AuthMeReloaded#2373]
### What behaviour is observed:
I have downloaded the plugin with its latest version through the official site: https://github.com/AuthMe/AuthMeReloaded/releases/tag/5.6.0-beta2 And at the end of the download I got a Virus Alert.

### Steps/models to reproduce:
Download the latest version

### Error Log:
![image](https://user-images.githubusercontent.com/74229644/123890161-01573d80-d914-11eb-914f-ec85d3ec4666.png)

**Comment by sgdc3** [comment]
Cannot reproduce, which browser/antivirus are you using?

**Comment by sgdc3** [comment]
And which browser?

**Comment by Blox61** [comment]
Opera GX

**Comment by Blox61** [comment]
I have the same problem

**Comment by mtatko** [comment]
Some browsers like to mark JAR files as harmful, you can safely ignore this warning
