### ISSUE TITLE
bcrypt password

### ISSUE THREAD

**Issue by ssslambda** [AuthMe/AuthMeReloaded#2387]
hey, i would to use bcrypt but where are `PASSWORD_BCRYPT` should be in config.yml?

https://github.com/AuthMe/AuthMeReloaded/blob/master/samples/website_integration/Bcrypt.php

**Comment by ljacqu** [comment]
Search for 'bcrypt' in config.yml and you'll find a property called "passwordHash"—set that to BCRYPT (default is SHA256)
