### ISSUE TITLE
Advertise

### ISSUE THREAD

**Issue by lukaso1234more** [AuthMe/AuthMeReloaded#2389]
### What behaviour is observed:
when i join, in chat appier - Advertise your server for free at https://minecraft-list.org/

### What behaviour is expected:
I want remove it

### Steps/models to reproduce:
i dont know

### Plugin list:
https://www.beta.ctrlv.cz/Lbc6

### Environment description
normal paper spigot

### AuthMe build number:
build: 2453

### Configuration:
https://pastebin.com/13e7j316 config

**Comment by games647** [comment]
AuthMe doesn't have this message. It's either coming from another plugin or your server hoster.

**Comment by lukaso1234more** [comment]
but when i remove authme message dissapier

**Comment by ljacqu** [comment]
Then there‘s something weird in your commands.yml or some other config/translation file. Or you downloaded the AuthMe JAR from a shady source :joy:
