### ISSUE TITLE
many problems

### ISSUE THREAD

**Issue by MC-Nirvana** [AuthMe/AuthMeReloaded#2396]
### What behaviour is observed:
1.The MySQL database link prompt should be INFO but it is ERROR
2.After Java16, the MySQL database driver was replaced. But AuthMe uses the database driver before the replacement. There will be an error on the server with version 1.17 and above.
3.AuthMe will still try to download the GeoIP database file when GeoIP is not enabled.

### What behaviour is expected:
1.Database prompt information changed to INFO
2.Add the new MySQL driver for Java16 in the comments
3.Fix the problem that GeoIP still downloads database files when it is not turned on

### Steps/models to reproduce:
1.After opening the database and restarting the server, the log will show the AuthMe database link prompt. The prompt type is ERROR (it should be INFO)
2.The above error will be reported before modifying the value of mySQLDriverClassName in config.yml to com.mysql.cj.jdbc.Driver
3.It will try to download every time the server is started, no matter whether GeoIP is turned on or not

### Plugin list:
AuthMe

### Environment description
Standalone server
The database is MySQL
### AuthMe build number:
5.6.0-SNAPSHOT-b2482

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
I sent a screenshot of the log to Discord
### Configuration:
I sent part of the configuration file to Discord, and GeoIP is in the default state and has not been changed.

**Comment by nhanledev** [comment]
I have this in my log:
`[Server thread/WARN]: Nag author(s): '[Xephi, sgdc3, DNx5, timvisee, games647, ljacqu, Gnat008]' of 'AuthMe' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).`

I think this is related to this issue.

**Comment by sgdc3** [comment]
> 1.The MySQL database link prompt should be INFO but it is ERROR

That's an issue caused by HikariCP, not an issue on our side

**Comment by sgdc3** [comment]
> I have this in my log:
> `[Server thread/WARN]: Nag author(s): '[Xephi, sgdc3, DNx5, timvisee, games647, ljacqu, Gnat008]' of 'AuthMe' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).`
> 
> I think this is related to this issue.

No that's unrelated, this warning can be ignored.

**Comment by sgdc3** [comment]
Please open single reports for each issue
