### ISSUE TITLE
Can't connect to mysql

### ISSUE THREAD

**Issue by leoncp9** [AuthMe/AuthMeReloaded#2399]
### What behaviour is observed:
Server can't connect to my mysql

### What behaviour is expected:
What did you expect?

### Plugin list:
https://prnt.sc/1noin6w

### Environment description
Standalone server/ /MySql, ... and bungeecord mysql

### AuthMe build number:
#2482

### Error Log:
authme log: https://pastebin.com/Qw3Bj91s
server startup log: https://pastebin.com/wXdpC2Cj

### Configuration:
https://pastebin.com/RieZpbQp

**Comment by sgdc3** [comment]
Your DB seems to be corrupted/using custom column names, please ask for support on our discord server

**Comment by leoncp9** [comment]
the database is empty when i make the test
what is the problem with my mysql database?
i used utf8_general_ci for make the database, is not correct?
there are a lot of options
https://prnt.sc/1qe19vb
you kn know what is the options correct? (if there is)
