### ISSUE TITLE
1.17.1 Could not save LimboPlayer

### ISSUE THREAD

**Issue by smario82** [AuthMe/AuthMeReloaded#2413]
[config.yml.txt](https://github.com/AuthMe/AuthMeReloaded/files/7079634/config.yml.txt)

### Steps/models to reproduce:
Register or login

### Plugin list:
AuthMe, InvisibleItemFrames, ProtocolLib, SkinsRestorer, sleep-most

### Environment description
Standalone server, SQLite
Paper version git-Paper-219 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0a6d320)

### AuthMe build number:
AuthMe v5.6.0-beta2-b2453

### Error Log:
WARN]: [AuthMe] Could not save LimboPlayer for 'PlayerName' [InaccessibleObjectException]: Unable to make private java.util.Collections$EmptyList() accessible: module java.base does not "opens java.util" to unnamed module @3330b662

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by WongIong** [comment]
Same

**Comment by ljacqu** [comment]
Apologies for not being able to test myself at the moment but if someone of you encountering the issue want to try with build n. 2500 or above from https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/2500/ it would be great if you could do so and report your findings. If the reason for the bug is what I believe it is, it should be fixed.

**Comment by sgdc3** [comment]
@smario82 @WongIong please try again with the latest dev build

**Comment by smario82** [comment]
On Server: Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
with the latest dev-build it works without errors. Thanks!

**Comment by HEROBRINEyashar** [comment]
[10:14:12 WARN]: [AuthMe] Could not save LimboPlayer for 'UserName' [Ina
ccessibleObjectException]: Unable to make private java.util.Collections$EmptyLis
t() accessible: module java.base does not "opens java.util" to unnamed module @7
920ba90
