### ISSUE TITLE
Mail API is not set

### ISSUE THREAD

**Issue by LordVZlomka** [AuthMe/AuthMeReloaded#2420]
### What behaviour is observed:
What happened? - I was trying to test the email recovery system, and it did not work. I checked for anything related for mail api in the config and did not find anything.

### What behaviour is expected:
What did you expect? - To receive an email to recover my password

### Steps/models to reproduce:
The actions that cause the issue - Use /email recovery [email]

### Plugin list:
This can be found by running `/pl` - I have over 100 plugins...

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ... - The plugin is using SQLite

### AuthMe build number:
This can be found by running `/authme version` 5.6.0 b2425

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any) - "[Authme] Mail API is not set"

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data) - https://paste.gg/p/anonymous/89a32a5f25184337a226d8985676f645

**Comment by ljacqu** [comment]
You need to configure from where the mail is sent... Your config.yml doesn't have anything set in the Email section starting at line 346.
