### ISSUE TITLE
[Question] Import from LoginSecurity

### ISSUE THREAD

**Issue by Aadi-mone** [AuthMe/AuthMeReloaded#2432]
### What feature do you want to see added?

...

### Are there any alternatives?

...

### Anything else?

I used Login security for /login

Is there a way to import passwords and username from that plugin to authme?

**Comment by Aadi-mone** [comment]
@MineSAT @timvisee @garagepoort @toxuin 
can anyone help please?

**Comment by sgdc3** [comment]
Please look at #2449 for the solution
