### ISSUE TITLE
LoginSecurity import not working properly

### ISSUE THREAD

**Issue by ElTodoFull** [AuthMe/AuthMeReloaded#2449]
### What behaviour is observed?

All players fail to put in their password, even when they are sure, including me.

### Expected behaviour

They join with the same password they registered with loginsecurity

### To Reproduce

Install Authme and uninstall LoginSecurity.jar (using flatfile, leaving files in the server)
Restart purpur server
Configure authme  and enable MySQL database
restart server
run on console: authme converter loginsecurity
Everything seems to be successful

### Plugin list

velocity: authmevelocity, botsentry, fastlogin, floodgate, geyser, luckperms, skinsrestorer, spark
Purpur: ArmorStandTools, AsyncWorldEdit, AuthMe, AutoMessager, BlockLocker, BlocksHub, Captcha, ChatSentinel, ChestShop, ClaimChunk, CMILib, CommandHook, ConditionalEvents, ConsoleSpamFix, CoreProtect, CustomCrafting, CustomHeads*, DiscordSRV, dynmap, Essentials, Essentials_WarpGUI, EssentialsSpawn, ExtraContexts, FancyBags, FastLogin, floodgate, FurnitureLib, FurnitureMaker, GHolo, GMusic, Graves, GSit, ImageMaps, Insights, InventoryRollbackPlus, Jobs, KauriVPN, LibsDisguises, LimitCreative, LiteBans, LuckPerms, MessageFilter*, MobBanners, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Parkour, PL-Hide, PlaceholderAPI, Plan, PlayerParticles, ProtocolLib, PvPManager, RegionRaid, Shopkeepers, SimplePets, SkinsRestorer, SuperbVote, SuperVanish, TAB, Themis, TreasureChest, TreeGravity, UltraCosmetics, Vault, VentureChat, ViewDistanceTweaks, Votifier, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, XP-Deposit*

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

5.6.0-SNAPSHOT

### Configuration

https://paste.gg/p/anonymous/e6813475dc7446dcaf4bfa848c5ff923

**Comment by krusic22** [comment]
After migrating from LoginSecurity using the integrated converter. 
You have to add BCRYPT as a legacy hash in the AuthMe config. 
Like this: 
`legacyHashes: ['BCRYPT']`

**Comment by ElTodoFull** [comment]
> After migrating from LoginSecurity using the integrated converter. You have to add BCRYPT as a legacy hash in the AuthMe config. Like this: `legacyHashes: ['BCRYPT']`

That worked! Thank you so much! :)
I recommend adding that to the import instructions.
