### ISSUE TITLE
auth me not giving instructions

### ISSUE THREAD

**Issue by orang3i** [AuthMe/AuthMeReloaded#2451]
### What behaviour is observed?

on 1.18 auth me does'nt ask to register or login but it works when we blindly type /register and /login

### Expected behaviour

it should say "do /register <passoword> <confirmpassoword>

### To Reproduce

go to https://kennytv.eu/Paperclip-1.18-rc3-R0.1-EXPERIMENTAL-reobf-2.jar for paper 1.18 test build

install server 

install auth me 

run server 

join 

### Plugin list

![image](https://user-images.githubusercontent.com/86411355/143766647-8ddd832b-0eb5-4c2b-bcf4-eaded4d087d3.png)

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

5.6.0

### Configuration

https://paste.gg/p/anonymous/9fce73726c6545b390061d41b08b334b/files/3042a988958c42a485af1425d3b26bca/raw

**Comment by sgdc3** [comment]
@orang3i do you see any error in the server startup console log?

**Comment by orang3i** [comment]
> @orang3i do you see any error in the server startup console log?

no I don't get any errors for auth me atleast

**Comment by sgdc3** [comment]
Can you please provide us a full server log? Please try with only authme installed.

**Comment by orang3i** [comment]
> Can you please provide us a full server log? Please try with only authme installed.

@sgdc3 

https://pastebin.com/raw/phyCb1GG

**Comment by orang3i** [comment]
> Can you please provide us a full server log? Please try with only authme installed.

i deleted whole plugins folder and tried again and i think it is essentialsX messing with it @sgdc3

**Comment by orang3i** [comment]
i removed plugins 1 by 1 when i removed this it works when i add it it breaks

**Comment by orang3i** [comment]
https://www.spigotmc.org/resources/jakes-rtp.80201/

**Comment by sgdc3** [comment]
Idk, I just pushed a new build to jenkins with some minor dependencies fixes, try it first.

**Comment by orang3i** [comment]
>  Idk, I just pushed a new build to jenkins with some minor dependencies fixes, try it first. @orang3i
>  https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/

@sgdc3 ok i will update to you tomorrow
