### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by ConaII** [AuthMe/AuthMeReloaded#2459]
### What behaviour is observed?

Can't enable MySQL

Purpur 1.16.5-1171

### Expected behaviour

MySQL loads.

### To Reproduce

don't have time srry

### Plugin list

don't have time srry

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

AuthMe 5.6.0-SNAPSHOT-b2501

### Error log (if applicable)

https://pastebin.com/Suv1MhFe

### Configuration

https://pastebin.com/25ASvV3a

**Comment by sgdc3** [comment]
@ConaII Which version of MySql server are you using?

**Comment by ConaII** [comment]
Hello, I'm back.
I don't know, it's my host databases.
I just asked so i'm waiting for response.
https://docs.bloom.host/databases/
![image](https://user-images.githubusercontent.com/72966048/145586488-69875449-d7de-4c02-965b-36e6b0d01105.png)

**Comment by ConaII** [comment]
I think i got it, i have to test yet.

**Comment by ConaII** [comment]
Ok, it seems to work in the test server.

![image](https://user-images.githubusercontent.com/72966048/145588488-07943dc0-d2ea-48d5-a58a-0f8c989d2a32.png)

https://pastebin.com/9YBW0GVd

**Comment by ConaII** [comment]
Question, what happens to my SQLite "authme.db" file??
Does it transfer automatically or..?

**Comment by sgdc3** [comment]
@ConaII you have to perform a conversion: https://github.com/AuthMe/AuthMeReloaded/wiki/Converters#authme
