### ISSUE TITLE
Line 400 of config.yml links to an unsafe website

### ISSUE THREAD

**Issue by RooRay** [AuthMe/AuthMeReloaded#2467]
### What behaviour is observed?

The provided link for EssentialsX's tutorial on getting a MaxMind license key links to an adware instead of their official website.

### Expected behaviour

Link should go to https://essentialsx.**net**/wiki/GeoIP.html instead of https://essentialsx.**cf**/wiki/GeoIP.html

### To Reproduce

1. Go to line 400 of the config.yml file and copy the essentialsx link
2. Paste it into a web browser
3. Enjoy whatever ad you get

### Plugin list

Not applicable

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

5.6.0-beta2

### Configuration

N/A

**Comment by games647** [comment]
Maybe we should even link to the GitHub wiki page instead [1]? This should prevent such cases in the future.

[1] https://github.com/EssentialsX/Wiki/blob/master/GeoIP.md

**Comment by RooRay** [comment]
> Maybe we should even link to the GitHub wiki page instead [1]? This should prevent such cases in the future.
> 
> [1] https://github.com/EssentialsX/Wiki/blob/master/GeoIP.md

Yeah that'd probably be best

**Comment by sgdc3** [comment]
Thank you!
