### ISSUE TITLE
Don't prompt for login if the IP is the same.

### ISSUE THREAD

**Issue by ExistingProgrammer** [AuthMe/AuthMeReloaded#2468]
### What feature do you want to see added?

Sorry if the feature is already there and I couldn't find it, but it there a way to not ask the player to login if the IP address is the same as when they logged in before? Many websites also do this to not ask the user to login again and again, while not compromising the security of the user. So, is there already a way, or can there be a way to do this with AuthMe?

### Are there any alternatives?

None that I know of which don't compromise security.

### Anything else?

There should obviously be a option to toggle this feature off if people don't want it. Maybe we can also ask for email verification if the IP changed?
Want to be more secure? Maybe advanced users can specify the IP that can login automatically by themselves.

**Comment by itsHardStyl3r** [comment]
What you're talking about are Sessions. AuthMe has been supporting the feature since ages. Here's the reference: https://github.com/AuthMe/AuthMeReloaded/blob/master/samples/NewConfig.yml#L154

**Comment by ExistingProgrammer** [comment]
Thanks!
