### ISSUE TITLE
Email doesn’t send

### ISSUE THREAD

**Issue by WaldperlachFabi** [AuthMe/AuthMeReloaded#2489]
### What behaviour is observed?

If I try /Authme debug mail Waldperlach.Fabi@gmail.com it throws an error

### Expected behaviour

Sending an email to my email address 

### To Reproduce

Enter it it in console

### Plugin list

Only Authme reloaded

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

v5.6.0-beta2 (build: 2453)

### Error log (if applicable)

https://paste.gg/p/anonymous/566d9ba62fbe4085985330e64c2dcef6

### Configuration

https://paste.gg/p/anonymous/a0a6512f33ca457dba71a11cb795fe97

**Comment by MCausc78** [comment]
Wrong password
