### ISSUE TITLE
AuthMe Aborting Installation

### ISSUE THREAD

**Issue by ghost** [AuthMe/AuthMeReloaded#2517]
### What behaviour is observed?

Whenever I try to install authme I just get 
Aborting initialization of AuthMe: [IllegalStateException]: You need Java 1.8 or above to run this plugin!
I definitely do have java installed, the server would not run without it

I don't have MySql installed as this is a small server 

### Expected behaviour

AuthMe should install

### To Reproduce

1. Place AuthMe jar file in plugins folder
2. Run server

### Plugin list

just authme

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

5.4.0

### Error log (if applicable)

I can't copy the console because it's doing the any key to exit thing

### Configuration

(not installed)

**Comment by AkariDream** [comment]
this seems to have been going on for a while. pls find the corresponding log in .\server\logs\latest.log(or date.log.gz). then paste into pastebin.
could be a problem with ur java version. If it is in the case of Java >=1.8.0 and the server has prompted it at the time of loading.
if the console has prompted u to use version 1.8.0 (or later) Java still fails to load. then you need to make sure that your server core is working properly. i recommend paper or purpur(). 1.8 recommends flamepaper
`Akarin/tuinity has some problems in non-java 8/11 situations. if u do not have high version requirements. u can still use them`
