### ISSUE TITLE
Question - How can I change the password of an alt account?

### ISSUE THREAD

**Issue by zachariapopcorn** [AuthMe/AuthMeReloaded#2519]
### What feature do you want to see added?

I have an alt account on a Minecraft server, but I forgot the password on it. I can access my main on it, so I'm wondering if there's a way for me to change the password of said alt on the server, and if so, how do I do it?

### Are there any alternatives?

Uh, maybe

**Comment by Wasup1st** [comment]
I think u should search auth me commands and use them on the server console

**Comment by zachariapopcorn** [comment]
I don't have OP

**Comment by ljacqu** [comment]
Accounts are independent so you need to either have an admin change it for you, or if there‘s email recovery (i.e. if you added an email to the alt account) to try that. Otherwise there are no ties between your account and the alt.

**Comment by sepsol** [comment]
@ljacqu How can an admin change a password?
