### ISSUE TITLE
Authy passworld transport to authme!

### ISSUE THREAD

**Issue by Spartakingdom** [AuthMe/AuthMeReloaded#2522]
### What feature do you want to see added?

I need help of Authy passworld to transport in authme plugin! for resson is in authy don'y have the restart passworld and etc and i can't help one player of the restarting passworld for him! i like to ask can u guy's support Authy of transport to authme pass?

### Are there any alternatives?

I did try use a database don't work! all passworld have like this: of one database my account is this shows passworld for real is 99sk99sk0LoL and dash pass shows this: 5105189686f0de1f337acdaace57172478ed3198f53c9e511f2f1e4c663e6eb3 plz help!

**Comment by krusic22** [comment]
Looks like just plain SHA256.
You should be able to just copy the data to the AuthMe DB and set SHA256 as the legacy hash.

**Comment by Spartakingdom** [comment]
what u mean?

**Comment by ljacqu** [comment]
Can‘t really do much more without more information about the hashing or links to the plugin
