### ISSUE TITLE
Login permission

### ISSUE THREAD

**Issue by CuriousCoder1232** [AuthMe/AuthMeReloaded#2544]
### What behaviour is observed?

I have installed pex or permissions ex it says i have no permission to login i keep trying `- /login - /register` and it doesnt work.

### Expected behaviour

Its supposed do just do the command /login and it works.

### To Reproduce

' groups: 
  default:
    prefix: '&0[&1Guest&0]&3'
    default: true
    permissions: '*'
     option:
      rank: '1000'
  Trusted:
    prefix: '&9[Trusted]&3'
    inheritance:
    - default
    permissions:
    - essentials.feed
    - essentials.kit
    -  /register
     - /login
 
  Jr_Mod:
    prefix: '&l&0[&4Trail_Mod&0]&r'
    inheritance:
    - default
    - Trusted
    permissions:
    - essentials.fly
    - essentials.whois
    - /register
- /login
    options:
      rank: '900'
  Moderator:
    prefix: '&a[&7Moderator&a]&3'
    inheritance:
    - default
    - Trusted
    permissions:
    - essentials.gamemode
    - essentials.kick
    - essentials.me
    - /login
     - /register
    options:
      rank: '800'
    worlds: {}
  Super_Mod:
    prefix: '&l&4[Builder&4]&6'
    inheritance:
    - default
    - Trusted
    - Moderator
    permissions:
    - essentials.tp
    - essentials.gamemode
    -  /register 
    - /login
    options:
      rank: '700'
  Admin:
    prefix: '&b[Admin]&3'
    inheritance:
    - default
    - Moderator
    permissions:
    - '*'
    - -essentials.ban
    - -essentials.kill
    - -essentials.gamemode.others
    - -essentials.op
    - multiworld.command.flags
    - multiworld.command.spawn
   - /login
    - register
    options:
      rank: '600'
  Head_Admin:
    prefix: '&6[Head_Admin]&3'
    inheritance:
    - Admin
    options:
      rank: '100'
  Co_Owner:
    prefix: '&d[Co_Owner]&e'
    permissions:
    - -essentials.op
    - multiworld.command.create
    - multiworld.command.load
    - multiworld.command.unload
    - multiworld.command.delete
    - /register
    - /login
    users: Amogus:
    options:
      rank: '2'
   Owner:
    prefix: '&l&4[Owner&4]&6'
    inheritance:
    - default
    - Trusted
    - Moderator
    permissions:
    - essentials.tp
    - essentials.gamemode
     - /login
     - /register

    
  that is the permission ex and this is hte auth me

DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: authme
  backend: file
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: '12345'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLColumnEmail: email
  mySQLColumnId: id
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
  restrictions:
    allowChat: false
    allowCommands:
    - /login
    - /register
    - /l
    - /reg
    - /passpartu
    - /email
    - /captchaz
    maxRegPerIp: 100000
    maxNicknameLength: 20
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: false
    AllowRestrictedUser: false
    AllowedRestrictedUser: []
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: false
    minNicknameLength: 3
    allowMovement: false
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_?]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
  GameMode:
    ForceSurvivalMode: false
    ResetInventoryIfCreative: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
Xenoforo:
  predefinedSalt: ''
permission:
  EnablePermissionCheck: true
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
    newPasswordHash: SHA256
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, \n\n This is your new AuthMe password for the server
    \n\n <servername> : \n\n <generatedpass>\n\nDo not forget to change password after
    login! \n /changepassword <generatedpass> newPassword'
  maxRegPerEmail: 1
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  notifications: true

### Plugin list

Legendary smp 

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

2.7.11

### Error log (if applicable)

none

### Configuration

DataSource:   mySQLColumnName: username   mySQLTablename: authme   mySQLUsername: authme   backend: file   mySQLColumnLastLogin: lastlogin   mySQLDatabase: authme   mySQLPort: '3306'   mySQLColumnIp: ip   mySQLHost: 127.0.0.1   mySQLColumnPassword: password   mySQLPassword: '12345'   caching: true   mySQLlastlocX: x   mySQLlastlocY: y   mySQLlastlocZ: z   mySQLColumnEmail: email   mySQLColumnId: id GroupOptions:   UnregisteredPlayerGroup: ''   RegisteredPlayerGroup: ''   Permissions:     PermissionsOnJoin: [] settings:   sessions:     enabled: false     timeout: 10   restrictions:     allowChat: false     allowCommands:     - /login     - /register     - /l     - /reg     - /passpartu     - /email     - /captchaz     maxRegPerIp: 100000     maxNicknameLength: 20     ForceSingleSession: true     ForceSpawnLocOnJoinEnabled: false     SaveQuitLocation: false     AllowRestrictedUser: false     AllowedRestrictedUser: []     kickNonRegistered: false     kickOnWrongPassword: false     teleportUnAuthedToSpawn: false     minNicknameLength: 3     allowMovement: false     timeout: 30     allowedNicknameCharacters: '[a-zA-Z0-9_?]*'     allowedMovementRadius: 100     enablePasswordVerifier: true     ProtectInventoryBeforeLogIn: true     displayOtherAccounts: true     ForceSpawnOnTheseWorlds:     - world     - world_nether     - world_the_end     banUnsafedIP: false   GameMode:     ForceSurvivalMode: false     ResetInventoryIfCreative: false   security:     minPasswordLength: 4     unLoggedinGroup: unLoggedinGroup     passwordHash: SHA256     doubleMD5SaltLength: 8   registration:     enabled: true     messageInterval: 5     force: true     enableEmailRegistrationSystem: false     doubleEmailCheck: false   unrestrictions:     UnrestrictedName: []   messagesLanguage: en ExternalBoardOptions:   mySQLColumnSalt: ''   mySQLColumnGroup: ''   nonActivedUserGroup: -1   mySQLOtherUsernameColumns: [] Xenoforo:   predefinedSalt: '' permission:   EnablePermissionCheck: true BackupSystem:   ActivateBackup: false   OnServerStart: false   OnServerStop: true   MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\ Passpartu:   enablePasspartu: false Security:   SQLProblem:     stopServer: true   ReloadCommand:     useReloadCommandSupport: true   console:     noConsoleSpam: false     removePassword: true   captcha:     useCaptcha: false     maxLoginTry: 5     captchaLength: 5 Converter:   Rakamak:     fileName: users.rak     useIP: false     ipFileName: UsersIp.rak     newPasswordHash: SHA256 Email:   mailSMTP: smtp.gmail.com   mailPort: 465   mailAccount: ''   mailPassword: ''   mailSenderName: ''   RecoveryPasswordLength: 8   mailSubject: Your new AuthMe Password   mailText: 'Dear <playername>, \n\n This is your new AuthMe password for the server     \n\n <servername> : \n\n <generatedpass>\n\nDo not forget to change password after     login! \n /changepassword <generatedpass> newPassword'   maxRegPerEmail: 1 Hooks:   multiverse: true   chestshop: true   bungeecord: false   notifications: true

**Comment by CuriousCoder1232** [comment]
Any fixes?

**Comment by CuriousCoder1232** [comment]
I only use it because it supports ranks and I don’t know how to setup
luckperms

**Comment by MCausc78** [comment]
/lp creategroup <group name> [weight] ["display name"] - create a group
/lp deletegroup <group name>
/lp user <player> permission set <permission> [value true or false] [context like server=global] - add a permission to player
/lp user <player> permission unset <permission> [context] - remove a player permission
/lp user <player> permission clear [context] - clears all player permissions
/lp user <player> parent set <group> [context] - set group to player
/lp user <player> parent add <group> [context] - add a group to player
/lp user <player> parent remove <group> [context]
/lp user <player> parent clear [context] - clear all groups from player
/lp user <player> meta setprefix [priority] <prefix> [context] - set player prefix
/lp user <player> meta setsuffix [priority] <suffix> [context] - set player suffix
/lp user <player> meta clear - clear all player meta
Instead of 'user <player>' you can use 'group <group>'
Search more information on https://luckperms.net/wiki
Good luck!
