### ISSUE TITLE
Multiple registration per account

### ISSUE THREAD

**Issue by Kambran** [AuthMe/AuthMeReloaded#2546]
### What feature do you want to see added?

Is there a setting to make it so that a single account can make multiple registrations?

### Are there any alternatives?

/

**Comment by MCausc78** [comment]
Set settings.restrictions.maxRegPerIp option to 0 in AuthMe config

**Comment by Kambran** [comment]
right i did but it still says
![image](https://user-images.githubusercontent.com/78663738/169825889-350e82d0-4a81-4ce4-b592-d1473b80fc99.png)

**Comment by MCausc78** [comment]
Did you reload server/AuthMe config?

**Comment by MCausc78** [comment]
Try set settings.restrictions.maxLoginPerIp and settings.restrictions.maxJoinPerIp

**Comment by Kambran** [comment]
are all those settings in the config jar?

**Comment by Kambran** [comment]
DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: authme
  backend: file
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: authme
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 127.0.0.1
  mySQLColumnPassword: password
  mySQLPassword: '12345'
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLColumnEmail: email
  mySQLColumnId: id
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
  restrictions:
    allowChat: true
    allowCommands:
    - /login
    - /register
    maxRegPerIp: 0
    maxNicknameLength: 20
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: false
    SaveQuitLocation: true
    AllowRestrictedUser: false
    AllowedRestrictedUser: []
    kickNonRegistered: false
    kickOnWrongPassword: false
    teleportUnAuthedToSpawn: true
    minNicknameLength: 3
    allowMovement: false
    timeout: 30
    allowedNicknameCharacters: '[a-zA-Z0-9_?]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: false
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: truetesttest
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
  GameMode:
    ForceSurvivalMode: true
    ResetInventoryIfCreative: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
  registration:
    enabled: true
    messageInterval: 5
    force: false
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
Xenoforo:
  predefinedSalt: ''
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
    newPasswordHash: SHA256
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: ''
  mailPassword: ''
  mailSenderName: ''
  RecoveryPasswordLength: 8
  mailSubject: Your new AuthMe Password
  mailText: 'Dear <playername>, \n\n This is your new AuthMe password for the server
    \n\n <servername> : \n\n <generatedpass>\n\nDo not forget to change password after
    login! \n /changepassword <generatedpass> newPassword'
  maxRegPerEmail: 1
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: false
  notifications: true
is what i have at my config file right now

**Comment by Kambran** [comment]
can anyone help?

**Comment by ljacqu** [comment]
Looking at your config, I think you have an ancient version of AuthMe. Could you upgrade to a newer version?

**Comment by DonZekane** [comment]
"exeded" lol, the version being ancient is plausible.
