### ISSUE TITLE
bypasses authme to log in to op account

### ISSUE THREAD

**Issue by yinxiong110** [AuthMe/AuthMeReloaded#2559]
### What behaviour is observed?

Found on Chinese video websites
url：https://www.bilibili.com/video/BV1g94y127AQ
Looks like a cheating program

### Expected behaviour

Hope to repair

### To Reproduce

See video content for details

### Plugin list

See video content for details

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

latest version

### Error log (if applicable)

See video content for details

### Configuration

latest version

**Comment by Watereks** [comment]
Popular bag

**Comment by krusic22** [comment]
Can't really debug the issue, due to the lack of information.
Server version, server implementation (probably some horrible Forge Bukkit hybrid), ...

**Comment by Mhdtarek** [comment]
Thats probably a issue with the server and there isn't really that much information

**Comment by Aurorabili** [comment]
The original video has been deleted, but I hope to know more details and track this problem. Thank you

**Comment by sgdc3** [comment]
Duplicate https://github.com/AuthMe/AuthMeReloaded/issues/2571

**Comment by LowIQWithAutism** [comment]
Does this only work with an OPed account or can they login to any account?
