### ISSUE TITLE
Server is closing

### ISSUE THREAD

**Issue by Onatic48** [AuthMe/AuthMeReloaded#2565]
### What behaviour is observed?

When I open start.bat, all plugins are loading and then authme is giving an error and the server is closing

### Expected behaviour

To not give error

### To Reproduce

1. open start.bat
2. wait server to finish loading plugins
3. see the error

### Plugin list

![image](https://user-images.githubusercontent.com/56692181/173784528-e5b9e92b-02af-4de1-8365-1628ae113b00.png)

### Server Implementation

BungeeCord

### Database Implementation

SQLite

### AuthMe Version

v5.6.0-beta1-b2226

### Error log (if applicable)

https://paste.gg/p/anonymous/d20f91cb26974de998d3e278792f16de

### Configuration

https://paste.gg/p/anonymous/c96efc8c67e94bfabd81d2ea3358b19f

**Comment by andriycraft** [comment]
[11:42:27] [Server thread/WARN]: [AuthMe] Error during SQLite initialization: [SQLException]: out of memory
[11:42:27] [Server thread/WARN]: [AuthMe] Could not create data source: [SQLException]: out of memory

**Comment by andriycraft** [comment]
not a bug

**Comment by andriycraft** [comment]
ur server needs more ram
