### ISSUE TITLE
Please Help Meee!

### ISSUE THREAD

**Issue by GALLETI799** [AuthMe/AuthMeReloaded#2566]
### What behaviour is observed?

I uninstall the plugin authme and before that i cant use minecraft chat
please help me i cant use chat and commands :(

### Expected behaviour

Doesnt work my minecraft chat and commands before i uninstall authme

### To Reproduce

Click link

### Plugin list

AnimationLib, BCommons*, BetterRTP, BlockLocker, BloodMoon, BuycraftX, ChatManager, ChestCommands, Chunky, Citizens, ClearLag, ClickTpa*, CommandNPC*, ConditionalEvents, CrazyAuctions, DecentHolograms, DiscordSRV, EconomyShopGUI, Essentials, EssentialsChat, ExcellentCrates, ExecutableItems, Graves, HubThat, InteractiveBooks, ItemEditor, ItemsAdder, KarenProtect*, LibsDisguises, LightAPI, LoneLibs, LuckPerms, MessageAnnouncer, MeteoritesPro, MiniaturePets, ModelEngine, MoneyHunters, Multiverse-Core, MythicMobs, NBTAPI, NexEngine, PlaceholderAPI, PlayerKits, ProtocolLib, PvPManager, SCore, SimplePortals, SimpleScore, sleep-most, TAB, TimedRewards, Vault, Vehicles, WorldEdit, WorldGuard

### Server Implementation

BungeeCord

### Database Implementation

SQLite

### AuthMe Version

5.6.0-beta2

### Configuration

i uninstalled the plugin thats it

**Comment by JiangQiYan713** [comment]
在这个插件认证你登录前仅限于/l /reg这些登录，你改配置了嘛？
