### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by alextrevor** [AuthMe/AuthMeReloaded#2573]
### What behaviour is observed?

Hello! I need help. I explain what. I have a BungeeCord player first connected in the authorization lobby. register and then, if he wants to re-sign it, he throws it into authorization, an authorized player, abruptly reconnects to the hub, how to make sure that if an authorized player enters, he is immediately thrown into the hub, without connecting to authorization, and downloading the world.

### Expected behaviour

Hello! I need help. I explain what. I have a BungeeCord player first connected in the authorization lobby. register and then, if he wants to re-sign it, he throws it into authorization, an authorized player, abruptly reconnects to the hub, how to make sure that if an authorized player enters, he is immediately thrown into the hub, without connecting to authorization, and downloading the world.

### To Reproduce

Sorry, I didn't understand what it is

### Plugin list

Plugins (14): LuckPerms, AlwaysDay, Essentials, PlugMan, EasySetSpawn, VanishPlayerTool, ViaVersion, PlugManX, ViaBackwards, ProtocolLib, ViaRewind, SkinsRestorer, AuthServer, AuthMe

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

v5.6.0-beta2

### Error log (if applicable)

none

### Configuration

https://paste.gg/p/anonymous/8fd901e12a7946d1ae92ec812315c00b

**Comment by alextrevor** [comment]
HEEEEEEEEEEEEEEALP

**Comment by sgdc3** [comment]
@alextrevor Make sure  to reproduce the issue with the latest dev build + please change the issue title to something that describes your issue.
