### ISSUE TITLE
AuthmeBungee 2 servers

### ISSUE THREAD

**Issue by yoblex** [AuthMe/AuthMeReloaded#2575]
### What behaviour is observed?

hi all, tell me please, I use BungeeCord and AuthMe, I made an authorization server Survival, but I have 1 more world (server) in which the player enters through the portal, when the player is in the second world, he cannot use authme commands, what can I do ?
Do I need to install AuthMe on the second server?

### Expected behaviour

hi all, tell me please, I use BungeeCord and AuthMe, I made an authorization server Survival, but I have 1 more world (server) in which the player enters through the portal, when the player is in the second world, he cannot use authme commands, what can I do ?
Do I need to install AuthMe on the second server?

### To Reproduce

ok

### Plugin list

authme

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

5.6.0

### Configuration

*

**Comment by AruMoon** [comment]
Yes, you should install it on both servers and sync player logins using external database
