### ISSUE TITLE
Authorization by hostname

### ISSUE THREAD

**Issue by Aloki** [AuthMe/AuthMeReloaded#2582]
### What feature do you want to see added?

I want the possibility of authorization by hostname. So that the player can specify the server address of the form _abcdef.auth.mc.server.com_ or maybe _password.account.auth.mc.server.com_ and authorization occurs automatically (by linking an account and a random set of characters before _.auth.mc.server.com_).

### Are there any alternatives?

Didn't find any

**Comment by krusic22** [comment]
While it is possible to implement something like that, it's very insecure. 
Anyone on the same network (or ISP and up), would be able to see the DNS query and get the unencrypted password.
The server owner would also be able to simply look at the passwords in that case.
