### ISSUE TITLE
"Authentication required" When you join server

### ISSUE THREAD

**Issue by NoxyYT** [AuthMe/AuthMeReloaded#2597]
### What behaviour is observed?

i reconnect and see "Authentication required"

### Expected behaviour

i reconnect and see "Authentication required"

### To Reproduce

1. Register
2. Login
3. Tp On Server
4. reconnect on server
5. See "Authentication required"

### Plugin list

1. AuthMe
(only)

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

5.6.0-beta2 (build: 2453)

### Configuration

https://paste.gg/p/anonymous/517ac5bd7a344d88aae68a829cdd16c2

**Comment by AkariDream** [comment]
AuthMeBungee also requires you to install AuthMeReloaded on the "auth server". and find bungeecord hooks in the cfg of AuthMeReloaded. then set it to true.
uu cant have BungeeCord automatically send player to the same server as player were offline while using AuthMeBungee. u should also be aware of the risks of doing so on a cracked authentication server

**Comment by NoxyYT** [comment]
thank u
