### ISSUE TITLE
Console logs passwords

### ISSUE THREAD

**Issue by IsRealMe** [AuthMe/AuthMeReloaded#2619]
### What behaviour is observed?

On using command /login console logs whole command with password attached.

### Expected behaviour

Password of player should not be visible by console nor log files.

### To Reproduce

1. Enter server
2. Use /login
3. Check console for your password output

### Plugin list

![image](https://user-images.githubusercontent.com/27916876/190378188-637158f6-bbb0-4265-b68e-b69789ff4710.png)

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

AuthMeReloaded v5.6.0-beta2 (build: 2453)

### Error log (if applicable)

None

### Configuration

https://paste.gg/p/anonymous/54748046c13c4024a3f6718da2a1803a

**Comment by AkariDream** [comment]
its not AuthMeReloaded fault. look for plugins that listen to player commands (such as CoreProtect). if u are a singleton bukkit server. u should not give the "coreprotect.lookup.command" permission to everyone but yourself.
