### ISSUE TITLE
Every user owns every account

### ISSUE THREAD

**Issue by FelixDaemonWox** [AuthMe/AuthMeReloaded#2627]
### What behaviour is observed?

AuthMe says all users own every account 

### Expected behaviour

When a new user is registered they should only own their account, instead, every time a new user registers authme shows as if they own every single account registered

### To Reproduce

install AuthMe-5.6.0-beta2 on 
run server on Paper-148
get a friend or an alt so there's more than 1 player registered

### Plugin list

System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39) Host: Windows 10 10.0 (amd64)
Starting minecraft server version 1.19.2
This server is running Paper version git-Paper-148 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 05f6a5c)

plugmanx, esentials, gsit, images, luckperms, maintenance, authme, no chatreports, placeholderapi, protocollib, skinsrestorer, sleepmost, staffplus, tablist, worldedit, worldguard

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

AuthMe-5.6.0-beta2

### Error log (if applicable)

theres none

### Configuration

https://paste.gg/p/anonymous/0732fb87cffb45d79e3a48d075334e7f

**Comment by AkariDream** [comment]
if ure using something like a proxy (e.g. HAProxy). 
make sure that you set up IP forward appropriately. 
if its bungeecord. pls set ip_forward: true. and find spigot.yml on the spigot (or fork) server. _bungeecord:_ true_

**Comment by FelixDaemonWox** [comment]
I found out what the problem was, it's not authme's fault, it's because of minecrafts "enforce-secure-profile" option, apparently while enforce-secure-profile is set to true, the server doesn't get the ip adresses, leading to every user having the [0:0:0:0:0:0:0:1] ip. and that caused the bug.

**Comment by AkariDream** [comment]
i never recommend that anyone enable it without knowing what the option or feature is for
if u have more questions. u can maintain this thread directly. otherwise u need to close the problem. because the issue has been resolved
