### ISSUE TITLE
Build plugin

### ISSUE THREAD

**Issue by lynrayy** [AuthMe/AuthMeReloaded#2641]
### What behaviour is observed?

How to build it? I want to make some changes in plugin but can't get .jar

### Expected behaviour

.

### To Reproduce

.

### Plugin list

.

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

5.6.0-SNAPSHOT

### Configuration

Intellij Idea

**Comment by ljacqu** [comment]
Assuming you‘re the person who asked on Discord with a similar name
