### ISSUE TITLE
Allow online users to bypass AuthMe authorization

### ISSUE THREAD

**Issue by atsunaakiya** [AuthMe/AuthMeReloaded#2649]
### What feature do you want to see added?

Hi, I am hosting a server for my friends, some of them are online mode players, others are offline mode players.

Since it's very private server, we plan to setup a whitelist forbidding the players we don't know.
But since there are offline players, there is a chance that the attackers take advantage of the offline accounts to access our server.
Therefore, authorization is necessary to us. But online players complain about typing passwords.

Is there a way to distinguish the two kinds of users?
* For online players, they can directly start the game without any inconvenience.
* For offline players, they will need to login via AuthMe, or they cannot move/access their inventories.

Thanks.

### Are there any alternatives?

VPN.
None of my friends like it though.

**Comment by krusic22** [comment]
[FastLogin. ](https://github.com/games647/FastLogin)
