### ISSUE TITLE
AuthMe fails to load SQL database

### ISSUE THREAD

**Issue by MihaiGamerYT54** [AuthMe/AuthMeReloaded#2650]
### What behaviour is observed?

Server shuts down after AuthMe tries to load SQL database
"Failed to load native library:sqlite-3.36.0.3-b9f2e392-1e4c-4e1b-b849-8edb8db884a7-libsqlitejdbc.so." -- cant find jdbc driver 

### Expected behaviour

opposite of observed behaviour

### To Reproduce

1. download termux
2. pkg update && pkg upgrade && pkg install openjdk-17
3. wget https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/294/downloads/paper-1.19.2-294.jar
4. java -jar -Xmx1G paper-1.19.2-294.jar
5. cd Plugins
6. wget https://github.com/AuthMe/AuthMeReloaded/releases/download/5.6.0-beta2/AuthMe-5.6.0-beta2.jar
7. cd ..
8. java -jar -Xmx1G paper-1.19.2-294.jar

### Plugin list

Plugins (1): AuthMe

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

5.6.0

### Error log (if applicable)

https://gist.github.com/MihaiGamerYT54/eeaed23e18affd34d03445a1fd96f78c

### Configuration

default paper config

### nvm i found out that i need to use the jdbc driver

**Comment by MihaiGamerYT54** [comment]
i forgot the step to edit eula.txt

**Comment by MihaiGamerYT54** [comment]
nvm it doesnt work

**Comment by krusic22** [comment]
It tells you what to do.
Install the package that provides the required lib.

**Comment by MihaiGamerYT54** [comment]
no package exists for it, only a jar file 
i tried to do this:
export CLASSPATH=$CLASSPATH:~/a/sqlite-jdbc.jar
but same error

**Comment by MihaiGamerYT54** [comment]
Issue with termux. anlinux environment works normally but termux doesn't because of missing required classes
