### ISSUE TITLE
Common AuthMe Error

### ISSUE THREAD

**Issue by BlazeY2504** [AuthMe/AuthMeReloaded#2654]
### What behaviour is observed?

After trying to register this happens
![Screenshot 2022-12-08 5 39 44 PM](https://user-images.githubusercontent.com/113044858/206589665-7772f55f-8e89-4680-84fc-fa75f97ac795.png)
Saying that someone has execeeded the amount of registrations on that account and have tried it with my friend,brother, and even my ALT account!
If anyone knows how to fix this please let me know at my discord:
BlazeYT2504#1016

### Expected behaviour

I hope for someone to figure out the solution to the times exceeded to register bug/issue.

### To Reproduce

Make a ayunami replit eaglercraft server and add the AuthMe

### Plugin list

ClearLag,AuthMe,EaglerPluginInstaller,AutoSaver,AdminFun,tpLogin,EaglerPluginUpdater,Essentials,EssentialsSpawn,NoSpawn,PVP

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

2.7.11

### Configuration

?

**Comment by KELP1234** [comment]
So you mention that this is an eaglercraft (I assume eaglerX but it doesn't matter) server and is therefore using bungeecord (a proxy). Change your config to allow unlimited accounts per ip address. 🤡

**Comment by BlazeY2504** [comment]
KELP1234
thanks for the help but i kind of already got that a long time ago it took me a while to figure it out tho but thx
