### ISSUE TITLE
Cannot mock/spy class java.net.InetAddress

### ISSUE THREAD

**Issue by Justman10000** [AuthMe/AuthMeReloaded#2661]
### What behaviour is observed?

Error `Cannot mock/spy class java.net.InetAddress` while compiling

### Expected behaviour

Compiling successful

### To Reproduce

1. Clone
2. Install Java and Maven (if not yet available)
3. `mvn clean package`

### Plugin list

?

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

SNAPSHOT

### Configuration

?

**Comment by ljacqu** [comment]
Which test is failing with this?

**Comment by Justman10000** [comment]
> Which test is failing with this?

fr.xephi.authme.settings.commandconfig.CommandManagerTest

**Comment by ljacqu** [comment]
Indeed, it mocks IP addresses. But InetAddress is not a final class in various versions that I checked. What JDK are you using? (Version + distro)

**Comment by Justman10000** [comment]
> What JDK are you using? (Version + distro)

Java 19

**Comment by ljacqu** [comment]
Thanks, I see it was changed to a sealed class, hence cannot be mocked anymore. I fixed all tests locally except for one that needs the hostname of an IP address, which I have no idea how to abstract to a dummy function now. 
For now, if you want to build with Java 19, please disable the tests.

**Comment by Justman10000** [comment]
> Thanks, I see it was changed to a sealed class, hence cannot be mocked anymore. I fixed all tests locally except for one that needs the hostname of an IP address, which I have no idea how to abstract to a dummy function now. For now, if you want to build with Java 19, please disable the tests.

How?

**Comment by ljacqu** [comment]
You'd have to install another JDK version. But I just pushed fixes for what I described above. Please build with latest master and let us know if there are any other issues. Thanks!

**Comment by Justman10000** [comment]
> You'd have to install another JDK version. But I just pushed fixes for what I described above. Please build with latest master and let us know if there are any other issues. Thanks!

> Cannot mock/spy class java.net.InetAddress

**Comment by ljacqu** [comment]
What‘s up?

**Comment by Justman10000** [comment]
> What‘s up?

Still:
> Cannot mock/spy class java.net.InetAddress

**Comment by ljacqu** [comment]
Do a pull of master and explain the problem with more details.

**Comment by Justman10000** [comment]
> Do a pull of master and explain the problem with more details.

?
