### ISSUE TITLE
ERROR fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Exception during pool initialization.

### ISSUE THREAD

**Issue by UmutBey12122** [AuthMe/AuthMeReloaded#2666]
### What behaviour is observed?

authme throws an error and the server is shutting down

### Expected behaviour

please help someone who knows

### To Reproduce

See error

### Plugin list

![Screenshot_3](https://user-images.githubusercontent.com/87767196/211915574-baf3cebd-e05d-42e2-a1fc-cd01d5aafdd8.png)
![Screenshot_4](https://user-images.githubusercontent.com/87767196/211915674-e4bfde07-7893-45e8-bc4d-45cee814e83a.png)

### Server Implementation

BungeeCord

### Database Implementation

Mysql

### AuthMe Version

5.4.0

### Error log (if applicable)

https://paste.gg/p/anonymous/33ac68784e404697ae6058b70e05a9f2

### Configuration

https://paste.gg/p/anonymous/66ad8d64a4ab46c7a94bdb61697b93cb

**Comment by ljacqu** [comment]
> [AuthMe] Please check your database settings in the config.yml file!

Looks like some connection details of the database host were wrong (the username is empty, as seen in the logs)
