### ISSUE TITLE
Big bug on authme

### ISSUE THREAD

**Issue by atieover** [AuthMe/AuthMeReloaded#2676]
### What behaviour is observed?

Hello, if you are registering or logging to the server you can use /server and bypass authme login.

### Expected behaviour

Hello, if you are registering or logging to the server you can use /server and bypass authme login.

### To Reproduce

1. Make localhost server.
2. Add Authme plugin.
3. Try using the /server command if you are signing.

### Plugin list

AuthMe

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

5.4.0

### Configuration

its just bug

**Comment by mallusrgreatv2** [comment]
/server command shouldn't be there if it's not a proxy...

**Comment by mallusrgreatv2** [comment]
Also for "Server implementation" send the server jar name, like Spigot, Bukkit, Paper, Purpur

**Comment by sgdc3** [comment]
/server is not a standard spigot command, also you are running an outdated authme version
