### ISSUE TITLE
Exception during pool initialization

### ISSUE THREAD

**Issue by Nicolol1234** [AuthMe/AuthMeReloaded#2687]
### What behaviour is observed?

fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource error

### Expected behaviour

I expect the plugin work properly

### To Reproduce

Start a minecraft 1.19.3 (PurpurMC) server with:
- skinrestorer
-authme 5.6.0
- ProtocolLIB
- FastAsyncWorldEdit
- WordGuard
- Spark 

### Plugin list

- Skinrestorer
- Authme 5.6.0
- ProtocolLIB
- FastAsyncWorldEdit
- WordGuard
- Spark 

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

5.6.0 SNAPSHOT

### Error log (if applicable)

https://paste.gg/p/anonymous/ff34ec97749745a4b16e541c0af44c96

### Configuration

https://paste.gg/p/anonymous/add96ca748c34b9cb47e6d74ae4ab8a7

**Comment by ljacqu** [comment]
> [AuthMe] Please check your database settings in the config.yml file!

Looks like some connection details of the database host were wrong. Alternatively, the DB host didn't allow for external connections (I know some mainstream web hosts do that)
