### ISSUE TITLE
authmereloaded

### ISSUE THREAD

**Issue by Monif0** [AuthMe/AuthMeReloaded#2690]
### What behaviour is observed?

Hello, how can I go to this plugin with my database https://www.spigotmc.org/resources/authmereloaded.6269/
to connect
This is the config link
https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md
The database is also on the local host
Please change those parts and send it to me

### Expected behaviour

And my main question is, what should I do with this?
mySQLDriverClassName:
Because the wireless data is on localhost and on phpmyadmin

### To Reproduce

0k

### Plugin list

/pl authmereloaded

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

00

### Configuration

https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/config.md

**Comment by ljacqu** [comment]
External servers won't be able to connect to your localhost. Also, `mySQLDriverClassName` isn't a property anymore.
