### ISSUE TITLE
teleportUnAuthedToSpawn: true NOT WORKING!

### ISSUE THREAD

**Issue by MaxwellRose101** [AuthMe/AuthMeReloaded#2697]
### What behaviour is observed?

When I set teleportUnAuthedToSpawn to true, it doesn't work on my server. (By the way, my server is hosted on Replit.)

### Expected behaviour

It would teleport me to spawn when I logged in, and then it would send me to the place that I logged out at.

### To Reproduce

1. Set teleportUnAuthedToSpawn to true.
2. Restart server.
3. Log onto the server.
4. Spawn in the lobby.
5. Login/Register.
6. Not get teleported to where you logged out.

### Plugin list

![image](https://user-images.githubusercontent.com/122459654/224456364-3aab2850-ab43-4ae1-a04b-aa62351b9b33.png)

### Server Implementation

BungeeCord

### Database Implementation

SQLite

### AuthMe Version

5.1.0

### Configuration

https://replit.com/@MaxwellRose1019/lifesteal#server/plugins/AuthMe/config.yml

**Comment by F3F5** [comment]
use safe-player-location too!

**Comment by MaxwellRose101** [comment]
ok done it works now
