### ISSUE TITLE
Add verification after registration 

### ISSUE THREAD

**Issue by SomeTroller77** [AuthMe/AuthMeReloaded#2703]
### What feature do you want to see added?

Add a feature so that whenever a player registers, he also has to verify his email so that it would allow only geniune player email and the they can also verify whether they have typed right email or not

### Are there any alternatives?

no

**Comment by krusic22** [comment]
You already have the ability to verify before registering. Which makes a bit more sense.
https://github.com/AuthMe/AuthMeReloaded/wiki/Registration
![image](https://user-images.githubusercontent.com/8352435/229197151-012b174d-f2d2-4f9d-ae32-606bb38672b6.png)
