### ISSUE TITLE
AuthMe block all the commands

### ISSUE THREAD

**Issue by Probag586** [AuthMe/AuthMeReloaded#2708]
### What behaviour is observed?

AuthMe blocks all commands except its own.

I also tried resetting the plugin but still have the same problem (as a result the config.yml is the default).

### Expected behaviour

That AuthMe does not cause any problems in chatting and writing commands

### To Reproduce

1. Go in the server
2. type /register or /login
3. write in the chat

### Plugin list

Waterfall: AuthMeBungee-2.2.0-SNAPSHOT.jar, BanManagerBungeeCord.jar, Bmsg.jar, BungeeWhiteList.jar,  FastLoginBungee.jar,LuckPerms-Bungee-5.4.79.jar.

Paper1.8.8: Plugins (16): WorldEdit, VoidGen, PlaceholderAPI, AntiDisconnectSpam, OnlyProxyJoinAdvance, ViaVersion, ServersNPC, ViaBackwards, ProtocolLib, Multiverse-Core, LuckPerms, DeluxeHub, AuthMe, NametagEdit, LPC, FastLogin

### Server Implementation

BungeeCord

### Database Implementation

SQLite

### AuthMe Version

AuthMeReloaded v5.6.0-SNAPSHOT (build: 2599)

### Configuration

https://pastebin.com/mQqr4x39

**Comment by Probag586** [comment]
Ok, thanks I don't think it's a permanent fix but that's okay

**Comment by krusic22** [comment]
There is no BungeeCord AuthMe.
The is only AuthMeBungee which just protects Bungee from non logged in users and forwards login information to other servers under it.

**Comment by Probag586** [comment]
I fixed it by setting bungeecord to true in the config.yml
