### ISSUE TITLE
SpigotMC page description link problem

### ISSUE THREAD

**Issue by Janmm14** [AuthMe/AuthMeReloaded#2728]
### What behaviour is observed?

SpigotMC link to ci server links to bukkit redirect page,

### Expected behaviour

SpigotMC link to ci server links directly to ci server.

### To Reproduce

1. Go to https://www.spigotmc.org/resources/authmereloaded.6269/
2. Click on dev build link.
3. Get annoyed by bukkit redirect page.

### Plugin list

not relevant

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

not relevant

### Configuration

not relevant

**Comment by sgdc3** [comment]
Fixed, thank you
