### ISSUE TITLE
Deop issue

### ISSUE THREAD

**Issue by FixYourWork** [AuthMe/AuthMeReloaded#2733]
### What behaviour is observed?

When you have OP after joining the server you'd be deopped.

### Expected behaviour

Not be deopped.

### To Reproduce

Not be deopped.

### Plugin list

Tried with literally no plugins.

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

b2607

### Configuration

default config

**Comment by f3f5-dev** [comment]
this is not a bug, limbo section in authme causing this *protection*

**Comment by FixYourWork** [comment]
> this is not a bug, limbo section in authme causing this _protection_

how can i fix this deop issue then?

**Comment by ljacqu** [comment]
As ghost wrote, if a player is OP but not registered, to prevent security issues that player will not be opped back after registration. If a player is OP and registered, their OP status will be restored once they log in. If that is not the case (cannot say based on the short description), you'd need to post your config and some steps to reproduce.
