### ISSUE TITLE
premium mode connection specific to authme

### ISSUE THREAD

**Issue by Link0Darck** [AuthMe/AuthMeReloaded#2734]
### What feature do you want to see added?

Hello,
to begin with i've seen that there are appart plugins that work with authme to connect in premium mode but there's a problem when you choose it's either one or the other and that's it.

What I'd like is for authme to make a premium mode and if the plugin doesn't manage to connect to the server (microsoft alias mojang) to replay the passwords we registered on the server because as I mentioned above, the apparts plugins are either one or the other.

Sorry if you've misunderstood me, I'm French and my translation is bad.

Thanks in advance

### Are there any alternatives?

As I said, I've already tried almost all the plugins to connect to premium but the method is either one or the other.

**Comment by f3f5-dev** [comment]
https://ci.codemc.org/job/Games647/job/FastLogin/

https://github.com/games647/FastLogin

**Comment by Link0Darck** [comment]
> https://ci.codemc.org/job/Games647/job/FastLogin/
> 
> https://github.com/games647/FastLogin

Good morning,
Thank you for your answer but before starting the configuration I wanted to know what happens if there is a server failure (Microsoft / Mojang) and the person using the premium method does it pass passwords?
Thanks in advance

**Comment by Link0Darck** [comment]
Good morning,
I just close this due to my passage in online mode due to the EULA that we can end up in trial for a server and then in any case I had not managed to make it work in 1.20 due to the other plugins.
Well thanks for the help anyway
