### ISSUE TITLE
Can you provide a function to forcibly bind email addresses

### ISSUE THREAD

**Issue by Creeper-ops** [AuthMe/AuthMeReloaded#2751]
### What feature do you want to see added?

Can you provide a function to forcibly bind email addresses

### Are there any alternatives?

Nlogin But he is currently not suitable for our server

**Comment by ljacqu** [comment]
config.yml: change the `type` property under "registration" from PASSWORD to EMAIL

**Comment by Creeper-ops** [comment]
I wish to have password + email (forced binding)

**Comment by Creeper-ops** [comment]
@ljacqu

**Comment by ljacqu** [comment]
It's possible. See the `registration` section and read the comments
