### ISSUE TITLE
Java crash

### ISSUE THREAD

**Issue by felipeleite5w** [AuthMe/AuthMeReloaded#2768]
### What behaviour is observed?

Java crash randomly in my server

This message appears in CONSOLE! I believe its because I use sqlite not mysql for a big numbers of accounts, could anyone help me?

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1ff98903ab, pid=1, tid=0x00007f1ffbefe700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [sqlite-3.7.2-libsqlitejdbc.so+0x353ab]
#
# Core dump written. Default location: /home/container/core or core.1
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

### Expected behaviour

Not to crash

### To Reproduce

I dont know how to reproduce

### Plugin list

Only Authme, vault, essentials

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

5.6.0

### Error log (if applicable)

# # A fatal error has been detected by the Java Runtime Environment: # #  SIGSEGV (0xb) at pc=0x00007f1ff98903ab, pid=1, tid=0x00007f1ffbefe700 # # JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07) # Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops) # Problematic frame: # C  [sqlite-3.7.2-libsqlitejdbc.so+0x353ab] # # Core dump written. Default location: /home/container/core or core.1 # # If you would like to submit a bug report, please visit: #   http://bugreport.java.com/bugreport/crash.jsp # The crash happened outside the Java Virtual Machine in native code. # See problematic frame for where to report the bug. #

### Configuration

Standard

**Comment by felipeleite5w** [comment]
Core.1 here 

Stack: [0x00007f1ffbdfe000,0x00007f1ffbeff000],  sp=0x00007f1ffbefd1e8,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [sqlite-3.7.2-libsqlitejdbc.so+0x353ab]
J 166215 C2 org.sqlite.RS.getDouble(Ljava/lang/String;)D (10 bytes) @ 0x00007f20c6d96a5c [0x00007f20c6d96920+0x13c]
J 159355 C2 fr.xephi.authme.datasource.SQLite.buildAuthFromResultSet(Ljava/sql/ResultSet;)Lfr/xephi/authme/data/auth/PlayerAuth; (247 bytes) @ 0x00007f20cb249cec [0x00007f20cb248980+0x136c]
J 162561 C2 fr.xephi.authme.datasource.SQLite.getAuth(Ljava/lang/String;)Lfr/xephi/authme/data/auth/PlayerAuth; (369 bytes) @ 0x00007f20c87315dc [0x00007f20c8730ea0+0x73c]
J 158792 C2 fr.xephi.authme.libs.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Ljava/lang/Object;Lfr/xephi/authme/libs/google/common/cache/CacheLoader;)Lfr/xephi/authme/libs/google/common/util/concurrent/ListenableFuture; (125 bytes) @ 0x00007f20c49a8768 [0x00007f20c49a8680+0xe8]
J 158793 C2 fr.xephi.authme.libs.google.common.cache.LocalCache$Segment.refresh(Ljava/lang/Object;ILfr/xephi/authme/libs/google/common/cache/CacheLoader;Z)Ljava/lang/Object; (48 bytes) @ 0x00007f20c19ea45c [0x00007f20c19e9d40+0x71c]
J 177716 C2 fr.xephi.authme.libs.google.common.cache.LocalCache$LocalLoadingCache.refresh(Ljava/lang/Object;)V (9 bytes) @ 0x00007f20c4ac0540 [0x00007f20c4ac0400+0x140]
J 88590 C1 fr.xephi.authme.datasource.CacheDataSource.updateQuitLoc(Lfr/xephi/authme/data/auth/PlayerAuth;)Z (30 bytes) @ 0x00007f20c302b4dc [0x00007f20c302b2a0+0x23c]
J 91228 C1 fr.xephi.authme.process.quit.AsynchronousQuit.processQuit(Lorg/bukkit/entity/Player;)V (233 bytes) @ 0x00007f20c6f7a194 [0x00007f20c6f787c0+0x19d4]
J 74157 C1 fr.xephi.authme.process.Management$$Lambda$166.run()V (12 bytes) @ 0x00007f20c1cce7f4 [0x00007f20c1cce700+0xf4]
J 117280 C2 org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run()V (532 bytes) @ 0x00007f20c5e90684 [0x00007f20c5e90480+0x204]
J 222883 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f20c884036c [0x00007f20c88400e0+0x28c]
J 91330 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f20c47217c4 [0x00007f20c47216c0+0x104]
J 116988 C2 java.lang.Thread.run()V (17 bytes) @ 0x00007f20c4f2b72c [0x00007f20c4f2b6e0+0x4c]
v  ~StubRoutines::call_stub
V  [libjvm.so+0x682cc8]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x1048
V  [libjvm.so+0x684207]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x2f7
V  [libjvm.so+0x684740]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x60
V  [libjvm.so+0x71fce1]  thread_entry(JavaThread*, Thread*)+0x91
V  [libjvm.so+0xa8bc11]  JavaThread::thread_main_inner()+0xf1
V  [libjvm.so+0x9389d2]  java_start(Thread*)+0x132
C  [libpthread.so.0+0x8ea7]  start_thread+0xd7

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 42907  org.sqlite.NativeDB.column_type(JI)I (0 bytes) @ 0x00007f20c3bb8598 [0x00007f20c3bb8560+0x38]
J 166215 C2 org.sqlite.RS.getDouble(Ljava/lang/String;)D (10 bytes) @ 0x00007f20c6d96a5c [0x00007f20c6d96920+0x13c]
J 159355 C2 fr.xephi.authme.datasource.SQLite.buildAuthFromResultSet(Ljava/sql/ResultSet;)Lfr/xephi/authme/data/auth/PlayerAuth; (247 bytes) @ 0x00007f20cb249cec [0x00007f20cb248980+0x136c]
J 162561 C2 fr.xephi.authme.datasource.SQLite.getAuth(Ljava/lang/String;)Lfr/xephi/authme/data/auth/PlayerAuth; (369 bytes) @ 0x00007f20c87315dc [0x00007f20c8730ea0+0x73c]
J 158792 C2 fr.xephi.authme.libs.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Ljava/lang/Object;Lfr/xephi/authme/libs/google/common/cache/CacheLoader;)Lfr/xephi/authme/libs/google/common/util/concurrent/ListenableFuture; (125 bytes) @ 0x00007f20c49a8768 [0x00007f20c49a8680+0xe8]
J 158793 C2 fr.xephi.authme.libs.google.common.cache.LocalCache$Segment.refresh(Ljava/lang/Object;ILfr/xephi/authme/libs/google/common/cache/CacheLoader;Z)Ljava/lang/Object; (48 bytes) @ 0x00007f20c19ea45c [0x00007f20c19e9d40+0x71c]
J 177716 C2 fr.xephi.authme.libs.google.common.cache.LocalCache$LocalLoadingCache.refresh(Ljava/lang/Object;)V (9 bytes) @ 0x00007f20c4ac0540 [0x00007f20c4ac0400+0x140]
J 88590 C1 fr.xephi.authme.datasource.CacheDataSource.updateQuitLoc(Lfr/xephi/authme/data/auth/PlayerAuth;)Z (30 bytes) @ 0x00007f20c302b4dc [0x00007f20c302b2a0+0x23c]
J 91228 C1 fr.xephi.authme.process.quit.AsynchronousQuit.processQuit(Lorg/bukkit/entity/Player;)V (233 bytes) @ 0x00007f20c6f7a194 [0x00007f20c6f787c0+0x19d4]
J 74157 C1 fr.xephi.authme.process.Management$$Lambda$166.run()V (12 bytes) @ 0x00007f20c1cce7f4 [0x00007f20c1cce700+0xf4]
J 117280 C2 org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run()V (532 bytes) @ 0x00007f20c5e90684 [0x00007f20c5e90480+0x204]
J 222883 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f20c884036c [0x00007f20c88400e0+0x28c]
J 91330 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f20c47217c4 [0x00007f20c47216c0+0x104]
J 116988 C2 java.lang.Thread.run()V (17 bytes) @ 0x00007f20c4f2b72c [0x00007f20c4f2b6e0+0x4c]

**Comment by F3F5** [comment]
https://pastes.dev
