### ISSUE TITLE
Problems with DATABASE

### ISSUE THREAD

**Issue by FailsOfGamer** [AuthMe/AuthMeReloaded#2789]
### What behaviour is observed?

i have to log in on each server even if i turned on the bungeecord proxy autlogin: true

### Expected behaviour

i want help to solve my problem so my server will work again 

### To Reproduce

?

### Plugin list

![grafik](https://github.com/AuthMe/AuthMeReloaded/assets/161127055/a334da65-a10a-484a-b040-8768b416dec5)

### Server Implementation

BungeeCord

### Database Implementation

MySQL

### AuthMe Version

AuthMe-5.6.0-beta2.jar

### Error log (if applicable)

https://mclo.gs/60PrAD6

### Configuration

backend: https://mclo.gs/z3YOqU4, proxy: https://mclo.gs/eWBepkm

**Comment by knighthat** [comment]
Are those server have AuthMeReloaded plugin connected to the same MySQL database and the same table?
