### ISSUE TITLE
Toggle to remove "You own x accounts"

### ISSUE THREAD

**Issue by TheDiscordian** [AuthMe/AuthMeReloaded#2794]
### What feature do you want to see added?

I'd like there to be a config toggle for the "You own x accounts" message.

### Are there any alternatives?

I haven't found an alternative to this idea.

### Anything else?

I personally don't think checking IPv4 addresses yields enough useful information for how annoying this feature is. I'd really like the ability to disable it.

**Comment by ljacqu** [comment]
If you don't give the permission `authme.player.seeownaccounts` to your players, they will not see this message

https://github.com/AuthMe/AuthMeReloaded/blob/master/docs/permission_nodes.md
