### ISSUE TITLE
mysql don't work

### ISSUE THREAD

**Issue by 0w0aguga** [AuthMe/AuthMeReloaded#2798]
### What behaviour is observed?

Hello there! I tried to connect authme to mysql, but got this error. What should I do?

log: https://paste.gg/p/anonymous/9fa68c120ea14c54aed68e5711362e3e
cfg: https://paste.gg/p/anonymous/bfffa59ffe994c239348b3bca674141c

### Expected behaviour

-

### To Reproduce

-

### Plugin list

Authme, chunky, coreprotect, gsit, luckperms, openinv, orebfuscator, playereconomy, protocollib, simpletpa, skinsrestorer, simplevoicechat, worldedit

### Server Implementation

Standalone server (no proxy)

### Database Implementation

MySQL

### AuthMe Version

AuthMe-5.6.0-beta2

### Error log (if applicable)

https://paste.gg/p/anonymous/9fa68c120ea14c54aed68e5711362e3e

### Configuration

https://paste.gg/p/anonymous/bfffa59ffe994c239348b3bca674141c

**Comment by knighthat** [comment]
Here's your problem
```
[11:31:20 WARN]: [AuthMe] Could not create data source: [SQLSyntaxErrorException]: Access denied for user 'bd57075_s1'@'%' to database 'authme'
```
---
It means couple of things:
1. You didn't create this user on the database
2. Username/Password mismatch
3. Client IP address when you create this user doesn't match with what's connecting to it
4. Insufficient permission
> There could be more but these are common problems I've seen and dealt with (also first that come to my mind)
---
You can use external tool to connect to this database from the same machine to rule out the problem.

My recommendation is DBeaver (opensource, free, support most common (no)SQL databases) but it can be quite imitating for new user.
