### ISSUE TITLE
How to configure postgresql?

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [AuthMe/AuthMeReloaded#2801]
### What feature do you want to see added?

I changed the configuration like suggested in the comment above:

```
    # Valid values: SQLITE, MYSQL, POSTGRESQL
    backend: POSTGRESQL
```

but now there are a lot of mySQL*: configs, do I have to rename them to postgres or are they also used without renaming?

what do I have to put in mySQLDriverClassName: for postgres?

is it then `mySQLHost: localhost` or `postgresSQLHost: localhost` ?

### Are there any alternatives?

no, an example is needed

**Comment by sgdc3** [comment]
@0xFEEDC0DE64 set mySQLHost to your postgressql host and so on
