### ISSUE TITLE
More lobbies

### ISSUE THREAD

**Issue by ItzKubiq** [AuthMe/AuthMeReloaded#2802]
### What feature do you want to see added?

Idk how to add more lobbies on bungee cord. Like i have 3 lobbies and idk how to make player after login randomly send to any of theese. right now its possible to send him to only one, right?

### Are there any alternatives?

nothing

**Comment by knighthat** [comment]
1. You  need a database and connect all 3 to the same database
2. Then set '_allServersAreAuthServers_' and '_autoLogin_' to '_true_' in AuthMeBungee 
3. Also set '_Hooks.bungeecord_' to true in each AuthMeReloaded plugin's _config.yml_
4. Restart all servers that have settings changed
