### ISSUE TITLE
Request for Fabric Version

### ISSUE THREAD

**Issue by woaichijiba12345** [AuthMe/AuthMeReloaded#2872]
### What feature do you want to see added?

Hi, I really appreciate your work on Authme-reloaded. I would like to suggest creating a Fabric version of this plugin. Many players and server administrators are using Fabric, and having a Fabric-compatible version would be highly beneficial. Thank you for considering this request!

### Are there any alternatives?

No.

### Anything else?

No.

**Comment by sgdc3** [comment]
At this time, our plugin is specifically built around the Bukkit API, which means supporting multiple server implementations would require a significant amount of additional development effort. Consequently, we are unable to extend compatibility beyond Bukkit-based servers currently.
