### ISSUE TITLE
Authme 5.6.0 won't start in CraftBukkit server

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [AuthMe/AuthMeReloaded#2879]
### What behaviour is observed?

Server stop immediately after start.
```
[18:23:46] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-bCUSTOM
[18:23:46] [Server thread/WARN]: [AuthMe] You are running an unsupported server version (CraftBukkit v. 4312-Bukkit-0fb24bb (MC: 1.21.1)). AuthMe requires Spigot 1.8.X or later!
[18:23:46] [Server thread/WARN]: [AuthMe] THE SERVER IS GOING TO SHUT DOWN AS DEFINED IN THE CONFIGURATION!
```

### Expected behaviour

If server is Spigot 1.21.1 instead of CraftBukkit 1.21.1, the plugin works fine.

### To Reproduce

1. Get `BuildTools.jar` from spigot website
2. Run `java -jar BuildTools.jar --compile craftbukkit`
3. Get `craftbukkit-1.21.1.jar` from compile result

Run CraftBukkit instead of Spigot is not a mistake. And plugin is downloaded from bukkit website https://dev.bukkit.org/projects/authme-reloaded/files/5484191 instead of spigot website https://www.spigotmc.org/resources/authmereloaded.6269  

### Plugin list

`plugins` folder contains only `AuthMe-5.6.0.jar`, the server stops immediately, so no `/pl` can be executed by admin player or from console.
`AuthMe` folder is not generated after server start and stops.

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

5.6.0 I assume because no command can be executed

### Error log (if applicable)

Provided in "What behaviour is observed?" section

### Configuration

Blank server no config

**Comment by mhtvsSFrpHdE** [comment]
Get `authme-5.7.0-SNAPSHOT.jar` from https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded and the result is the same.

**Comment by krusic22** [comment]
This is intended behavior. CraftBukkit only exists for legacy reasons, while Spigot gets the feature and API changes.
Therefore AuthMe is build againts the Spigot API, requiring the server to run at least Spigot.
