### ISSUE TITLE
New PhpBB3 3.1.6 or 3.1.7 is supported?

### ISSUE THREAD

**Issue by falconhome** [AuthMe/AuthMeReloaded#470]
Hi Guys!

I have PHPBB3 3.1.7 forum engine + spigot MC:1.8.8 game srv + AuthMe 5.0_B3 with ALL clean install (+all the plugins which need for base MC srv like essential, group manager, etc), but when i try to use the AuthMe i got "wrong password" msg in the game... 

So, before i start a long explanation about my config files, i would like to know i am a stupid or i found something...

Choices:
a.) if i am a newbeee, and i cannot understand the configuration instructions (i'll jump :) )
b.) if its a new issue, which newly reported, i will be explain where i am in a bug looking for process, and if i got a solution i will push the "Donate" button ;)

So guys, here we goo... ;)

Thanks
 Falcon

**Comment by sgdc3** [comment]
You should never use version 5.0 Now our buildserver is offline, but when it will be avariable, please try latest build, it fixes TONS of bugs. About PHPBB we need someone to test it ;)

**Comment by falconhome** [comment]
Hi Guys!

Thx, my phpbb forum and AuthMe 5.2 b703 works well.
tested phpbbs - 3.1.6, and 3.1.7 - both OK
- /login - OK both side 
- /changepassword - OK both side (PHPBB and Minecraft)
- game side /register and /unregister going - unexpected error ... 

The config.yml on: http://pastebin.com/jSXUU9p1 - for anybody who do not wanted to spend too many time for base config

messages_hu.yml - http://pastebin.com/Wb8300Wf - just for fun ;)

Other: If the in game registration disabled in config, for the new players know this after, if they try to register... In this case i think better solution to inform promptly them "In game registration disabled, please visit our registration site..." 

I promised, i will push the donate button, but i find the AuthMe on several places with donate possibilities, but i did not know  which one is yours ;) Pls send me a link in priv.

Thanks,
  Falcon

**Comment by sgdc3** [comment]
What's the error with registration/unregistration

**Comment by sgdc3** [comment]
?

**Comment by ljacqu** [comment]
Is there an error when someone does /register in the server log? It would be very interesting to see that :)

---

> Other: If the in game registration disabled in config, for the new players know this after, if they try to register... In this case i think better solution to inform promptly them "In game registration disabled, please visit our registration site..."

What's the current behavior?

**Comment by falconhome** [comment]
Hi,
1.) messages_hu - for sure ;), that was the reason why i put it here (open source ;))
2.) I go to check the logs...

**Comment by falconhome** [comment]
messages_hu updated, because i missed a line, now it is complete

**Comment by falconhome** [comment]
_"Other: If the in game registration disabled in config, for the new players know this after, if they try to register... In this case i think better solution to inform promptly them "In game registration disabled, please visit our registration site..."_

Update: I made some mistake in my "CommunityBridge" plugin config file, and that caused the problem... **Now, function /unregister working well...** (the user deleted from the PHPBB. This is make some inconvenience in PHPBB side (for example, unlinked forum comments, etc - but i think this is phpbb admin side problem ;) )

InGame /register 
case a.) if in the authme config file disabled the ingame registration parameter it's works well -> no error in logs, good message
case b.) if i enable it, and try to register -> I got an error message:

&& In Game error message:
>An unexpected error occurred, please contact an administrator

&& Server Console error message:
[22:50:07 INFO]: UUID of player test is 530fa97a-357f-3c19-94d3-0c5c65c18fe8
[22:50:07 INFO]: test[/192.168.213.150:5610] logged in with entity id 63 at ([world]-1288.0, 127.0, -1662.0)
[22:50:21 WARN]: [AuthMe] Column 'user_form_salt' cannot be null

&& grep from Minecraft Server Log:
[22:50:07] [Thread-10/INFO]: UUID of player test is 530fa97a-357f-3c19-94d3-0c5c65c18fe8
[22:50:07] [Server thread/INFO]: test[/192.168.213.150:5610] logged in with entity id 63 at ([world]-1288.0, 127.0, -1662.0)
[22:50:21] [Craft Scheduler Thread - 6/WARN]: [AuthMe] Column 'user_form_salt' cannot be null
[22:51:07] [Server thread/INFO]: test lost connection: §4Login timeout exceeded, you have been kicked from the server, please try again!
[22:51:07] [Craft Scheduler Thread - 9/WARN]: [CommunityBridge] Not changing permissions group due to permissions system group name lookup failure for web application group ID: . Player 'test' primary group state unchanged.

&& PHPBB side 
- user not created, no pending registration, nothing

I think you have to look around the salt creation or store_db side.

Rgsd,
  F

**Comment by falconhome** [comment]
Hi guys!

I saw on all open issues, and i think this issue can be move to low priority, because i found a very simple workaround! ;) If anybody (not registered) arrives into the game server, i tell them please register first on <myphpbb.myserver.com> webpage. So you have time... ;)

Br
 F

**Comment by games647** [comment]
I saw this ticket from PHPBB: https://tracker.phpbb.com/browse/PHPBB3-11610

Looks like they changed to Bcrypt. Maybe you can fix it like in #691
