### ISSUE TITLE
Keep login status after reload

### ISSUE THREAD

**Issue by arturek1666** [AuthMe/AuthMeReloaded#563]
Hi, Is it possible to don't have to login when you do /reload.

**Comment by ljacqu** [comment]
/reload should literally reload the plugin; in case anything goes wrong it's a "fresh" start (more or less). So that would be a bad idea

**Comment by arturek1666** [comment]
Well other plugin did had that and they had no problem it's just like if they leave and join they don't  have to login and they should be able to do same with the /reload. It's possible because other plugins that are now outdated did had this option.

**Comment by sgdc3** [comment]
@arturek1666 I think @arturek1666 means that it's more secure to restart the entire plugin ;) Anyway, you can use the session feature to auto-login players after a reload!

**Comment by sgdc3** [comment]
@ljacqu I have to admit that reload should keep the login status, maybe we should only update the isLogged status from the database.

**Comment by ljacqu** [comment]
@sgdc3 I'd like to suggest to remove the isLogged status on the db. This is not a state that should be persisted but something we should keep track of with a ConcurrentMap or so.
Whether we clear the map or not upon reload, I don't really care. So we could keep it then and it would seem like a good compromise? :)

**Comment by sgdc3** [comment]
Nope, we can't do this due to sync between sessions and webinterfaces integration ;)

**Comment by ljacqu** [comment]
Yup as discussed on gitter
I see why it's there but maybe it could be changed that we keep track of it internally differently—but not in the near future I guess. To be honest it blows my mind that this actualy works and doesn't cause security issues

**Comment by Twonox** [comment]
One time I could /reload without /login right after. But with latest build I can't.

**Comment by ljacqu** [comment]
From @sgdc3: Xephi did this in 3.4 but it was broken. Code is still around but implementation was broken/messy, but could serve as a template to implement this again.
