### ISSUE TITLE
Merge AuthMeBridgeBukkit into Authme

### ISSUE THREAD

**Issue by sgdc3** [AuthMe/AuthMeReloaded#610]
We need also to merge it with our (and maybe useless atm) plugin messaging stuff.

**Comment by ljacqu** [comment]
@sgdc3 @Gnat008 I think this is finished, right? Or are we still missing some logic from https://github.com/AuthMe/AuthMeBungee-Deprecated?

**Comment by sgdc3** [comment]
Nope, we need to re-create the entire bungee communication system.

**Comment by ljacqu** [comment]
@sgdc3 The repository I refer to in my previous comment (https://github.com/Xephi/AuthMeReloaded/issues/610#issuecomment-237898353) no longer exists. Is this issue still relevant? If so, where is the repo now?

**Comment by ljacqu** [comment]
@sgdc3

**Comment by sgdc3** [comment]
I'll try to work on it, i don't have any plan atm

**Comment by sgdc3** [comment]
Closing as we need a complete rewriteof the bungee integration
