### ISSUE TITLE
Add a cancellable session restore event.

### ISSUE THREAD

**Issue by DardBrinza** [AuthMe/AuthMeReloaded#620]
Hey. Can you add support for plugin AccountProtector+?

How to add:
1 ) The player enters the server and it opens a window with a request for pincode and conversely(customizable).
2 ) He enters the pincode, the window is closed and there is a regular password prompt :)
In the coming days will support version 1.8.

Plugin:
https://www.spigotmc.org/resources/accountprotector-%E2%82%AC1-99-for-first-10-buyers.20036/

The author agree to add support and is ready to provide you with plugin.
Thanks

**Comment by sgdc3** [comment]
We already have a nice API, I think AccountProtector's dev should use it ;)

**Comment by DardBrinza** [comment]
API is not working with the session, and the possibility to postpone the password prompt to paragraph 2.

**Comment by sgdc3** [comment]
What's the issue with the session?

**Comment by DardBrinza** [comment]
Help :D

**Comment by sgdc3** [comment]
solution: create a feature that allows another plugin to cancel a session restore event.

**Comment by DNx5** [comment]
is this still needed?

**Comment by ljacqu** [comment]
Yes, it's a good addition

**Comment by ljacqu** [comment]
Hi @DardBrinza, we've finally added the event! It's called `RestoreSessionEvent` and its being fired is the last thing that happens before a session is restored (unless the event gets canceled, of course). OK to close this issue?

**Comment by sgdc3** [comment]
@DardBrinza Any news? ;)
