### ISSUE TITLE
Group-specific settings

### ISSUE THREAD

**Issue by sgdc3** [AuthMe/AuthMeReloaded#629]
From a pm i received on dev.bukkit.org:
"Hey, first off great job on the plugin. It's an amazing piece of work!
If you could spare a few moments to clarify two questions I have regarding the plugin, I would be most grateful. So I've tried to look into this myself but came to inconclusive results. Here's what I'm aiming for:
- I would like to set it up so only certain groups are forced to register (e.g only staff groups _must_ register, while players don't) I've only managed to make it optional to register, but if possible I'd like to make it so staff groups must register.
- Prevent chat only from unauthenticated registered accounts I found the global chat option, however if I disable chat for non-authenticated accounts, even players who didn't register can't chat. Is this normal behaviour? I'd like to have it so that players can always chat, but staff accounts that are not logged in can't send chat messages.
  As it stands, I'm not sure whether this is even possible.
  Thank you in advance! Regards"

**Comment by ljacqu** [comment]
Since others have just split this with more relevant titles I close this as a duplicate.

See #1416 "Allowing AuthMe only for certain groups" and #1417  "Prevent chat for specific groups only"
