### ISSUE TITLE
[Suggestion] Essentials afk enhancement

### ISSUE THREAD

**Issue by rErEaT** [AuthMe/AuthMeReloaded#664]
Can I remove the essentials.afk.auto permission before login?

So globally can I remove any permission what I want before login?

**Comment by rErEaT** [comment]
so nothing happend with this?:S

**Comment by rErEaT** [comment]
@sgdc3 :D

**Comment by sgdc3** [comment]
blocked by the new forced commands features

**Comment by rErEaT** [comment]
So its unable to make?

**Comment by sgdc3** [comment]
@rErEaT We'll add this in the future ;)

**Comment by rErEaT** [comment]
okay, thanks :D

**Comment by Platinteufel** [comment]
I've never used it, but isn't that possible with the unLoggedinGroup?

**Comment by ljacqu** [comment]
Moving this to the next milestone although it's very likely that no work will have to be done for this issue. It's probably possible to solve this using the permission groups feature we've fixed in 5.3 and/or the commands.yml config which was introduced in 5.2.

**Comment by rErEaT** [comment]
should it possible in commands.yml? :D

**Comment by sgdc3** [comment]
yeah, it is possible

**Comment by rErEaT** [comment]
at this moment I can do it or need another update for work?

**Comment by ljacqu** [comment]
It should be possible by using onLogin, and optionally onLogout. You just need to add a command that gives / removes the permission.
Alternatively, with the permission group switching we've also implemented in 5.3 it should be possible, using `registeredPlayerGroup` in config.yml

**Comment by rErEaT** [comment]
> onJoin:
>    afkremove:
>      command: 'pex user %p add -essentials.afk.auto'
>      executor: CONSOLE
> onLogin:
>    afkrevoke:
>      command: 'pex user %p remove -essentials.afk.auto'
>      executor: CONSOLE
> # These commands are called whenever a logged in player uses /logout or quits.
> # The commands are not run if a player that was not logged in quits the server.
> # Note: if your server crashes, these commands won't be run, so don't rely on them to undo
> # 'onLogin' commands that would be dangerous for non-logged in players to have!
> onLogout:
>    afkrevoke:
>      command: 'pex user %p remove -essentials.afk.auto'
>      executor: CONSOLE
> onRegister: {}
> onSessionLogin: {}
> # Commands to run whenever a player is unregistered (by himself, or by an admin)
> onUnregister:
>    afkremove:
>      command: 'pex user %p add -essentials.afk.auto'
>      executor: CONSOLE

looks like works 👍 
But is there anyway to clear the permissions.yml file if it hasn't got any permission or group?
like this
>   b874c95b-0b54-3744-9c27-fe0527956db3:
>     permissions: []
>     options:
>       last-logout-time: '1496481378'
>       name: foxi69
>       last-login-time: '1496481234'

**Comment by sgdc3** [comment]
> But is there anyway to clear the permissions.yml file if it hasn't got any permission or group?
like this

That's a PEX limitation...

**Comment by rErEaT** [comment]
oh okay, then its works perfectly, thanks guys for your hard work :)
