### ISSUE TITLE
messages_zhhk.yml encoding error when startup

### ISSUE THREAD

**Issue by i998979** [AuthMe/AuthMeReloaded#749]
I am going to talk about messages_zhhk.yml's error
first of all, I run the server once and generate the config
I edited this line
messagesLanguage: zhhk
then i restart the server
after the player joined and login timeout, it shows a weird message

17:15:14 [資訊] [????????] disconnected with: [??蝟餌絞] ???暹???

but that is not the original one in the messages_zhhk.yml
it suppose to be ANSI
so, please fix this.

**Comment by DNx5** [comment]
I think the console doesn't support UTF-8

**Comment by i998979** [comment]
It should work at least on client side.
