### ISSUE TITLE
tempban using external ban management plugins

### ISSUE THREAD

**Issue by Done84** [AuthMe/AuthMeReloaded#794]
Hi. This is an enhancement suggestion.
It would be nice if the temp ban feature for when users try a password too many times and its wrong to use external ban management plugins.
Maybe a custom command with a %player placeholder.

Something like this:
    tempban:
        enableTempban: true
        maxLoginTries: 5
        command: 'bmtempban %player 30min Login tries limit reached bra bla bla'

**Comment by Twonox** [comment]
It's very good idea !

**Comment by friishon** [comment]
ok, remenber implement this please 
 when exceeds the attempts, send an email to the player to verify if he try to login or not
if he was use an url to recover his account (unban his account)
if not was him use an url to permanent ban
