### ISSUE TITLE
[Dev] Review datasource column defaults

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#814]
- Does it really make sense to have x, y, z last positions default to 0? If no data is available player should probably not be teleported at all in a lastposition context. Same for last world.
- realname in SQLite defaults to Player but not in MySQL...? But in MySQL it is still defined `NOT NULL`
- email defaults to `your@email.com` - now we essentially check against this value instead of an intuitive NULL.

**Comment by sgdc3** [comment]
also the 127.0 0.1 default ip xd

**Comment by ljacqu** [comment]
I propose to close this even though I've left the location columns untouched. The big learning during this issue and #792 is that we kind of need NOT NULL columns to have a default value - SQLite requires that a NOT NULL column have a default value if it is added to a table later on, and various forum software we want to support has requirements for e.g. the email to be not null. Here the default value comes into play.

On PlayerAuth level we can handle these default values by replacing them with NULL. So if you get a PlayerAuth from the data source and the email returned from the database was `your@email.com`, then `playerAuth.getEmail()` will return `null`. Of course, if we interact differently with the DB (e.g. by fetching the email only), then these values will of course NOT be replaced to null. 

So despite the changes it seems that we're stuck with the default values. The best way to handle it is to be aware of them and have some constant / a method available to check for this, as we have in `PlayerAuth` now or e.g. `Utils#isEmailEmpty`.
