### ISSUE TITLE
Spawn Direction

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#815]
We are always spawning South direction. We can keep the looking direction before logouting ?

**Comment by ljacqu** [comment]
There's an issue for this, but I cannot find it. Also relates to #802

**Comment by Twonox** [comment]
When `teleportUnAuthedToSpawn: true` the direction is not saved.

**Comment by Twonox** [comment]
@DNx5  @sgdc3  @games647

**Comment by ljacqu** [comment]
We all get notified of new issues, no need to mention people specifically. As I said, someone already opened an issue for this.

**Comment by ljacqu** [comment]
Finally found it, #463 
It mentions two issues, so let's keep this one open to handle the position storing, and we'll use #463 just for the primary issue it mentions.

**Comment by DNx5** [comment]
I believe it fixed in `jsoncache-fix` branch

**Comment by sgdc3** [comment]
@Twonox

**Comment by DNx5** [comment]
@sgdc3 we still not merge it

**Comment by ljacqu** [comment]
@DNx5 You're referring to the change to JsonCache in 145747505f82d004f8f04347575f7774248876a3, right? But what about the PlayerAuth? 

I checked out jsoncache-fix branch and right now I'm never teleported to my last position anymore. I'm investigating...

**Comment by ljacqu** [comment]
@DNx5 AsynchronousQuit:
```java
Location loc = player.isDead() ? spawnLoader.getSpawnLocation(player) : player.getLocation();
```

I found out that `player.isDead()` always returns `true` here (because player is already gone from the server?), so last location used is always spawn.

I said I tested some features on the branch successfully; unfortunately I found out that my launch configuration was flawed and I was testing a week old version... :cat2:

**Comment by DNx5** [comment]
@ljacqu should add `player.isOnline()` in that line.

**Comment by Twonox** [comment]
Now, this issue happen only if `SaveQuitLocation: true` & `teleportUnAuthedToSpawn: false`
Since `teleportUnAuthedToSpawn: true` not affect our position and our logout location, this issue doesn't cause problem for me.

**Comment by ljacqu** [comment]
Hi @Twonox @molor, this is now implemented and available in the newest build. Please let us know whether this issue can be closed or if there's something still missing.

**Comment by Twonox** [comment]
Thank you, it works fine ! :)
