### ISSUE TITLE
what variable as player name? (in language file)

### ISSUE THREAD

**Issue by LapizSeller** [AuthMe/AuthMeReloaded#829]
as title said, what variable as player name in language file? i try %p, %player, %name, %username, all won't work.

**Comment by sgdc3** [comment]
Atm this works only with some messages, with 5.3 we are going to provide 100% customizable messages ;)

**Comment by sgdc3** [comment]
What's the goal of this? @LapizSeller @ljacqu

**Comment by ljacqu** [comment]
Apparently @LapizSeller has the need to be able to use a tag that will be replaced to the player's name in any message.

**Comment by sgdc3** [comment]
Uh, nice

**Comment by sgdc3** [comment]
Moving to 5.5, we are too late with 5.4

**Comment by ljacqu** [comment]
Reopen: please see remarks in https://github.com/AuthMe/AuthMeReloaded/pull/1509#issuecomment-370165252

**Comment by sgdc3** [comment]
Closing: #1520
