### ISSUE TITLE
Hungarian TODO messages translated

### ISSUE THREAD

**Issue by rErEaT** [AuthMe/AuthMeReloaded#836]
> incomplete_email_settings: 'Hiba: nem lett beállítva az össze szükséges beállítás az email küldéshez. Vedd fel a kapcsolatot egy adminnal.'
> accounts_owned_other: 'A %name nevű játékosnak, %count db regisztrációja van:'
> kicked_admin_registered: 'Adminisztrátor által regisztrálva lettél; kérlek lépj be újra!'
> accounts_owned_self: '%count db regisztrációd van:'

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by rErEaT** [comment]
:)

**Comment by rErEaT** [comment]
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/517980/messages_hu.zip)

100% translated :)

**Comment by ljacqu** [comment]
Thank you :) Much appreciated

**Comment by rErEaT** [comment]
[messages_hu.zip](https://github.com/Xephi/AuthMeReloaded/files/537468/messages_hu.zip)

latest update :D

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by rErEaT** [comment]
[help_hu.zip](https://github.com/AuthMe/AuthMeReloaded/files/914039/help_hu.zip)

Does it need anything more or It will 100% translate the help menu? :)

**Comment by ljacqu** [comment]
Thanks @rErEaT, and sorry it took so long. The messages are now integrated :)

**Comment by sgdc3** [comment]
Whoops, i forgot about that, sorry ;)
