### ISSUE TITLE
Country whitelist and bungee

### ISSUE THREAD

**Issue by Pijanista** [AuthMe/AuthMeReloaded#847]
While this thing works great on single server without bungee, but with bungee there is like 20-30% of bots that are not on whitelist will pass on the server.

**Comment by sgdc3** [comment]
@Gnat008 maybe related to the bypass bug?

**Comment by sgdc3** [comment]
@Pijanista is this still an issue?

**Comment by Eufranio** [comment]
It is for me. Also the AntiBot won't work properly on Bungee environments, some bots will still join the server.

**Comment by sgdc3** [comment]
@Pijanista Any news about that? Is the issue still happening?

**Comment by krusic22** [comment]
No bots currently bypass the country check. Tho I am using Waterfall and Paper. Also note already registered users bypass the country check by default.

**Comment by sgdc3** [comment]
I wasn't able to reproduce the issue, i think we can close this.
