### ISSUE TITLE
[API] Missing wrong authentication event

### ISSUE THREAD

**Issue by chief-j** [AuthMe/AuthMeReloaded#857]
Can I somehow check if a player has entered an incorrect password at login?

**Comment by chief-j** [comment]
so, it is possible to do? How can I get the correct or not correct input password?

**Comment by sgdc3** [comment]
We need to add this feature to out api ;)

**Comment by chief-j** [comment]
isAuthenticated not worked with Session Reconnection

**Comment by sgdc3** [comment]
@chief-j could you open another issue for that ;)

**Comment by ljacqu** [comment]
A new event is now thrown when the password is invalid: `fr.xephi.authme.events.FailedLoginEvent`. OK to close, @chief-j?

**Comment by sgdc3** [comment]
@chief-j Does it work?
