### ISSUE TITLE
False "Already playing"

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#879]
Sometimes when we join the serveur we receive this:
http://image.noelshack.com/fichiers/2016/30/1469467734-2016-07-25-19-11-05.png

Build 1238

**Comment by sgdc3** [comment]
Probably you crashed and the servwr is waiting the connection timeout to kick your profile

**Comment by Twonox** [comment]
No no no, I have tested in my principal server and in my test server with same authme and I have this problem in both server. When I remove authme there is no this problem.

**Comment by nathampa0909** [comment]
What plugins you use on your server? Can you list it?

**Comment by Twonox** [comment]
I wouldn't give list of my plugins but you can ask me if I have a specific plugin.
@sgdc3 If I use build 1228 there is no this problem. The problem comes from build after this one.

**Comment by nathampa0909** [comment]
@Twonow Do you use ProtocolSupport?

**Comment by sgdc3** [comment]
@Twonox SO this is the first build that doesn't work, right? http://ci.xephi.fr/job/AuthMeReloaded/1229/

**Comment by Twonox** [comment]
@nathampa0909  I don't use it.
@sgdc3 I don't know, I have choose randomly the build 1228 and this build don't have this problem.

**Comment by sgdc3** [comment]
i need to find the commit that caused the issue

**Comment by Twonox** [comment]
Now I don't have this problem, I don't know why. (With latest and old build of authme).
Before, I had 50% probability to receive this message with Authme in my two servers. It's strange.
If it starts again, I will do more test.

**Comment by nathampa0909** [comment]
@sdgc3 I have this problem too, my build is a old build (build 186). Do not happen always but when happen the player logout from the server but the account continue online a time.

**Comment by ljacqu** [comment]
@Twonox still occurring or would this be OK to close?

**Comment by nathampa0909** [comment]
@ljacqu In my server still occurring. I asked my players and they say that the bug is occurring yet.

**Comment by ljacqu** [comment]
@nathampa0909 Good to know, thanks

**Comment by Twonox** [comment]
There is no longer this problem in my server.

**Comment by sgdc3** [comment]
@nathampa0909 still happening? :)

**Comment by nathampa0909** [comment]
@sgdc3 yeah, but I'm using the build 1384 ( http://prntscr.com/dpiu9y ). I need to update to next dev version?

**Comment by sgdc3** [comment]
we are amost ready for the 5.2 release, i assume thencurrent build is stable enought for testing ;)

**Comment by nathampa0909** [comment]
@sgdc3 Ok, I will update and send answers here later.

**Comment by nathampa0909** [comment]
@sgdc3 still happening, version: http://prnt.sc/dpumnq

**Comment by ljacqu** [comment]
@nathampa0909 Crap, I know what it is. 

We disable kicks based on the message, i.e. if the kick message is "You logged in from another location" we disable the kick. Now of course the message is "Esse nick já está online no servidor!" so we don't recognize this kick message. How did you translate this kick reason?

**Comment by sgdc3** [comment]
@ljacqu You're right! Good catch! ;)

**Comment by nathampa0909** [comment]
@ljacq http://prntscr.com/dq3459
In messages_en.yml: same_nick: '&4Esse nick já está online no servidor!'

**Comment by nathampa0909** [comment]
UP!

I saw other reports and I'm using TacoSpigot on 1.8.8.

The problem continue.

**Comment by ljacqu** [comment]
Funny, "my" server also has this issue. As a quick fix I wanted to add this to commands.yml:
```yml
onLogout:
  kick:
    command: 'kick %p You have logged out'
    executor: CONSOLE
```

and it has no effect! The server noticing that I quit still takes as much time and all I get from adding this "Error: Player not found.". If I kick myself manually it works well and I can rejoin instantly.

At this point I wonder if we're just super slow at handling someone leaving (which I doubt), or some other plugin is blocking this from happening in a timely fashion. In my case I'd assume it's lag, but I don't know...

**Comment by ljacqu** [comment]
As an update to this, I'm having the same bug but it only happens to me, strangely enough! I get the same behavior on vanilla Spigot so I guess my client / my internet is being weird.
Without AuthMe there are less symptoms because "you have logged in from another location!" does not get prevented. A potential workaround would be to allow this to happen if the ip of the joining player matches the online player's.

**Comment by ljacqu** [comment]
Hi @Twonox @nathampa0909, is this still something you are experiencing? If so I could implement the workaround described in the above command soon.

**Comment by Twonox** [comment]
Hi, I shall not answer because I no longer use Authme. My server is online mode since some months.

**Comment by sgdc3** [comment]
@ljacqu we recently changed how we handle the join, probably we fixed that.

**Comment by ljacqu** [comment]
@sgdc3 That's a good point—would you agree to close this? The reason I asked if this was still relevant was that we'd hear it from others if they experienced this, too.

**Comment by sgdc3** [comment]
we'll see if anyone has issues with 5.4.0
