### ISSUE TITLE
Add captcha to register? Solution for spambot

### ISSUE THREAD

**Issue by Typhome** [AuthMe/AuthMeReloaded#930]
We're having problem with spambots that can register and then full spam server chat.
I thought that register with captcha would help to prevent this... IP ban is not helpful here, because it uses proxy IPs (+ dynamic IPs etc).

Picture of spambot doing task: https://i.gyazo.com/ab3a705b350db0144bba369351e03d68.png

**Comment by sgdc3** [comment]
Noncheatplus? xD

**Comment by sgdc3** [comment]
Captcha on register would annoy players, we can add it but i don't thibk it would be good dor your server.

**Comment by ljacqu** [comment]
Agree, but on the other hand registering will only be done once per player :)

**Comment by sgdc3** [comment]
@ljacqu I would close this as wontfix, is that ok for you?

**Comment by ljacqu** [comment]
It's a reasonable feature request. Why are you against it?

**Comment by sgdc3** [comment]
> but on the other hand registering will only be done once per player :)

You said that, sorry, i'm not against that, but we have to move it to the next milestone

**Comment by ljacqu** [comment]
Sorry, it's been a stressful week for me xP

**Comment by sgdc3** [comment]
> Wow, you're quoting me totally out of context. It was a reply to you saying we shouldn't do it because it will annoy people

Sorry i think i didn't understand the context at all, sorry ;)

**Comment by ljacqu** [comment]
The sorry's all mine; I didn't have to get so worked up ^^ Sorry :)

**Comment by ljacqu** [comment]
I'm stuck at the moment because when a user connects to a server I need to use the RegisterCaptchaManager in BungeeService to check if a captcha is required (to set the appropriate message), but at the same time I need to use BungeeService inside RegisterCaptchaManager to update the captcha message when the code check has failed (because the code then changes).

So either I split services, introduce a mechanism to have circular dependencies, or I go the cheap way and just set a message on login that doesn't contain the captcha code. I'm not happy with any of those approaches.

**Comment by ljacqu** [comment]
Hi @sgdc3 @games647 @HexelDev, although I'd prefer not to have any circular dependencies I think this might be the best approach for this case here. I don't see any natural way to split the services. What do you think?

**Comment by games647** [comment]
@ljacqu Does the captcha service really needs to have BungeeCord access? Shouldn't there only be two cases:

1) player is logged in by the previous server -> force login without captcha
2) player is not logged in -> require register with an independent generated captcha

or do I miss something?

**Comment by ljacqu** [comment]
I'm an idiot, sorry, I meant the limbo service. This has nothing to do with bungee :smile:

**Comment by ljacqu** [comment]
Hi @Typhome, this is now available with build n. 1897 and above at https://ci.xephi.fr/job/AuthMeReloaded/

Could we ask you for feedback whether we can close this or if something doesn't conform to your expectations?

**Comment by Typhome** [comment]
Hello @ljacqu, I tested this new feature and it works. Thank you. Now this issue is solved, I'll close it.

**Comment by ljacqu** [comment]
Thank you for the prompt answer! :)
