### ISSUE TITLE
Some users can't move Authme+Bungee

### ISSUE THREAD

**Issue by SliderKP** [AuthMe/AuthMeReloaded#941]
some users can't move in my server "lobby", only can jump, with AuthMe build #1287, Spigot 1.8.8, authmebridge-bungeecord-1.6.2 without errors.

**Comment by smiggle0404** [comment]
I have the exact same issue, not sure what to do :(

**Comment by sgdc3** [comment]
@SliderKP Try this setup:

AuthMe: https://circleci-tkn.rhcloud.com/api/v1/project/AuthMe/AuthMeReloaded/tree/master/latest/artifacts/AuthMe.jar

AuthMeBridge: http://ci.xephi.fr/job/AuthMeBridge/lastSuccessfulBuild/artifact/authmebridge-authme/target/AuthMeBridge-1.6.2-SNAPSHOT.jar

BungeAuthMeBridge: http://ci.xephi.fr/job/AuthMeBridge/lastSuccessfulBuild/artifact/authmebridge-bungee/target/BungeeAuthMeBridge-1.6.2-SNAPSHOT.jar

**Comment by sgdc3** [comment]
enable the authmebridge autologin feature

**Comment by SliderKP** [comment]
autologin are disabled, now is enabled and tomorrow i will try these versions,

**Comment by SliderKP** [comment]
with the new updates, users need to relogin when they move from server to server

**Comment by sgdc3** [comment]
yeah, you need to use authmebridge with autologin feature enabled atm

**Comment by sgdc3** [comment]
Official autologin support will return soon ;)

**Comment by sgdc3** [comment]
@SliderKP

**Comment by SliderKP** [comment]
sorry for slow to respond , okey currently my server every time they change server some users have to re-enter your account , some not, and as for users who could not move, the problem continues , i will wait updates,

**Comment by sgdc3** [comment]
> the problem continues

:/ Could you post your config and describe your network setup?

**Comment by ReaperAngels** [comment]
I added 'walkspeed 1' to the commands running after the player logs in. Works like a charm.

**Comment by sgdc3** [comment]
We are going to rewrite the bungee integration
