### ISSUE TITLE
AuthMe purged active playerdata

### ISSUE THREAD

**Issue by Eufranio** [AuthMe/AuthMeReloaded#944]
After enable the AuthMe purge feature, it started deleting files from active users when the server starts.
Maybe related to Bungee, i'm using a bungee network and the server is a Forced Host, with IP Forwarding enabled.

**Comment by ljacqu** [comment]
Maybe related to #886? Do you have a db backup? If so, any entries with lastLogin = 0 in there for (somewhat) regular players?

**Comment by Eufranio** [comment]
I don't have a database backup, also i'm using MySQL :/

**Comment by ljacqu** [comment]
All I can offer is to check the code to make sure we're running the purge process correctly – having had a quick look at the code on mobile, I don't think we have something wrong there. 
BUT what could be an option is that we store 0 as lastlogin somewhere for some reason. This might be worth checking quickly. 
You say you use bungeecord; maybe @sgdc3 or @Gnat008 could think of another cause?

**Comment by ljacqu** [comment]
Finally, please make sure your purge settings have sensible values and that we're not talking about a player that was on a long vacation or something :P

**Comment by Eufranio** [comment]
In my config, i have `daysBeforeRemovePlayer: 30` . The players had their items, and then the server restarted (auto restart), and when i saw the console was logging the data purge of the players.

**Comment by sgdc3** [comment]
In my opinion it can't be an issue with bungee, the most probable cause is that for some reason the last login timestamp of the player was wrong.

**Comment by sgdc3** [comment]
Maybe 0? @ljacqu

**Comment by Eufranio** [comment]
So?

**Comment by sgdc3** [comment]
We plan to release 5.2 very soon. After the release we are going to fix all the minor issues and release 5.3 beta 1 ;)

**Comment by ljacqu** [comment]
I assigned this to me 22 days ago for verification and then forgot about it. The code looks fine and without being able to reproduce this again we're kind of stuck. What I intend to do for this issue is to create some kind of test setup for now to check it once more, and for the future so that we have one.
