### ISSUE TITLE
[Erro Mysql Authme] POOL error - Crash Players

### ISSUE THREAD

**Issue by alexhackers** [AuthMe/AuthMeReloaded#995]
[AuthMeMYSQLPool housekeeper/WARN]: [AuthMeMYSQLPool housekeeper] WARN fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Thread starvation or clock leap detected (housekeeper delta=1m458ms431µs498ns).

this error happens and crashes players

Version: AuthMeReloaded v5.2-SNAPSHOT (build: 1323)

**Comment by DNx5** [comment]
that warning appears when your server is lagging. make sure it isn't AuthMe that cause the lag.

**Comment by ljacqu** [comment]
@alexhackers Did this happen just this once (and was there considerable lag)? Or is this a common occurrence?

**Comment by alexhackers** [comment]
Common Occurrence

**Comment by ljacqu** [comment]
how many players typically?
what if you remove authme, still laggy? Maybe a timings report would be useful so we can see what is making the server slow, be it authme or somethign else

**Comment by alexhackers** [comment]
http://hastebin.com/xuweguhuca.md

now , have this error
and my server in timings no have reports of lag

Sorry my english !

**Comment by sgdc3** [comment]
What's your spigot version? Could you post your plugin list?

**Comment by alexhackers** [comment]
PaperSpigot 1.7
Plugins: http://i.imgur.com/FwSUVIx.png

**Comment by sgdc3** [comment]
@alexhackers still happening?

**Comment by alexhackers** [comment]
Yes

**Comment by ljacqu** [comment]
anyway to find out about the server's memory usage? i wonder if this is a case of a severely overloaded server or something.
